// Code generated by tools/aigen. DO NOT EDIT.
//
// Source: internal/ai/features/registry.go
// Regenerate with: make generate (or `go run ./tools/aigen`).
//
// This file is the TypeScript mirror of the Go AI feature registry.
// Backend (internal/ai/features) and frontend (this file) cannot drift
// because CI runs `go run ./tools/aigen --check` and fails the build
// if a regeneration is required.
//
// Phase-50 / 0001 — F0 AI-Off Contract (ADR-015).

export type AiFeatureId = "ai-provider-health" | "chatbot-llm";

export interface AiFeatureMeta {
  readonly id: AiFeatureId;
  readonly name: string;
  readonly description: string;
  readonly tier: string;
  readonly defaultOn: boolean;
  readonly needsRag: boolean;
  readonly needsTools: boolean;
  readonly needsStream: boolean;
  readonly uiTestIds: readonly string[];
}

export const AI_FEATURES: Readonly<Record<AiFeatureId, AiFeatureMeta>> = Object.freeze({
  "ai-provider-health": Object.freeze({
    id: "ai-provider-health",
    name: "AI Provider Health (ops)",
    description: "Diagnostic endpoint that reports the active AI provider and its capabilities. Off by default; enable only for ops debugging.",
    tier: "F",
    defaultOn: false,
    needsRag: false,
    needsTools: false,
    needsStream: false,
    uiTestIds: Object.freeze([] as const),
  }),
  "chatbot-llm": Object.freeze({
    id: "chatbot-llm",
    name: "LLM Chatbot",
    description: "Conversational fleet assistant powered by an LLM. Falls back to the heuristic chatbot when AI is off.",
    tier: "U",
    defaultOn: false,
    needsRag: true,
    needsTools: true,
    needsStream: true,
    uiTestIds: Object.freeze(["ai-feature-chatbot-llm"] as const),
  }),
});

export const AI_FEATURE_IDS: readonly AiFeatureId[] = Object.freeze([
  "ai-provider-health",
  "chatbot-llm",
] as const);

export function isKnownAiFeature(id: string): id is AiFeatureId {
  return Object.prototype.hasOwnProperty.call(AI_FEATURES, id);
}
