// Code generated by tools/aigen. DO NOT EDIT.
//
// Source: internal/ai/features/registry.go
// Regenerate with: make generate (or `go run ./tools/aigen`).
//
// This file is the TypeScript mirror of the Go AI feature registry.
// Backend (internal/ai/features) and frontend (this file) cannot drift
// because CI runs `go run ./tools/aigen --check` and fails the build
// if a regeneration is required.
//
// Phase-50 / 0001 — F0 AI-Off Contract (ADR-015).

export type AiFeatureId = "__redaction_bypass__" | "__usage__" | "ai-provider-health" | "anomaly-explanations" | "chatbot-llm" | "digest-narration" | "drive-coaching" | "nl-alert-builder" | "nl-automation-builder" | "nl-search" | "yir-narration";

export interface AiFeatureMeta {
  readonly id: AiFeatureId;
  readonly name: string;
  readonly description: string;
  readonly tier: string;
  readonly defaultOn: boolean;
  readonly needsRag: boolean;
  readonly needsTools: boolean;
  readonly needsStream: boolean;
  readonly uiTestIds: readonly string[];
}

export const AI_FEATURES: Readonly<Record<AiFeatureId, AiFeatureMeta>> = Object.freeze({
  "__redaction_bypass__": Object.freeze({
    id: "__redaction_bypass__",
    name: "AI Redaction Bypass Report",
    description: "Per-(feature, provider) bypass summary from F8 redact decorator. Gates on ai_mode != 'off' only.",
    tier: "F",
    defaultOn: false,
    needsRag: false,
    needsTools: false,
    needsStream: false,
    uiTestIds: Object.freeze(["ai-feature-redaction-bypass"] as const),
  }),
  "__usage__": Object.freeze({
    id: "__usage__",
    name: "AI Usage Card",
    description: "Per-call audit log + spend visualisation for the AI provider chain. Gates on ai_mode != 'off' only.",
    tier: "F",
    defaultOn: false,
    needsRag: false,
    needsTools: false,
    needsStream: false,
    uiTestIds: Object.freeze(["ai-feature-usage"] as const),
  }),
  "ai-provider-health": Object.freeze({
    id: "ai-provider-health",
    name: "AI Provider Health (ops)",
    description: "Diagnostic endpoint that reports the active AI provider and its capabilities. Off by default; enable only for ops debugging.",
    tier: "F",
    defaultOn: false,
    needsRag: false,
    needsTools: false,
    needsStream: false,
    uiTestIds: Object.freeze([] as const),
  }),
  "anomaly-explanations": Object.freeze({
    id: "anomaly-explanations",
    name: "Anomaly explanation narration",
    description: "Opt-in LLM narration that explains already-detected anomalies in plain language. The deterministic detector and safe-range explanations remain the baseline when AI is off.",
    tier: "U",
    defaultOn: false,
    needsRag: false,
    needsTools: true,
    needsStream: true,
    uiTestIds: Object.freeze(["ai-feature-anomaly-explanations-root"] as const),
  }),
  "chatbot-llm": Object.freeze({
    id: "chatbot-llm",
    name: "LLM Chatbot",
    description: "Conversational fleet assistant powered by an LLM. Falls back to the heuristic chatbot when AI is off.",
    tier: "U",
    defaultOn: false,
    needsRag: true,
    needsTools: true,
    needsStream: true,
    uiTestIds: Object.freeze(["ai-feature-chatbot-llm-root"] as const),
  }),
  "digest-narration": Object.freeze({
    id: "digest-narration",
    name: "Weekly digest narration",
    description: "Opt-in LLM narration of the weekly digest. The deterministic template digest remains the baseline when AI is off.",
    tier: "U",
    defaultOn: false,
    needsRag: false,
    needsTools: true,
    needsStream: true,
    uiTestIds: Object.freeze(["ai-feature-digest-narration-root"] as const),
  }),
  "drive-coaching": Object.freeze({
    id: "drive-coaching",
    name: "Per-drive coaching",
    description: "Opt-in LLM-narrated 2-4 paragraph coaching summary for an individual drive. Reads from the deterministic per-drive aggregates surfaced by the existing /drives/{driveID} handler and a small typed telemetry-summary tool; the deterministic stat cards, hero gauges, and energy summary on the drive detail page remain the canonical baseline when AI is off.",
    tier: "N",
    defaultOn: false,
    needsRag: false,
    needsTools: true,
    needsStream: true,
    uiTestIds: Object.freeze(["ai-feature-drive-coaching-root"] as const),
  }),
  "nl-alert-builder": Object.freeze({
    id: "nl-alert-builder",
    name: "Natural-language alert builder",
    description: "Opt-in LLM assistant that drafts typed AlertRule DTOs from a plain-language description. The deterministic AlertStudio form + validators remain the baseline when AI is off; saving still flows through the existing typed alerts handler.",
    tier: "N",
    defaultOn: false,
    needsRag: false,
    needsTools: true,
    needsStream: true,
    uiTestIds: Object.freeze(["ai-feature-nl-alert-builder-root"] as const),
  }),
  "nl-automation-builder": Object.freeze({
    id: "nl-automation-builder",
    name: "Natural-language automation builder",
    description: "Opt-in LLM assistant that drafts typed Automation graph DTOs (trigger + conditions + actions) from a plain-language description. The deterministic AutomationBuilder graph editor + validators remain the baseline when AI is off; saving still flows through the existing typed automations handler.",
    tier: "N",
    defaultOn: false,
    needsRag: false,
    needsTools: true,
    needsStream: true,
    uiTestIds: Object.freeze(["ai-feature-nl-automation-builder-root"] as const),
  }),
  "nl-search": Object.freeze({
    id: "nl-search",
    name: "Natural-language search",
    description: "Opt-in LLM-assisted natural-language search across the user's drives, charging sessions, and alert history via the F7 RAG retriever. The deterministic typed search filters at /search remain the baseline when AI is off; results are still rendered via the existing typed search handler — the AI side panel only narrates and cites the retrieved chunks.",
    tier: "N",
    defaultOn: false,
    needsRag: true,
    needsTools: true,
    needsStream: true,
    uiTestIds: Object.freeze(["ai-feature-nl-search-root"] as const),
  }),
  "yir-narration": Object.freeze({
    id: "yir-narration",
    name: "Year-in-review narration",
    description: "Opt-in LLM narration of the annual year-in-review slides. The deterministic template slides remain the baseline when AI is off.",
    tier: "U",
    defaultOn: false,
    needsRag: false,
    needsTools: true,
    needsStream: true,
    uiTestIds: Object.freeze(["ai-feature-yir-narration-root"] as const),
  }),
});

export const AI_FEATURE_IDS: readonly AiFeatureId[] = Object.freeze([
  "__redaction_bypass__",
  "__usage__",
  "ai-provider-health",
  "anomaly-explanations",
  "chatbot-llm",
  "digest-narration",
  "drive-coaching",
  "nl-alert-builder",
  "nl-automation-builder",
  "nl-search",
  "yir-narration",
] as const);

export function isKnownAiFeature(id: string): id is AiFeatureId {
  return Object.prototype.hasOwnProperty.call(AI_FEATURES, id);
}
