// Maps each SemanticIconName to a lucide icon export name (PascalCase).
// Consumed by SemanticIcon.web.tsx (lucide-react) and SemanticIcon.native via
// lucide-react-native. Names that don't resolve fall back to the monogram glyph.
import type {SemanticIconName} from './semanticIconData';

export const SEMANTIC_ICON_LUCIDE: Record<SemanticIconName, string> = {
  severityCritical: 'OctagonAlert',
  severityWarn: 'TriangleAlert',
  severityInfo: 'Info',
  warning: 'TriangleAlert',
  info: 'Info',
  alertCircle: 'CircleAlert',
  success: 'CircleCheck',
  successFilled: 'CircleCheckBig',
  error: 'CircleX',
  helpCircle: 'CircleHelp',

  battery: 'Battery',
  batteryCharging: 'BatteryCharging',
  batteryFull: 'BatteryFull',
  batteryMedium: 'BatteryMedium',
  batteryWarning: 'BatteryWarning',
  charging: 'BatteryCharging',
  charger: 'PlugZap',
  bolt: 'Zap',
  powerShare: 'Share2',

  vehicle: 'Car',
  navigation: 'Navigation',
  navigationAlt: 'Compass',
  map: 'Map',
  mapPinned: 'MapPinned',
  location: 'MapPin',
  locate: 'LocateFixed',
  drive: 'Route',
  drives: 'Route',
  trip: 'Milestone',
  signpost: 'Signpost',
  fence: 'Fence',
  flag: 'Flag',
  fuel: 'Fuel',
  satellite: 'Satellite',
  radar: 'Radar',

  analytics: 'ChartColumn',
  trends: 'ChartLine',
  pieChart: 'ChartPie',
  layoutDashboard: 'LayoutDashboard',
  layoutGrid: 'LayoutGrid',
  layoutTemplate: 'LayoutTemplate',
  trendUp: 'TrendingUp',
  trendDown: 'TrendingDown',
  speed: 'Gauge',
  speedCircle: 'Gauge',
  efficiency: 'Leaf',
  activity: 'Activity',
  range: 'Ruler',
  target: 'Target',
  workflow: 'Workflow',
  award: 'Award',
  trophy: 'Trophy',
  star: 'Star',

  notifications: 'Bell',
  notificationsMuted: 'BellOff',
  notificationsActive: 'BellRing',
  notificationsAdd: 'BellPlus',

  climate: 'Thermometer',
  climateHot: 'ThermometerSun',
  cooling: 'Snowflake',
  heating: 'Flame',
  weather: 'CloudSun',
  cabin: 'Armchair',
  cloud: 'Cloud',
  wind: 'Wind',
  flame: 'Flame',
  droplets: 'Droplets',
  moon: 'Moon',
  moonStar: 'MoonStar',
  sun: 'Sun',
  sunMoon: 'SunMoon',

  security: 'ShieldCheck',
  securityAlert: 'ShieldAlert',
  securityCheck: 'ShieldCheck',
  securityOff: 'ShieldOff',
  locked: 'Lock',
  unlocked: 'LockOpen',
  key: 'Key',
  keyRound: 'KeyRound',
  fingerprint: 'Fingerprint',
  guard: 'ShieldAlert',

  media: 'Music',
  headphones: 'Headphones',
  speaker: 'Speaker',
  volume: 'Volume2',
  volumeLow: 'Volume1',
  volumeOff: 'VolumeX',

  maintenance: 'Wrench',
  settings: 'Settings',
  settingsAlt: 'Settings2',
  preferences: 'SlidersHorizontal',
  cpu: 'Cpu',
  database: 'Database',
  databaseBackup: 'DatabaseBackup',
  hardDrive: 'HardDrive',
  hardDriveDownload: 'HardDriveDownload',
  monitor: 'Monitor',
  terminal: 'Terminal',
  server: 'Server',
  network: 'Network',
  globe: 'Globe',
  link: 'Link',
  package: 'Package',
  shoppingCart: 'ShoppingCart',
  archive: 'Archive',
  history: 'History',
  stethoscope: 'Stethoscope',
  bug: 'Bug',
  scanSearch: 'ScanSearch',
  recycle: 'Recycle',
  bot: 'Bot',
  gamepad: 'Gamepad2',
  palette: 'Palette',
  keyboard: 'Keyboard',
  tv: 'Tv',
  power: 'Power',
  radio: 'Radio',
  radioTower: 'RadioTower',
  wifi: 'Wifi',
  wifiOff: 'WifiOff',
  heart: 'Heart',
  heartPulse: 'HeartPulse',

  user: 'User',
  users: 'Users',
  userCheck: 'UserCheck',
  userPlus: 'UserPlus',
  userX: 'UserX',
  home: 'House',

  dollarSign: 'DollarSign',
  wallet: 'Wallet',
  receipt: 'Receipt',

  calendar: 'Calendar',
  calendarCheck: 'CalendarCheck',
  calendarClock: 'CalendarClock',
  calendarPlus: 'CalendarPlus',
  calendarMinus: 'CalendarMinus',
  clock: 'Clock',
  timer: 'Timer',
  bedDouble: 'BedDouble',
  sparkles: 'Sparkles',
  lightbulb: 'Lightbulb',

  add: 'Plus',
  remove: 'Minus',
  close: 'X',
  confirm: 'Check',
  next: 'ChevronRight',
  previous: 'ChevronLeft',
  expand: 'ChevronDown',
  collapse: 'ChevronUp',
  expandAll: 'ChevronsDown',
  collapseAll: 'ChevronsUp',
  forward: 'ArrowRight',
  back: 'ArrowLeft',
  arrowUp: 'ArrowUp',
  arrowDown: 'ArrowDown',
  arrowLeftRight: 'ArrowLeftRight',
  arrowRightLeft: 'ArrowRightLeft',
  arrowUpDown: 'ArrowUpDown',
  arrowUpFromDot: 'ArrowUpFromDot',
  arrowDownToDot: 'ArrowDownToDot',
  externalLink: 'ExternalLink',
  drillThrough: 'ArrowUpRight',
  drillDown: 'CornerDownRight',
  search: 'Search',
  filter: 'Filter',
  more: 'Ellipsis',
  moreInline: 'EllipsisVertical',
  menu: 'Menu',

  edit: 'Pencil',
  pencil: 'Pencil',
  delete: 'Trash2',
  copy: 'Copy',
  save: 'Save',
  download: 'Download',
  upload: 'Upload',
  share: 'Share2',
  send: 'Send',
  fileDown: 'FileDown',
  fileText: 'FileText',
  fileJson: 'FileJson',
  fileSpreadsheet: 'FileSpreadsheet',
  folderOpen: 'FolderOpen',

  refresh: 'RefreshCw',
  undo: 'Undo2',
  undoAlt: 'Undo',
  redo: 'Redo2',
  loading: 'LoaderCircle',
  play: 'Play',
  pause: 'Pause',
  stop: 'Square',
  circleStop: 'CircleStop',
  skipBack: 'SkipBack',
  skipForward: 'SkipForward',
  eraser: 'Eraser',

  show: 'Eye',
  hide: 'EyeOff',

  doorOpen: 'DoorOpen',
  tirePressure: 'CircleGauge',
  split: 'Split',
  hammer: 'Hammer',
  leaf: 'Leaf',

  dog: 'Dog',
  tent: 'Tent',
  gitCompare: 'GitCompare',
};
