package trip

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/ev-dev-labs/teslasync/internal/database"
	"github.com/ev-dev-labs/teslasync/internal/models"
	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

// The SI canonical schema (migration 000185_drives_si) keeps trips and
// trip_drives forward-only:
//   - trips: id, vehicle_id, name, started_at, ended_at, created_by_user,
//            auto_generated, notes
//   - trip_drives: trip_id, drive_id, position INT NOT NULL
//
// Distance / energy / duration aggregates are not stored on trips. List reads
// recompute SI-canonical totals from constituent drives.

type TripRepo struct {
	db *database.DB
}

func NewTripRepo(db *database.DB) *TripRepo {
	return &TripRepo{db: db}
}

// TripSummary is the repository projection used by GET /trips. It keeps the
// base models.Trip schema clean while carrying computed SI aggregates for the
// list response DTO.
type TripSummary struct {
	Trip           models.Trip
	TotalDistanceM float64
	TotalEnergyWh  float64
	TotalDurationS int64
	DriveCount     int64
	ChargeCount    int64
	TotalCost      float64
}

const tripSummarySelectColumns = `
t.id,
t.vehicle_id,
COALESCE(t.name, '') AS name,
t.started_at,
t.ended_at,
t.created_by_user,
COALESCE(t.auto_generated, false) AS auto_generated,
t.notes,
COALESCE(td_agg.distance_m, 0)::DOUBLE PRECISION AS total_distance_m,
COALESCE(td_agg.energy_used_wh, 0)::DOUBLE PRECISION AS total_energy_wh,
COALESCE(td_agg.duration_s, 0)::BIGINT AS total_duration_s,
COALESCE(td_agg.drive_count, 0)::BIGINT AS drive_count,
COALESCE((
SELECT COUNT(*)
FROM charging_sessions cs
WHERE cs.vehicle_id = t.vehicle_id
  AND cs.started_at < COALESCE(t.ended_at, NOW())
  AND COALESCE(cs.ended_at, cs.started_at) >= t.started_at
), 0)::BIGINT AS charge_count,
COALESCE((
SELECT SUM(cs.cost_decimal)
FROM charging_sessions cs
WHERE cs.vehicle_id = t.vehicle_id
  AND cs.started_at < COALESCE(t.ended_at, NOW())
  AND COALESCE(cs.ended_at, cs.started_at) >= t.started_at
), 0)::DOUBLE PRECISION AS total_cost`

const tripSummaryFromClause = `
FROM trips t
LEFT JOIN (
SELECT td.trip_id,
       SUM(COALESCE(d.distance_m, 0))      AS distance_m,
       SUM(COALESCE(d.energy_used_wh, 0))  AS energy_used_wh,
       SUM(COALESCE(d.duration_s, 0))      AS duration_s,
       COUNT(d.id)                         AS drive_count
FROM trip_drives td
JOIN drives d ON d.id = td.drive_id
GROUP BY td.trip_id
) td_agg ON td_agg.trip_id = t.id`

func scanTripSummary(rows pgx.Rows) (*TripSummary, error) {
	out := &TripSummary{}
	if err := rows.Scan(
		&out.Trip.ID,
		&out.Trip.VehicleID,
		&out.Trip.Name,
		&out.Trip.StartedAt,
		&out.Trip.EndedAt,
		&out.Trip.CreatedByUser,
		&out.Trip.AutoGenerated,
		&out.Trip.Notes,
		&out.TotalDistanceM,
		&out.TotalEnergyWh,
		&out.TotalDurationS,
		&out.DriveCount,
		&out.ChargeCount,
		&out.TotalCost,
	); err != nil {
		return nil, err
	}
	return out, nil
}

func (r *TripRepo) GetByVehicle(ctx context.Context, vehicleID int64, limit, offset int, startTime, endTime time.Time) ([]*TripSummary, error) {
	query := `SELECT ` + tripSummarySelectColumns + tripSummaryFromClause + ` WHERE t.vehicle_id=$1`
	args := []interface{}{vehicleID}
	argIdx := 2
	if !startTime.IsZero() {
		query += fmt.Sprintf(" AND t.started_at >= $%d", argIdx)
		args = append(args, startTime)
		argIdx++
	}
	if !endTime.IsZero() {
		query += fmt.Sprintf(" AND t.started_at <= $%d", argIdx)
		args = append(args, endTime)
		argIdx++
	}
	query += fmt.Sprintf(" ORDER BY t.started_at DESC LIMIT $%d OFFSET $%d", argIdx, argIdx+1)
	args = append(args, limit, offset)
	rows, err := r.db.Pool.Query(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var trips []*TripSummary
	for rows.Next() {
		t, err := scanTripSummary(rows)
		if err != nil {
			return nil, err
		}
		trips = append(trips, t)
	}
	return trips, rows.Err()
}

func (r *TripRepo) GetAll(ctx context.Context, limit, offset int, startTime, endTime time.Time) ([]*TripSummary, error) {
	query := `SELECT ` + tripSummarySelectColumns + tripSummaryFromClause + ` WHERE 1=1`
	args := []interface{}{}
	argIdx := 1
	if !startTime.IsZero() {
		query += fmt.Sprintf(" AND t.started_at >= $%d", argIdx)
		args = append(args, startTime)
		argIdx++
	}
	if !endTime.IsZero() {
		query += fmt.Sprintf(" AND t.started_at <= $%d", argIdx)
		args = append(args, endTime)
		argIdx++
	}
	query += fmt.Sprintf(" ORDER BY t.started_at DESC LIMIT $%d OFFSET $%d", argIdx, argIdx+1)
	args = append(args, limit, offset)
	rows, err := r.db.Pool.Query(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var trips []*TripSummary
	for rows.Next() {
		t, err := scanTripSummary(rows)
		if err != nil {
			return nil, err
		}
		trips = append(trips, t)
	}
	return trips, rows.Err()
}

func (r *TripRepo) GetDriveIDs(ctx context.Context, tripID int64) ([]int64, error) {
	query := `SELECT drive_id FROM trip_drives WHERE trip_id=$1 ORDER BY position`
	rows, err := r.db.Pool.Query(ctx, query, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var ids []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

// GenerateMonthlyTrips creates monthly trip summaries by aggregating drives
// and charging sessions. Creates trips for all months with drives, including
// the current month (marked as in-progress). Idempotent — a month is inserted
// once, refreshed while it is the current month, and closed out once it ends.
func (r *TripRepo) GenerateMonthlyTrips(ctx context.Context) (int, error) {
	// One source of truth for "which month is running". The finalize pass below
	// and the in-progress upsert must agree on this boundary, otherwise a month
	// could be closed by one step and reopened by the other on every tick.
	now := time.Now().UTC()
	currentMonth := time.Date(now.Year(), now.Month(), 1, 0, 0, 0, 0, time.UTC)

	// Completed months are inserted only once; the current month is upserted below.
	query := `
		WITH drive_months AS (
			SELECT vehicle_id,
			       date_trunc('month', started_at) AS month_start
			FROM drives
			WHERE started_at IS NOT NULL
			GROUP BY vehicle_id, date_trunc('month', started_at)
		),
		existing_trips AS (
			SELECT vehicle_id,
			       date_trunc('month', started_at) AS month_start
			FROM trips
		),
		missing AS (
			SELECT dm.vehicle_id, dm.month_start
			FROM drive_months dm
			LEFT JOIN existing_trips et
			  ON dm.vehicle_id = et.vehicle_id AND dm.month_start = et.month_start
			WHERE et.vehicle_id IS NULL
			  AND dm.month_start < date_trunc('month', NOW())
			ORDER BY dm.month_start
		)
		SELECT vehicle_id, month_start FROM missing
	`

	rows, err := r.db.Pool.Query(ctx, query)
	if err != nil {
		return 0, fmt.Errorf("find missing months: %w", err)
	}
	defer rows.Close()

	type monthKey struct {
		vehicleID  int64
		monthStart time.Time
	}
	var missing []monthKey
	for rows.Next() {
		var mk monthKey
		if err := rows.Scan(&mk.vehicleID, &mk.monthStart); err != nil {
			return 0, err
		}
		missing = append(missing, mk)
	}
	if err := rows.Err(); err != nil {
		return 0, err
	}

	created := 0
	for _, mk := range missing {
		if _, err := r.UpsertMonthTrip(ctx, mk.vehicleID, mk.monthStart, false); err != nil {
			return created, err
		}
		created++
	}

	// Close out any month that is over but still carries in-progress state.
	// Without this a month first written while it was current keeps its
	// "(In Progress)" name and its provisional ended_at forever, because the
	// query above only ever considers months that have no trip at all.
	if err := r.finalizePastMonths(ctx, currentMonth); err != nil {
		return created, fmt.Errorf("finalize past months: %w", err)
	}

	// Upsert the current month as in-progress.
	curMonthVehicles, err := r.vehiclesWithDrivesInMonth(ctx, currentMonth)
	if err != nil {
		return created, fmt.Errorf("current month vehicles: %w", err)
	}
	for _, vid := range curMonthVehicles {
		if _, err := r.UpsertMonthTrip(ctx, vid, currentMonth, true); err != nil {
			return created, fmt.Errorf("upsert current month: %w", err)
		}
		created++
	}

	return created, nil
}

// finalizePastMonths re-runs the monthly upsert in completed mode for every
// generated summary whose month has ended but whose row still reads as
// in-progress — that is, whose ended_at is not the month boundary.
//
// Scope is deliberately narrow. Only rows the generator owns are touched:
// they start exactly on a month boundary, have no owning user, and carry
// either the auto_generated flag or one of the two names this file writes.
// Rows created before auto_generated was set are matched by name, so existing
// installs repair themselves on the next tick without a backfill migration.
func (r *TripRepo) finalizePastMonths(ctx context.Context, currentMonth time.Time) error {
	rows, err := r.db.Pool.Query(ctx, `
		SELECT vehicle_id, started_at
		FROM trips
		WHERE started_at < $1
		  AND started_at = date_trunc('month', started_at)
		  AND created_by_user IS NULL
		  AND (auto_generated IS TRUE
		       OR name LIKE '% Summary'
		       OR name LIKE '% (In Progress)')
		  AND (ended_at IS NULL OR ended_at <> started_at + INTERVAL '1 month')
		ORDER BY started_at
	`, currentMonth)
	if err != nil {
		return fmt.Errorf("find stale months: %w", err)
	}

	type monthKey struct {
		vehicleID  int64
		monthStart time.Time
	}
	var stale []monthKey
	for rows.Next() {
		var mk monthKey
		if err := rows.Scan(&mk.vehicleID, &mk.monthStart); err != nil {
			rows.Close()
			return err
		}
		stale = append(stale, mk)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return err
	}

	for _, mk := range stale {
		if _, err := r.UpsertMonthTrip(ctx, mk.vehicleID, mk.monthStart.UTC(), false); err != nil {
			return fmt.Errorf("close month %s: %w", mk.monthStart.Format("Jan 2006"), err)
		}
	}
	if len(stale) > 0 {
		log.Info().
			Int("finalized", len(stale)).
			Str("current_month", currentMonth.Format("Jan 2006")).
			Msg("trip generator: closed out months left in progress")
	}
	return nil
}

// vehiclesWithDrivesInMonth returns vehicle IDs that have drives in the given month.
func (r *TripRepo) vehiclesWithDrivesInMonth(ctx context.Context, monthStart time.Time) ([]int64, error) {
	monthEnd := monthStart.AddDate(0, 1, 0)
	rows, err := r.db.Pool.Query(ctx, `
		SELECT DISTINCT vehicle_id FROM drives
		WHERE started_at >= $1 AND started_at < $2 AND started_at IS NOT NULL
	`, monthStart, monthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var ids []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

// UpsertMonthTrip creates or updates a trip summary for a given vehicle/month.
// For in-progress months, it updates the existing trip with fresh aggregates.
//
// Migration 000185 eliminated the total_distance, total_energy, and
// total_duration columns from trips; those values are recomputed
// from constituent drives on read (see tripSelectColumns). The writer now
// only persists the columns that still exist on the SI schema (vehicle_id,
// name, started_at, ended_at). The legacy ON CONFLICT clause is removed
// because the SI schema has no unique constraint on (vehicle_id, started_at);
// idempotency is achieved by the explicit "find existing first, then update
// or insert" path.
func (r *TripRepo) UpsertMonthTrip(ctx context.Context, vehicleID int64, monthStart time.Time, inProgress bool) (int64, error) {
	monthEnd := monthStart.AddDate(0, 1, 0)
	name := monthStart.Format("Jan 2006") + " Summary"
	if inProgress {
		name = monthStart.Format("Jan 2006") + " (In Progress)"
	}

	// Use the current time as ended_at for the in-progress month.
	effectiveEnd := monthEnd
	if inProgress {
		effectiveEnd = time.Now().UTC()
	}

	// Find an existing monthly trip for this vehicle.
	var tripID int64
	err := r.db.Pool.QueryRow(ctx, `
		SELECT id FROM trips
		WHERE vehicle_id = $1 AND started_at = $2
	`, vehicleID, monthStart).Scan(&tripID)
	switch {
	case err == nil:
		// Existing monthly trip: refresh name and end time.
		if _, err := r.db.Pool.Exec(ctx, `
			UPDATE trips SET name=$1, ended_at=$2, auto_generated=TRUE
			WHERE id=$3
		`, name, effectiveEnd, tripID); err != nil {
			return 0, fmt.Errorf("update trip: %w", err)
		}
	case errors.Is(err, pgx.ErrNoRows):
		if err := r.db.Pool.QueryRow(ctx, `
			INSERT INTO trips (vehicle_id, name, started_at, ended_at, auto_generated)
			VALUES ($1, $2, $3, $4, TRUE)
			RETURNING id
		`, vehicleID, name, monthStart, effectiveEnd).Scan(&tripID); err != nil {
			return 0, fmt.Errorf("insert trip: %w", err)
		}
	default:
		return 0, fmt.Errorf("lookup trip: %w", err)
	}

	// Link drives to the trip via trip_drives. The SI schema requires a
	// `position` ordering column; assign positions by chronological drive
	// start. Use a transaction so the wipe + reinsert is atomic and the
	// final ordering is correct even if the membership shifts (e.g., a
	// new drive lands inside the month between runs).
	tx, err := r.db.Pool.Begin(ctx)
	if err != nil {
		return 0, fmt.Errorf("begin link tx: %w", err)
	}
	defer tx.Rollback(ctx)
	if _, err := tx.Exec(ctx, `DELETE FROM trip_drives WHERE trip_id=$1`, tripID); err != nil {
		return 0, fmt.Errorf("clear trip_drives: %w", err)
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO trip_drives (trip_id, drive_id, position)
		SELECT $1, id,
		       ROW_NUMBER() OVER (ORDER BY started_at)
		FROM drives
		WHERE vehicle_id = $2
		  AND started_at >= $3 AND started_at < $4
	`, tripID, vehicleID, monthStart, monthEnd); err != nil {
		return 0, fmt.Errorf("link drives: %w", err)
	}
	if err := tx.Commit(ctx); err != nil {
		return 0, fmt.Errorf("commit link tx: %w", err)
	}

	return tripID, nil
}
