{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teslasync.fullname" . }}-redis
  labels:
    {{- include "teslasync.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "teslasync.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "teslasync.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      {{- include "teslasync.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "teslasync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          securityContext:
            {{- toYaml .Values.redis.securityContext | nindent 12 }}
          image: {{ .Values.redis.image | quote }}
          {{- with .Values.redis.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          {{- with .Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
        {{- if .Values.redis.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "teslasync.fullname" . }}-redis-data
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}
