apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teslasync.fullname" . }}
  labels:
    {{- include "teslasync.labels" . | nindent 4 }}
type: Opaque
stringData:
  TESLA_CLIENT_ID: {{ .Values.tesla.clientId | quote }}
  TESLA_CLIENT_SECRET: {{ .Values.tesla.clientSecret | quote }}
  DATABASE_PASS: {{ include "teslasync.postgresql.password" . | quote }}
  {{- if and (not .Values.redis.enabled) .Values.redis.external.password }}
  REDIS_PASSWORD: {{ .Values.redis.external.password | quote }}
  {{- end }}
  {{- if .Values.grafana.enabled }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.grafana.adminPassword | quote }}
  {{- end }}
  {{- if .Values.encryption.key }}
  ENCRYPTION_KEY: {{ .Values.encryption.key | quote }}
  {{- end }}
