apiVersion: v1
kind: Service
metadata:
  name: {{ include "teslasync.fullname" . }}-api
  labels:
    {{- include "teslasync.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    {{- if .Values.metrics.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.port | quote }}
    prometheus.io/path: "/metrics"
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "teslasync.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teslasync.fullname" . }}-web
  labels:
    {{- include "teslasync.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  {{- if and (eq .Values.web.service.type "LoadBalancer") .Values.web.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.web.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.web.service.type "LoadBalancer") .Values.web.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.web.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.web.service.type "NodePort") .Values.web.service.nodePort }}
      nodePort: {{ .Values.web.service.nodePort }}
      {{- end }}
  selector:
    {{- include "teslasync.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- end }}
