{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teslasync.fullname" . }}-mongodb
  labels:
    {{- include "teslasync.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: {{ .Values.mongodb.service.type }}
  selector:
    {{- include "teslasync.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
{{- end }}
