{{- if .Values.observability.tempo.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teslasync.fullname" . }}-tempo
  labels:
    {{- include "teslasync.labels" . | nindent 4 }}
    app.kubernetes.io/component: tempo
spec:
  type: ClusterIP
  selector:
    {{- include "teslasync.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tempo
  ports:
    - name: http
      port: 3200
      targetPort: 3200
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
{{- end }}
