apiVersion: 1

playlists:
  - name: TeslaSync Overview
    interval: 30s
    items:
      - type: dashboard_by_uid
        value: teslasync-home
      - type: dashboard_by_uid
        value: teslasync-fleet-overview
      - type: dashboard_by_uid
        value: teslasync-quick-stats
      - type: dashboard_by_uid
        value: teslasync-vehicle-overview
      - type: dashboard_by_uid
        value: teslasync-charging
      - type: dashboard_by_uid
        value: teslasync-drives
      - type: dashboard_by_uid
        value: teslasync-battery-health
