import { lazy } from 'react';
import {
  Battery, BatteryWarning, Zap, Car, MapPin, Shield, Thermometer,
  Activity, BarChart3, Gauge, Wifi, TrendingUp, Monitor,
  DollarSign, Calendar, CloudSun, CircleDot, CreditCard, Hash,
  MonitorSmartphone, List, Grid3X3, Workflow, DoorOpen, Eye,
  Command, CalendarRange, Bell, Music, HeartPulse, Moon, Navigation,
} from 'lucide-react';
import type { WidgetDef } from './types';

export const WIDGET_REGISTRY: WidgetDef[] = [
  // ── Vehicle ──
  {
    id: 'vehicle-hero',
    name: 'Vehicle Card',
    description: 'Vehicle name, model, state, battery at a glance',
    icon: Car,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 9 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./VehicleHeroWidget')),
  },
  {
    id: 'vehicle-hero-card',
    name: 'Vehicle Hero Card',
    description: 'Vehicle name, model, state badge (online/asleep/driving/charging), battery, range, temp',
    icon: CreditCard,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./VehicleHeroCardWidget')),
  },
  {
    id: 'vehicle-twin',
    name: 'Digital Twin',
    description: 'Visual car state: doors, windows, lights',
    icon: Monitor,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./DigitalTwinWidget')),
  },
  {
    id: 'digital-twin-mini',
    name: 'Digital Twin Mini',
    description: 'Small version of vehicle digital twin SVG: doors, windows, lock, charge port',
    icon: Monitor,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./DigitalTwinMiniWidget')),
  },

  {
    id: 'software-update-status',
    name: 'Software Update',
    description: 'Current firmware version, update availability, download/install progress bar',
    icon: MonitorSmartphone,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SoftwareUpdateStatusWidget')),
  },
  {
    id: 'odometer-counter',
    name: 'Odometer Counter',
    description: 'Animated odometer with rolling digit animation and distance breakdown',
    icon: Hash,
    category: 'vehicle',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./OdometerCounterWidget')),
  },

  // ── Battery ──
  {
    id: 'battery-gauge',
    name: 'Battery Level',
    description: 'Battery percentage with radial gauge',
    icon: Battery,
    category: 'battery',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./BatteryGaugeWidget')),
  },
  {
    id: 'battery-radial-gauge',
    name: 'Battery Radial Gauge',
    description: 'Large radial gauge showing battery percentage with color gradient (green>amber>red)',
    icon: Battery,
    category: 'battery',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./BatteryRadialGaugeWidget')),
  },
  {
    id: 'range-estimate',
    name: 'Range Estimate',
    description: 'Rated, ideal, and estimated range',
    icon: Gauge,
    category: 'battery',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./RangeEstimateWidget')),
  },
  {
    id: 'range-bar',
    name: 'Range Bar',
    description: 'Horizontal bar showing rated, ideal, and estimated range with EPA comparison',
    icon: Gauge,
    category: 'battery',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./RangeBarWidget')),
  },
  {
    id: 'battery-degradation-trend',
    name: 'Battery Degradation Trend',
    description: 'Line chart showing max range capacity over months',
    icon: TrendingUp,
    category: 'battery',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./BatteryDegradationTrendWidget')),
  },
  {
    id: 'energy-flow',
    name: 'Energy Flow',
    description: 'Live power flow diagram',
    icon: Activity,
    category: 'battery',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./EnergyFlowWidget')),
  },
  {
    id: 'projected-range',
    name: 'Projected Range',
    description: 'AI-predicted range based on driving habits, weather, elevation',
    icon: Navigation,
    category: 'battery',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./ProjectedRangeWidget')),
  },

  // ── Energy ──
  {
    id: 'energy-flow-animated',
    name: 'Energy Flow Animated',
    description: 'Animated energy flow diagram: battery→drive, regen→battery, charger→battery',
    icon: Workflow,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./EnergyFlowAnimatedWidget')),
  },
  {
    id: 'vampire-drain',
    name: 'Vampire Drain',
    description: 'Phantom drain rate: avg %/day, recent drain events',
    icon: BatteryWarning,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./VampireDrainWidget')),
  },
  {
    id: 'sleep-efficiency',
    name: 'Sleep Efficiency',
    description: 'How well the car sleeps: efficiency %, drain rate, wake events',
    icon: Moon,
    category: 'energy',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./SleepEfficiencyWidget')),
  },

  // ── Driving ──
  {
    id: 'recent-drives',
    name: 'Recent Drives',
    description: 'Last 5 drives with distance and efficiency',
    icon: Car,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./RecentDrivesWidget')),
  },
  {
    id: 'drive-score',
    name: 'Driving Score',
    description: 'Weekly efficiency and driving score',
    icon: TrendingUp,
    category: 'driving',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./DriveScoreWidget')),
  },
  {
    id: 'recent-drives-list',
    name: 'Recent Drives List',
    description: 'Last 5-10 drives: distance, duration, efficiency, start/end locations',
    icon: List,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./RecentDrivesListWidget')),
  },
  {
    id: 'drive-score-gauge',
    name: 'Drive Score Gauge',
    description: 'Radial gauge showing weekly score (0-100) with efficiency, smoothness, and speed breakdown',
    icon: Gauge,
    category: 'driving',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./DriveScoreGaugeWidget')),
  },
  {
    id: 'drive-efficiency-chart',
    name: 'Drive Efficiency Chart',
    description: 'Area chart of Wh/mi over last 30 days with rolling average overlay',
    icon: TrendingUp,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./DriveEfficiencyChartWidget')),
  },
  {
    id: 'speed-heatmap',
    name: 'Speed Heatmap',
    description: 'Heatmap: time-of-day vs day-of-week speed distribution',
    icon: Grid3X3,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SpeedHeatmapWidget')),
  },

  // ── Charging ──
  {
    id: 'charge-status',
    name: 'Charge Status',
    description: 'Current charge state, amps, time remaining',
    icon: Zap,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./ChargeStatusWidget')),
  },
  {
    id: 'charge-status-live',
    name: 'Charge Status Live',
    description: 'Live charging: current amps/volts/power, time remaining, energy added',
    icon: Zap,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./ChargeStatusLiveWidget')),
  },
  {
    id: 'charge-history',
    name: 'Charge History',
    description: 'Recent charging sessions chart',
    icon: BarChart3,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ChargeHistoryWidget')),
  },
  {
    id: 'charge-session-chart',
    name: 'Charge Session Chart',
    description: 'Bar chart of recent charge sessions: energy per session, color-coded by charger type (home/SC/destination)',
    icon: Zap,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ChargeSessionChartWidget')),
  },
  {
    id: 'charge-cost-tracker',
    name: 'Charge Cost Tracker',
    description: 'Monthly charging cost breakdown: total kWh, total cost, cost per mile, vs gas savings',
    icon: DollarSign,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ChargeCostTrackerWidget')),
  },
  {
    id: 'charging-schedule',
    name: 'Charging Schedule',
    description: 'Shows scheduled charge time, departure time, charge limit',
    icon: Calendar,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ChargingScheduleWidget')),
  },

  // ── Climate ──
  {
    id: 'climate-status',
    name: 'Climate',
    description: 'Inside/outside temp, HVAC state',
    icon: Thermometer,
    category: 'climate',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./ClimateStatusWidget')),
  },
  {
    id: 'climate-control-panel',
    name: 'Climate Control Panel',
    description: 'Inside/outside temp, HVAC on/off, fan speed, seat heaters, steering heat',
    icon: Thermometer,
    category: 'climate',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ClimateControlPanelWidget')),
  },
  {
    id: 'weather-at-car',
    name: 'Weather at Car',
    description: 'Current weather at vehicle location: temp, conditions icon',
    icon: CloudSun,
    category: 'climate',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./WeatherAtCarWidget')),
  },

  // ── Security ──
  {
    id: 'security-status',
    name: 'Security',
    description: 'Lock, sentry, doors, windows status',
    icon: Shield,
    category: 'security',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./SecurityStatusWidget')),
  },
  {
    id: 'door-window-status',
    name: 'Door & Window Status',
    description: 'Grid showing 4 doors + 4 windows with open/closed/partial badges',
    icon: DoorOpen,
    category: 'security',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./DoorWindowStatusWidget')),
  },
  {
    id: 'sentry-event-log',
    name: 'Sentry Event Log',
    description: 'Recent sentry events with timestamps',
    icon: Eye,
    category: 'security',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SentryEventLogWidget')),
  },

  // ── Commands ──
  {
    id: 'command-quick-actions',
    name: 'Quick Actions',
    description: 'Grid of command buttons: Lock, Unlock, Climate, Frunk, Horn, Flash',
    icon: Command,
    category: 'commands',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./CommandQuickActionsWidget')),
  },

  // ── Media ──
  {
    id: 'media-now-playing',
    name: 'Now Playing',
    description: 'Current media: song title, artist, source',
    icon: Music,
    category: 'media',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./MediaNowPlayingWidget')),
  },

  // ── Tires ──
  {
    id: 'tire-pressure-visual',
    name: 'Tire Pressure Visual',
    description: 'Four-tire diagram with pressure per tire, color-coded (green/amber/red)',
    icon: CircleDot,
    category: 'tires',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./TirePressureVisualWidget')),
  },

  // ── Telemetry ──
  {
    id: 'live-signals',
    name: 'Live Signals',
    description: 'Real-time signal values with sparklines',
    icon: Wifi,
    category: 'telemetry',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./LiveSignalsWidget')),
  },
  {
    id: 'live-signal-sparklines',
    name: 'Live Signal Sparklines',
    description: 'Configurable list of 4-6 signals with mini sparkline charts (last 5 min)',
    icon: Activity,
    category: 'telemetry',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./LiveSignalSparklinesWidget')),
  },

  // ── Analytics ──
  {
    id: 'fleet-stats',
    name: 'Fleet Stats',
    description: 'Fleet-wide metrics and totals',
    icon: BarChart3,
    category: 'analytics',
    defaultSize: { cols: 4, rows: 2 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./FleetStatsWidget')),
  },
  {
    id: 'fleet-stats-bar',
    name: 'Fleet Stats Bar',
    description: 'Fleet-wide: total vehicles, online count, total miles today, total energy',
    icon: BarChart3,
    category: 'analytics',
    defaultSize: { cols: 4, rows: 2 },
    minSize: { cols: 3, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./FleetStatsBarWidget')),
  },
  {
    id: 'weekly-summary-card',
    name: 'Weekly Summary',
    description: 'This week vs last week: total miles, kWh, cost, efficiency',
    icon: CalendarRange,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./WeeklySummaryCardWidget')),
  },

  // ── Alerts ──
  {
    id: 'alert-feed',
    name: 'Alert Feed',
    description: 'Recent alerts reverse-chronological with severity badges',
    icon: Bell,
    category: 'alerts',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./AlertFeedWidget')),
  },

  // ── Automations ──
  {
    id: 'automation-status',
    name: 'Automation Status',
    description: 'Active automations: last run, success/fail badge, next scheduled',
    icon: Workflow,
    category: 'automations',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./AutomationStatusWidget')),
  },

  // ── System ──
  {
    id: 'uptime-monitor',
    name: 'Uptime Monitor',
    description: 'System health: DB, MQTT, Tesla API, Fleet Telemetry status',
    icon: HeartPulse,
    category: 'system',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./UptimeMonitorWidget')),
  },
  {
    id: 'quick-nav',
    name: 'Quick Navigation',
    description: 'Shortcut links to key pages',
    icon: MapPin,
    category: 'system',
    defaultSize: { cols: 4, rows: 2 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./QuickNavWidget')),
  },
  {
    id: 'location-map',
    name: 'Vehicle Location Map',
    description: 'Live map of vehicle position with heading arrow',
    icon: MapPin,
    category: 'maps',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./LocationMapWidget')),
  },
];

export function getWidgetDef(widgetId: string): WidgetDef | undefined {
  return WIDGET_REGISTRY.find((w) => w.id === widgetId);
}
