import { lazy } from 'react';
import {
  Battery, BatteryFull, BatteryWarning, Zap, Car, MapPin, Shield, Thermometer,
  Activity, BarChart2, BarChart3, Gauge, Wifi, TrendingUp, Monitor, Download,
  DollarSign, Calendar, CloudSun, CircleDot, CreditCard, Hash,
  MonitorSmartphone, List, Grid3X3, Workflow, DoorOpen, Eye,
  Command, CalendarRange, CalendarDays, Bell, Music, HeartPulse, Moon, Navigation, Navigation2, Terminal,
  Cpu, RotateCcw, Route, Lightbulb, Trophy, Clock, AlertTriangle, AlertOctagon,
  Sparkles, Cog, Wrench, FileText, ShieldCheck, ShieldAlert, ThermometerSun,
  Sun, Plug, TrendingDown, GitBranch, Radio, ListMusic, Home,
  PieChart as PieIcon, Server, PlayCircle, Crosshair, AlertCircle,
} from 'lucide-react';
import type { WidgetDef } from './types';

export const WIDGET_REGISTRY: WidgetDef[] = [
  // ── Vehicle ──
  {
    id: 'vehicle-hero',
    name: 'Vehicle Card',
    description: 'Vehicle name, model, state, battery at a glance',
    icon: Car,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 9 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./VehicleHeroWidget')),
  },
  {
    id: 'vehicle-hero-card',
    name: 'Vehicle Hero Card',
    description: 'Vehicle name, model, state badge (online/asleep/driving/charging), battery, range, temp',
    icon: CreditCard,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./VehicleHeroCardWidget')),
  },
  {
    id: 'vehicle-twin',
    name: 'Digital Twin',
    description: 'Visual car state: doors, windows, lights',
    icon: Monitor,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./DigitalTwinWidget')),
  },
  {
    id: 'digital-twin-mini',
    name: 'Digital Twin Mini',
    description: 'Small version of vehicle digital twin SVG: doors, windows, lock, charge port',
    icon: Monitor,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./DigitalTwinMiniWidget')),
  },

  {
    id: 'software-update-status',
    name: 'Software Update',
    description: 'Current firmware version, update availability, download/install progress bar',
    icon: MonitorSmartphone,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SoftwareUpdateStatusWidget')),
  },
  {
    id: 'software-update-history',
    name: 'Update History',
    description: 'Firmware update timeline: versions installed, dates, changelogs',
    icon: Download,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SoftwareUpdateHistoryWidget')),
  },
  {
    id: 'odometer-counter',
    name: 'Odometer Counter',
    description: 'Animated odometer with rolling digit animation and distance breakdown',
    icon: Hash,
    category: 'vehicle',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./OdometerCounterWidget')),
  },
  {
    id: 'drivetrain-health',
    name: 'Drivetrain Health',
    description: 'Motor temp, stator temp, inverter health, overall powertrain score',
    icon: Cog,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./DrivetrainHealthWidget')),
  },
  {
    id: 'motor-performance',
    name: 'Motor Performance',
    description: 'Live motor data: torque, stator temp, gear state, g-forces',
    icon: Zap,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./MotorPerformanceWidget')),
  },
  {
    id: 'vehicle-specs',
    name: 'Vehicle Specs',
    description: 'Configuration reference: model, trim, paint, wheels, options',
    icon: FileText,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./VehicleSpecsWidget')),
  },

  // ── Battery ──
  {
    id: 'battery-gauge',
    name: 'Battery Level',
    description: 'Battery percentage with radial gauge',
    icon: Battery,
    category: 'battery',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./BatteryGaugeWidget')),
  },
  {
    id: 'battery-radial-gauge',
    name: 'Battery Radial Gauge',
    description: 'Large radial gauge showing battery percentage with color gradient (green>amber>red)',
    icon: Battery,
    category: 'battery',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./BatteryRadialGaugeWidget')),
  },
  {
    id: 'range-estimate',
    name: 'Range Estimate',
    description: 'Rated, ideal, and estimated range',
    icon: Gauge,
    category: 'battery',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./RangeEstimateWidget')),
  },
  {
    id: 'range-bar',
    name: 'Range Bar',
    description: 'Horizontal bar showing rated, ideal, and estimated range with EPA comparison',
    icon: Gauge,
    category: 'battery',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./RangeBarWidget')),
  },
  {
    id: 'battery-degradation-trend',
    name: 'Battery Degradation Trend',
    description: 'Line chart showing max range capacity over months',
    icon: TrendingUp,
    category: 'battery',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./BatteryDegradationTrendWidget')),
  },
  {
    id: 'energy-flow',
    name: 'Energy Flow',
    description: 'Live power flow diagram',
    icon: Activity,
    category: 'battery',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./EnergyFlowWidget')),
  },
  {
    id: 'projected-range',
    name: 'Projected Range',
    description: 'AI-predicted range based on driving habits, weather, elevation',
    icon: Navigation,
    category: 'battery',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./ProjectedRangeWidget')),
  },
  {
    id: 'battery-cells',
    name: 'Battery Cells',
    description: 'Cell-level voltage heatmap, min/max/avg, temperature per module',
    icon: Cpu,
    category: 'battery',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./BatteryCellsWidget')),
  },
  {
    id: 'battery-degradation-forecast',
    name: 'Battery Forecast',
    description: 'Predictive degradation: when battery hits 80%, risk factors, recommendations',
    icon: TrendingDown,
    category: 'battery',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./BatteryDegradationForecastWidget')),
  },
  {
    id: 'battery-health-analytics',
    name: 'Battery Analytics',
    description: 'Deep battery health: cycles, charge depth, temp exposure, DC fast ratio',
    icon: HeartPulse,
    category: 'battery',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./BatteryHealthAnalyticsWidget')),
  },

  // ── Energy ──
  {
    id: 'energy-flow-animated',
    name: 'Energy Flow Animated',
    description: 'Animated energy flow diagram: battery→drive, regen→battery, charger→battery',
    icon: Workflow,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./EnergyFlowAnimatedWidget')),
  },
  {
    id: 'vampire-drain',
    name: 'Vampire Drain',
    description: 'Phantom drain rate: avg %/day, recent drain events',
    icon: BatteryWarning,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./VampireDrainWidget')),
  },
  {
    id: 'sleep-efficiency',
    name: 'Sleep Efficiency',
    description: 'How well the car sleeps: efficiency %, drain rate, wake events',
    icon: Moon,
    category: 'energy',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./SleepEfficiencyWidget')),
  },
  {
    id: 'solar-production',
    name: 'Solar Production',
    description: 'Daily solar generation chart from Tesla Energy / Powerwall',
    icon: Sun,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SolarProductionWidget')),
  },
  {
    id: 'live-power-flow',
    name: 'Live Power Flow',
    description: 'Real-time solar→battery→home→grid power routing diagram',
    icon: Workflow,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./LivePowerFlowWidget')),
  },
  {
    id: 'energy-site-info',
    name: 'Energy Site',
    description: 'Tesla Energy system: solar capacity, Powerwall count, gateway firmware',
    icon: Home,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./EnergySiteInfoWidget')),
  },
  {
    id: 'backup-history',
    name: 'Backup History',
    description: 'Power outage events: Powerwall backup triggers, duration, energy used',
    icon: BatteryFull,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./BackupHistoryWidget')),
  },
  {
    id: 'power-flow-history',
    name: 'Power Flow History',
    description: 'Historical solar/battery/grid/home power routing over 24 hours',
    icon: TrendingUp,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./PowerFlowHistoryWidget')),
  },

  // ── Driving ──
  {
    id: 'recent-drives',
    name: 'Recent Drives',
    description: 'Last 5 drives with distance and efficiency',
    icon: Car,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./RecentDrivesWidget')),
  },
  {
    id: 'drive-score',
    name: 'Driving Score',
    description: 'Weekly efficiency and driving score',
    icon: TrendingUp,
    category: 'driving',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./DriveScoreWidget')),
  },
  {
    id: 'recent-drives-list',
    name: 'Recent Drives List',
    description: 'Last 5-10 drives: distance, duration, efficiency, start/end locations',
    icon: List,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./RecentDrivesListWidget')),
  },
  {
    id: 'drive-score-gauge',
    name: 'Drive Score Gauge',
    description: 'Radial gauge showing weekly score (0-100) with efficiency, smoothness, and speed breakdown',
    icon: Gauge,
    category: 'driving',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./DriveScoreGaugeWidget')),
  },
  {
    id: 'drive-efficiency-chart',
    name: 'Drive Efficiency Chart',
    description: 'Area chart of Wh/mi over last 30 days with rolling average overlay',
    icon: TrendingUp,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./DriveEfficiencyChartWidget')),
  },
  {
    id: 'speed-heatmap',
    name: 'Speed Heatmap',
    description: 'Heatmap: time-of-day vs day-of-week speed distribution',
    icon: Grid3X3,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SpeedHeatmapWidget')),
  },
  {
    id: 'driving-dynamics',
    name: 'Driving Dynamics',
    description: 'Acceleration, braking, lateral g-forces with driving style indicator',
    icon: Gauge,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./DrivingDynamicsWidget')),
  },
  {
    id: 'speed-profile',
    name: 'Speed Profile',
    description: 'Speed distribution histogram with efficiency overlay — find your optimal speed',
    icon: Activity,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SpeedProfileWidget')),
  },
  {
    id: 'regen-efficiency',
    name: 'Regen Braking',
    description: 'Regenerative braking recovery rate, total kWh recovered, max regen power',
    icon: RotateCcw,
    category: 'driving',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./RegenEfficiencyWidget')),
  },
  {
    id: 'route-efficiency',
    name: 'Route Efficiency',
    description: 'Recurring routes ranked by energy efficiency with weather/elevation impact',
    icon: Route,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./RouteEfficiencyWidget')),
  },
  {
    id: 'driving-coach',
    name: 'Driving Coach',
    description: 'AI-powered driving tips: personalized efficiency recommendations',
    icon: Lightbulb,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./DrivingCoachWidget')),
  },
  {
    id: 'trip-summary',
    name: 'Trip Summary',
    description: 'Recent trips: start→end, distance, duration, drive segments, charge stops',
    icon: Navigation,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./TripSummaryWidget')),
  },

  // ── Charging ──
  {
    id: 'charge-status',
    name: 'Charge Status',
    description: 'Current charge state, amps, time remaining',
    icon: Zap,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./ChargeStatusWidget')),
  },
  {
    id: 'charge-status-live',
    name: 'Charge Status Live',
    description: 'Live charging: current amps/volts/power, time remaining, energy added',
    icon: Zap,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./ChargeStatusLiveWidget')),
  },
  {
    id: 'charge-history',
    name: 'Charge History',
    description: 'Recent charging sessions chart',
    icon: BarChart3,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ChargeHistoryWidget')),
  },
  {
    id: 'charge-session-chart',
    name: 'Charge Session Chart',
    description: 'Bar chart of recent charge sessions: energy per session, color-coded by charger type (home/SC/destination)',
    icon: Zap,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ChargeSessionChartWidget')),
  },
  {
    id: 'charge-cost-tracker',
    name: 'Charge Cost Tracker',
    description: 'Monthly charging cost breakdown: total kWh, total cost, cost per mile, vs gas savings',
    icon: DollarSign,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ChargeCostTrackerWidget')),
  },
  {
    id: 'charging-schedule',
    name: 'Charging Schedule',
    description: 'Shows scheduled charge time, departure time, charge limit',
    icon: Calendar,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ChargingScheduleWidget')),
  },
  {
    id: 'cost-forecast',
    name: 'Cost Forecast',
    description: '6-month charging cost projection with seasonal trends',
    icon: TrendingUp,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./CostForecastWidget')),
  },
  {
    id: 'charging-optimizer',
    name: 'Charging Optimizer',
    description: 'Smart charging schedule: optimal time, target SOC, cost savings',
    icon: Sparkles,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ChargingOptimizerWidget')),
  },
  {
    id: 'wall-connector',
    name: 'Wall Connector',
    description: 'Home charging stats from Tesla Wall Connector: daily kWh, session history',
    icon: Plug,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./WallConnectorWidget')),
  },
  {
    id: 'charging-telemetry',
    name: 'Charging Telemetry',
    description: 'Live charging metrics: voltage, amperage, power, phases, charger type',
    icon: Gauge,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ChargingTelemetryWidget')),
  },
  {
    id: 'supercharger-history',
    name: 'Supercharger History',
    description: 'Tesla Supercharger sessions: location, energy, cost from Tesla account',
    icon: Zap,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SuperchargerHistoryWidget')),
  },
  {
    id: 'charge-plans',
    name: 'Charge Plans',
    description: 'Active charge plan, rate schedule: peak/off-peak hours with rates',
    icon: Clock,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ChargePlansWidget')),
  },

  // ── Climate ──
  {
    id: 'climate-status',
    name: 'Climate',
    description: 'Inside/outside temp, HVAC state',
    icon: Thermometer,
    category: 'climate',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./ClimateStatusWidget')),
  },
  {
    id: 'climate-control-panel',
    name: 'Climate Control Panel',
    description: 'Inside/outside temp, HVAC on/off, fan speed, seat heaters, steering heat',
    icon: Thermometer,
    category: 'climate',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ClimateControlPanelWidget')),
  },
  {
    id: 'weather-at-car',
    name: 'Weather at Car',
    description: 'Current weather at vehicle location: temp, conditions icon',
    icon: CloudSun,
    category: 'climate',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./WeatherAtCarWidget')),
  },
  {
    id: 'climate-history',
    name: 'Climate History',
    description: 'Inside vs outside temperature chart over time',
    icon: ThermometerSun,
    category: 'climate',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./ClimateHistoryWidget')),
  },

  // ── Security ──
  {
    id: 'security-status',
    name: 'Security',
    description: 'Lock, sentry, doors, windows status',
    icon: Shield,
    category: 'security',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('./SecurityStatusWidget')),
  },
  {
    id: 'door-window-status',
    name: 'Door & Window Status',
    description: 'Grid showing 4 doors + 4 windows with open/closed/partial badges',
    icon: DoorOpen,
    category: 'security',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./DoorWindowStatusWidget')),
  },
  {
    id: 'sentry-event-log',
    name: 'Sentry Event Log',
    description: 'Recent sentry events with timestamps',
    icon: Eye,
    category: 'security',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SentryEventLogWidget')),
  },
  {
    id: 'safety-features',
    name: 'Safety Features',
    description: 'ADAS status: autopilot, collision warning, lane departure, blind spot',
    icon: ShieldAlert,
    category: 'security',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SafetyFeaturesWidget')),
  },
  {
    id: 'safety-history',
    name: 'Safety History',
    description: 'ADAS event timeline: collision warnings, AEB, lane departures, disengagements',
    icon: AlertOctagon,
    category: 'security',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SafetyHistoryWidget')),
  },
  {
    id: 'guard-mode',
    name: 'Guard Mode',
    description: 'Anti-theft guard status, recent security events, panic button',
    icon: Shield,
    category: 'security',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./GuardModeWidget')),
  },

  // ── Commands ──
  {
    id: 'command-quick-actions',
    name: 'Quick Actions',
    description: 'Grid of command buttons: Lock, Unlock, Climate, Frunk, Horn, Flash',
    icon: Command,
    category: 'commands',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./CommandQuickActionsWidget')),
  },
  {
    id: 'command-history',
    name: 'Command History',
    description: 'Recent vehicle commands: lock, unlock, climate — with success/fail status',
    icon: Terminal,
    category: 'commands',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./CommandHistoryWidget')),
  },

  // ── Media ──
  {
    id: 'media-now-playing',
    name: 'Now Playing',
    description: 'Current media: song title, artist, source',
    icon: Music,
    category: 'media',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./MediaNowPlayingWidget')),
  },
  {
    id: 'media-history',
    name: 'Media History',
    description: 'Recently played tracks: title, artist, source, playback history',
    icon: ListMusic,
    category: 'media',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./MediaHistoryWidget')),
  },

  // ── Tires ──
  {
    id: 'tire-pressure-visual',
    name: 'Tire Pressure Visual',
    description: 'Four-tire diagram with pressure per tire, color-coded (green/amber/red)',
    icon: CircleDot,
    category: 'tires',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./TirePressureVisualWidget')),
  },
  {
    id: 'tire-pressure-history',
    name: 'Tire Pressure History',
    description: 'Pressure trends for all 4 tires over time with recommended range',
    icon: CircleDot,
    category: 'tires',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./TirePressureHistoryWidget')),
  },

  // ── Telemetry ──
  {
    id: 'live-signals',
    name: 'Live Signals',
    description: 'Real-time signal values with sparklines',
    icon: Wifi,
    category: 'telemetry',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./LiveSignalsWidget')),
  },
  {
    id: 'live-signal-sparklines',
    name: 'Live Signal Sparklines',
    description: 'Configurable list of 4-6 signals with mini sparkline charts (last 5 min)',
    icon: Activity,
    category: 'telemetry',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./LiveSignalSparklinesWidget')),
  },
  {
    id: 'signal-health',
    name: 'Signal Health',
    description: 'Telemetry signal coverage: active signals, data gaps, freshness',
    icon: Activity,
    category: 'telemetry',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SignalHealthWidget')),
  },

  // ── Analytics ──
  {
    id: 'fleet-stats',
    name: 'Fleet Stats',
    description: 'Fleet-wide metrics and totals',
    icon: BarChart3,
    category: 'analytics',
    defaultSize: { cols: 4, rows: 2 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./FleetStatsWidget')),
  },
  {
    id: 'fleet-stats-bar',
    name: 'Fleet Stats Bar',
    description: 'Fleet-wide: total vehicles, online count, total miles today, total energy',
    icon: BarChart3,
    category: 'analytics',
    defaultSize: { cols: 4, rows: 2 },
    minSize: { cols: 3, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./FleetStatsBarWidget')),
  },
  {
    id: 'weekly-summary-card',
    name: 'Weekly Summary',
    description: 'This week vs last week: total miles, kWh, cost, efficiency',
    icon: CalendarRange,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./WeeklySummaryCardWidget')),
  },
  {
    id: 'weekly-digest',
    name: 'Weekly Digest',
    description: 'This week vs last week: distance, drives, energy, efficiency trends',
    icon: CalendarDays,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./WeeklyDigestWidget')),
  },
  {
    id: 'monthly-mileage',
    name: 'Monthly Mileage',
    description: 'Bar chart of monthly driving distance over last 12 months',
    icon: BarChart3,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./MonthlyMileageWidget')),
  },
  {
    id: 'lifetime-stats',
    name: 'Lifetime Stats',
    description: 'All-time totals: distance, drives, energy, CO₂ saved, ownership days',
    icon: Trophy,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./LifetimeStatsWidget')),
  },
  {
    id: 'mileage-stats',
    name: 'Mileage Stats',
    description: 'Driving averages: daily, weekly, monthly distance + milestone projection',
    icon: TrendingUp,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./MileageStatsWidget')),
  },
  {
    id: 'state-timeline',
    name: 'State Timeline',
    description: 'Vehicle state distribution: driving, charging, asleep, idle breakdown',
    icon: Clock,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./StateTimelineWidget')),
  },
  {
    id: 'anomaly-detector',
    name: 'Anomaly Detector',
    description: 'Statistical outlier alerts: unusual battery, temp, or driving anomalies',
    icon: AlertTriangle,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./AnomalyDetectorWidget')),
  },
  {
    id: 'fsm-distribution',
    name: 'State Distribution',
    description: 'Donut chart of time in each state + recent state transitions feed',
    icon: GitBranch,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./FSMDistributionWidget')),
  },
  {
    id: 'cost-breakdown',
    name: 'Cost Breakdown',
    description: 'Charging cost by source: home vs Supercharger vs destination, gas savings',
    icon: PieIcon,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./CostBreakdownWidget')),
  },
  {
    id: 'year-review',
    name: 'Year in Review',
    description: 'Annual recap: total miles, drives, energy, highlights, achievements',
    icon: Calendar,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./YearReviewWidget')),
  },
  {
    id: 'analytics-summary',
    name: 'Analytics Summary',
    description: 'Fleet-wide snapshot: distance, efficiency, energy, cost per mile',
    icon: BarChart3,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./AnalyticsSummaryWidget')),
  },

  // ── Alerts ──
  {
    id: 'alert-feed',
    name: 'Alert Feed',
    description: 'Recent alerts reverse-chronological with severity badges',
    icon: Bell,
    category: 'alerts',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./AlertFeedWidget')),
  },
  {
    id: 'notification-stats',
    name: 'Notification Stats',
    description: 'Notification delivery rate, active channels, recent delivery log',
    icon: Bell,
    category: 'alerts',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./NotificationStatsWidget')),
  },

  // ── Automations ──
  {
    id: 'automation-status',
    name: 'Automation Status',
    description: 'Active automations: last run, success/fail badge, next scheduled',
    icon: Workflow,
    category: 'automations',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./AutomationStatusWidget')),
  },
  {
    id: 'automation-history',
    name: 'Automation History',
    description: 'Recent automation runs: success/failure status, execution times',
    icon: PlayCircle,
    category: 'automations',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./AutomationHistoryWidget')),
  },

  // ── System ──
  {
    id: 'uptime-monitor',
    name: 'Uptime Monitor',
    description: 'System health: DB, MQTT, Tesla API, Fleet Telemetry status',
    icon: HeartPulse,
    category: 'system',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./UptimeMonitorWidget')),
  },
  {
    id: 'mqtt-status',
    name: 'MQTT Status',
    description: 'Fleet Telemetry MQTT connection: status, message rate, throughput',
    icon: Radio,
    category: 'system',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./MQTTStatusWidget')),
  },
  {
    id: 'quick-nav',
    name: 'Quick Navigation',
    description: 'Shortcut links to key pages',
    icon: MapPin,
    category: 'system',
    defaultSize: { cols: 4, rows: 2 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./QuickNavWidget')),
  },
  {
    id: 'api-usage',
    name: 'API Usage',
    description: 'API call volume, response times, error rates, top endpoints',
    icon: BarChart2,
    category: 'system',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./APIUsageWidget')),
  },
  {
    id: 'location-map',
    name: 'Vehicle Location Map',
    description: 'Live map of vehicle position with heading arrow',
    icon: MapPin,
    category: 'maps',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./LocationMapWidget')),
  },
  {
    id: 'location-favorites',
    name: 'Favorite Locations',
    description: 'Frequently visited places, current location status (home/work/other)',
    icon: MapPin,
    category: 'maps',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./LocationFavoritesWidget')),
  },
  {
    id: 'geofence-status',
    name: 'Geofence Status',
    description: 'Configured geofences with inside/outside status for current vehicle',
    icon: Crosshair,
    category: 'maps',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./GeofenceWidget')),
  },
  {
    id: 'destination-eta',
    name: 'Destination ETA',
    description: 'Active navigation: destination, distance remaining, arrival countdown',
    icon: Navigation2,
    category: 'maps',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./DestinationETAWidget')),
  },

  // ── Maintenance ──
  {
    id: 'maintenance-tracker',
    name: 'Maintenance',
    description: 'Upcoming maintenance reminders + recent service history',
    icon: Wrench,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./MaintenanceTrackerWidget')),
  },

  // ── Warranty ──
  {
    id: 'warranty-status',
    name: 'Warranty Status',
    description: 'Warranty countdown: time remaining, mileage remaining, coverage types',
    icon: ShieldCheck,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('./WarrantyStatusWidget')),
  },

  // ── Subscriptions ──
  {
    id: 'subscriptions',
    name: 'Subscriptions',
    description: 'Tesla subscriptions: Premium Connectivity, FSD, expiry dates, renewal',
    icon: CreditCard,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SubscriptionsWidget')),
  },

  // ── System Health ──
  {
    id: 'system-health',
    name: 'System Health',
    description: 'Server health: DB, MQTT, Tesla API status, memory, connections',
    icon: Server,
    category: 'system',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./SystemHealthWidget')),
  },
  {
    id: 'telemetry-errors',
    name: 'Telemetry Errors',
    description: 'Fleet Telemetry error monitor: VINs with errors, error types, counts',
    icon: AlertCircle,
    category: 'system',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('./TelemetryErrorsWidget')),
  },
];

export function getWidgetDef(widgetId: string): WidgetDef | undefined {
  return WIDGET_REGISTRY.find((w) => w.id === widgetId);
}
