import { WIDGET_REGISTRY } from '../widgets/registry';
import type {
  SavedDashboard,
  WidgetInstance,
  RGLLayouts,
  RGLLayout,
} from '../widgets/types';

export interface ImportValidation {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  dashboard: SavedDashboard | null;
  missingWidgets: string[];
  availableWidgets: string[];
}

/** Clamp a value between min and max */
function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}

/** Check if a value is a finite positive number */
function isFinitePositive(n: unknown): n is number {
  return typeof n === 'number' && Number.isFinite(n) && n >= 0;
}

/**
 * Sanitize a single layout item to ensure valid coordinates.
 *
 * Grid units must be non-negative integers, and an item must fit fully inside
 * the grid: `x + w <= cols`. Width is resolved first so `x` can be clamped to
 * `cols - w` — otherwise a hand-edited or malicious import could place a widget
 * partly off the right edge (react-grid-layout then shoves it during compaction,
 * corrupting the imported layout). Fractional values are floored so RGL never
 * receives sub-cell coordinates.
 */
function sanitizeLayoutItem(item: RGLLayout, cols: number): RGLLayout {
  const w = isFinitePositive(item.w) ? clamp(Math.floor(item.w), 1, cols) : 1;
  const h = isFinitePositive(item.h) ? clamp(Math.floor(item.h), 1, 8) : 1;
  const x = isFinitePositive(item.x) ? clamp(Math.floor(item.x), 0, cols - w) : 0;
  const y = isFinitePositive(item.y) ? Math.floor(item.y) : 0;
  return { ...item, x, y, w, h };
}

/** Validate and normalize raw JSON into a safe dashboard import */
export function validateImportData(raw: string): ImportValidation {
  const errors: string[] = [];
  const warnings: string[] = [];

  // 1. Parse JSON
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return {
      isValid: false,
      errors: ['Invalid JSON format'],
      warnings,
      dashboard: null,
      missingWidgets: [],
      availableWidgets: [],
    };
  }

  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    return {
      isValid: false,
      errors: ['Expected a JSON object'],
      warnings,
      dashboard: null,
      missingWidgets: [],
      availableWidgets: [],
    };
  }

  const data = parsed as Record<string, unknown>;

  // 2. Check required fields
  if (!data.name || typeof data.name !== 'string') {
    errors.push('Missing or invalid "name" field');
  }
  if (!Array.isArray(data.widgets)) {
    errors.push('Missing or invalid "widgets" array');
  }
  if (!data.layouts || typeof data.layouts !== 'object') {
    errors.push('Missing or invalid "layouts" object');
  }

  if (errors.length > 0) {
    return {
      isValid: false,
      errors,
      warnings,
      dashboard: null,
      missingWidgets: [],
      availableWidgets: [],
    };
  }

  // 3. Validate widget entries
  const rawWidgets = data.widgets as unknown[];
  const validWidgets: WidgetInstance[] = [];
  const seenIds = new Set<string>();

  for (const w of rawWidgets) {
    if (typeof w !== 'object' || w === null) continue;
    const widget = w as Record<string, unknown>;
    if (typeof widget.widgetId !== 'string') continue;

    // Generate unique ID for duplicates or missing IDs
    let id = typeof widget.id === 'string' ? widget.id : `w-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
    if (seenIds.has(id)) {
      id = `${id}-dup-${Math.random().toString(36).slice(2, 6)}`;
    }
    seenIds.add(id);

    validWidgets.push({
      id,
      widgetId: widget.widgetId,
      config: typeof widget.config === 'object' && widget.config !== null
        ? (widget.config as Record<string, unknown>)
        : undefined,
    });
  }

  // 4. Check widget availability against registry
  const registryIds = new Set(WIDGET_REGISTRY.map((def) => def.id));
  const available = validWidgets.filter((w) => registryIds.has(w.widgetId));
  const missing = validWidgets.filter((w) => !registryIds.has(w.widgetId));

  if (missing.length > 0) {
    warnings.push(`${missing.length} widget(s) not available and will be skipped`);
  }
  if (available.length === 0) {
    errors.push('No compatible widgets found in this layout');
    return {
      isValid: false,
      errors,
      warnings,
      dashboard: null,
      missingWidgets: missing.map((w) => w.widgetId),
      availableWidgets: [],
    };
  }

  // 5. Sanitize layouts
  const rawLayouts = data.layouts as Record<string, unknown>;
  const availableIds = new Set(available.map((w) => w.id));
  const sanitizedLayouts: RGLLayouts = {};
  const breakpointCols: Record<string, number> = { lg: 4, md: 3, sm: 2, xs: 1 };

  for (const [bp, cols] of Object.entries(breakpointCols)) {
    const rawBpLayout = rawLayouts[bp];
    if (!Array.isArray(rawBpLayout)) {
      // Will be regenerated by reconcileLayouts on import
      continue;
    }
    const items: RGLLayout[] = [];
    for (const entry of rawBpLayout) {
      if (typeof entry !== 'object' || entry === null) continue;
      const item = entry as Record<string, unknown>;
      if (typeof item.i !== 'string' || !availableIds.has(item.i)) continue;
      items.push(
        sanitizeLayoutItem(
          {
            i: item.i,
            x: typeof item.x === 'number' ? item.x : 0,
            y: typeof item.y === 'number' ? item.y : 0,
            w: typeof item.w === 'number' ? item.w : 1,
            h: typeof item.h === 'number' ? item.h : 1,
            minW: typeof item.minW === 'number' ? item.minW : undefined,
            minH: typeof item.minH === 'number' ? item.minH : undefined,
            maxW: typeof item.maxW === 'number' ? item.maxW : undefined,
            maxH: typeof item.maxH === 'number' ? item.maxH : undefined,
          },
          cols,
        ),
      );
    }
    sanitizedLayouts[bp] = items;
  }

  // 6. Build validated dashboard
  const now = new Date().toISOString();
  const validatedDashboard: SavedDashboard = {
    id: `import-${Date.now()}`,
    name: String(data.name).slice(0, 100),
    widgets: available,
    layouts: sanitizedLayouts,
    createdAt: now,
    updatedAt: now,
    isDefault: false,
  };

  return {
    isValid: true,
    errors,
    warnings,
    dashboard: validatedDashboard,
    missingWidgets: missing.map((w) => w.widgetId),
    availableWidgets: available.map((w) => w.widgetId),
  };
}

/** Encode a string to URL-safe base64 */
export function toUrlSafeBase64(str: string): string {
  // Encode UTF-8 first
  const utf8 = new TextEncoder().encode(str);
  let binary = '';
  for (const byte of utf8) {
    binary += String.fromCharCode(byte);
  }
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

/** Decode URL-safe base64 to string */
export function fromUrlSafeBase64(encoded: string): string {
  const padded = encoded.replace(/-/g, '+').replace(/_/g, '/');
  const binary = atob(padded);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return new TextDecoder().decode(bytes);
}

/** Build a minimal export payload for share URLs (strips timestamps, IDs) */
export function buildMinimalExport(dashboard: SavedDashboard): string {
  const minimal = {
    name: dashboard.name,
    widgets: dashboard.widgets.map((w) => ({
      id: w.id,
      widgetId: w.widgetId,
      ...(w.config ? { config: w.config } : {}),
    })),
    layouts: dashboard.layouts,
  };
  return JSON.stringify(minimal);
}
