/** Parent-owned catalog handoff: prefix each property with developerReference.sharedCompletion. */
export const completionCopy = {
  title: 'Shared library completion reference',
  subtitle: 'Twenty shared-library contracts · deterministic DEV-only fixtures',
  notice: 'Synthetic presentation fixtures only, not live vehicle data or production migration. Acceptance is recorded separately from this reference surface.',
  narrow: 'Use a narrow allocated container',
  reset: 'Reset all fixture interactions',
  selectionTitle: '01 / 06 · Weekday selection and pill semantics',
  selectionDescription: 'Caller order, explicit empty selection and disabled days are preserved. Tabs and pressed filters remain different interaction contracts.',
  days: 'Ordered fixture weekdays',
  disabledDays: 'Disabled fixture weekdays',
  monday: 'Monday — early operational review',
  wednesday: 'Wednesday — extended cross-team follow-up',
  friday: 'Friday — reserved and unavailable',
  sunday: 'Sunday — end-of-week evidence review',
  selectedDays: 'Selected day IDs in callback order: {{ids}}',
  none: 'None selected; this fixture does not infer all days.',
  clearDays: 'Clear weekday selection',
  filters: 'Pressed evidence filters',
  tabs: 'Roving metric tabs',
  all: 'All prepared evidence',
  unresolved: 'Unresolved observations with long contextual labels',
  unavailable: 'Unavailable specialist classification',
  activeFilter: 'Active filter: {{label}}',
  activeTab: 'Active metric: {{label}}',
  evidenceTitle: '02 / 05 · Categorical composition and rich details',
  evidenceDescription: 'Prepared proportions are not renormalized. Tiny omitted fills retain readable evidence; rich definition rows wrap within their own allocated width.',
  verified: 'Verified observations with complete supporting context',
  pending: 'Pending observations awaiting independent reconciliation',
  tiny: 'Rare classification deliberately omitted only from the track',
  zero: 'Measured zero occurrences',
  compositionSummary: 'Fixture composition: 750 verified, 249 pending, 1 rare and 0 measured-zero observations.',
  zeroSummary: 'Caller-prepared zero-total composition; no category has a measured occurrence.',
  count750: '750 observations · 75%',
  count249: '249 observations · 24.9%',
  count1: '1 observation · 0.1%; fill omitted',
  count0: '0 observations · 0%',
  identity: 'Evidence identity with a deliberately long wrapping label',
  identityValue: 'fixture-evidence/independent-review/long-stable-record-identifier-0007',
  readiness: 'Readiness and source provenance',
  readyBadge: 'Prepared fixture',
  note: 'Caller-supplied rich details remain selectable, readable and independent of ranking or source policy.',
  unknown: 'Unknown — no reading supplied',
  unknownLabel: 'Unresolved reading, not an invented zero',
  zeroLabel: 'Explicitly measured zero',
  copyTitle: '03 / 04 · Code payload and clipboard feedback',
  copyDescription: 'Displayed rich code can differ from its exact clipboard payload. Clipboard permission failures reveal caller-owned manual recovery without mutating global browser APIs.',
  code: 'Prepared JSON evidence payload',
  wrappedCode: 'Wrapped display with a separate copy action',
  copyPayload: 'Copy exact fixture payload',
  copyDisabled: 'Copy unavailable payload',
  copySuccess: 'The exact fixture payload was copied successfully.',
  copyFailure: 'Clipboard access failed. Select the exact payload below and copy it manually.',
  copyIdle: 'Clipboard outcome has not been requested.',
  showManual: 'Open manual-copy recovery example',
  closeManual: 'Close manual-copy recovery example',
  manual: 'Manual-copy payload',
  widgetTitle: '07 / 08 · Gauge readings and caller-ranked lists',
  widgetDescription: 'Preservation mode distinguishes unknown, measured zero, valid intervals and invalid scales. Ranking preserves caller business order independently of magnitude.',
  gaugeUnknown: 'Unknown fixture gauge',
  gaugeZero: 'Measured-zero fixture gauge',
  gaugeInterval: 'Prepared interval gauge',
  gaugeInvalid: 'Invalid caller-scale fixture gauge',
  gaugeStatus: 'Illustrative caller-defined status, not a health judgement',
  gaugeMarker: 'Caller reference point: 60',
  scoreUnit: 'fixture points',
  sourceOrder: 'Preserve caller rank order',
  magnitudeOrder: 'Use existing descending-value order',
  rankUnknown: 'First business-ranked item — reading still unresolved',
  rankZero: 'Second business-ranked item — verified measured zero',
  rankPositive: 'Third business-ranked item — complete evidence with a long explanatory label',
  rankNegative: 'Fourth business-ranked item — negative measured adjustment',
  rankEmpty: 'The prepared ranking contains no records.',
  eventTitle: '09 · Rich timeline rows and event feed',
  eventDescription: 'Prepared absolute UTC time labels prevent clock-dependent output. Source order remains explicit; title navigation and action controls are siblings, never nested.',
  eventFirst: 'First caller-ordered evidence review with an intentionally long title that must remain readable',
  eventSecond: 'Later timestamp, second in caller order',
  eventInvalid: 'Unparseable timestamp with caller-owned unresolved label',
  eventSubtitle: 'Independent context retained below the linked title across narrow containers.',
  eventMetadata: 'Fixture identity: review-0007 · unresolved value is unknown, not zero.',
  eventTimeFirst: '2026-08-01 09:00 UTC',
  eventTimeSecond: '2026-08-02 10:00 UTC',
  eventTimeUnknown: 'Time unresolved',
  eventAction: 'Inspect prepared event',
  eventActionResult: 'Inspected fixture event: {{id}}',
  eventIdle: 'No event action invoked.',
  eventEmpty: 'No prepared events in this independent feed.',
  newestFirst: 'Use newest-first event order',
  bulkTitle: '10 · Bulk selection scope and action recovery',
  bulkDescription: 'The toolbar only receives loaded IDs. Scope wording never invents a filtered denominator or silently expands selection.',
  selectLoaded: 'Select the two loaded fixture records',
  loadedSummary: '{{count}} loaded fixture records selected; filtered total unknown',
  filteredSummary: '{{count}} explicitly selected fixture records in a known 27-record filtered result',
  loadedScope: 'Loaded scope, unknown total',
  filteredScope: 'Filtered scope, known total',
  bulkExport: 'Prepare selected-record export',
  bulkFail: 'Exercise recoverable action failure',
  bulkDelete: 'Remove selected fixture records',
  bulkDisabled: 'Unavailable bulk operation',
  bulkDisabledReason: 'This prepared capability is disabled; no permission or matching-ID inference is performed.',
  bulkConfirm: 'Remove only the selected fixture records?',
  bulkConfirmDescription: 'This changes local DEV fixture selection only. No API call or production mutation is performed.',
  bulkResult: 'Action received these exact IDs: {{ids}}',
  bulkFailure: 'Synthetic action failed; the explicit selection remains available for retry.',
  bulkIdle: 'No bulk action invoked.',
  bulkPending: 'Prepared export is pending; complete it explicitly to inspect toolbar loading and disabled state.',
  bulkComplete: 'Complete the pending fixture export',
  sourceTitle: '11 · Specialist source states and independent neighbor',
  sourceDescription: 'Choose each source state without removing its shell. Specialist loading geometry, prerequisite-empty recovery and retained-error retry stay local to this source.',
  sourceLabel: 'Prepared specialist evidence',
  stateControls: 'Choose the fixture source state',
  loadingGeometry: 'Specialist loading geometry: three evidence rows',
  sourceEmpty: 'The prepared specialist source returned no records.',
  prerequisite: 'Specialist prerequisite: choose prepared evidence before evaluating this source.',
  resolvePrerequisite: 'Load prepared specialist evidence',
  sourceError: 'Synthetic specialist source failure; the independent neighbor remains successful.',
  sourceRetained: 'Synthetic refresh failed. All previously prepared evidence and its actions remain available.',
  neighbor: 'Successful independent neighbor',
  neighborBody: 'This independently prepared evidence remains visible in loading, empty, fatal-error and retained-error scenarios.',
  chartTitle: '12 · Canonical ChartCard capability chain',
  chartDescription: 'One LayoutCard title and one EmbeddedChart / ChartContainer controller. The plot intentionally uses fewer rows than the complete accessibility and CSV alternatives.',
  chartName: 'Prepared daily evidence score',
  chartLongDescription: 'Twelve deterministic observations. The visual line displays four; the accessible table and CSV retain all twelve, including unknown and measured-zero values.',
  chartDate: 'Fixture UTC date',
  chartValue: 'Evidence score',
  chartSource: 'DEV prepared evidence only',
  chartRange: '1–12 August 2026 · UTC',
  chartFreshness: 'Fixed fixture; not a live update time',
  chartEmpty: 'The prepared chart contains no observations.',
  chartEmptyDescription: 'Retain the canonical viewport and recovery action without drawing misleading axes.',
  chartError: 'Synthetic chart source failed.',
  chartRetry: 'Restore prepared chart observations',
  chartAction: 'Inspect complete chart scope',
  chartActionResult: 'Complete chart scope contains 12 observations; plotted subset contains 4.',
  chartIdle: 'No chart action invoked.',
  chartFooter: 'Complete evidence remains available in the data alternative and CSV. Toolbar actions operate on the same canonical frame.',
  orderedTitle: '13 · Caller-owned ordered instructions',
  accordionTitle: '14 · Stacked disclosure description',
  chronologyTitle: '15 · Explicit timeline summary chronology',
  containmentTitle: '16 · Small multiples in a narrow allocated slot',
  metricTitle: '17 · Compact passive readings',
  transportTitle: '18 · Optional playback capabilities',
  overviewTitle: '19 · Read-only temporal evidence',
  bipolarTitle: '20 · Missing, zero and signed readings',
  orderedName: 'Caller-prepared ordered instructions',
  orderedFirst: 'Prepare the complete caller-supplied evidence with its stable identity',
  orderedSecond: 'Review the prepared evidence without inferring completion or eligibility',
  completedState: 'Completed by the caller',
  currentState: 'Current step selected by the caller',
  recordAction: 'Record fixture action',
  actionCount: '{{count}} fixture actions recorded',
  chronologyLabel: 'Oldest-first prepared chronology',
  primarySeries: 'First complete series',
  secondarySeries: 'Second complete series',
  progressLabel: 'Prepared passive progress reading',
  missingProgress: 'Missing passive reading, not measured zero',
  overviewLabel: 'Read-only prepared events',
  unknownOverview: 'Read-only events with unknown temporal bounds',
  signedLabel: 'Caller-supplied asymmetric signed scale',
} as const;
