package io.teslasync.android.navigation

import androidx.annotation.StringRes
import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import io.teslasync.android.R

/**
 * Resolves [Destination] / [NavGroup] titles to localized string resources at the Compose boundary
 * (the route table itself is locale-agnostic data, per ADR-014). Unknown ids fall back to the
 * not-found title so a future destination can never crash the navigation chrome.
 */
@StringRes
fun navTitleRes(id: String): Int = titleRes[id] ?: R.string.nav_not_found

@StringRes
fun navGroupTitleRes(group: NavGroup): Int = groupRes.getValue(group)

@Composable
fun navTitle(destination: Destination): String = stringResource(navTitleRes(destination.id))

@Composable
fun navGroupTitle(group: NavGroup): String = stringResource(navGroupTitleRes(group))

private val titleRes: Map<String, Int> =
    mapOf(
        "dashboard" to R.string.nav_dashboard,
        "quickStats" to R.string.nav_quick_stats,
        "glance" to R.string.nav_glance,
        "explore" to R.string.nav_explore,
        "vehicles" to R.string.nav_vehicles,
        "vehicleDetail" to R.string.nav_vehicle_detail,
        "vehicleAccess" to R.string.nav_vehicle_access,
        "digitalTwin" to R.string.nav_digital_twin,
        "charging" to R.string.nav_charging,
        "chargeDetail" to R.string.nav_charge_detail,
        "chargingCurve" to R.string.nav_charging_curve,
        "chargingHeatmap" to R.string.nav_charging_heatmap,
        "costAnalysis" to R.string.nav_cost_analysis,
        "teslaChargingHistory" to R.string.nav_tesla_charging_history,
        "teslaChargingSessions" to R.string.nav_tesla_charging_sessions,
        "smartCharge" to R.string.nav_smart_charge,
        "powershare" to R.string.nav_powershare,
        "trips" to R.string.nav_trips,
        "tripDetail" to R.string.nav_trip_detail,
        "drives" to R.string.nav_drives,
        "driveDetail" to R.string.nav_drive_detail,
        "tripReplay" to R.string.nav_trip_replay,
        "driveScore" to R.string.nav_drive_score,
        "drivingDynamics" to R.string.nav_driving_dynamics,
        "drivetrainHealth" to R.string.nav_drivetrain_health,
        "efficiency" to R.string.nav_efficiency,
        "speedProfile" to R.string.nav_speed_profile,
        "regenEfficiency" to R.string.nav_regen_efficiency,
        "routeEfficiency" to R.string.nav_route_efficiency,
        "tripPlanner" to R.string.nav_trip_planner,
        "energy" to R.string.nav_energy,
        "batteryHealth" to R.string.nav_battery_health,
        "batteryCells" to R.string.nav_battery_cells,
        "batteryDegradation" to R.string.nav_battery_degradation,
        "energyFlow" to R.string.nav_energy_flow,
        "powerFlow" to R.string.nav_power_flow,
        "energyProducts" to R.string.nav_energy_products,
        "vampireDrain" to R.string.nav_vampire_drain,
        "projectedRange" to R.string.nav_projected_range,
        "sleepEfficiency" to R.string.nav_sleep_efficiency,
        "analytics" to R.string.nav_analytics,
        "statistics" to R.string.nav_statistics,
        "periodCompare" to R.string.nav_period_compare,
        "mileage" to R.string.nav_mileage,
        "trueCost" to R.string.nav_true_cost,
        "weeklyDigest" to R.string.nav_weekly_digest,
        "timeline" to R.string.nav_timeline,
        "fleetCompare" to R.string.nav_fleet_compare,
        "lifetimeStats" to R.string.nav_lifetime_stats,
        "yearReview" to R.string.nav_year_review,
        "liveMap" to R.string.nav_live_map,
        "locations" to R.string.nav_locations,
        "geofences" to R.string.nav_geofences,
        "navigationRoute" to R.string.nav_navigation_route,
        "temperatureImpact" to R.string.nav_temperature_impact,
        "climateControl" to R.string.nav_climate_control,
        "tirePressure" to R.string.nav_tire_pressure,
        "maintenance" to R.string.nav_maintenance,
        "softwareUpdates" to R.string.nav_software_updates,
        "safetySettings" to R.string.nav_safety_settings,
        "guardMode" to R.string.nav_guard_mode,
        "mediaPlayer" to R.string.nav_media_player,
        "automations" to R.string.nav_automations,
        "automationList" to R.string.nav_automation_list,
        "automationBuilder" to R.string.nav_automation_builder,
        "notificationsInbox" to R.string.nav_notifications_inbox,
        "notificationsArchived" to R.string.nav_notifications_archived,
        "notificationsAlerts" to R.string.nav_notifications_alerts,
        "notificationsChannels" to R.string.nav_notifications_channels,
        "notificationsWebhooks" to R.string.nav_notifications_webhooks,
        "notificationsBrowser" to R.string.nav_notifications_browser,
        "notificationsQuietHours" to R.string.nav_notifications_quiet_hours,
        "notificationsRules" to R.string.nav_notifications_rules,
        "notificationsStudio" to R.string.nav_notifications_studio,
        "notificationsAudit" to R.string.nav_notifications_audit,
        "signalsWorkspace" to R.string.nav_signals_workspace,
        "signalExplorer" to R.string.nav_signal_explorer,
        "signalLog" to R.string.nav_signal_log,
        "liveSignalMonitor" to R.string.nav_live_signal_monitor,
        "signalDiff" to R.string.nav_signal_diff,
        "signalGaps" to R.string.nav_signal_gaps,
        "mqttInspector" to R.string.nav_mqtt_inspector,
        "anomalyDetection" to R.string.nav_anomaly_detection,
        "devTools" to R.string.nav_dev_tools,
        "apiKeys" to R.string.nav_api_keys,
        "apiLogs" to R.string.nav_api_logs,
        "fleetApi" to R.string.nav_fleet_api,
        "teslaFeatures" to R.string.nav_tesla_features,
        "teslaRegion" to R.string.nav_tesla_region,
        "teslaOrders" to R.string.nav_tesla_orders,
        "gasPrice" to R.string.nav_gas_price,
        "securityAccess" to R.string.nav_security_access,
        "backup" to R.string.nav_backup,
        "apiPlayground" to R.string.nav_api_playground,
        "redisSignals" to R.string.nav_redis_signals,
        "adminFeedback" to R.string.nav_admin_feedback,
        "adminTelemetryCoverage" to R.string.nav_admin_telemetry_coverage,
        "adminDlq" to R.string.nav_admin_dlq,
        "adminFlags" to R.string.nav_admin_flags,
        "adminIngestXray" to R.string.nav_admin_ingest_xray,
        "adminLiveSignals" to R.string.nav_admin_live_signals,
        "adminSchemaDrift" to R.string.nav_admin_schema_drift,
        "adminSlowQueries" to R.string.nav_admin_slow_queries,
        "adminVehicleCost" to R.string.nav_admin_vehicle_cost,
        "adminDiskForecast" to R.string.nav_admin_disk_forecast,
        "adminSecretRotation" to R.string.nav_admin_secret_rotation,
        "adminAuditLog" to R.string.nav_admin_audit_log,
        "adminGdprExports" to R.string.nav_admin_gdpr_exports,
        "powerSql" to R.string.nav_power_sql,
        "powerGrafana" to R.string.nav_power_grafana,
        "powerDashboards" to R.string.nav_power_dashboards,
        "systemStatus" to R.string.nav_system_status,
        "incidentTimeline" to R.string.nav_incident_timeline,
        "statusApiDocs" to R.string.nav_status_api_docs,
        "dataExport" to R.string.nav_data_export,
        "exports" to R.string.nav_exports,
        "dataRepair" to R.string.nav_data_repair,
        "dbHealth" to R.string.nav_db_health,
        "stateDebugger" to R.string.nav_state_debugger,
        "commands" to R.string.nav_commands,
        "commandHistory" to R.string.nav_command_history,
        "chatbot" to R.string.nav_chatbot,
        "roadmap" to R.string.nav_roadmap,
        "teslaAccount" to R.string.nav_tesla_account,
        "myActivity" to R.string.nav_my_activity,
        "settings" to R.string.nav_settings,
        "settingsSafety" to R.string.nav_settings_safety,
        "account2fa" to R.string.nav_account_2fa,
        "accountSessions" to R.string.nav_account_sessions,
        "accountPrivacy" to R.string.nav_account_privacy,
        "integrationsHelix" to R.string.nav_integrations_helix,
        "onboarding" to R.string.nav_onboarding,
        "search" to R.string.nav_search,
        "sharedDrive" to R.string.nav_shared_drive,
        "sharingTrips" to R.string.nav_sharing_trips,
        "watchFace" to R.string.nav_watch_face,
        "notFound" to R.string.nav_not_found,
    )

private val groupRes: Map<NavGroup, Int> =
    mapOf(
        NavGroup.Dashboard to R.string.nav_group_dashboard,
        NavGroup.Vehicles to R.string.nav_group_vehicles,
        NavGroup.Charging to R.string.nav_group_charging,
        NavGroup.TripsDrives to R.string.nav_group_trips_drives,
        NavGroup.BatteryEnergy to R.string.nav_group_battery_energy,
        NavGroup.Analytics to R.string.nav_group_analytics,
        NavGroup.Maps to R.string.nav_group_maps,
        NavGroup.VehicleSystems to R.string.nav_group_vehicle_systems,
        NavGroup.Automations to R.string.nav_group_automations,
        NavGroup.Notifications to R.string.nav_group_notifications,
        NavGroup.Telemetry to R.string.nav_group_telemetry,
        NavGroup.Diagnostics to R.string.nav_group_diagnostics,
        NavGroup.Admin to R.string.nav_group_admin,
        NavGroup.PowerUser to R.string.nav_group_power_user,
        NavGroup.System to R.string.nav_group_system,
        NavGroup.Settings to R.string.nav_group_settings,
        NavGroup.Onboarding to R.string.nav_group_onboarding,
        NavGroup.Search to R.string.nav_group_search,
        NavGroup.Sharing to R.string.nav_group_sharing,
        NavGroup.Watch to R.string.nav_group_watch,
        NavGroup.NotFound to R.string.nav_group_not_found,
    )
