import { Icons, type LucideIcon } from '@/lib/icons'
import { SidebarGlyphs } from '@/lib/sidebarGlyphs'

export const SIDEBAR_SHORTCUT_ICONS = {
  search: Icons.search,
  suggested: Icons.sparkles,
  saved: Icons.star,
  allPages: Icons.compass,
  alerts: Icons.notificationsActive,
  display: Icons.palette,
}

// Destination glyphs are stable across navigation styles and when a page is pinned.
export const SIDEBAR_ROUTE_ICONS: Record<string, LucideIcon> = {
  '/energy': SidebarGlyphs.filePieChart,
  '/destination-transitions': SidebarGlyphs.waypoints,
  '/explore': SidebarGlyphs.folderSearch,
  '/journeys': SidebarGlyphs.listStart,
  '/action-center': SidebarGlyphs.bellDot,
  '/vehicles': SidebarGlyphs.keySquare,
  '/drive-dna': SidebarGlyphs.scanFace,
  '/notifications/browser': SidebarGlyphs.bellElectric,
  '/tesla-physics': SidebarGlyphs.telescope,
  '/charger-health': SidebarGlyphs.plug2,
  '/tesla-api-usage': Icons.satellite,
  '/signals': SidebarGlyphs.signalHigh,
  '/signal-change-points': Icons.arrowUpFromDot,
  '/ownership/data-governance': Icons.folderOpen,
  '/api-logs': SidebarGlyphs.fileClock,
  '/utilization': Icons.layoutGrid,
  '/driving-dynamics': Icons.arrowUpDown,
  '/outage': Icons.warning,
  '/command-history': Icons.skipBack,
  '/admin/audit-log': SidebarGlyphs.bookText,
  '/fsd': Icons.bot,
  '/drivetrain-health': SidebarGlyphs.serverCog,
  '/intelligence/federated-learning': SidebarGlyphs.usersRound,
  '/battery-passport': SidebarGlyphs.bookMarked,
  '/benchmarks/privacy': Icons.hide,
  '/command-reliability': Icons.success,
  '/notifications/health': Icons.successFilled,
  '/ownership/insurance-telematics': SidebarGlyphs.shieldPlus,
  '/safety-settings': SidebarGlyphs.shieldQuestion,
  '/account/2fa': Icons.keyRound,
  '/milestones': Icons.flag,
  '/explorer': Icons.map,
  '/intelligence/road-hazards': Icons.alertCircle,
  '/roadmap': SidebarGlyphs.listTree,
  '/tco': SidebarGlyphs.calculator,
  '/ownership/subscription-roi': Icons.drillThrough,
  '/admin/vehicle-cost': SidebarGlyphs.circleDollarSign,
  '/charging-curve': SidebarGlyphs.scatterChart,
  '/admin/disk-forecast': SidebarGlyphs.hardDriveUpload,
  '/signal-trend': SidebarGlyphs.audioWaveform,
  '/drive-calendar': SidebarGlyphs.calendarDays,
  '/departure-forecast': SidebarGlyphs.sunrise,
  '/charging-heatmap': SidebarGlyphs.calendarRange,
  '/smart-charge': SidebarGlyphs.alarmClock,
  '/preconditioning-effectiveness': SidebarGlyphs.thermometerSnowflake,
  '/projected-range': SidebarGlyphs.signalMedium,
  '/intelligence/tco-optimizer': SidebarGlyphs.coins,
  '/ownership/model-trust': Icons.helpCircle,
  '/ownership/warranty-command': SidebarGlyphs.badgeDollarSign,
  '/firmware-impact': Icons.refresh,
  '/signal-mutual-information': SidebarGlyphs.gitFork,
  '/cycle-stress': Icons.batteryWarning,
  '/hvac-cycling': Icons.wind,
  '/intelligence/journey-assurance': Icons.checklist,
  '/signal-deadband': SidebarGlyphs.listFilter,
  '/intelligence/component-survival': SidebarGlyphs.timerOff,
  '/diagnostics/rul': SidebarGlyphs.hourglass,
  '/admin/slow-queries': SidebarGlyphs.clock3,
  '/charger-resilience': SidebarGlyphs.plugZap,
  '/intelligence/twin-lab': SidebarGlyphs.dna,
  '/diagnostics/root-cause': Icons.drillDown,
  '/signal-correlation': SidebarGlyphs.axis3d,
  '/energy-orchestrator': SidebarGlyphs.databaseZap,
  '/automations': Icons.redo,
  '/intelligence/firmware-canary': Icons.batteryMedium,
  '/tesla-features': Icons.settingsAlt,
  '/admin/flags': SidebarGlyphs.fileSliders,
  '/energy-ledger': SidebarGlyphs.receiptText,
  '/intelligence/charging-forensics': SidebarGlyphs.microscope,
  '/ownership/charging-reconciliation': SidebarGlyphs.creditCard,
  '/intelligence/behavioral-sentinel': SidebarGlyphs.scanEye,
  '/guard-mode': SidebarGlyphs.siren,
  '/cabin-thermal': Icons.flame,
  '/temperature-impact': Icons.weather,
  '/power-flow': Icons.power,
  '/intelligence/charging-site-twin': SidebarGlyphs.cableCar,
  '/range-buffer': SidebarGlyphs.batteryLow,
  '/tire-differential-drift': Icons.split,
  '/ownership/tariff-lab': SidebarGlyphs.landmark,
  '/intelligence/emergency-resilience': SidebarGlyphs.briefcaseMedical,
  '/data-repair': Icons.undo,
  '/system-status': SidebarGlyphs.signalLow,
  '/ownership/consumables-lifecycle': Icons.archive,
  '/intelligence-packs': SidebarGlyphs.puzzle,
  '/admin/ingest-xray': Icons.arrowDownToDot,
  '/admin/data-quality': Icons.error,
  '/anomaly-detection': SidebarGlyphs.badgeAlert,
  '/signal-entropy': SidebarGlyphs.binary,
  '/tesla-region': SidebarGlyphs.globe2,
  '/admin/telemetry/coverage': SidebarGlyphs.radioReceiver,
  '/mqtt-inspector': SidebarGlyphs.signalZero,
  '/admin/gdpr-exports': Icons.fileDown,
  '/science': SidebarGlyphs.flaskConical,
  '/vehicle-management': SidebarGlyphs.factory,
  '/speed-profile': Icons.locate,
  '/segments': Icons.ghost,
  '/charge-departure-alignment': SidebarGlyphs.calendarHeart,
  '/charge-advisor': Icons.lightbulb,
  '/period-compare': SidebarGlyphs.calendarFold,
  '/analytics/carbon': SidebarGlyphs.trees,
  '/drive-archetypes': SidebarGlyphs.libraryBig,
  '/notifications/quiet-hours': Icons.moonStar,
  '/account/sessions': Icons.userCheck,
  '/me/activity': SidebarGlyphs.clock4,
  '/admin/schema-drift': Icons.undoAlt,
  '/admin/secret-rotation': Icons.unlocked,
  // Yielded glyphs: these destinations gave their literal glyphs to their
  // section icons (sections render icon-only on the collapsed rail, so
  // they get first pick of literal glyphs; destinations always show
  // labels). Keeps the glyph-uniqueness contract intact.
  '/charging': Icons.cloudLightning,
  '/analytics': Icons.fileSpreadsheet,
  '/maintenance': SidebarGlyphs.briefcaseBusiness,
  '/journey-fragmentation': SidebarGlyphs.listCollapse,
  '/api-playground': Icons.keyboard,
  '/notifications/inbox': Icons.speaker,
  '/security-access': Icons.doorOpen,
  '/tesla-account': Icons.userPlus,
  '/service-intelligence': SidebarGlyphs.bookOpen,
}

export const SIDEBAR_SECTION_ICONS: Record<string, LucideIcon> = {
  Home: Icons.layoutTemplate,
  Vehicles: SidebarGlyphs.carFront,
  'Tesla Physics': SidebarGlyphs.atom,
  Driving: Icons.navigation,
  Charging: Icons.charger,
  Battery: Icons.batteryCharging,
  Energy: Icons.bolt,
  Service: Icons.maintenance,
  Cabin: Icons.cabin,
  Reports: Icons.analytics,
  Commands: Icons.terminal,
  Automation: Icons.workflow,
  Notifications: Icons.notifications,
  'Advanced Intelligence': SidebarGlyphs.sparkle,
  'Ownership Intelligence': SidebarGlyphs.handshake,
  Security: Icons.locked,
  Account: Icons.user,
  Settings: SidebarGlyphs.cog,
  Integrations: Icons.network,
  Data: Icons.database,
  Diagnostics: Icons.stethoscope,
  About: Icons.info,
}
