import { Icons, type LucideIcon } from '@/lib/icons'
import { CollectionGlyphs } from '@/lib/sidebarCollectionGlyphs'

export const SIDEBAR_COLLECTION_ICONS: Record<string, LucideIcon> = {
  '/statistics': CollectionGlyphs.panelTop,
  '/efficiency': CollectionGlyphs.grid2x2,
  '/cost-analysis': CollectionGlyphs.banknote,
  '/system-status': CollectionGlyphs.badgeInfo,
  '/db-health': CollectionGlyphs.folderSearch,
  '/signals': Icons.wifi,
  '/signal-correlation': CollectionGlyphs.routeOff,
  '/anomaly-detection': CollectionGlyphs.badgeX,
  '/timeline': Icons.skipForward,
  '/vehicles': CollectionGlyphs.bus,
  '/digital-twin': Icons.tv,
  '/locations': Icons.locate,
  '/drives': Icons.calendarPlus,
  '/trips': CollectionGlyphs.ticket,
  '/journeys': Icons.departure,
  '/drive-score': Icons.star,
  '/driving-dynamics': CollectionGlyphs.bike,
  '/charging': CollectionGlyphs.cable,
  '/smart-charge': CollectionGlyphs.sunset,
  '/charger-health': Icons.securityOff,
  '/battery': CollectionGlyphs.heartHandshake,
  '/projected-range': Icons.wifiOff,
  '/energy': Icons.cloudLightning,
  '/maintenance': CollectionGlyphs.fileHeart,
  '/tire-pressure': CollectionGlyphs.ambulance,
  '/software-updates': Icons.upload,
  '/climate-control': Icons.weather,
  '/commands': Icons.play,
  '/automations': CollectionGlyphs.messageSquareCode,
  '/notifications/inbox': Icons.speaker,
  '/security-access': Icons.userX,
  '/tesla-account': Icons.doorOpen,
  '/chatbot': CollectionGlyphs.messageCircleMore,
  '/data-export': Icons.fileSpreadsheet,
  '/ownership/tariff-lab': CollectionGlyphs.circlePercent,
  '/ownership/driver-attribution': CollectionGlyphs.userRoundCheck,
  '/admin/flags': CollectionGlyphs.userRoundCog,
  '/dev-tools': CollectionGlyphs.code2,
}
