// <auto-generated path="web/src/lib/globalShortcuts.tsx, web/src/hooks/useKeyboardShortcuts.ts, web/src/lib/commandRegistry.ts" />
// Faithful transcription of the three static module-level sources the web GlobalShortcuts seeder
// (web/src/lib/globalShortcuts.tsx) pours into the shortcut registry via useShortcut(defs):
//   1. The four universal app keys (Ctrl+K, /, ?, Esc) — group "Actions".
//   2. Every GOTO_SHORTCUTS entry (web/src/hooks/useKeyboardShortcuts.ts) — the g+letter navigation
//      table — group "Navigation (press g then…)".
//   3. Every commandRegistry entry (web/src/lib/commandRegistry.ts) that declares a `shortcut` hint
//      — group "Commands".
// Each entry carries only the launcher-relevant fields (id, key tokens, i18n key + English fallback,
// and — for navigation — the route the g+letter targets). Fallbacks mirror the canonical English
// values in Strings/en/Resources.resw so the headless projection asserts the same copy the app renders.

using System.Globalization;
using TeslaSync.App.Core.Notifications;
using TeslaSync.App.ModalsDialogs;

namespace TeslaSync.App.MiscSurfaces;

/// <summary>
/// One universal global shortcut — the native projection of a web "universal" entry in
/// <c>GlobalShortcuts</c> (the four app-wide keys <c>Ctrl+K</c>, <c>/</c>, <c>?</c>, <c>Esc</c>). Holds the
/// stable <see cref="Id"/>, the display <see cref="Keys"/> tokens, and the description i18n key + English
/// fallback. Pure data, asserted headlessly.
/// </summary>
/// <param name="Id">The stable definition id (web <c>id</c>).</param>
/// <param name="Keys">The key tokens, each rendered as a <c>kbd</c> chip (web <c>keys</c>).</param>
/// <param name="DescriptionKey">i18n key for the description.</param>
/// <param name="DescriptionFallback">English fallback for <paramref name="DescriptionKey"/>.</param>
public sealed record GlobalActionShortcut(
    string Id,
    IReadOnlyList<string> Keys,
    string DescriptionKey,
    string DescriptionFallback);

/// <summary>
/// One navigation global shortcut — the native projection of a web <c>GOTO_SHORTCUTS</c> entry
/// (web/src/hooks/useKeyboardShortcuts.ts). The web composes its description as
/// <c>t('shortcuts.goto', 'Go to {{label}}', { label })</c>, so this carries the destination
/// <see cref="Path"/> (for parity/data completeness) and the label i18n key + the exact web label as the
/// fallback. The web's <c>GOTO_SHORTCUTS</c> labels are raw English literals; giving each its own keyed
/// fallback keeps the rendered copy identical while still flowing through the i18n facade. Pure data.
/// </summary>
/// <param name="Key">The second key token (web object key, e.g. <c>"d"</c>); the chord is <c>g</c> then this.</param>
/// <param name="Path">The route the g+letter navigates to (web <c>target.path</c>).</param>
/// <param name="LabelKey">i18n key for the destination label interpolated into the "Go to {0}" template.</param>
/// <param name="LabelFallback">The exact web <c>target.label</c> string (English fallback).</param>
public sealed record GlobalNavigationShortcut(
    string Key,
    string Path,
    string LabelKey,
    string LabelFallback);

/// <summary>
/// One palette-command global shortcut — the native projection of a web <c>commandRegistry</c> entry that
/// declares a <c>shortcut</c> hint (web/src/lib/commandRegistry.ts). The web registers these informationally
/// so the cheatsheet lists them; the palette command itself owns the live key handling. Holds the source
/// command id, the single key token, and the command's label i18n key + English fallback. Pure data.
/// </summary>
/// <param name="CommandId">The source <c>commandRegistry</c> id (web <c>c.id</c>).</param>
/// <param name="Key">The shortcut hint token (web <c>c.shortcut</c>, e.g. <c>"T"</c>).</param>
/// <param name="LabelKey">The command's label i18n key (web <c>c.labelKey</c>).</param>
/// <param name="LabelFallback">English fallback for <paramref name="LabelKey"/> (web <c>c.labelFallback</c>).</param>
public sealed record GlobalCommandShortcut(
    string CommandId,
    string Key,
    string LabelKey,
    string LabelFallback);

/// <summary>
/// The static global-shortcut catalogue the <see cref="GlobalShortcuts"/> seeder registers — the native
/// projection of the three module-level sources the web <c>GlobalShortcuts</c> composes
/// (web/src/lib/globalShortcuts.tsx): the four universals, the <c>GOTO_SHORTCUTS</c> navigation table, and
/// the <c>commandRegistry</c> entries that declare a <c>shortcut</c>. The web component imports these as
/// module data (not via a hook), so the native surface seeds its model from the same fixed catalogue.
/// <see cref="Build"/> resolves every label through the i18n facade and projects the catalogue into the
/// shared <see cref="ShortcutDefinition"/> records (all <see cref="ShortcutScope.Global"/>, exactly as the
/// web sets <c>scope: 'global'</c>) the registry + cheatsheet consume. Pure (no WinUI types) so the
/// projection is asserted without a UI host.
/// </summary>
public static class GlobalShortcutsCatalog
{
    /// <summary>Number of universal shortcuts (web universals array length).</summary>
    public const int UniversalCount = 4;

    /// <summary>Number of navigation shortcuts (web <c>GOTO_SHORTCUTS</c> entry count).</summary>
    public const int NavigationCount = 14;

    /// <summary>Number of palette-command shortcuts (web <c>commandRegistry.filter(c =&gt; c.shortcut)</c> length).</summary>
    public const int CommandCount = 3;

    /// <summary>Total definitions the seeder registers (web <c>[...universals, ...navigation, ...palette].length</c>).</summary>
    public const int TotalCount = UniversalCount + NavigationCount + CommandCount;

    /// <summary>
    /// The four universal app keys, in web order: <c>Ctrl+K</c> and <c>/</c> (open palette), <c>?</c> (show
    /// shortcuts) and <c>Esc</c> (close / cancel). All render under the "Actions" group.
    /// </summary>
    public static IReadOnlyList<GlobalActionShortcut> Universals { get; } = new GlobalActionShortcut[]
    {
        new("global.palette.ctrlk", new[] { "Ctrl", "K" }, "translation.shortcuts.openPalette", "Open command palette"),
        new("global.palette.slash", new[] { "/" }, "translation.shortcuts.openPaletteAlt", "Open command palette"),
        new("global.shortcuts.help", new[] { "?" }, "translation.shortcuts.openShortcuts", "Show keyboard shortcuts"),
        new("global.shortcuts.escape", new[] { "Esc" }, "translation.shortcuts.close", "Close modal / cancel"),
    };

    /// <summary>
    /// The g+letter navigation table, in web <c>GOTO_SHORTCUTS</c> declaration order. Each entry's chord is
    /// <c>g</c> then the entry key; the description is "Go to {label}". All render under the "Navigation"
    /// group. The fallbacks transcribe the web <c>target.label</c> strings verbatim.
    /// </summary>
    public static IReadOnlyList<GlobalNavigationShortcut> Navigation { get; } = new GlobalNavigationShortcut[]
    {
        new("d", "/", "translation.shortcuts.gotoTarget.dashboard", "Dashboard"),
        new("v", "/vehicles", "translation.shortcuts.gotoTarget.vehicles", "Vehicles"),
        new("c", "/charging", "translation.shortcuts.gotoTarget.charging", "Charging"),
        new("r", "/drives", "translation.shortcuts.gotoTarget.drives", "Drives"),
        new("t", "/trips", "translation.shortcuts.gotoTarget.trips", "Trips"),
        new("b", "/battery", "translation.shortcuts.gotoTarget.battery", "Battery & Energy"),
        new("a", "/analytics", "translation.shortcuts.gotoTarget.analytics", "Analytics"),
        new("e", "/efficiency", "translation.shortcuts.gotoTarget.efficiency", "Efficiency"),
        new("s", "/settings", "translation.shortcuts.gotoTarget.settings", "Settings"),
        new("n", "/notifications/inbox", "translation.shortcuts.gotoTarget.notifications", "Notifications"),
        new("l", "/live-signals", "translation.shortcuts.gotoTarget.liveSignals", "Live Signals"),
        new("o", "/automations", "translation.shortcuts.gotoTarget.automations", "Automations"),
        new("x", "/commands", "translation.shortcuts.gotoTarget.commands", "Commands"),
        new("i", "/climate", "translation.shortcuts.gotoTarget.climate", "Climate"),
    };

    /// <summary>
    /// The palette commands that declare a <c>shortcut</c> hint, in web <c>commandRegistry</c> declaration
    /// order: theme picker (<c>T</c>), keyboard shortcuts (<c>?</c>) and dashboard edit (<c>E</c>). All render
    /// under the "Commands" group.
    /// </summary>
    public static IReadOnlyList<GlobalCommandShortcut> Commands { get; } = new GlobalCommandShortcut[]
    {
        new("pref.themePicker", "T", "translation.palette.cmd.themePicker", "Open theme picker"),
        new("action.shortcuts", "?", "translation.palette.cmd.shortcuts", "Show keyboard shortcuts"),
        new("action.dashboard.edit", "E", "translation.palette.cmd.dashboardEdit", "Edit dashboard layout"),
    };

    /// <summary>
    /// Project the catalogue into the shared <see cref="ShortcutDefinition"/> records the registry + cheatsheet
    /// consume — the native port of the web <c>defs</c> <c>useMemo</c>. Resolves the three group titles and the
    /// "Go to {0}" template through <paramref name="localizer"/>, composes each navigation description from the
    /// template + the destination label, and emits the definitions in web order
    /// (<c>[...universals, ...navigation, ...palette]</c>), every one <see cref="ShortcutScope.Global"/>.
    /// </summary>
    /// <param name="localizer">The i18n facade every label resolves through (web <c>useTranslation</c>).</param>
    public static IReadOnlyList<ShortcutDefinition> Build(ILocalizer localizer)
    {
        ArgumentNullException.ThrowIfNull(localizer);

        string actionsGroup = localizer.GetString(
            GlobalShortcutsRegistration.ActionsGroupKey, GlobalShortcutsRegistration.ActionsGroupFallback);
        string navigationGroup = localizer.GetString(
            GlobalShortcutsRegistration.NavigationGroupKey, GlobalShortcutsRegistration.NavigationGroupFallback);
        string commandsGroup = localizer.GetString(
            GlobalShortcutsRegistration.CommandsGroupKey, GlobalShortcutsRegistration.CommandsGroupFallback);
        string gotoTemplate = localizer.GetString(
            GlobalShortcutsRegistration.GotoTemplateKey, GlobalShortcutsRegistration.GotoTemplateFallback);

        var defs = new List<ShortcutDefinition>(TotalCount);

        foreach (GlobalActionShortcut action in Universals)
        {
            defs.Add(new ShortcutDefinition
            {
                Id = action.Id,
                Keys = action.Keys,
                Description = localizer.GetString(action.DescriptionKey, action.DescriptionFallback),
                Group = actionsGroup,
                Scope = ShortcutScope.Global,
            });
        }

        foreach (GlobalNavigationShortcut nav in Navigation)
        {
            string label = localizer.GetString(nav.LabelKey, nav.LabelFallback);
            defs.Add(new ShortcutDefinition
            {
                Id = $"global.goto.{nav.Key}",
                Keys = new[] { "g", nav.Key },
                Description = string.Format(CultureInfo.CurrentCulture, gotoTemplate, label),
                Group = navigationGroup,
                Scope = ShortcutScope.Global,
            });
        }

        foreach (GlobalCommandShortcut command in Commands)
        {
            defs.Add(new ShortcutDefinition
            {
                Id = $"global.palette.cmd.{command.CommandId}",
                Keys = new[] { command.Key },
                Description = localizer.GetString(command.LabelKey, command.LabelFallback),
                Group = commandsGroup,
                Scope = ShortcutScope.Global,
            });
        }

        return defs;
    }
}
