import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import { applyDocumentDirection } from '@/lib/i18nDir'
import ar from './ar.json'
import englishShell from './en/shell.json'
import runtimeManifest from './en/runtime-manifest.json'
import he from './he.json'

const englishNamespaceModules = import.meta.glob<{ default: Record<string, unknown> }>(
  './en/locale-*.json',
)

/**
 * Slim projection of `en/usage-manifest.json` generated by
 * `scripts/split-i18n-catalog.mjs`.
 *
 * `complete` lists namespaces the static shell already carries in full,
 * `missing` lists keys the source references that the catalog provably cannot
 * answer, `detail` lists namespaces that own a
 * `locale-detail-<namespace>.json` chunk, and `grouped` maps a feature bundle
 * to the namespaces it carries. The full manifest is ~50 KB gzipped and stays
 * out of the startup chunk — only this resolution table ships.
 */
interface LocaleRuntimeManifest {
  complete: string[]
  missing: string[]
  detail: string[]
  grouped: Record<string, string[]>
}

const manifest = runtimeManifest as LocaleRuntimeManifest
const completeNamespaces = new Set(manifest.complete)
const knownMissingKeys = new Set(manifest.missing)
const detailNamespaces = new Set(manifest.detail)
const groupedNamespaceBundles = new Map<string, string>()
for (const [bundle, namespaces] of Object.entries(manifest.grouped)) {
  for (const namespace of namespaces) groupedNamespaceBundles.set(namespace, bundle)
}
// A complete namespace has no chunk of its own — the shell already carries it —
// but it is still a real namespace, so it must pass the known-namespace gate.
const knownEnglishNamespaces = new Set([
  ...completeNamespaces,
  ...detailNamespaces,
  ...groupedNamespaceBundles.keys(),
])

/** i18next plural/context suffixes appended to a base key at lookup time. */
const PLURAL_SUFFIX = /^(.+?)(?:_[A-Za-z0-9]+)?(?:_ordinal)?_(?:zero|one|two|few|many|other)$/

function fallbackBundleFor(namespace: string): string | undefined {
  if (detailNamespaces.has(namespace)) return `detail-${namespace}`
  return groupedNamespaceBundles.get(namespace)
}

/**
 * True when the statically embedded shell can already answer `key`.
 *
 * i18next reports a plural lookup under its base key, so a shell that ships
 * `count_one` / `count_other` must not be treated as missing `count`.
 */
function shellResolves(key: string): boolean {
  const segments = key.split('.')
  const leaf = segments.pop()
  if (!leaf) return false
  let node: unknown = englishShell
  for (const segment of segments) {
    if (!node || typeof node !== 'object') return false
    node = (node as Record<string, unknown>)[segment]
  }
  if (!node || typeof node !== 'object') return false
  const parent = node as Record<string, unknown>
  if (Object.prototype.hasOwnProperty.call(parent, leaf)) return true
  const base = PLURAL_SUFFIX.exec(leaf)?.[1] ?? leaf
  return Object.keys(parent).some(
    (candidate) => candidate === base || candidate.startsWith(`${base}_`),
  )
}

/**
 * True when the build proved no chunk can ever answer `key`.
 *
 * i18next may report either the literal key or one of its plural forms, so
 * both are checked against the generated list.
 */
function isKnownMissing(key: string): boolean {
  if (knownMissingKeys.has(key)) return true
  const segments = key.split('.')
  const leaf = segments.pop()
  if (!leaf) return false
  const base = PLURAL_SUFFIX.exec(leaf)?.[1]
  return base !== undefined && knownMissingKeys.has([...segments, base].join('.'))
}

function recordProbeMissingKey(key: string) {
  const target = globalThis as typeof globalThis & { __TESLASYNC_I18N_PROBE_KEYS__?: string[] }
  if (target.__TESLASYNC_I18N_PROBE_KEYS__) target.__TESLASYNC_I18N_PROBE_KEYS__.push(key)
}

i18n.use(initReactI18next).init({
  resources: {
    ar: { translation: ar },
    en: { translation: englishShell },
    he: { translation: he },
  },
  lng: 'en',
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
  react: {
    bindI18n: 'languageChanged',
    bindI18nStore: 'added',
  },
  saveMissing: true,
  missingKeyHandler: (_languages, namespace, key) => {
    if (namespace !== 'translation') return
    const keyPath = String(key)
    if (!keyPath.includes('.')) return
    const topLevelNamespace = keyPath.split('.')[0]
    if (!knownEnglishNamespaces.has(topLevelNamespace)) return
    // The shell already carries this namespace end to end, so a miss is a
    // source typo. Fetching a chunk we already hold would waste a request on
    // every cold render — including a direct NotFound hit.
    if (completeNamespaces.has(topLevelNamespace)) return
    // The build proved this key is absent from en.json, so the chunk that
    // would be fetched cannot contain it. Requesting it burns a round trip and
    // a slot in the route's deferred-locale budget for nothing.
    if (isKnownMissing(keyPath)) return
    // Already answerable offline: a genuine typo, not a deferred namespace.
    if (shellResolves(keyPath)) return
    recordProbeMissingKey(keyPath)
    void requestEnglishNamespace(topLevelNamespace)
  },
})

// Keep <html dir> + <html lang> in sync with the active language.
// Apply once on boot so the very first paint after i18n
// init matches the resolved language, then again on every subsequent
// `i18n.changeLanguage(...)` call.
applyDocumentDirection(i18n.language)
i18n.on('languageChanged', (lang) => {
  applyDocumentDirection(lang)
})

interface ResourceStoreInternals {
  addResourceBundle(
    language: string,
    namespace: string,
    resources: Record<string, unknown>,
    deep: boolean,
    overwrite: boolean,
    options: { silent: boolean; skipCopy: boolean },
  ): void
  emit(event: 'added', language: string, namespace: string): void
}

const englishBundlePromises = new Map<string, Promise<void>>()
const englishNamespacePromises = new Map<string, Promise<void>>()
const negativeNamespacePromises = new Map<string, Promise<void>>()
const reportedUnknownNamespaces = new Set<string>()
const pendingResources: Record<string, unknown>[] = []
const RESOURCE_FLUSH_DELAY_MS = 50
let flushTimer: ReturnType<typeof setTimeout> | null = null
let flushResolvers: Array<() => void> = []

function flushResources() {
  flushTimer = null
  const resources = pendingResources.splice(0)
  const resolvers = flushResolvers
  flushResolvers = []
  const store = i18n.store as unknown as ResourceStoreInternals

  for (const resource of resources) {
    store.addResourceBundle('en', 'translation', resource, true, true, {
      silent: true,
      skipCopy: true,
    })
  }
  // react-i18next listens to the resource-store event. A single debounced
  // emission refreshes every concurrent namespace without a global language
  // change or one rerender per downloaded locale bundle.
  store.emit('added', 'en', 'translation')
  resolvers.forEach((resolve) => resolve())
}

function queueResources(resources: Record<string, unknown>) {
  return new Promise<void>((resolve) => {
    pendingResources.push(resources)
    flushResolvers.push(resolve)
    // Scheduled from the first pending resource and deliberately not reset by
    // later arrivals: a steady trickle of bundle loads still batches, but no
    // caller waits longer than one flush window for its strings to appear.
    if (flushTimer === null) {
      flushTimer = globalThis.setTimeout(flushResources, RESOURCE_FLUSH_DELAY_MS)
    }
  })
}

/** Test-only scheduler drain that prevents a delayed store event leaking into a later test. */
export function flushPendingEnglishResourcesForTest() {
  if (flushTimer === null) return
  globalThis.clearTimeout(flushTimer)
  flushResources()
}

function unknownNamespace(namespace: string) {
  const existing = negativeNamespacePromises.get(namespace)
  if (existing) return existing
  const promise = Promise.reject(new Error(`Unknown English translation namespace: ${namespace}`))
  // The missing-key caller consumes this rejection. Keeping it cached means
  // repeated t() calls neither retry work nor flood console output.
  promise.catch(() => undefined)
  negativeNamespacePromises.set(namespace, promise)
  return promise
}

function hasEnglishNamespace(namespace: string) {
  const resources = i18n.getResourceBundle('en', 'translation') as Record<string, unknown> | undefined
  return resources !== undefined && Object.prototype.hasOwnProperty.call(resources, namespace)
}

/**
 * Loads one generated locale chunk.
 *
 * A rejected promise is not cached, so a chunk that failed on a flaky network
 * is retried the next time a component asks for one of its keys.
 */
function loadEnglishBundle(bundle: string): Promise<void> {
  const existing = englishBundlePromises.get(bundle)
  if (existing) return existing
  const loadModule = englishNamespaceModules[`./en/locale-${bundle}.json`]
  if (!loadModule) return Promise.reject(new Error(`Unknown English locale bundle: ${bundle}`))

  const promise = loadModule()
    .then(({ default: resources }) => queueResources(resources))
    .catch((error: unknown) => {
      englishBundlePromises.delete(bundle)
      throw error
    })
  englishBundlePromises.set(bundle, promise)
  return promise
}

function requestEnglishNamespace(namespace: string) {
  return loadEnglishNamespace(namespace).catch((error: unknown) => {
    if (!reportedUnknownNamespaces.has(namespace)) {
      reportedUnknownNamespaces.add(namespace)
      console.error(`[i18n] Failed to load English namespace "${namespace}":`, error)
    }
  })
}

/**
 * Loads the English namespace for a feature after it first requests a key.
 *
 * The promise is cached only while it succeeds. A failed network/chunk load
 * can be retried on a later render without losing the caller's inline
 * fallback. A namespace the generator never emitted is negative-cached so a
 * render loop cannot turn one typo into unbounded work.
 */
export function loadEnglishNamespace(namespace: string): Promise<void> {
  const existing = englishNamespacePromises.get(namespace)
  if (existing) return existing
  // Nothing to fetch: the startup chunk already carries the whole namespace.
  if (completeNamespaces.has(namespace)) return Promise.resolve()

  const bundle = fallbackBundleFor(namespace)
  if (!bundle) return unknownNamespace(namespace)

  const promise = loadEnglishBundle(bundle)
    .then(() => {
      if (hasEnglishNamespace(namespace)) return
      return unknownNamespace(namespace)
    })
    .catch((error: unknown) => {
      if (!negativeNamespacePromises.has(namespace)) {
        englishNamespacePromises.delete(namespace)
      }
      throw error
    })
  englishNamespacePromises.set(namespace, promise)
  return promise
}

/**
 * Load all deferred English namespaces.
 *
 * This compatibility helper is deliberately not called during startup. Tests
 * and explicit preloading flows can use it when they require a complete
 * catalog, while normal route rendering loads only requested namespaces.
 */
export function loadEnglishResources(): Promise<void> {
  const bundles = new Set<string>([
    ...manifest.detail.map((namespace) => `detail-${namespace}`),
    ...Object.keys(manifest.grouped),
  ])
  return Promise.all([...bundles].map(loadEnglishBundle)).then(() => undefined)
}

export default i18n
