/**
 * @deprecated — Do not import from this barrel. Use hooks from @/api/hooks/ instead.
 * This file exists only for backward compatibility and will be removed.
 *
 * For types: import from @/api/types
 * For data fetching: use hooks from @/api/hooks/
 * For imperative requests (in queryFn): import request from @/api/client
 */

export { ApiError, getApiBase, request } from './client'
export type {
  Vehicle,
  Position,
  Drive,
  ChargingSession,
  DriveTelemetryReading,
  ChargeTelemetryReading,
  Geofence,
  AppSettings,
  PollingConfig,
  VehicleState,
  AuthStatus,
  EnergyStats,
  BatteryReport,
  Alert,
  AlertRule,
  AlertRuleSeverity,
  AlertRuleOp,
  AlertRuleInput,
  AlertRuleUpdate,
  AlertTestTarget,
  AlertTestRequest,
  StatsSummary,
  FleetAnalytics,
  CommandResult,
  NotificationChannel,
  NotificationLog,
  NotificationStats,
  WorkerStatus,
  WorkersHealth,
  ChatMessage,
  ChatResponse,
  ChatSessionInfo,
  VehicleStatus,
  VEHICLE_STATUSES,
  deriveVehicleStatus,
  statusVariant,
  statusDotColor,
  TirePressureSnapshot,
  MotorSnapshot,
  ClimateSnapshot,
  SecurityEvent,
  SoftwareUpdate,
  VampireDrainEvent,
  VampireDrainStats,
  DailyMileage,
  MonthlyMileage,
  MileageStats,
  VisitedLocation,
  Trip,
  VehicleStateRecord,
  StateSummary,
  DailyStateBreakdown,
  APIKey,
  AuditLog,
  APIUsage,
  CompressionStats,
  ExtendedHealthResponse,
  BackupStats,
  MapConfig,
  APICallLog,
  APICallLogResponse,
  APICallLogStats,
  VersionInfo,
  UpdateCheckResult,
  NotificationSchedule,
  NotificationPreference,
  NotificationAnalytics,
  NotificationMetric,
  ExportJobSummary,
  ExportJobSubmitRequest,
  ExportJobSubmitResponse,
  TelemetryStatus,
  GasPriceStatus,
  GasPriceHistory,
  StaleSessionsResponse,
  CaptureStats,
  ChargingHeatmapCell,
  ChargingLocationBreakdown,
  ChargingHeatmapSummary,
  ChargingHeatmapData,
  SpeedBucket,
  EfficiencyCategory,
  EfficiencyPoint,
  SpeedProfileData,
  TempEfficiencyBucket,
  VampireDrainBucket,
  MonthlyTempTrend,
  TemperatureImpactData,
  RouteSummary,
  RouteDriveDetail,
  RouteEfficiencyData,
  RouteDetailData,
  ChargingTelemetry,
  MediaSnapshot,
  VehicleConfigSnapshot,
  LocationSnapshot,
  SafetySnapshot,
  UserPreferenceSnapshot,
  BackupConfig,
  BackupRun,
  TCOAnalytics,
  SleepAnalytics,
  RegenData,
  BatteryDegradationData,
} from './types'

export { getAuthStatus, getAuthURL, disconnectAuth } from './auth'

export {
  getVehicleStatus,
  getVehicles,
  getVehicle,
  syncVehicles,
  getVehicleState,
  getVehiclePositions,
  wakeVehicle,
  deleteVehicle,
  sendCommand,
  getTirePressure,
  getLatestTirePressure,
  getMotorData,
  getMotorLatest,
  getClimateData,
  getClimateLatest,
  getSecurityEvents,
  getSecurityLatest,
  getChargingTelemetry,
  getChargingTelemetryLatest,
  getMediaData,
  getMediaLatest,
  getVehicleConfigData,
  getVehicleConfigLatest,
  getLocationSnapshots,
  getLocationSnapshotLatest,
  getSafetyData,
  getSafetyLatest,
  getUserPreferences,
  getUserPreferenceLatest,
  getSoftwareUpdates,
  getVehicleTimeline,
  getStateSummary,
  getDailyStateBreakdown,
} from './vehicles'

export {
  getDrives,
  getDrive,
  getDrivePositions,
  getDriveTelemetry,
} from './drives'

export {
  getChargingSessions,
  getChargingSession,
  getChargeTelemetry,
} from './charging'

export {
  getSettings,
  updateSettings,
  toggleAPISuspend,
  getPollingConfig,
  updatePollingConfig,
  getGeofences,
  createGeofence,
  updateGeofence,
  deleteGeofence,
  getAlerts,
  markAlertRead,
  getAlertRules,
  updateAlertRule,
  createAlertRule,
  deleteAlertRule,
  getNotificationChannels,
  getNotificationChannel,
  createNotificationChannel,
  updateNotificationChannel,
  deleteNotificationChannel,
  toggleNotificationChannel,
  testNotificationChannel,
  getNotificationLogs,
  getNotificationStats,
  getNotificationSchedules,
  createNotificationSchedule,
  deleteNotificationSchedule,
  getNotificationPreferences,
  updateNotificationPreference,
  getNotificationAnalytics,
  getChannelMetrics,
  getGasPriceStatus,
  pollGasPrice,
  toggleGasPrice,
  updateGasPriceConfig,
  getGasPriceHistory,
  getMapConfig,
} from './settings'

export {
  getEnergyStats,
  getBatteryReport,
  getFleetAnalytics,
  getChargingHeatmap,
  getSpeedProfile,
  getTemperatureImpact,
  getRouteEfficiency,
  getRouteEfficiencyDetail,
  getTCOAnalytics,
  getSleepAnalytics,
  getRegenStats,
  getBatteryDegradation,
  getDailyMileage,
  getMonthlyMileage,
  getMileageStats,
  getVampireDrainEvents,
  getVampireDrainStats,
  getVisitedLocations,
  getTrips,
} from './analytics'

export {
  getCaptureStats,
  getTelemetryStatus,
  getAPICallLogs,
  getAPICallLogStats,
  getAPIUsage,
  getCompressionStats,
  getExtendedHealth,
  getBackupStats,
  getWorkersHealth,
  getVersionInfo,
  checkForUpdates,
  getStaleSessions,
  updateChargingSession,
  updateDrive,
  closeChargingSession,
  closeDrive,
  deleteChargingSession,
  deleteDrive,
  getBackupConfigs,
  getBackupConfig,
  createBackupConfig,
  updateBackupConfig,
  deleteBackupConfig,
  triggerBackup,
  triggerQuickBackup,
  getBackupRuns,
  getBackupRun,
  downloadBackup,
  verifyBackup,
  previewRestore,
  getAPIKeys,
  createAPIKey,
  deleteAPIKey,
  revokeAPIKey,
  getAuditLogs,
  submitExportJob,
  getExportJobs,
  getExportJob,
  getExportJobDownloadUrl,
  submitImportJob,
  sendChatMessage,
  getChatHistory,
  getChatSessions,
  renameChatSession,
  deleteChatSession,
} from './devtools'
