export function generateCarbonCertificate(data: {
  vehicleName: string
  totalKm: number
  totalKwh: number
  ownerName?: string
}) {
  const gasEquivalentL = (data.totalKm / 100) * 8 // 8L/100km avg gas car
  const co2SavedKg = gasEquivalentL * 2.31 // kg CO2 per liter
  const treesEquivalent = Math.round(co2SavedKg / 22) // ~22kg CO2 per tree/year
  const gallonsSaved = Math.round(gasEquivalentL * 0.264172)

  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  printWindow.document.write(`<!DOCTYPE html><html><head>
    <title>Carbon Offset Certificate — TeslaSync</title>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;900&display=swap');
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { font-family: 'Inter', sans-serif; background: #0a0a1a; color: #e4e4ef; display: flex; justify-content: center; padding: 40px; }
      .cert { width: 700px; border: 2px solid #00f0ff; border-radius: 24px; padding: 48px; position: relative; overflow: hidden; }
      .cert::before { content: ''; position: absolute; top: 0; left: 0; right: 0; bottom: 0; background: radial-gradient(circle at 30% 20%, rgba(0,240,255,0.06), transparent 60%), radial-gradient(circle at 70% 80%, rgba(16,185,129,0.04), transparent 60%); }
      .content { position: relative; z-index: 1; }
      h1 { text-align: center; font-size: 28px; font-weight: 900; background: linear-gradient(135deg, #00f0ff, #10b981); -webkit-background-clip: text; -webkit-text-fill-color: transparent; margin-bottom: 8px; }
      .subtitle { text-align: center; font-size: 12px; color: #6b7280; letter-spacing: 3px; text-transform: uppercase; margin-bottom: 32px; }
      .hero { text-align: center; margin: 32px 0; }
      .hero-number { font-size: 64px; font-weight: 900; color: #10b981; }
      .hero-unit { font-size: 18px; color: #6b7280; }
      .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 32px 0; }
      .stat { text-align: center; padding: 16px; border: 1px solid rgba(0,240,255,0.15); border-radius: 12px; }
      .stat-value { font-size: 24px; font-weight: 700; color: #00f0ff; }
      .stat-label { font-size: 10px; color: #6b7280; margin-top: 4px; text-transform: uppercase; }
      .owner { text-align: center; margin-top: 32px; padding-top: 24px; border-top: 1px solid rgba(255,255,255,0.1); }
      .owner-name { font-size: 20px; font-weight: 600; color: #e4e4ef; }
      .date { text-align: center; font-size: 11px; color: #4b5563; margin-top: 16px; }
      .footer { text-align: center; margin-top: 24px; font-size: 10px; color: #374151; }
      @media print { body { background: white; } .cert { border-color: #10b981; } h1 { color: #0077b6; } .hero-number { color: #059669; } .stat-value { color: #0077b6; } .owner-name, .content { color: #111827; } }
    </style>
  </head><body>
    <div class="cert"><div class="content">
      <h1>\u{1f30d} Carbon Offset Certificate</h1>
      <div class="subtitle">Powered by TeslaSync</div>
      <div class="hero">
        <div class="hero-number">${Math.round(co2SavedKg).toLocaleString()}</div>
        <div class="hero-unit">kg CO\u{2082} Avoided</div>
      </div>
      <div class="stats">
        <div class="stat"><div class="stat-value">${Math.round(data.totalKm).toLocaleString()}</div><div class="stat-label">km Driven Electric</div></div>
        <div class="stat"><div class="stat-value">${treesEquivalent}</div><div class="stat-label">Trees Equivalent</div></div>
        <div class="stat"><div class="stat-value">${gallonsSaved}</div><div class="stat-label">Gallons Saved</div></div>
      </div>
      <div class="stats">
        <div class="stat"><div class="stat-value">${Math.round(data.totalKwh)}</div><div class="stat-label">kWh Clean Energy</div></div>
        <div class="stat"><div class="stat-value">${Math.round(gasEquivalentL)}</div><div class="stat-label">Liters Gas Avoided</div></div>
        <div class="stat"><div class="stat-value">${data.vehicleName}</div><div class="stat-label">Vehicle</div></div>
      </div>
      <div class="owner">
        <div class="owner-name">${data.ownerName || 'TeslaSync User'}</div>
      </div>
      <div class="date">Generated on ${new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}</div>
      <div class="footer">This certificate is generated by TeslaSync based on actual driving data. Not an official carbon offset.</div>
    </div></div>
  </body></html>`)
  printWindow.document.close()
  printWindow.print()
}
