import { printStylesheetURL, printWhenReady } from './printDocument'

function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

export function generateCarbonCertificate(data: {
  vehicleName: string
  totalKm: number
  totalKwh: number
  ownerName?: string
}) {
  const gasEquivalentL = (data.totalKm / 100) * 8 // 8L/100km avg gas car
  const co2SavedKg = gasEquivalentL * 2.31 // kg CO2 per liter
  const treesEquivalent = Math.round(co2SavedKg / 22) // ~22kg CO2 per tree/year
  const gallonsSaved = Math.round(gasEquivalentL * 0.264172)

  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  printWindow.document.write(`<!DOCTYPE html><html><head>
    <title>Carbon Offset Certificate — TeslaSync</title>
    <link rel="stylesheet" href="${printStylesheetURL()}">
  </head><body class="certificate-document">
    <div class="cert"><div class="content">
      <h1>\u{1f30d} Carbon Offset Certificate</h1>
      <div class="subtitle">Powered by TeslaSync</div>
      <div class="hero">
        <div class="hero-number">${Math.round(co2SavedKg).toLocaleString()}</div>
        <div class="hero-unit">kg CO\u{2082} Avoided</div>
      </div>
      <div class="stats">
        <div class="stat"><div class="stat-value">${Math.round(data.totalKm).toLocaleString()}</div><div class="stat-label">km Driven Electric</div></div>
        <div class="stat"><div class="stat-value">${treesEquivalent}</div><div class="stat-label">Trees Equivalent</div></div>
        <div class="stat"><div class="stat-value">${gallonsSaved}</div><div class="stat-label">Gallons Saved</div></div>
      </div>
      <div class="stats">
        <div class="stat"><div class="stat-value">${Math.round(data.totalKwh)}</div><div class="stat-label">kWh Clean Energy</div></div>
        <div class="stat"><div class="stat-value">${Math.round(gasEquivalentL)}</div><div class="stat-label">Liters Gas Avoided</div></div>
        <div class="stat"><div class="stat-value">${escapeHtml(data.vehicleName)}</div><div class="stat-label">Vehicle</div></div>
      </div>
      <div class="owner">
        <div class="owner-name">${escapeHtml(data.ownerName || 'TeslaSync User')}</div>
      </div>
      <div class="date">Generated on ${new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}</div>
      <div class="footer">This certificate is generated by TeslaSync based on actual driving data. Not an official carbon offset.</div>
    </div></div>
  </body></html>`)
  printWindow.document.close()
  printWhenReady(printWindow)
}
