/**
 * Canonical concept-to-icon registry.
 *
 * RULES:
 *  - Always import icons from this file, NOT directly from `lucide-react`.
 *  - Adding a new icon here implicitly enforces it as the canonical choice
 *    for that concept across the app.
 *  - Some related concepts intentionally collapse to the same icon (e.g.
 *    `severityWarn` and `warning` both point at `AlertTriangle`) — that is
 *    the registry's job.
 *  - For app primitives (Tesla logo, app branding) keep them as SVG assets
 *    under `web/public` or `components/branding/`, NOT here.
 *
 * See `docs/ICON_GUIDELINES.md` for usage and exception rules.
 */

import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Archive,
  Armchair,
  ArrowDown,
  ArrowDownRight,
  ArrowDownToDot,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  ArrowUpDown,
  ArrowUpFromDot,
  ArrowUpRight,
  Award,
  BarChart3,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryMedium,
  BatteryWarning,
  BedDouble,
  Bell,
  BellOff,
  BellPlus,
  BellRing,
  Bolt,
  Bot,
  Bug,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarMinus,
  CalendarPlus,
  Car,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsUp,
  CircleDot,
  CircleStop,
  Clock,
  Cloud,
  CloudRain,
  Copy,
  Cpu,
  Database,
  DatabaseBackup,
  Dog,
  DollarSign,
  DoorOpen,
  Download,
  Droplets,
  Edit3,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  Fence,
  FileDown,
  FileJson,
  FileSpreadsheet,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  Flame,
  FolderOpen,
  Fuel,
  Gamepad2,
  Gauge,
  GaugeCircle,
  GitCompare,
  Globe,
  Hammer,
  HardDrive,
  HardDriveDownload,
  Headphones,
  Heart,
  HeartPulse,
  HelpCircle,
  History,
  Home,
  Info,
  Key,
  KeyRound,
  Keyboard,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Leaf,
  Lightbulb,
  Link,
  LineChart,
  Loader2,
  Locate,
  Lock,
  Map,
  MapPin,
  MapPinned,
  ParkingCircle,
  Menu,
  Milestone,
  Minus,
  Monitor,
  Moon,
  MoonStar,
  MoreHorizontal,
  MoreVertical,
  Music,
  Navigation,
  Navigation2,
  Network,
  Package,
  Palette,
  Pause,
  Pencil,
  PieChart,
  Play,
  Plug,
  Plus,
  Power,
  Radar,
  Radio,
  RadioTower,
  Receipt,
  Recycle,
  Redo2,
  RefreshCw,
  RotateCcw,
  Route,
  Satellite,
  Save,
  ScanSearch,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  ShoppingCart,
  Signpost,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  Speaker,
  Split,
  Square,
  Star,
  Stethoscope,
  Sun,
  SunMoon,
  Target,
  Tent,
  Terminal,
  Thermometer,
  ThermometerSun,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Tv,
  Undo2,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserPlus,
  UserX,
  Users,
  Volume1,
  Volume2,
  VolumeX,
  Wallet,
  Wifi,
  WifiOff,
  Wind,
  Workflow,
  Wrench,
  X,
  XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export type { LucideIcon };

/**
 * Canonical icon-per-concept mapping.
 * Always import via `Icons.<concept>`, never the bare lucide name.
 *
 * Naming:
 *  - semantic concept names (battery, charging, vehicle, ...) for things that
 *    have a clear meaning in the app domain
 *  - short UI/action verbs (add, edit, delete, refresh, ...) for primitives
 *  - lower-camel-case lucide name as a fallback for specialty icons that don't
 *    map to a richer concept (dog, hammer, tent, ...) — still routed through
 *    this registry so the audit can stay accurate.
 */
export const Icons = {
  // ── Severity & status (also see severityTokens in tokens.ts) ────────────
  severityCritical: AlertOctagon,
  severityWarn: AlertTriangle,
  severityInfo: Info,
  warning: AlertTriangle,
  info: Info,
  alertCircle: AlertCircle,
  success: CheckCircle,
  successFilled: CheckCircle2,
  error: XCircle,
  helpCircle: HelpCircle,

  // ── Battery / charging ──────────────────────────────────────────────────
  battery: Battery,
  batteryCharging: BatteryCharging,
  batteryFull: BatteryFull,
  batteryMedium: BatteryMedium,
  batteryWarning: BatteryWarning,
  charging: Zap,
  charger: Plug,
  bolt: Bolt,
  powerShare: Zap,

  // ── Vehicle / mobility ──────────────────────────────────────────────────
  vehicle: Car,
  navigation: Navigation,
  navigationAlt: Navigation2,
  map: Map,
  mapPinned: MapPinned,
  parking: ParkingCircle,
  location: MapPin,
  locate: Locate,
  drive: Route,
  drives: Route,
  trip: Milestone,
  signpost: Signpost,
  fence: Fence,
  flag: Flag,
  fuel: Fuel,
  satellite: Satellite,
  radar: Radar,

  // ── Analytics / charts ──────────────────────────────────────────────────
  analytics: BarChart3,
  trends: LineChart,
  pieChart: PieChart,
  layoutDashboard: LayoutDashboard,
  layoutGrid: LayoutGrid,
  layoutTemplate: LayoutTemplate,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  speed: Gauge,
  speedCircle: GaugeCircle,
  efficiency: Activity,
  activity: Activity,
  range: Gauge,
  target: Target,
  workflow: Workflow,
  award: Award,
  trophy: Trophy,
  star: Star,

  // ── Notifications / alerts ──────────────────────────────────────────────
  notifications: Bell,
  notificationsMuted: BellOff,
  notificationsActive: BellRing,
  notificationsAdd: BellPlus,

  // ── Climate / weather ───────────────────────────────────────────────────
  climate: Thermometer,
  climateHot: ThermometerSun,
  cooling: Snowflake,
  heating: Sun,
  weather: CloudRain,
  cabin: Armchair,
  cloud: Cloud,
  wind: Wind,
  flame: Flame,
  droplets: Droplets,
  moon: Moon,
  moonStar: MoonStar,
  sun: Sun,
  sunMoon: SunMoon,

  // ── Security / access ───────────────────────────────────────────────────
  security: Shield,
  securityAlert: ShieldAlert,
  securityCheck: ShieldCheck,
  securityOff: ShieldOff,
  locked: Lock,
  unlocked: Unlock,
  key: Key,
  keyRound: KeyRound,
  fingerprint: Fingerprint,
  guard: ShieldAlert,

  // ── Media ───────────────────────────────────────────────────────────────
  media: Music,
  headphones: Headphones,
  speaker: Speaker,
  volume: Volume2,
  volumeLow: Volume1,
  volumeOff: VolumeX,

  // ── Maintenance / system ────────────────────────────────────────────────
  maintenance: Wrench,
  settings: Settings,
  settingsAlt: Settings2,
  preferences: SlidersHorizontal,
  cpu: Cpu,
  database: Database,
  databaseBackup: DatabaseBackup,
  hardDrive: HardDrive,
  hardDriveDownload: HardDriveDownload,
  monitor: Monitor,
  terminal: Terminal,
  server: Server,
  network: Network,
  globe: Globe,
  link: Link,
  package: Package,
  shoppingCart: ShoppingCart,
  archive: Archive,
  history: History,
  stethoscope: Stethoscope,
  bug: Bug,
  scanSearch: ScanSearch,
  recycle: Recycle,
  bot: Bot,
  gamepad: Gamepad2,
  palette: Palette,
  keyboard: Keyboard,
  tv: Tv,
  power: Power,
  radio: Radio,
  radioTower: RadioTower,
  wifi: Wifi,
  wifiOff: WifiOff,
  heart: Heart,
  heartPulse: HeartPulse,

  // ── People ──────────────────────────────────────────────────────────────
  user: User,
  users: Users,
  userCheck: UserCheck,
  userPlus: UserPlus,
  userX: UserX,
  home: Home,

  // ── Cost ────────────────────────────────────────────────────────────────
  dollarSign: DollarSign,
  wallet: Wallet,
  receipt: Receipt,

  // ── Time / scheduling ───────────────────────────────────────────────────
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  calendarClock: CalendarClock,
  calendarPlus: CalendarPlus,
  calendarMinus: CalendarMinus,
  clock: Clock,
  timer: Timer,
  bedDouble: BedDouble,
  sparkles: Sparkles,
  lightbulb: Lightbulb,

  // ── UI / actions ────────────────────────────────────────────────────────
  add: Plus,
  remove: Minus,
  close: X,
  confirm: Check,
  next: ChevronRight,
  previous: ChevronLeft,
  expand: ChevronDown,
  collapse: ChevronUp,
  expandAll: ChevronsDown,
  collapseAll: ChevronsUp,
  forward: ArrowRight,
  back: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeftRight: ArrowLeftRight,
  arrowRightLeft: ArrowRightLeft,
  arrowUpDown: ArrowUpDown,
  arrowUpFromDot: ArrowUpFromDot,
  arrowDownToDot: ArrowDownToDot,
  externalLink: ExternalLink,
  drillThrough: ArrowUpRight,
  drillDown: ArrowDownRight,

  search: Search,
  filter: Filter,
  more: MoreVertical,
  moreInline: MoreHorizontal,
  menu: Menu,

  edit: Edit3,
  pencil: Pencil,
  delete: Trash2,
  copy: Copy,
  save: Save,
  download: Download,
  upload: Upload,
  share: Share2,
  send: Send,
  fileDown: FileDown,
  fileText: FileText,
  fileJson: FileJson,
  fileSpreadsheet: FileSpreadsheet,
  folderOpen: FolderOpen,

  refresh: RefreshCw,
  undo: RotateCcw,
  undoAlt: Undo2,
  redo: Redo2,
  loading: Loader2,
  play: Play,
  pause: Pause,
  stop: Square,
  circleStop: CircleStop,
  skipBack: SkipBack,
  skipForward: SkipForward,
  eraser: Eraser,

  show: Eye,
  hide: EyeOff,

  // ── Vehicle systems / state ─────────────────────────────────────────────
  doorOpen: DoorOpen,
  tirePressure: CircleDot,
  split: Split,
  hammer: Hammer,
  leaf: Leaf,

  // ── Specialty / one-offs (registry-routed for audit hygiene) ────────────
  dog: Dog,
  tent: Tent,
  gitCompare: GitCompare,
} satisfies Record<string, LucideIcon>;

/** Concept key in the registry. */
export type IconKey = keyof typeof Icons;
