import { formatDate, formatDateTime } from './dateFormat'
import { fmtNumber } from './numberFormat'

/**
 * Loose drive/vehicle/stats input shapes accepted by the report builders.
 *
 * The report functions are deliberately permissive — they accept anything
 * that loosely matches the wire shape because reports are produced from
 * pages that combine multiple API responses (drive detail, vehicle list,
 * derived stats) and several legacy fields. The interfaces below let the
 * compiler verify field names without forcing every caller to map their
 * shape into a strict {@link import('../api/types').Drive} first.
 */
export interface DriveReportInput {
  id?: number
  start_date?: string | null
  end_date?: string | null
  /** Distance in kilometres (already converted by the page). */
  distance?: number | null
  duration_min?: number | null
  speed_max?: number | null
  start_battery_level?: number | null
  end_battery_level?: number | null
  start_range_km?: number | null
  end_range_km?: number | null
}

export interface VehicleReportInput {
  display_name?: string | null
}

export interface MonthlyReportStats {
  total_distance_km?: number | null
  total_drives?: number | null
  total_energy_kwh?: number | null
  total_cost?: number | null
  avg_efficiency_wh_km?: number | null
}

export function generateDriveReport(drive: DriveReportInput, vehicle: VehicleReportInput | null | undefined) {
  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  const startDate = drive.start_date ?? ''
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Drive Report - ${formatDate(startDate)}</title>
      <style>
        body { font-family: system-ui, sans-serif; padding: 40px; color: #1a1a2e; }
        h1 { color: #0077b6; border-bottom: 2px solid #0077b6; padding-bottom: 8px; }
        h2 { color: #059669; margin-top: 24px; }
        table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        th { background: #f3f4f6; text-align: left; padding: 8px 12px; font-size: 12px; text-transform: uppercase; }
        td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; }
        .stat { display: inline-block; width: 23%; text-align: center; margin: 8px 1%; padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; }
        .stat-value { font-size: 24px; font-weight: 700; color: #0077b6; }
        .stat-label { font-size: 11px; color: #6b7280; margin-top: 4px; }
        .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 11px; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <h1>TeslaSync — Drive Report</h1>
      <p><strong>Vehicle:</strong> ${vehicle?.display_name || 'N/A'} | <strong>Date:</strong> ${formatDateTime(startDate)}</p>

      <div>
        <div class="stat"><div class="stat-value">${drive.distance != null ? fmtNumber(drive.distance, 1) : '—'}</div><div class="stat-label">km Distance</div></div>
        <div class="stat"><div class="stat-value">${Math.round(drive.duration_min || 0)}</div><div class="stat-label">min Duration</div></div>
        <div class="stat"><div class="stat-value">${drive.speed_max != null ? fmtNumber(drive.speed_max, 0) : '—'}</div><div class="stat-label">km/h Max Speed</div></div>
        <div class="stat"><div class="stat-value">${drive.start_battery_level ?? '?'}→${drive.end_battery_level ?? '?'}</div><div class="stat-label">% Battery</div></div>
      </div>

      <h2>Details</h2>
      <table>
        <tr><td>Start Time</td><td>${formatDateTime(startDate)}</td></tr>
        <tr><td>End Time</td><td>${drive.end_date ? formatDateTime(drive.end_date) : 'In progress'}</td></tr>
        <tr><td>Distance</td><td>${fmtNumber(drive.distance ?? 0, 1)} km</td></tr>
        <tr><td>Duration</td><td>${Math.floor((drive.duration_min || 0) / 60)}h ${Math.round((drive.duration_min || 0) % 60)}m</td></tr>
        <tr><td>Average Speed</td><td>${fmtNumber((drive.distance || 0) / ((drive.duration_min || 1) / 60), 0)} km/h</td></tr>
        <tr><td>Max Speed</td><td>${drive.speed_max != null ? fmtNumber(drive.speed_max, 0) : '—'} km/h</td></tr>
        <tr><td>Battery Used</td><td>${(drive.start_battery_level || 0) - (drive.end_battery_level || 0)}%</td></tr>
        <tr><td>Start Range</td><td>${drive.start_range_km != null ? fmtNumber(drive.start_range_km, 0) : '—'} km</td></tr>
        <tr><td>End Range</td><td>${drive.end_range_km != null ? fmtNumber(drive.end_range_km, 0) : '—'} km</td></tr>
      </table>

      <div class="footer">Generated by TeslaSync · ${new Date().toLocaleString()}</div>
    </body>
    </html>
  `)
  printWindow.document.close()
  printWindow.print()
}

export function generateMonthlyReport(
  stats: MonthlyReportStats | null | undefined,
  vehicles: ReadonlyArray<VehicleReportInput> | null | undefined,
) {
  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>TeslaSync Monthly Report</title>
      <style>
        body { font-family: system-ui, sans-serif; padding: 40px; color: #1a1a2e; }
        h1 { color: #0077b6; }
        table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        th { background: #f3f4f6; text-align: left; padding: 8px; font-size: 12px; text-transform: uppercase; }
        td { padding: 8px; border-bottom: 1px solid #e5e7eb; }
        .footer { margin-top: 40px; text-align: center; color: #9ca3af; font-size: 11px; }
      </style>
    </head>
    <body>
      <h1>TeslaSync — Monthly Summary</h1>
      <p>Generated: ${new Date().toLocaleString()}</p>
      <table>
        <tr><th>Metric</th><th>Value</th></tr>
        <tr><td>Total Vehicles</td><td>${vehicles?.length || 0}</td></tr>
        <tr><td>Total Distance</td><td>${fmtNumber(stats?.total_distance_km ?? 0, 0)} km</td></tr>
        <tr><td>Total Drives</td><td>${stats?.total_drives || 0}</td></tr>
        <tr><td>Total Energy</td><td>${fmtNumber(stats?.total_energy_kwh ?? 0, 0)} kWh</td></tr>
        <tr><td>Total Cost</td><td>$${fmtNumber(stats?.total_cost ?? 0, 2)}</td></tr>
        <tr><td>Avg Efficiency</td><td>${fmtNumber(stats?.avg_efficiency_wh_km ?? 0, 0)} Wh/km</td></tr>
      </table>
      <div class="footer">Generated by TeslaSync · ${new Date().toLocaleString()}</div>
    </body>
    </html>
  `)
  printWindow.document.close()
  printWindow.print()
}
