/**
 * Route templating and URL scrubbing for browser-side diagnostics.
 *
 * Pure, side-effect-free, and dependency-light on purpose: it is imported by
 * `errorReporter` (which is installed in `main.tsx` before React exists) and by
 * `webVitalsReporter`. Its only import is the autogenerated `routeRegistry`,
 * which is a frozen data array with no imports of its own — so there is no
 * import cycle and nothing runs at module load beyond the declarations below.
 * The registry index is built lazily on first use.
 *
 * ── Why the route registry matters ──────────────────────────────────────────
 * Shape heuristics alone cannot tell an opaque parameter from a page name.
 * `/s/share-token-abc` looks exactly like `/analytics/battery-degradation`:
 * lowercase words, hyphen separators, no digits. Without the registry the
 * share token survives normalisation, is buffered in an error payload, and is
 * POSTed the moment the consent policy resolves — a client-boundary disclosure
 * that no amount of backend normalisation can undo.
 *
 * So a segment becomes `:id` when EITHER
 *   (a) the route registry says that position is a `:param`, or
 *   (b) the segment's shape is identifier-like (integer, UUID, hex blob, VIN,
 *       coordinate, e-mail, percent-encoding, long mixed token, or anything
 *       outside the conservative word allow-list).
 *
 * ── Parity with the backend ─────────────────────────────────────────────────
 * The emitted placeholder is `:id`, matching `NormalizeRoute` in
 * `internal/api/webvitals/normalize.go`, so a template produced here survives
 * the server-side pass byte-identically.
 */

import { ROUTE_REGISTRY } from './routeRegistry'

/** The single sink for every redacted path segment. */
export const ID_PLACEHOLDER = ':id'

/** Route-template label ceiling, mirrored from the backend normaliser. */
export const MAX_ROUTE_LENGTH = 50
export const MAX_ROUTE_SEGMENTS = 6

const INT_SEGMENT = /^\d+$/
const UUID_SEGMENT =
  /^[0-9a-fA-F]{8}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{12}$/
const HEX_BLOB = /^[0-9a-fA-F]{20,}$/
/** ISO 3779 VIN alphabet (I, O, Q excluded), 17 characters. */
const VIN_SEGMENT = /^[A-HJ-NPR-Z0-9]{17}$/
const GEO_SEGMENT = /^-?\d{1,3}\.\d+(,-?\d{1,3}\.\d+)?$/
const DIGIT_TOKEN = /^[A-Za-z0-9_.-]{12,}$/
const SAFE_SEGMENT = /^[a-z0-9]+([._-][a-z0-9]+)*$/
const HAS_DIGIT = /\d/

interface RouteShape {
  /** Lower-cased literal segments; parameter positions hold ''. */
  segments: string[]
  /** True at every `:param` position. */
  paramAt: boolean[]
  paramCount: number
}

let shapeIndex: Map<number, RouteShape[]> | null = null

/** Lazily index the registry by segment count. Pure memo, no side effects. */
function ensureIndex(): Map<number, RouteShape[]> {
  if (shapeIndex) return shapeIndex
  const byLength = new Map<number, RouteShape[]>()
  for (const entry of ROUTE_REGISTRY) {
    const raw = entry.path.split('/').filter(s => s !== '')
    const paramAt = raw.map(s => s.startsWith(':'))
    const shape: RouteShape = {
      segments: raw.map((s, i) => (paramAt[i] ? '' : s.toLowerCase())),
      paramAt,
      paramCount: paramAt.reduce((n, p) => n + (p ? 1 : 0), 0),
    }
    const list = byLength.get(raw.length)
    if (list) list.push(shape)
    else byLength.set(raw.length, [shape])
  }
  // Prefer the most literal match so `/automations/new` never resolves
  // through a `:param` shape of the same length.
  for (const list of byLength.values()) {
    list.sort((a, b) => a.paramCount - b.paramCount)
  }
  shapeIndex = byLength
  return shapeIndex
}

/**
 * Find the registry route whose literal segments all match, and return its
 * parameter mask. `null` when the path is not a known route.
 */
function matchRegistry(lowerSegments: string[]): boolean[] | null {
  const candidates = ensureIndex().get(lowerSegments.length)
  if (!candidates) return null
  for (const candidate of candidates) {
    let ok = true
    for (let i = 0; i < lowerSegments.length; i++) {
      if (candidate.paramAt[i]) continue
      if (candidate.segments[i] !== lowerSegments[i]) {
        ok = false
        break
      }
    }
    if (ok) return candidate.paramAt
  }
  return null
}

/** Apply the shape heuristics to a single path segment. */
export function normalizeRouteSegment(part: string): string {
  if (INT_SEGMENT.test(part)) return ID_PLACEHOLDER
  if (UUID_SEGMENT.test(part)) return ID_PLACEHOLDER
  if (HEX_BLOB.test(part)) return ID_PLACEHOLDER
  if (VIN_SEGMENT.test(part.toUpperCase()) && HAS_DIGIT.test(part)) return ID_PLACEHOLDER
  if (GEO_SEGMENT.test(part)) return ID_PLACEHOLDER
  if (/[@%:=]/.test(part)) return ID_PLACEHOLDER
  if (DIGIT_TOKEN.test(part) && HAS_DIGIT.test(part)) return ID_PLACEHOLDER
  const lower = part.toLowerCase()
  if (!SAFE_SEGMENT.test(lower)) return ID_PLACEHOLDER
  return lower
}

/**
 * Percent-decode one path segment for analysis.
 *
 * `opaque: true` means the caller must redact rather than interpret: either the
 * encoding is malformed (`%zz`, `%2`) or the decoded value reintroduces
 * structural characters (`%2F` → `/`), both of which are attempts — deliberate
 * or accidental — to smuggle a value past segment-level analysis.
 *
 * Decoding matters for matching: `/year%2Dreview/2024` must still resolve to
 * the canonical `/year-review/:year` route. Mirrors `safeDecodeSegment` in
 * internal/api/webvitals/normalize.go.
 */
export function safeDecodeSegment(segment: string): { value: string; opaque: boolean } {
  if (!segment.includes('%')) return { value: segment, opaque: false }
  try {
    const decoded = decodeURIComponent(segment)
    if (/[/?#\\]/.test(decoded)) return { value: segment, opaque: true }
    return { value: decoded, opaque: false }
  } catch {
    return { value: segment, opaque: true }
  }
}

/**
 * Convert a browser pathname (or full URL) into a bounded, privacy-safe route
 * template. Query strings and fragments are dropped entirely, and the scheme +
 * authority of an absolute or protocol-relative URL is discarded (a host can
 * encode a tenant).
 */
export function normalizeRouteTemplate(input: string): string {
  if (!input) return '/'

  let p = input
  const cut = p.search(/[?#]/)
  if (cut >= 0) p = p.slice(0, cut)

  const schemeAt = p.indexOf('://')
  if (schemeAt >= 0) {
    const rest = p.slice(schemeAt + 3)
    const slash = rest.indexOf('/')
    p = slash >= 0 ? rest.slice(slash) : '/'
  } else if (p.startsWith('//')) {
    const rest = p.slice(2)
    const slash = rest.indexOf('/')
    p = slash >= 0 ? rest.slice(slash) : '/'
  }

  const rawSegments = p.split('/').filter(s => s !== '')
  if (rawSegments.length === 0) return '/'

  const decoded = rawSegments.map(safeDecodeSegment)
  const paramAt = matchRegistry(decoded.map(d => d.value.toLowerCase()))

  let segments = decoded.map((d, i) => {
    if (paramAt?.[i]) return ID_PLACEHOLDER
    if (d.opaque) return ID_PLACEHOLDER
    return normalizeRouteSegment(d.value)
  })

  if (segments.length > MAX_ROUTE_SEGMENTS) {
    segments = segments.slice(0, MAX_ROUTE_SEGMENTS)
  }

  let out = `/${segments.join('/')}`
  if (out.length > MAX_ROUTE_LENGTH) {
    out = out.slice(0, MAX_ROUTE_LENGTH)
    // Prefer cutting at a segment boundary so the label stays readable and two
    // different deep routes don't collide on a half-word.
    const lastSlash = out.lastIndexOf('/')
    if (lastSlash > 0) out = out.slice(0, lastSlash)
  }
  return out === '' ? '/' : out
}

const ABSOLUTE_URL = /\bhttps?:\/\/[^\s"'<>)\]}]+/gi

/**
 * Strip `?query` and `#fragment` from every absolute URL in a block of text.
 *
 * Free-text diagnostics (error messages, stack frames) routinely embed URLs.
 * A query string or fragment is the most common place a share token, an
 * invite code, or a filter containing a location ends up, and none of it is
 * needed to debug a crash.
 */
export function stripUrlQueryAndHash(text: string): string {
  if (!text) return text
  return text.replace(ABSOLUTE_URL, url => {
    const cut = url.search(/[?#]/)
    return cut >= 0 ? url.slice(0, cut) : url
  })
}

// ─────────────────────────────────────────────────────────────────────────────
// URL-like value scrubbing in free text
// ─────────────────────────────────────────────────────────────────────────────

/**
 * File extensions that mark a build artifact rather than an application route.
 *
 * A stack frame such as `/assets/index-abc123.js:1:2` is the single most useful
 * thing in a crash report and carries no user data, so its path is preserved
 * verbatim. Everything else that looks like a URL path gets templated.
 */
const ASSET_EXTENSIONS = new Set([
  'js',
  'mjs',
  'cjs',
  'jsx',
  'ts',
  'tsx',
  'map',
  'css',
  'scss',
  'wasm',
  'html',
  'htm',
  'svg',
  'png',
  'jpg',
  'jpeg',
  'gif',
  'webp',
  'avif',
  'ico',
  'woff',
  'woff2',
  'ttf',
  'otf',
  'eot',
])

/** `:line:col` suffix that a stack frame appends to a script URL. */
const LINE_COL_SUFFIX = /(:\d+(?::\d+)?)$/

/**
 * A URL-like run, anchored to a preceding boundary character so a bare `/`
 * inside a word (`a/b/c`) is not treated as a root-relative path.
 *
 * Deliberately no lookbehind: Safari < 16.4 throws a SyntaxError at parse time
 * on lookbehind, which would take the whole bundle down.
 */
const URL_LIKE = /(^|[\s"'([{,;=|])((?:https?:\/\/|\/\/)[^\s"'<>)\]}]+|\/[^\s"'<>)\]}]*)/gi

/** True when a final path segment carries a build-artifact extension. */
function hasAssetExtension(segment: string): boolean {
  const dot = segment.lastIndexOf('.')
  if (dot <= 0) return false
  return ASSET_EXTENSIONS.has(segment.slice(dot + 1).toLowerCase())
}

/**
 * True when the path resolves to a declared SPA route, so its parameter
 * positions are known exactly.
 */
export function isKnownRouteTemplate(path: string): boolean {
  const segments = path
    .split(/[?#]/)[0]
    .split('/')
    .filter(s => s !== '')
  if (segments.length === 0) return true
  return matchRegistry(segments.map(s => safeDecodeSegment(s).value.toLowerCase())) !== null
}

/**
 * Heuristic for a segment of an UNKNOWN path (no canonical route declares its
 * parameters). Long values, and medium-length values carrying a separator, are
 * the shape of slugs, tokens and composite keys; short structural words like
 * `api`, `v1` or `assets` are not.
 *
 * Applied ONLY to free-text URL scrubbing, never to the route label, because
 * a label needs the fidelity that distinguishes `/analytics/tco` from
 * `/analytics/carbon`.
 */
function looksOpaqueInUnknownPath(segment: string): boolean {
  if (segment === '' || segment === ID_PLACEHOLDER) return false
  if (segment.length >= 12) return true
  if (segment.length >= 8 && /[-_.]/.test(segment)) return true
  return false
}

/**
 * Template a path for FREE TEXT (not for a metric label).
 *
 * Known routes get exact parameter templating. Unknown paths get conservative
 * redaction, because nothing declares which of their segments are parameters.
 */
function templatePathForFreeText(path: string): string {
  const templated = normalizeRouteTemplate(path)
  if (isKnownRouteTemplate(path)) return templated
  return templated
    .split('/')
    .map(segment => (looksOpaqueInUnknownPath(segment) ? ID_PLACEHOLDER : segment))
    .join('/')
}

/**
 * Rewrite one URL-like token.
 *
 * Order is load-bearing:
 *   1. Query and fragment are removed from the WHOLE token first. Doing this
 *      after the authority split lets `https://host?code=abc/x` be read as
 *      authority `host?code=abc` + path `/x`, which retains the parameter.
 *   2. A trailing `:line:col` (or `:port` on an authority-only URL) is lifted
 *      off and re-attached verbatim.
 *   3. Scheme + authority are separated from the path.
 *   4. The path is templated — except for the FINAL segment of a build
 *      artifact, which is preserved so stack frames stay actionable.
 */
function scrubUrlLike(token: string): string {
  // 1. Query and fragment: gone, unconditionally, before anything is parsed.
  const queryAt = token.search(/[?#]/)
  let rest = queryAt >= 0 ? token.slice(0, queryAt) : token

  // 2. `:line:col` on a stack frame — or `:port` on an authority-only URL,
  //    which round-trips identically because the suffix is re-appended.
  let suffix = ''
  const lineCol = LINE_COL_SUFFIX.exec(rest)
  if (lineCol) {
    suffix = lineCol[1]
    rest = rest.slice(0, rest.length - suffix.length)
  }

  // 3. Scheme + authority.
  let prefix = ''
  const schemeAt = rest.indexOf('://')
  if (schemeAt >= 0) {
    const afterScheme = rest.slice(schemeAt + 3)
    const slash = afterScheme.indexOf('/')
    // Authority-only URL: there is no path to template, and the query and
    // fragment are already gone.
    if (slash < 0) return rest + suffix
    prefix = rest.slice(0, schemeAt + 3) + afterScheme.slice(0, slash)
    rest = afterScheme.slice(slash)
  } else if (rest.startsWith('//')) {
    const afterSlashes = rest.slice(2)
    const slash = afterSlashes.indexOf('/')
    if (slash < 0) return rest + suffix
    prefix = `//${afterSlashes.slice(0, slash)}`
    rest = afterSlashes.slice(slash)
  } else if (!rest.startsWith('/')) {
    return token
  }

  if (rest === '' || rest === '/') return `${prefix}/${suffix}`

  // 4. Build artifacts: keep ONLY the final filename. The directories above it
  //    are ordinary path segments and can carry a token —
  //    `/share/SECRETTOKENVALUE/index.html` and `/s/tok-private-abc/main.js`
  //    are both real shapes — so they are templated like any other path.
  const segments = rest.split('/').filter(Boolean)
  const last = segments[segments.length - 1]
  if (last !== undefined && hasAssetExtension(last)) {
    const parents = segments.slice(0, -1)
    const parentPath = parents.length > 0 ? templatePathForFreeText(`/${parents.join('/')}`) : ''
    return `${prefix}${parentPath}/${last}${suffix}`
  }

  return `${prefix}${templatePathForFreeText(rest)}${suffix}`
}

/** Trailing sentence punctuation that is not part of a URL. */
const TRAILING_PUNCTUATION = /[.,;:!?]+$/

/**
 * Normalise the path component of EVERY URL-like value in a block of text —
 * absolute, protocol-relative and root-relative — not just the current page.
 *
 * A static page can legitimately reference another share link
 * (`https://host/s/another-token`), and a stack frame or error message can
 * carry a root-relative path from a fetch that failed. Templating only the
 * current URL leaves those opaque paths intact all the way to the backend.
 *
 * Query strings and fragments are always removed. `:line:col` suffixes and
 * build-artifact paths survive so stack traces stay debuggable.
 */
export function redactUrlsInText(text: string): string {
  if (!text) return text
  return text.replace(URL_LIKE, (_match, lead: string, token: string) => {
    // `…/edit;` — the semicolon is prose, not part of the path, and leaving it
    // attached defeats the registry match for the whole route.
    const trailing = TRAILING_PUNCTUATION.exec(token)
    const trail = trailing ? trailing[0] : ''
    const core = trail ? token.slice(0, token.length - trail.length) : token
    return lead + scrubUrlLike(core) + trail
  })
}

export interface LocationLike {
  href?: string
  pathname?: string
  search?: string
  hash?: string
}

function currentLocation(): LocationLike | undefined {
  if (typeof window === 'undefined' || !window.location) return undefined
  const { href, pathname, search, hash } = window.location
  return { href, pathname, search, hash }
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/** Optional `?query` and/or `#fragment` immediately following a base URL. */
const TRAILING_QUERY_HASH = String.raw`(?:\?[^\s"'<>)\]}]*)?(?:#[^\s"'<>)\]}]*)?`

function originOf(href: string | undefined): string {
  if (!href) return ''
  const match = /^https?:\/\/[^/]+/i.exec(href)
  return match ? match[0] : ''
}

/**
 * Scrub every URL-like value in a block of text, then sweep any residual
 * verbatim spelling of the current page URL.
 *
 * The general pass ({@link redactUrlsInText}) does the heavy lifting: it
 * templates the path of every absolute, protocol-relative and root-relative URL
 * and always drops query and fragment. The current-location sweep afterwards
 * catches the rarer case where the pathname appears without a URL boundary in
 * front of it (concatenated into a sentence, for example).
 *
 * Run this BEFORE generic secret redaction: a `[REDACTED]` marker injected
 * into a query string would otherwise break URL boundary detection.
 */
export function redactLocationInText(
  text: string,
  location: LocationLike | undefined = currentLocation(),
): string {
  if (!text) return text

  let out = redactUrlsInText(text)
  if (!location) return out

  const pathname = location.pathname ?? '/'
  const template = normalizeRouteTemplate(pathname)
  const origin = originOf(location.href)

  const bases = Array.from(new Set([origin ? `${origin}${pathname}` : '', pathname]))
    // A bare "/" would match every separator in the text.
    .filter(base => base.length > 1 && base !== template)
    .sort((a, b) => b.length - a.length)

  for (const base of bases) {
    out = out.replace(new RegExp(escapeRegExp(base) + TRAILING_QUERY_HASH, 'g'), template)
  }
  return out
}

/** Test-only: drop the memoised registry index. */
export function __resetRouteTemplateIndexForTests(): void {
  shapeIndex = null
}
