import {
  Ambulance,
  BadgeInfo,
  BadgeX,
  Banknote,
  Bike,
  Bus,
  Cable,
  CirclePercent,
  Code2,
  FileHeart,
  FolderSearch,
  Grid2x2,
  HeartHandshake,
  MessageCircleMore,
  MessageSquareCode,
  PanelTop,
  RouteOff,
  Sunset,
  Ticket,
  UserRoundCheck,
  UserRoundCog,
  type LucideIcon,
} from 'lucide-react'

// Loaded with CollectionTreeRow, not with the always-visible app shell.
export const CollectionGlyphs = {
  ambulance: Ambulance,
  badgeInfo: BadgeInfo,
  badgeX: BadgeX,
  banknote: Banknote,
  bike: Bike,
  bus: Bus,
  cable: Cable,
  circlePercent: CirclePercent,
  code2: Code2,
  fileHeart: FileHeart,
  folderSearch: FolderSearch,
  grid2x2: Grid2x2,
  heartHandshake: HeartHandshake,
  messageCircleMore: MessageCircleMore,
  messageSquareCode: MessageSquareCode,
  panelTop: PanelTop,
  routeOff: RouteOff,
  sunset: Sunset,
  ticket: Ticket,
  userRoundCheck: UserRoundCheck,
  userRoundCog: UserRoundCog,
} satisfies Record<string, LucideIcon>
