import {
  AlarmClock,
  Atom,
  AudioWaveform,
  Axis3d,
  BadgeAlert,
  BadgeDollarSign,
  BatteryLow,
  BellElectric,
  BellDot,
  Binary,
  BookMarked,
  BookOpen,
  BookText,
  BriefcaseBusiness,
  BriefcaseMedical,
  CableCar,
  Calculator,
  CalendarDays,
  CalendarFold,
  CalendarHeart,
  CalendarRange,
  CarFront,
  CarTaxiFront,
  CircleDollarSign,
  Clock3,
  Clock4,
  Cog,
  Coins,
  CreditCard,
  DatabaseZap,
  Dna,
  Factory,
  FileClock,
  FilePieChart,
  FileSliders,
  FlaskConical,
  FolderHeart,
  FolderSearch,
  GitFork,
  Globe2,
  Grid3x3,
  Handshake,
  HardDriveUpload,
  Hourglass,
  KeySquare,
  Landmark,
  LibraryBig,
  ListCollapse,
  ListFilter,
  ListStart,
  ListTree,
  Microscope,
  Plug2,
  PlugZap,
  Puzzle,
  RadioReceiver,
  ReceiptText,
  ScanEye,
  ScanFace,
  ScatterChart,
  ServerCog,
  ShieldBan,
  ShieldPlus,
  ShieldQuestion,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  Siren,
  Sparkle,
  Sunrise,
  Telescope,
  ThermometerSnowflake,
  TimerOff,
  Trees,
  UsersRound,
  Waypoints,
  type LucideIcon,
} from 'lucide-react'

// Route-only glyphs stay out of the eagerly loaded app icon registry.
export const SidebarGlyphs = {
  alarmClock: AlarmClock,
  atom: Atom,
  audioWaveform: AudioWaveform,
  axis3d: Axis3d,
  badgeAlert: BadgeAlert,
  badgeDollarSign: BadgeDollarSign,
  batteryLow: BatteryLow,
  bellElectric: BellElectric,
  bellDot: BellDot,
  binary: Binary,
  bookMarked: BookMarked,
  bookOpen: BookOpen,
  bookText: BookText,
  briefcaseBusiness: BriefcaseBusiness,
  briefcaseMedical: BriefcaseMedical,
  cableCar: CableCar,
  calculator: Calculator,
  calendarDays: CalendarDays,
  calendarFold: CalendarFold,
  calendarHeart: CalendarHeart,
  calendarRange: CalendarRange,
  carFront: CarFront,
  carTaxiFront: CarTaxiFront,
  circleDollarSign: CircleDollarSign,
  clock3: Clock3,
  clock4: Clock4,
  cog: Cog,
  coins: Coins,
  creditCard: CreditCard,
  databaseZap: DatabaseZap,
  dna: Dna,
  factory: Factory,
  fileClock: FileClock,
  filePieChart: FilePieChart,
  fileSliders: FileSliders,
  flaskConical: FlaskConical,
  folderHeart: FolderHeart,
  folderSearch: FolderSearch,
  gitFork: GitFork,
  globe2: Globe2,
  grid3x3: Grid3x3,
  handshake: Handshake,
  hardDriveUpload: HardDriveUpload,
  hourglass: Hourglass,
  keySquare: KeySquare,
  landmark: Landmark,
  libraryBig: LibraryBig,
  listCollapse: ListCollapse,
  listFilter: ListFilter,
  listStart: ListStart,
  listTree: ListTree,
  microscope: Microscope,
  plug2: Plug2,
  plugZap: PlugZap,
  puzzle: Puzzle,
  radioReceiver: RadioReceiver,
  receiptText: ReceiptText,
  scanEye: ScanEye,
  scanFace: ScanFace,
  scatterChart: ScatterChart,
  serverCog: ServerCog,
  shieldBan: ShieldBan,
  shieldPlus: ShieldPlus,
  shieldQuestion: ShieldQuestion,
  signalHigh: SignalHigh,
  signalLow: SignalLow,
  signalMedium: SignalMedium,
  signalZero: SignalZero,
  siren: Siren,
  sparkle: Sparkle,
  sunrise: Sunrise,
  telescope: Telescope,
  thermometerSnowflake: ThermometerSnowflake,
  timerOff: TimerOff,
  trees: Trees,
  usersRound: UsersRound,
  waypoints: Waypoints,
} satisfies Record<string, LucideIcon>
