export { WidgetEventFeed, type EventFeedItem } from './WidgetEventFeed';
export { WidgetGaugeHero, type GaugeHeroConfig, type GaugeHeroStat } from './WidgetGaugeHero';
export { WidgetStatGrid, type StatGridItem } from './WidgetStatGrid';
export { WidgetChartSummary, type ChartSummaryStat } from './WidgetChartSummary';
export { WidgetDetailCard, type DetailEntry } from './WidgetDetailCard';
export { WidgetRankedList, type RankedItem } from './WidgetRankedList';
export { WidgetComparisonCard, type ComparisonMetric } from './WidgetComparisonCard';
export { WidgetBigNumber } from './WidgetBigNumber';
export { WidgetMapView } from './WidgetMapView';
export { WidgetStatusGrid, type StatusCell } from './WidgetStatusGrid';
export { WidgetTipCards, type TipItem } from './WidgetTipCards';
