package main

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// routePathRE extracts the `path:` field from every ROUTE_REGISTRY entry.
// The source file is itself generated with a fixed shape (single-quoted
// values, one entry per line), so a targeted regex is stable and avoids
// pulling a TypeScript parser into the toolchain.
var routePathRE = regexp.MustCompile(`\bpath:\s*'([^']+)'`)

// ParseRoutePaths returns the sorted, de-duplicated set of route paths declared
// in a routeRegistry.ts source. Sorting makes the generated artifact
// deterministic regardless of declaration order.
func ParseRoutePaths(source string) ([]string, error) {
	matches := routePathRE.FindAllStringSubmatch(source, -1)
	if len(matches) == 0 {
		return nil, fmt.Errorf("no `path:` entries found — has routeRegistry.ts changed shape?")
	}

	seen := make(map[string]struct{}, len(matches))
	paths := make([]string, 0, len(matches))
	for _, m := range matches {
		p := m[1]
		if !strings.HasPrefix(p, "/") {
			return nil, fmt.Errorf("route %q does not start with '/'", p)
		}
		if strings.ContainsAny(p, "?# ") {
			return nil, fmt.Errorf("route %q contains a query, fragment or space", p)
		}
		if _, dup := seen[p]; dup {
			continue
		}
		seen[p] = struct{}{}
		paths = append(paths, p)
	}

	sort.Strings(paths)
	return paths, nil
}

// Render emits the generated Go source.
func Render(paths []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/routetemplategen. DO NOT EDIT.\n")
	b.WriteString("// Source: web/src/lib/routeRegistry.ts\n")
	b.WriteString("//\n")
	b.WriteString("// Regenerate with:\n")
	b.WriteString("//\tgo run ./cmd/routetemplategen\n")
	b.WriteString("//\n")
	b.WriteString("// Drift is enforced by TestGeneratedRoutePathsMatchWebRegistry.\n\n")
	b.WriteString("package webvitals\n\n")
	b.WriteString("// generatedRoutePaths is the canonical SPA route table. Segments beginning\n")
	b.WriteString("// with ':' are client-controlled parameter positions and are templated to\n")
	b.WriteString("// `:id` before a route can become a Prometheus label.\n")
	fmt.Fprintf(&b, "var generatedRoutePaths = [%d]string{\n", len(paths))
	for _, p := range paths {
		fmt.Fprintf(&b, "\t%q,\n", p)
	}
	b.WriteString("}\n")
	return b.String()
}
