// Unit tests for `useBreadcrumbs`. The hook's public contract is: given the
// declarative `ROUTE_META` map, the current location, and the route params,
// walk the `parent` chain and produce an ordered breadcrumb trail (root →
// current), resolving labels (override > i18n > defaultLabel), substituting
// `{{param}}` placeholders, and composing per-item hrefs (current item = plain
// text, no link).
//
// We mock `@/lib/routeMeta` with a small deterministic fixture rather than
// depending on the autogenerated registry: that keeps these tests stable when
// routes are added AND lets us exercise the two defensive branches that are
// unreachable with the (acyclic, fully-linked) real registry — a dangling
// parent (`if (!meta) break`) and a parent cycle (`visited` short-circuit).
// The registry↔meta integration itself is covered by lib/__tests__/routeMeta.test.ts.

import type { ReactNode } from 'react';
import { describe, it, expect, vi } from 'vitest';
import { renderHook } from '@testing-library/react';
import { MemoryRouter, Routes, Route } from 'react-router-dom';

import { useBreadcrumbs } from './useBreadcrumbs';

vi.mock('@/lib/routeMeta', () => ({
  ROUTE_META: {
    '/': { i18nKey: 'routes.dashboard', defaultLabel: 'Dashboard' },
    '/drives': { i18nKey: 'routes.drives', defaultLabel: 'Drives' },
    '/drives/:id': { i18nKey: 'routes.driveDetail', defaultLabel: 'Drive Detail', parent: '/drives' },
    '/drives/:id/replay': { i18nKey: 'routes.tripReplay', defaultLabel: 'Trip Replay', parent: '/drives/:id' },
    '/items': { i18nKey: 'routes.items', defaultLabel: 'Items' },
    // defaultLabel carries a placeholder to prove i18n-path substitution.
    '/items/:id': { i18nKey: 'routes.itemDetail', defaultLabel: 'Item {{id}}', parent: '/items' },
    // parent points at a route that is NOT in the map → walk must stop cleanly.
    '/orphan': { i18nKey: 'routes.orphan', defaultLabel: 'Orphan', parent: '/ghost' },
    // mutually-referential parents → walk must terminate, not loop forever.
    '/cycle-a': { i18nKey: 'routes.cycleA', defaultLabel: 'Cycle A', parent: '/cycle-b' },
    '/cycle-b': { i18nKey: 'routes.cycleB', defaultLabel: 'Cycle B', parent: '/cycle-a' },
  } satisfies Record<string, { i18nKey: string; defaultLabel: string; parent?: string }>,
}));

// `t(key, fallback)` mirrors production's missing-translation behaviour: return
// the caller-supplied default label. The hook does its own `{{param}}`
// interpolation, so the mock deliberately does not interpolate.
vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key: string, fallback?: string) => (typeof fallback === 'string' ? fallback : key),
    i18n: { language: 'en', changeLanguage: vi.fn() },
  }),
}));

function renderCrumbs(
  entry: string,
  routePattern: string,
  overrides?: Partial<Record<string, string>>,
) {
  const wrapper = ({ children }: { children: ReactNode }) => (
    <MemoryRouter initialEntries={[entry]}>
      <Routes>
        {/* Rendering the hook inside the matched Route is what makes
            useParams() resolve the concrete :param values. */}
        <Route path={routePattern} element={<>{children}</>} />
      </Routes>
    </MemoryRouter>
  );
  return renderHook(() => useBreadcrumbs(overrides), { wrapper });
}

describe('useBreadcrumbs', () => {
  it('returns an empty trail for a route with no ROUTE_META entry', () => {
    const { result } = renderCrumbs('/totally-unknown-xyz', '*');
    expect(result.current).toEqual([]);
  });

  it('renders a single, unlinked item for a top-level route (no parent)', () => {
    const { result } = renderCrumbs('/drives', '/drives');
    expect(result.current).toHaveLength(1);
    // The current (trailing) item is plain text — no href.
    expect(result.current[0]).toEqual({ label: 'Drives', href: undefined });
  });

  it('walks a one-level parent chain: parent is linked, current is not', () => {
    const { result } = renderCrumbs('/drives/123', '/drives/:id');
    expect(result.current).toHaveLength(2);
    expect(result.current[0]).toEqual({ label: 'Drives', href: '/drives' });
    expect(result.current[1]).toEqual({ label: 'Drive Detail', href: undefined });
  });

  it('substitutes :param values into ancestor hrefs across a deep chain', () => {
    const { result } = renderCrumbs('/drives/123/replay', '/drives/:id/replay');
    expect(result.current.map((i) => i.label)).toEqual(['Drives', 'Drive Detail', 'Trip Replay']);
    expect(result.current[0].href).toBe('/drives');
    // :id resolved from the URL — this is the ancestor detail link.
    expect(result.current[1].href).toBe('/drives/123');
    expect(result.current[2].href).toBeUndefined();
  });

  it('prefers a per-render override label over the i18n/default label', () => {
    const { result } = renderCrumbs('/drives/123', '/drives/:id', { '/drives/:id': 'My Trip' });
    expect(result.current[1].label).toBe('My Trip');
    // Ancestors without an override keep their default label.
    expect(result.current[0].label).toBe('Drives');
  });

  it('expands a {{param}} placeholder inside an override label', () => {
    const { result } = renderCrumbs('/drives/123', '/drives/:id', { '/drives/:id': 'Drive #{{id}}' });
    expect(result.current[1].label).toBe('Drive #123');
  });

  it('replaces EVERY occurrence of a repeated {{param}} placeholder', () => {
    // Regression guard: a label that references the same param twice must be
    // fully resolved, not just its first occurrence.
    const { result } = renderCrumbs('/drives/123', '/drives/:id', { '/drives/:id': '{{id}} · {{id}}' });
    expect(result.current[1].label).toBe('123 · 123');
  });

  it('substitutes a placeholder that comes from the default (i18n) label', () => {
    const { result } = renderCrumbs('/items/7', '/items/:id');
    expect(result.current[0]).toEqual({ label: 'Items', href: '/items' });
    expect(result.current[1].label).toBe('Item 7');
  });

  it('stops the walk cleanly when a parent has no ROUTE_META entry', () => {
    const { result } = renderCrumbs('/orphan', '/orphan');
    expect(result.current).toHaveLength(1);
    expect(result.current[0]).toEqual({ label: 'Orphan', href: undefined });
  });

  it('terminates (does not infinite-loop) on a cyclic parent chain', () => {
    const { result } = renderCrumbs('/cycle-a', '/cycle-a');
    // a → b → (a already visited) → break: exactly two items, root-first.
    expect(result.current).toHaveLength(2);
    expect(result.current.map((i) => i.label)).toEqual(['Cycle B', 'Cycle A']);
    expect(result.current[0].href).toBe('/cycle-b');
    expect(result.current[1].href).toBeUndefined();
  });
});
