package models

import "time"

// Notification mirrors the typed `notifications` schema.
// Append-only delivery log: each row represents one rendered+dispatched
// notification attempt. Status changes are tracked via DeliveryStatus and
// Attempts (no UpdatedAt — table is effectively immutable per row).
//
// Schema source: .github/prompts/db-refactor/schema/20-notifications.sql
//
//	(migrations/000142_baseline_typed.up.sql, table `notifications`).
//
// ADR-005: no `raw_json` / JSONB carve-out. All fields are typed columns.
type Notification struct {
	ID int64 `db:"id" json:"id"`
	// Ts is the moment the notification row was created (event time).
	Ts time.Time `db:"ts" json:"ts"`
	// VehicleID is NULL when the notification is not vehicle-scoped
	// (e.g. system-wide alerts).
	VehicleID *int64 `db:"vehicle_id" json:"vehicle_id,omitempty"`
	// RuleID is NULL when the notification was not generated by an alert rule
	// (e.g. ad-hoc / digest / system notifications).
	RuleID    *int64 `db:"rule_id"    json:"rule_id,omitempty"`
	ChannelID int64  `db:"channel_id" json:"channel_id"`
	// Severity is one of: 'info', 'warn', 'critical'.
	Severity string `db:"severity" json:"severity"`
	Title    string `db:"title"    json:"title"`
	Body     string `db:"body"     json:"body"`
	// DeliveryStatus is one of: 'pending', 'delivered', 'failed', 'suppressed'.
	DeliveryStatus string     `db:"delivery_status" json:"delivery_status"`
	DeliveredAt    *time.Time `db:"delivered_at"    json:"delivered_at,omitempty"`
	ErrorMessage   *string    `db:"error_message"   json:"error_message,omitempty"`
	// Attempts counts dispatch attempts made for this notification.
	Attempts int16 `db:"attempts" json:"attempts"`
}
