// <auto-generated />
// Generated verbatim from web/src/features/system/pages/StatusApiDocsPage.tsx example payloads via
// JSON.stringify(example, null, 2). Do not hand-edit — regenerate to preserve byte-for-byte web parity.
namespace TeslaSync.App.FeatureViews.SystemOps;

/// <summary>
/// The verbatim example-response payloads each endpoint card renders inside its disclosure (web
/// <c>Endpoint.example</c> rendered through <c>JSON.stringify(example, null, 2)</c>). Pure data,
/// Microsoft.UI-free, so the projection is unit-tested headlessly; reproduced exactly so the native
/// disclosure shows the identical JSON a self-hosted operator reads on the web docs page.
/// </summary>
internal static class StatusApiExamples
{
    /// <summary>The example response body for the <c>Snapshot</c> endpoint card.</summary>
    public const string Snapshot =
        """
        {
          "status": "operational",
          "generated_at": "2025-01-15T14:32:11Z",
          "version": {
            "build": "1.4.2",
            "go_version": "go1.22.5",
            "started_at": "2025-01-10T08:00:00Z"
          },
          "counts": {
            "components_total": 8,
            "components_healthy": 8,
            "components_degraded": 0,
            "components_unhealthy": 0
          },
          "resources": {
            "goroutines": 142,
            "uptime_seconds": 458321.4,
            "go_version": "go1.22.5"
          },
          "incidents": []
        }
        """;

    /// <summary>The example response body for the <c>Components</c> endpoint card.</summary>
    public const string Components =
        """
        {
          "generated_at": "2025-01-15T14:32:11Z",
          "counts": {
            "components_total": 3,
            "components_healthy": 3,
            "components_degraded": 0,
            "components_unhealthy": 0
          },
          "components": [
            {
              "name": "database",
              "status": "healthy",
              "consecutive_failures": 0,
              "last_check_at": "2025-01-15T14:32:08Z"
            },
            {
              "name": "mqtt",
              "status": "healthy",
              "consecutive_failures": 0,
              "last_check_at": "2025-01-15T14:32:08Z"
            },
            {
              "name": "tesla",
              "status": "healthy",
              "consecutive_failures": 0,
              "last_check_at": "2025-01-15T14:32:08Z"
            }
          ]
        }
        """;

    /// <summary>The example response body for the <c>Resources</c> endpoint card.</summary>
    public const string Resources =
        """
        {
          "generated_at": "2025-01-15T14:32:11Z",
          "resources": {
            "goroutines": 142,
            "uptime_seconds": 458321.4,
            "go_version": "go1.22.5"
          }
        }
        """;

    /// <summary>The example response body for the <c>Uptime</c> endpoint card.</summary>
    public const string Uptime =
        """
        {
          "window": "30d",
          "uptime_percent": 100,
          "healthy_count": 8,
          "total_count": 8,
          "generated_at": "2025-01-15T14:32:11Z",
          "historical_source": "current_snapshot",
          "note": "Per-window uptime requires the heartbeat history backend (planned). This value reflects the current snapshot only."
        }
        """;

    /// <summary>The example response body for the <c>Incidents</c> endpoint card.</summary>
    public const string Incidents =
        """
        {
          "count": 1,
          "incidents": [
            {
              "id": 17,
              "title": "MQTT broker reconnect storm",
              "status": "monitoring",
              "severity": "minor",
              "source": "manual",
              "affected_components": [
                "mqtt"
              ],
              "started_at": "2025-01-15T13:55:00Z",
              "updated_at": "2025-01-15T14:20:00Z",
              "updates": [
                {
                  "at": "2025-01-15T13:55:00Z",
                  "status": "investigating",
                  "message": "Incident opened.",
                  "author": "operator"
                },
                {
                  "at": "2025-01-15T14:10:00Z",
                  "status": "identified",
                  "message": "Cause: TLS cert rotation gap.",
                  "author": "operator"
                },
                {
                  "at": "2025-01-15T14:20:00Z",
                  "status": "monitoring",
                  "message": "Cert rotated; watching.",
                  "author": "operator"
                }
              ]
            }
          ]
        }
        """;

    /// <summary>The example response body for the <c>Live</c> endpoint card.</summary>
    public const string Live =
        """
        {
          "note": "event: status\\ndata: <full StatusSnapshot JSON>\\n\\n"
        }
        """;
}
