ALTER TABLE settings ADD COLUMN theme VARCHAR(20) NOT NULL DEFAULT 'neon-cyan';
ALTER TABLE settings ADD COLUMN mode VARCHAR(20) NOT NULL DEFAULT 'dark';
ALTER TABLE settings ADD COLUMN custom_primary VARCHAR(10) NOT NULL DEFAULT '#00b4d8';
ALTER TABLE settings ADD COLUMN custom_accent VARCHAR(10) NOT NULL DEFAULT '#e63946';
