-- Add pgvector for semantic search over vehicle data.
--
-- Powers the AI chatbot "find similar drives / charges / alerts" features.
-- Embeddings are generated by an LLM provider (OpenAI by default) from a
-- human-readable summary of each entity, then stored alongside the source
-- entity reference. Cosine similarity (HNSW index) drives nearest-neighbor
-- search at query time.
--
-- Requires the postgres image to ship the `vector` extension. The pgvector
-- project publishes images that bundle it: `pgvector/pgvector:pg17`.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS embeddings (
    id           BIGSERIAL PRIMARY KEY,
    entity_type  TEXT        NOT NULL,           -- 'drive', 'charge', 'alert', 'daily_summary'
    entity_id    BIGINT      NOT NULL,           -- FK to source table (logical, no constraint)
    vehicle_id   BIGINT      NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
    content      TEXT        NOT NULL,           -- Human-readable summary text
    embedding    vector(1536),                   -- OpenAI text-embedding-3-small dimension
    metadata     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT embeddings_entity_unique UNIQUE (entity_type, entity_id)
);

-- HNSW index for fast approximate nearest neighbor search on cosine distance.
-- m / ef_construction defaults are tuned for read-heavy workloads with <1M rows.
CREATE INDEX IF NOT EXISTS idx_embeddings_vector
    ON embeddings
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- Composite indexes for filtered searches (per-vehicle, per-type).
CREATE INDEX IF NOT EXISTS idx_embeddings_entity   ON embeddings (entity_type, vehicle_id);
CREATE INDEX IF NOT EXISTS idx_embeddings_vehicle  ON embeddings (vehicle_id, created_at DESC);
