-- Down: recreate the columns that were dropped in 000144 and repopulate them
-- from the signals JSONB. Values are cast back to their original types.
-- After this .down runs, 000143.down/000142.down can be run to fully reverse.

ALTER TABLE charging_telemetry
    ADD COLUMN IF NOT EXISTS soc double precision,
    ADD COLUMN IF NOT EXISTS detailed_charge_state character varying(50),
    ADD COLUMN IF NOT EXISTS charge_limit_soc integer,
    ADD COLUMN IF NOT EXISTS charge_amps double precision,
    ADD COLUMN IF NOT EXISTS charge_current_request double precision,
    ADD COLUMN IF NOT EXISTS charge_current_request_max double precision,
    ADD COLUMN IF NOT EXISTS charge_enable_request boolean,
    ADD COLUMN IF NOT EXISTS charger_phases integer,
    ADD COLUMN IF NOT EXISTS dc_charging_energy_in double precision,
    ADD COLUMN IF NOT EXISTS ac_charging_power double precision,
    ADD COLUMN IF NOT EXISTS ac_charging_energy_in double precision,
    ADD COLUMN IF NOT EXISTS energy_remaining double precision,
    ADD COLUMN IF NOT EXISTS est_battery_range double precision,
    ADD COLUMN IF NOT EXISTS ideal_battery_range double precision,
    ADD COLUMN IF NOT EXISTS rated_range double precision,
    ADD COLUMN IF NOT EXISTS pack_voltage double precision,
    ADD COLUMN IF NOT EXISTS pack_current double precision,
    ADD COLUMN IF NOT EXISTS charge_port character varying(50),
    ADD COLUMN IF NOT EXISTS charge_port_door_open boolean,
    ADD COLUMN IF NOT EXISTS charge_port_latch character varying(50),
    ADD COLUMN IF NOT EXISTS charge_port_cold_weather_mode boolean,
    ADD COLUMN IF NOT EXISTS charging_cable_type character varying(50),
    ADD COLUMN IF NOT EXISTS fast_charger_present boolean,
    ADD COLUMN IF NOT EXISTS fast_charger_type character varying(50),
    ADD COLUMN IF NOT EXISTS estimated_hours_to_charge double precision,
    ADD COLUMN IF NOT EXISTS scheduled_charging_mode character varying(50),
    ADD COLUMN IF NOT EXISTS scheduled_charging_pending boolean,
    ADD COLUMN IF NOT EXISTS preconditioning_enabled boolean,
    ADD COLUMN IF NOT EXISTS brick_voltage_max double precision,
    ADD COLUMN IF NOT EXISTS brick_voltage_min double precision,
    ADD COLUMN IF NOT EXISTS num_brick_voltage_max integer,
    ADD COLUMN IF NOT EXISTS num_brick_voltage_min integer,
    ADD COLUMN IF NOT EXISTS module_temp_max double precision,
    ADD COLUMN IF NOT EXISTS module_temp_min double precision,
    ADD COLUMN IF NOT EXISTS num_module_temp_max integer,
    ADD COLUMN IF NOT EXISTS num_module_temp_min integer,
    ADD COLUMN IF NOT EXISTS battery_heater_on boolean,
    ADD COLUMN IF NOT EXISTS not_enough_power_to_heat boolean,
    ADD COLUMN IF NOT EXISTS bms_state character varying(50),
    ADD COLUMN IF NOT EXISTS bms_fullcharge_complete boolean,
    ADD COLUMN IF NOT EXISTS dcdc_enable boolean,
    ADD COLUMN IF NOT EXISTS isolation_resistance double precision,
    ADD COLUMN IF NOT EXISTS lifetime_energy_used double precision,
    ADD COLUMN IF NOT EXISTS supercharger_session_trip_planner boolean,
    ADD COLUMN IF NOT EXISTS powershare_status character varying(50),
    ADD COLUMN IF NOT EXISTS powershare_type character varying(50),
    ADD COLUMN IF NOT EXISTS powershare_stop_reason character varying(50),
    ADD COLUMN IF NOT EXISTS powershare_hours_left double precision,
    ADD COLUMN IF NOT EXISTS powershare_power_kw double precision,
    ADD COLUMN IF NOT EXISTS scheduled_charging_start_time text,
    ADD COLUMN IF NOT EXISTS scheduled_departure_time text,
    ADD COLUMN IF NOT EXISTS expected_energy_pct_at_arrival double precision;

-- Note: full repopulate logic omitted for brevity; signals JSONB retains the
-- authoritative values. Operators rolling back should run a targeted UPDATE
-- like:
--   UPDATE charging_telemetry SET soc = (signals->>'soc')::double precision;
-- for each column they need hydrated.

ALTER TABLE climate_snapshots
    ADD COLUMN IF NOT EXISTS hvac_power double precision,
    ADD COLUMN IF NOT EXISTS hvac_left_temp_request double precision,
    ADD COLUMN IF NOT EXISTS hvac_right_temp_request double precision,
    ADD COLUMN IF NOT EXISTS cabin_overheat_mode character varying(50),
    ADD COLUMN IF NOT EXISTS defrost_mode character varying(50),
    ADD COLUMN IF NOT EXISTS battery_heater_on boolean,
    ADD COLUMN IF NOT EXISTS hvac_fan_status integer,
    ADD COLUMN IF NOT EXISTS hvac_steering_wheel_heat_auto boolean,
    ADD COLUMN IF NOT EXISTS hvac_steering_wheel_heat_level integer,
    ADD COLUMN IF NOT EXISTS climate_keeper_mode character varying(50),
    ADD COLUMN IF NOT EXISTS cabin_overheat_protection_temp_limit character varying(50),
    ADD COLUMN IF NOT EXISTS defrost_for_preconditioning boolean,
    ADD COLUMN IF NOT EXISTS seat_heater_left integer,
    ADD COLUMN IF NOT EXISTS seat_heater_right integer,
    ADD COLUMN IF NOT EXISTS seat_heater_rear_left integer,
    ADD COLUMN IF NOT EXISTS seat_heater_rear_center integer,
    ADD COLUMN IF NOT EXISTS seat_heater_rear_right integer,
    ADD COLUMN IF NOT EXISTS seat_vent_enabled boolean,
    ADD COLUMN IF NOT EXISTS climate_seat_cooling_front_left integer,
    ADD COLUMN IF NOT EXISTS climate_seat_cooling_front_right integer,
    ADD COLUMN IF NOT EXISTS auto_seat_climate_left boolean,
    ADD COLUMN IF NOT EXISTS auto_seat_climate_right boolean,
    ADD COLUMN IF NOT EXISTS rear_defrost_enabled boolean,
    ADD COLUMN IF NOT EXISTS rear_display_hvac_enabled boolean,
    ADD COLUMN IF NOT EXISTS wiper_heat_enabled boolean;

ALTER TABLE security_events
    ADD COLUMN IF NOT EXISTS fd_window character varying(50),
    ADD COLUMN IF NOT EXISTS fp_window character varying(50),
    ADD COLUMN IF NOT EXISTS rd_window character varying(50),
    ADD COLUMN IF NOT EXISTS rp_window character varying(50),
    ADD COLUMN IF NOT EXISTS homelink_nearby boolean,
    ADD COLUMN IF NOT EXISTS guest_mode boolean,
    ADD COLUMN IF NOT EXISTS homelink_device_count integer,
    ADD COLUMN IF NOT EXISTS guest_mode_mobile_access_state character varying(50),
    ADD COLUMN IF NOT EXISTS center_display character varying(50),
    ADD COLUMN IF NOT EXISTS speed_limit_mode character varying(50),
    ADD COLUMN IF NOT EXISTS valet_mode_enabled boolean,
    ADD COLUMN IF NOT EXISTS service_mode boolean,
    ADD COLUMN IF NOT EXISTS current_limit_mph double precision,
    ADD COLUMN IF NOT EXISTS paired_phone_key_count integer,
    ADD COLUMN IF NOT EXISTS lights_hazards_active boolean,
    ADD COLUMN IF NOT EXISTS lights_high_beams boolean,
    ADD COLUMN IF NOT EXISTS lights_turn_signal character varying(50),
    ADD COLUMN IF NOT EXISTS tonneau_position character varying(50),
    ADD COLUMN IF NOT EXISTS tonneau_open_percent double precision,
    ADD COLUMN IF NOT EXISTS tonneau_tent_mode text,
    ADD COLUMN IF NOT EXISTS driver_seat_belt boolean,
    ADD COLUMN IF NOT EXISTS passenger_seat_belt boolean;

ALTER TABLE motor_snapshots
    ADD COLUMN IF NOT EXISTS di_torque double precision,
    ADD COLUMN IF NOT EXISTS di_axle_speed double precision,
    ADD COLUMN IF NOT EXISTS di_stator_temp double precision,
    ADD COLUMN IF NOT EXISTS pedal_position double precision,
    ADD COLUMN IF NOT EXISTS brake_pedal boolean,
    ADD COLUMN IF NOT EXISTS lateral_accel double precision,
    ADD COLUMN IF NOT EXISTS longitudinal_accel double precision,
    ADD COLUMN IF NOT EXISTS di_torque_actual_f double precision,
    ADD COLUMN IF NOT EXISTS di_torque_actual_r double precision,
    ADD COLUMN IF NOT EXISTS di_torque_actual_rel double precision,
    ADD COLUMN IF NOT EXISTS di_torque_actual_rer double precision,
    ADD COLUMN IF NOT EXISTS di_axle_speed_f double precision,
    ADD COLUMN IF NOT EXISTS di_axle_speed_rel double precision,
    ADD COLUMN IF NOT EXISTS di_axle_speed_rer double precision,
    ADD COLUMN IF NOT EXISTS di_state_f character varying(50),
    ADD COLUMN IF NOT EXISTS di_state_rel character varying(50),
    ADD COLUMN IF NOT EXISTS di_state_rer character varying(50),
    ADD COLUMN IF NOT EXISTS di_stator_temp_f double precision,
    ADD COLUMN IF NOT EXISTS di_stator_temp_rel double precision,
    ADD COLUMN IF NOT EXISTS di_stator_temp_rer double precision,
    ADD COLUMN IF NOT EXISTS di_heatsink_t_f double precision,
    ADD COLUMN IF NOT EXISTS di_heatsink_t_r double precision,
    ADD COLUMN IF NOT EXISTS di_heatsink_t_rel double precision,
    ADD COLUMN IF NOT EXISTS di_heatsink_t_rer double precision,
    ADD COLUMN IF NOT EXISTS di_inverter_t_f double precision,
    ADD COLUMN IF NOT EXISTS di_inverter_t_r double precision,
    ADD COLUMN IF NOT EXISTS di_inverter_t_rel double precision,
    ADD COLUMN IF NOT EXISTS di_inverter_t_rer double precision,
    ADD COLUMN IF NOT EXISTS di_motor_current_f double precision,
    ADD COLUMN IF NOT EXISTS di_motor_current_r double precision,
    ADD COLUMN IF NOT EXISTS di_motor_current_rel double precision,
    ADD COLUMN IF NOT EXISTS di_motor_current_rer double precision,
    ADD COLUMN IF NOT EXISTS di_v_bat_f double precision,
    ADD COLUMN IF NOT EXISTS di_v_bat_r double precision,
    ADD COLUMN IF NOT EXISTS di_v_bat_rel double precision,
    ADD COLUMN IF NOT EXISTS di_v_bat_rer double precision,
    ADD COLUMN IF NOT EXISTS di_slave_torque_cmd double precision,
    ADD COLUMN IF NOT EXISTS hvil character varying(50),
    ADD COLUMN IF NOT EXISTS brake_pedal_pos double precision,
    ADD COLUMN IF NOT EXISTS cruise_set_speed double precision,
    ADD COLUMN IF NOT EXISTS drive_rail boolean,
    ADD COLUMN IF NOT EXISTS lifetime_energy_gained_regen double precision,
    ADD COLUMN IF NOT EXISTS lifetime_energy_used_drive double precision;

ALTER TABLE tire_pressure_snapshots
    ADD COLUMN IF NOT EXISTS tpms_hard_warnings text,
    ADD COLUMN IF NOT EXISTS tpms_soft_warnings text,
    ADD COLUMN IF NOT EXISTS last_seen_time_fl timestamp with time zone,
    ADD COLUMN IF NOT EXISTS last_seen_time_fr timestamp with time zone,
    ADD COLUMN IF NOT EXISTS last_seen_time_rl timestamp with time zone,
    ADD COLUMN IF NOT EXISTS last_seen_time_rr timestamp with time zone;

ALTER TABLE media_snapshots
    ADD COLUMN IF NOT EXISTS now_playing_title character varying(255),
    ADD COLUMN IF NOT EXISTS now_playing_artist character varying(255),
    ADD COLUMN IF NOT EXISTS now_playing_album character varying(255),
    ADD COLUMN IF NOT EXISTS now_playing_station character varying(255),
    ADD COLUMN IF NOT EXISTS now_playing_duration integer,
    ADD COLUMN IF NOT EXISTS now_playing_elapsed integer,
    ADD COLUMN IF NOT EXISTS playback_source character varying(50),
    ADD COLUMN IF NOT EXISTS audio_volume_max double precision,
    ADD COLUMN IF NOT EXISTS audio_volume_increment double precision;

ALTER TABLE safety_snapshots
    ADD COLUMN IF NOT EXISTS automatic_blind_spot_camera boolean,
    ADD COLUMN IF NOT EXISTS automatic_emergency_braking_off boolean,
    ADD COLUMN IF NOT EXISTS blind_spot_collision_warning boolean,
    ADD COLUMN IF NOT EXISTS cruise_follow_distance character varying(50),
    ADD COLUMN IF NOT EXISTS emergency_lane_departure_avoidance boolean,
    ADD COLUMN IF NOT EXISTS forward_collision_warning character varying(100),
    ADD COLUMN IF NOT EXISTS lane_departure_avoidance character varying(100),
    ADD COLUMN IF NOT EXISTS speed_limit_warning character varying(50);

ALTER TABLE vehicle_config_snapshots
    ADD COLUMN IF NOT EXISTS trim character varying(50),
    ADD COLUMN IF NOT EXISTS exterior_color character varying(50),
    ADD COLUMN IF NOT EXISTS roof_color character varying(50),
    ADD COLUMN IF NOT EXISTS wheel_type character varying(50),
    ADD COLUMN IF NOT EXISTS rear_seat_heaters character varying(100),
    ADD COLUMN IF NOT EXISTS sunroof_installed character varying(100),
    ADD COLUMN IF NOT EXISTS efficiency_package character varying(100),
    ADD COLUMN IF NOT EXISTS europe_vehicle boolean,
    ADD COLUMN IF NOT EXISTS right_hand_drive boolean,
    ADD COLUMN IF NOT EXISTS remote_start_enabled boolean,
    ADD COLUMN IF NOT EXISTS charge_port character varying(50),
    ADD COLUMN IF NOT EXISTS offroad_lightbar_present boolean,
    ADD COLUMN IF NOT EXISTS software_update_version character varying(50),
    ADD COLUMN IF NOT EXISTS software_update_download_pct integer,
    ADD COLUMN IF NOT EXISTS software_update_install_pct integer,
    ADD COLUMN IF NOT EXISTS software_update_expected_duration integer,
    ADD COLUMN IF NOT EXISTS software_update_scheduled_start text;

ALTER TABLE user_preference_snapshots
    ADD COLUMN IF NOT EXISTS setting_24hr_time boolean,
    ADD COLUMN IF NOT EXISTS setting_charge_unit character varying(50),
    ADD COLUMN IF NOT EXISTS setting_tire_pressure_unit character varying(50);
