-- Phase-42 / Prompt 0033: Recreate drives + trips + trip_drives with
-- SI-canonical columns.
--
-- ADR-004 #4: every unit-bearing column lives in canonical SI and the
-- unit suffix is part of the column name (distance_m for meters,
-- duration_s for seconds, energy_used_wh / regen_energy_wh for
-- Watt-hours, avg_speed_mps / max_speed_mps for meters-per-second,
-- avg_power_w / peak_power_w for Watts, ambient_temp_c_avg for
-- Celsius, *_odometer_m for meters). The contract is self-documenting
-- and audit-grep-able — a future reader (or a linter) cannot mistake
-- an SI value for a wire-format value, and the schema cannot drift
-- back toward the imperial / kilo-prefixed columns that the legacy
-- baseline carried.
--
-- Forward-only rewrite: the pre-phase-42 drive / trip tables were
-- created by 000142_baseline_typed (which itself dropped legacy
-- variants and reinstalled them with mixed imperial + kilo-prefixed
-- columns: a distance column in miles, a duration column in minutes,
-- speed columns in miles-per-hour, energy columns in kilo-watt-hours,
-- battery columns as smallint percent, and a CHECK constraint on
-- ended_status). Phase-42 is forward-only with no legacy retention
-- (.github/ARCHITECTURE.md ADR-004), so this migration drops the
-- legacy `drives`, `trips`, and `trip_drives` tables wholesale and
-- recreates them with SI-canonical columns. Existing rows are not
-- migrated; clients backfill from MQTT replay and the
-- session-completion writer if needed (prompt 0090 runbook).
--
-- Cascading drop notes:
--   * The legacy `drives` table had a foreign-key reference from
--     `share_tokens.drive_id` (migration 000125_add_share_tokens).
--     The CASCADE on `DROP TABLE drives` drops that FK constraint
--     but leaves the `share_tokens` table itself in place. Existing
--     `share_tokens` rows therefore lose their referential link to
--     the (now-recreated) `drives` table; a follow-up prompt
--     reinstalls the FK once the drive-writer wires up against the
--     new schema.
--   * The legacy `trip_drives` join carried an `added_at` audit
--     column from 000142. This rewrite replaces it with the
--     prompt-mandated `position INT NOT NULL` ordering column. Any
--     pre-phase-42 join rows are discarded by the CASCADE drop;
--     trip composition is rebuilt by the user-curated trip writer.
--
-- Slot variance: prompt 0033 hardcodes slot 000165, but that slot is
-- already occupied by 000165_push_subscriptions (a pre-phase-42
-- migration committed before this phase began). Slot 000185 is the
-- next free slot after the trailing edge of existing migrations
-- (000184_charging_si is the immediately prior phase-42 migration,
-- created by prompt 0032). This mirrors the slot-variance the
-- predecessor phase-42 prompts 0022 (000160 -> 000181), 0030
-- (000162 -> 000182), 0031 (000163 -> 000183), and 0032
-- (000164 -> 000184) applied. The schema, semantics, and gate intent
-- are otherwise exactly as the prompt specifies.
--
-- Tables created (all regular tables — none are hypertables; row
-- counts are bounded by drive frequency, not telemetry tick rate):
--   drives       — one row per Tesla drive (started_at -> ended_at
--                  summary with SI-canonical aggregates).
--   trips        — higher-level user grouping of consecutive drives
--                  (commute, road trip). Optional, user-curated,
--                  optionally auto_generated by a future prompt.
--   trip_drives  — M:N join between trips and drives with an
--                  ordered `position` column for trip composition.
--
-- Routing rule (a later phase-42 prompt wires this in routing.yaml):
--   drive-summary writer  -> drives           (built from drive_telemetry
--                                              + signal_log close-out)
--   trip writer           -> trips            (user-curated; not a
--                                              direct router destination)
--   trip composition      -> trip_drives      (user-curated)
--
-- Compression and retention policies are intentionally NOT applied
-- here: these are regular tables (not hypertables), and the prompt
-- explicitly notes that the row counts are low. Phase-42 defers any
-- per-table policy decisions to a later operational prompt regardless.

-- Defensive: drop any leftover legacy drive / trip objects so this
-- migration is self-healing if a developer reapplies an old database
-- snapshot. Order matters — drop the join first, then trips (no
-- inbound FK), then drives (CASCADE handles the residual FK from
-- share_tokens).
DROP TABLE IF EXISTS trip_drives CASCADE;
DROP TABLE IF EXISTS trips       CASCADE;
DROP TABLE IF EXISTS drives      CASCADE;

-- =========================================================================
-- drives — one row per Tesla drive (started_at -> ended_at summary).
-- Regular table keyed by `id`. Built by the drive-completion writer
-- at end-of-drive time from the per-tick rows in drive_telemetry plus
-- the latest signal_log values for SoC / odometer / position. Distance
-- in meters, duration in seconds, energy in Watt-hours, speed in
-- meters-per-second, power in Watts, temperature in Celsius — all SI.
-- =========================================================================
CREATE TABLE drives (
  id                  BIGSERIAL    PRIMARY KEY,
  vehicle_id          BIGINT       NOT NULL,
  started_at          TIMESTAMPTZ  NOT NULL,
  ended_at            TIMESTAMPTZ,
  start_lat           DOUBLE PRECISION,
  start_lng           DOUBLE PRECISION,
  end_lat             DOUBLE PRECISION,
  end_lng             DOUBLE PRECISION,
  start_place         TEXT,
  end_place           TEXT,
  start_odometer_m    DOUBLE PRECISION,
  end_odometer_m      DOUBLE PRECISION,
  distance_m          DOUBLE PRECISION,
  duration_s          BIGINT,
  start_soc_pct       REAL,
  end_soc_pct         REAL,
  energy_used_wh      DOUBLE PRECISION,
  regen_energy_wh     DOUBLE PRECISION,
  avg_speed_mps       DOUBLE PRECISION,
  max_speed_mps       DOUBLE PRECISION,
  avg_power_w         DOUBLE PRECISION,
  peak_power_w        DOUBLE PRECISION,
  ambient_temp_c_avg  DOUBLE PRECISION
);

CREATE INDEX drives_vehicle_started ON drives (vehicle_id, started_at DESC);

COMMENT ON TABLE drives IS
  'Phase-42 SI-canonical drive-summary table. One row per drive, built at end-of-drive time from drive_telemetry + signal_log close-out. Regular table (not a hypertable) — row count is bounded by drive frequency.';
COMMENT ON COLUMN drives.id IS
  'Surrogate primary key (BIGSERIAL). drive_telemetry.drive_id refers to this value (no DB-level FK; the hot path must not block on a referential check).';
COMMENT ON COLUMN drives.vehicle_id IS
  'Vehicles foreign-key value (no constraint at this slot to keep the writer hot path lock-free; a later prompt may reinstate the constraint once vehicle ingestion is settled).';
COMMENT ON COLUMN drives.started_at IS
  'Wall-clock timestamp at which the drive began (first VehicleSpeed > 0 tick after Park exit).';
COMMENT ON COLUMN drives.ended_at IS
  'Wall-clock timestamp at which the drive ended. NULL while in progress.';
COMMENT ON COLUMN drives.start_lat IS
  'WGS84 latitude in decimal degrees at drive start (angular, no SI conversion).';
COMMENT ON COLUMN drives.start_lng IS
  'WGS84 longitude in decimal degrees at drive start (angular, no SI conversion).';
COMMENT ON COLUMN drives.end_lat IS
  'WGS84 latitude in decimal degrees at drive end.';
COMMENT ON COLUMN drives.end_lng IS
  'WGS84 longitude in decimal degrees at drive end.';
COMMENT ON COLUMN drives.start_place IS
  'Geocoded place name at drive start. Free-text label.';
COMMENT ON COLUMN drives.end_place IS
  'Geocoded place name at drive end. Free-text label.';
COMMENT ON COLUMN drives.start_odometer_m IS
  'Odometer reading in meters at drive start (SI). Sourced from Odometer.';
COMMENT ON COLUMN drives.end_odometer_m IS
  'Odometer reading in meters at drive end (SI). Sourced from Odometer.';
COMMENT ON COLUMN drives.distance_m IS
  'Drive distance in meters (SI). Maintained by the close-out writer (typically end_odometer_m - start_odometer_m, but recomputed from per-tick integration when odometer is missing).';
COMMENT ON COLUMN drives.duration_s IS
  'Drive duration in seconds (SI). BIGINT to keep arithmetic exact even for multi-day drives.';
COMMENT ON COLUMN drives.start_soc_pct IS
  'Battery SoC at drive start, percent of pack capacity (0-100). Sourced from BatteryLevel at started_at. REAL is sufficient for percent values.';
COMMENT ON COLUMN drives.end_soc_pct IS
  'Battery SoC at drive end, percent of pack capacity (0-100). Sourced from BatteryLevel at ended_at.';
COMMENT ON COLUMN drives.energy_used_wh IS
  'Net pack energy consumed during the drive in Watt-hours (SI). Excludes regenerative recovery (tracked separately as regen_energy_wh).';
COMMENT ON COLUMN drives.regen_energy_wh IS
  'Energy returned to the pack via regenerative braking in Watt-hours (SI).';
COMMENT ON COLUMN drives.avg_speed_mps IS
  'Mean speed during the active portion of the drive in meters-per-second (SI). Sourced from VehicleSpeed.';
COMMENT ON COLUMN drives.max_speed_mps IS
  'Peak speed observed during the drive in meters-per-second (SI).';
COMMENT ON COLUMN drives.avg_power_w IS
  'Mean traction power during the active portion of the drive in Watts (SI). Negative values represent net regen periods.';
COMMENT ON COLUMN drives.peak_power_w IS
  'Peak instantaneous traction power observed during the drive in Watts (SI).';
COMMENT ON COLUMN drives.ambient_temp_c_avg IS
  'Mean ambient (outside) temperature during the drive in Celsius (canonical SI form for this codebase).';

-- =========================================================================
-- trips — higher-level user grouping of consecutive drives.
-- Optional, user-curated grouping (e.g., a commute, a road trip, a
-- vacation). May also be `auto_generated` by a future automation
-- prompt. Notes are free-text; created_by_user is nullable so an
-- auto-generated trip can omit attribution.
-- =========================================================================
CREATE TABLE trips (
  id              BIGSERIAL    PRIMARY KEY,
  vehicle_id      BIGINT       NOT NULL,
  name            TEXT,
  started_at      TIMESTAMPTZ  NOT NULL,
  ended_at        TIMESTAMPTZ,
  created_by_user BIGINT,
  auto_generated  BOOLEAN      DEFAULT false,
  notes           TEXT
);

CREATE INDEX trips_vehicle_started ON trips (vehicle_id, started_at DESC);

COMMENT ON TABLE trips IS
  'Phase-42 user-curated trip grouping (e.g., a commute, road trip, or vacation). Composition is stored in trip_drives. Distance / energy / duration aggregates are intentionally NOT denormalized here — they are recomputed from constituent drives on read to avoid drift.';
COMMENT ON COLUMN trips.id IS
  'Surrogate primary key (BIGSERIAL). Referenced by trip_drives.trip_id with ON DELETE CASCADE.';
COMMENT ON COLUMN trips.name IS
  'User-supplied trip name. Free-text. Nullable so an auto-generated trip can be unnamed at creation.';
COMMENT ON COLUMN trips.started_at IS
  'Wall-clock timestamp at which the trip is considered to begin (typically the started_at of the earliest constituent drive).';
COMMENT ON COLUMN trips.ended_at IS
  'Wall-clock timestamp at which the trip is considered to end. NULL while open.';
COMMENT ON COLUMN trips.created_by_user IS
  'User id (no DB-level FK at this slot) of the user who created the trip. Nullable: an auto_generated trip has no human author.';
COMMENT ON COLUMN trips.auto_generated IS
  'TRUE when the trip was created by an automation rule (a future phase-42 prompt wires the auto-grouping logic). Defaults to FALSE for user-curated trips.';
COMMENT ON COLUMN trips.notes IS
  'User-supplied free-text notes. No length cap.';

-- =========================================================================
-- trip_drives — M:N join between trips and drives.
-- Composite primary key (trip_id, drive_id). The `position` column
-- carries the user-defined ordering of drives within a trip (1-based,
-- monotonically increasing per trip; the writer is responsible for
-- assigning positions). ON DELETE CASCADE on both FKs ensures that
-- removing a trip cleans up the membership rows without touching
-- drives, and removing a drive removes its trip memberships without
-- touching trips.
-- =========================================================================
CREATE TABLE trip_drives (
  trip_id  BIGINT NOT NULL REFERENCES trips(id)  ON DELETE CASCADE,
  drive_id BIGINT NOT NULL REFERENCES drives(id) ON DELETE CASCADE,
  position INT    NOT NULL,
  PRIMARY KEY (trip_id, drive_id)
);

CREATE INDEX trip_drives_drive ON trip_drives (drive_id);

COMMENT ON TABLE trip_drives IS
  'Phase-42 M:N join between trips and drives, with ordered membership. Cascade delete on the parent trip removes membership rows without touching drives; cascade delete on a drive removes its memberships without touching trips.';
COMMENT ON COLUMN trip_drives.position IS
  'Ordering of this drive within its trip (1-based, monotonically increasing per trip). Maintained by the trip writer; not enforced as a DB constraint.';
