-- Phase 3: Drop columns that have been migrated to the signals JSONB column.
-- ONLY run this after all application code reads from signals (either via the
-- repo-layer JSONB facade or via (signals->>'field')::type in raw SQL queries).
--
-- The columns listed here intentionally EXCLUDE the "core" columns kept for
-- indexed query access:
--   charging_telemetry:         battery_level, charge_state, charger_voltage,
--                               charge_rate_mph, dc_charging_power, time_to_full_charge
--   climate_snapshots:          inside_temp, outside_temp, hvac_ac_enabled,
--                               hvac_auto_mode, hvac_fan_speed
--   security_events:            locked, sentry_mode, door_state, driver_seat_occupied
--   motor_snapshots:            vehicle_speed, gear, di_state
--   tire_pressure_snapshots:    front_left, front_right, rear_left, rear_right
--   media_snapshots:            playback_status, audio_volume
--   safety_snapshots:           pin_to_drive_enabled, miles_since_reset,
--                               self_driving_miles_since_reset
--   vehicle_config_snapshots:   car_type, version, vehicle_name
--   user_preference_snapshots:  setting_distance_unit, setting_temperature_unit

ALTER TABLE charging_telemetry
    DROP COLUMN IF EXISTS soc,
    DROP COLUMN IF EXISTS detailed_charge_state,
    DROP COLUMN IF EXISTS charge_limit_soc,
    DROP COLUMN IF EXISTS charge_amps,
    DROP COLUMN IF EXISTS charge_current_request,
    DROP COLUMN IF EXISTS charge_current_request_max,
    DROP COLUMN IF EXISTS charge_enable_request,
    DROP COLUMN IF EXISTS charger_phases,
    DROP COLUMN IF EXISTS dc_charging_energy_in,
    DROP COLUMN IF EXISTS ac_charging_power,
    DROP COLUMN IF EXISTS ac_charging_energy_in,
    DROP COLUMN IF EXISTS energy_remaining,
    DROP COLUMN IF EXISTS est_battery_range,
    DROP COLUMN IF EXISTS ideal_battery_range,
    DROP COLUMN IF EXISTS rated_range,
    DROP COLUMN IF EXISTS pack_voltage,
    DROP COLUMN IF EXISTS pack_current,
    DROP COLUMN IF EXISTS charge_port,
    DROP COLUMN IF EXISTS charge_port_door_open,
    DROP COLUMN IF EXISTS charge_port_latch,
    DROP COLUMN IF EXISTS charge_port_cold_weather_mode,
    DROP COLUMN IF EXISTS charging_cable_type,
    DROP COLUMN IF EXISTS fast_charger_present,
    DROP COLUMN IF EXISTS fast_charger_type,
    DROP COLUMN IF EXISTS estimated_hours_to_charge,
    DROP COLUMN IF EXISTS scheduled_charging_mode,
    DROP COLUMN IF EXISTS scheduled_charging_pending,
    DROP COLUMN IF EXISTS preconditioning_enabled,
    DROP COLUMN IF EXISTS brick_voltage_max,
    DROP COLUMN IF EXISTS brick_voltage_min,
    DROP COLUMN IF EXISTS num_brick_voltage_max,
    DROP COLUMN IF EXISTS num_brick_voltage_min,
    DROP COLUMN IF EXISTS module_temp_max,
    DROP COLUMN IF EXISTS module_temp_min,
    DROP COLUMN IF EXISTS num_module_temp_max,
    DROP COLUMN IF EXISTS num_module_temp_min,
    DROP COLUMN IF EXISTS battery_heater_on,
    DROP COLUMN IF EXISTS not_enough_power_to_heat,
    DROP COLUMN IF EXISTS bms_state,
    DROP COLUMN IF EXISTS bms_fullcharge_complete,
    DROP COLUMN IF EXISTS dcdc_enable,
    DROP COLUMN IF EXISTS isolation_resistance,
    DROP COLUMN IF EXISTS lifetime_energy_used,
    DROP COLUMN IF EXISTS supercharger_session_trip_planner,
    DROP COLUMN IF EXISTS powershare_status,
    DROP COLUMN IF EXISTS powershare_type,
    DROP COLUMN IF EXISTS powershare_stop_reason,
    DROP COLUMN IF EXISTS powershare_hours_left,
    DROP COLUMN IF EXISTS powershare_power_kw,
    DROP COLUMN IF EXISTS scheduled_charging_start_time,
    DROP COLUMN IF EXISTS scheduled_departure_time,
    DROP COLUMN IF EXISTS expected_energy_pct_at_arrival;

ALTER TABLE climate_snapshots
    DROP COLUMN IF EXISTS hvac_power,
    DROP COLUMN IF EXISTS hvac_left_temp_request,
    DROP COLUMN IF EXISTS hvac_right_temp_request,
    DROP COLUMN IF EXISTS cabin_overheat_mode,
    DROP COLUMN IF EXISTS defrost_mode,
    DROP COLUMN IF EXISTS battery_heater_on,
    DROP COLUMN IF EXISTS hvac_fan_status,
    DROP COLUMN IF EXISTS hvac_steering_wheel_heat_auto,
    DROP COLUMN IF EXISTS hvac_steering_wheel_heat_level,
    DROP COLUMN IF EXISTS climate_keeper_mode,
    DROP COLUMN IF EXISTS cabin_overheat_protection_temp_limit,
    DROP COLUMN IF EXISTS defrost_for_preconditioning,
    DROP COLUMN IF EXISTS seat_heater_left,
    DROP COLUMN IF EXISTS seat_heater_right,
    DROP COLUMN IF EXISTS seat_heater_rear_left,
    DROP COLUMN IF EXISTS seat_heater_rear_center,
    DROP COLUMN IF EXISTS seat_heater_rear_right,
    DROP COLUMN IF EXISTS seat_vent_enabled,
    DROP COLUMN IF EXISTS climate_seat_cooling_front_left,
    DROP COLUMN IF EXISTS climate_seat_cooling_front_right,
    DROP COLUMN IF EXISTS auto_seat_climate_left,
    DROP COLUMN IF EXISTS auto_seat_climate_right,
    DROP COLUMN IF EXISTS rear_defrost_enabled,
    DROP COLUMN IF EXISTS rear_display_hvac_enabled,
    DROP COLUMN IF EXISTS wiper_heat_enabled;

ALTER TABLE security_events
    DROP COLUMN IF EXISTS fd_window,
    DROP COLUMN IF EXISTS fp_window,
    DROP COLUMN IF EXISTS rd_window,
    DROP COLUMN IF EXISTS rp_window,
    DROP COLUMN IF EXISTS homelink_nearby,
    DROP COLUMN IF EXISTS guest_mode,
    DROP COLUMN IF EXISTS homelink_device_count,
    DROP COLUMN IF EXISTS guest_mode_mobile_access_state,
    DROP COLUMN IF EXISTS center_display,
    DROP COLUMN IF EXISTS speed_limit_mode,
    DROP COLUMN IF EXISTS valet_mode_enabled,
    DROP COLUMN IF EXISTS service_mode,
    DROP COLUMN IF EXISTS current_limit_mph,
    DROP COLUMN IF EXISTS paired_phone_key_count,
    DROP COLUMN IF EXISTS lights_hazards_active,
    DROP COLUMN IF EXISTS lights_high_beams,
    DROP COLUMN IF EXISTS lights_turn_signal,
    DROP COLUMN IF EXISTS tonneau_position,
    DROP COLUMN IF EXISTS tonneau_open_percent,
    DROP COLUMN IF EXISTS tonneau_tent_mode,
    DROP COLUMN IF EXISTS driver_seat_belt,
    DROP COLUMN IF EXISTS passenger_seat_belt;

ALTER TABLE motor_snapshots
    DROP COLUMN IF EXISTS di_torque,
    DROP COLUMN IF EXISTS di_axle_speed,
    DROP COLUMN IF EXISTS di_stator_temp,
    DROP COLUMN IF EXISTS pedal_position,
    DROP COLUMN IF EXISTS brake_pedal,
    DROP COLUMN IF EXISTS lateral_accel,
    DROP COLUMN IF EXISTS longitudinal_accel,
    DROP COLUMN IF EXISTS di_torque_actual_f,
    DROP COLUMN IF EXISTS di_torque_actual_r,
    DROP COLUMN IF EXISTS di_torque_actual_rel,
    DROP COLUMN IF EXISTS di_torque_actual_rer,
    DROP COLUMN IF EXISTS di_axle_speed_f,
    DROP COLUMN IF EXISTS di_axle_speed_rel,
    DROP COLUMN IF EXISTS di_axle_speed_rer,
    DROP COLUMN IF EXISTS di_state_f,
    DROP COLUMN IF EXISTS di_state_rel,
    DROP COLUMN IF EXISTS di_state_rer,
    DROP COLUMN IF EXISTS di_stator_temp_f,
    DROP COLUMN IF EXISTS di_stator_temp_rel,
    DROP COLUMN IF EXISTS di_stator_temp_rer,
    DROP COLUMN IF EXISTS di_heatsink_t_f,
    DROP COLUMN IF EXISTS di_heatsink_t_r,
    DROP COLUMN IF EXISTS di_heatsink_t_rel,
    DROP COLUMN IF EXISTS di_heatsink_t_rer,
    DROP COLUMN IF EXISTS di_inverter_t_f,
    DROP COLUMN IF EXISTS di_inverter_t_r,
    DROP COLUMN IF EXISTS di_inverter_t_rel,
    DROP COLUMN IF EXISTS di_inverter_t_rer,
    DROP COLUMN IF EXISTS di_motor_current_f,
    DROP COLUMN IF EXISTS di_motor_current_r,
    DROP COLUMN IF EXISTS di_motor_current_rel,
    DROP COLUMN IF EXISTS di_motor_current_rer,
    DROP COLUMN IF EXISTS di_v_bat_f,
    DROP COLUMN IF EXISTS di_v_bat_r,
    DROP COLUMN IF EXISTS di_v_bat_rel,
    DROP COLUMN IF EXISTS di_v_bat_rer,
    DROP COLUMN IF EXISTS di_slave_torque_cmd,
    DROP COLUMN IF EXISTS hvil,
    DROP COLUMN IF EXISTS brake_pedal_pos,
    DROP COLUMN IF EXISTS cruise_set_speed,
    DROP COLUMN IF EXISTS drive_rail,
    DROP COLUMN IF EXISTS lifetime_energy_gained_regen,
    DROP COLUMN IF EXISTS lifetime_energy_used_drive;

ALTER TABLE tire_pressure_snapshots
    DROP COLUMN IF EXISTS tpms_hard_warnings,
    DROP COLUMN IF EXISTS tpms_soft_warnings,
    DROP COLUMN IF EXISTS last_seen_time_fl,
    DROP COLUMN IF EXISTS last_seen_time_fr,
    DROP COLUMN IF EXISTS last_seen_time_rl,
    DROP COLUMN IF EXISTS last_seen_time_rr;

ALTER TABLE media_snapshots
    DROP COLUMN IF EXISTS now_playing_title,
    DROP COLUMN IF EXISTS now_playing_artist,
    DROP COLUMN IF EXISTS now_playing_album,
    DROP COLUMN IF EXISTS now_playing_station,
    DROP COLUMN IF EXISTS now_playing_duration,
    DROP COLUMN IF EXISTS now_playing_elapsed,
    DROP COLUMN IF EXISTS playback_source,
    DROP COLUMN IF EXISTS audio_volume_max,
    DROP COLUMN IF EXISTS audio_volume_increment;

ALTER TABLE safety_snapshots
    DROP COLUMN IF EXISTS automatic_blind_spot_camera,
    DROP COLUMN IF EXISTS automatic_emergency_braking_off,
    DROP COLUMN IF EXISTS blind_spot_collision_warning,
    DROP COLUMN IF EXISTS cruise_follow_distance,
    DROP COLUMN IF EXISTS emergency_lane_departure_avoidance,
    DROP COLUMN IF EXISTS forward_collision_warning,
    DROP COLUMN IF EXISTS lane_departure_avoidance,
    DROP COLUMN IF EXISTS speed_limit_warning;

ALTER TABLE vehicle_config_snapshots
    DROP COLUMN IF EXISTS trim,
    DROP COLUMN IF EXISTS exterior_color,
    DROP COLUMN IF EXISTS roof_color,
    DROP COLUMN IF EXISTS wheel_type,
    DROP COLUMN IF EXISTS rear_seat_heaters,
    DROP COLUMN IF EXISTS sunroof_installed,
    DROP COLUMN IF EXISTS efficiency_package,
    DROP COLUMN IF EXISTS europe_vehicle,
    DROP COLUMN IF EXISTS right_hand_drive,
    DROP COLUMN IF EXISTS remote_start_enabled,
    DROP COLUMN IF EXISTS charge_port,
    DROP COLUMN IF EXISTS offroad_lightbar_present,
    DROP COLUMN IF EXISTS software_update_version,
    DROP COLUMN IF EXISTS software_update_download_pct,
    DROP COLUMN IF EXISTS software_update_install_pct,
    DROP COLUMN IF EXISTS software_update_expected_duration,
    DROP COLUMN IF EXISTS software_update_scheduled_start;

ALTER TABLE user_preference_snapshots
    DROP COLUMN IF EXISTS setting_24hr_time,
    DROP COLUMN IF EXISTS setting_charge_unit,
    DROP COLUMN IF EXISTS setting_tire_pressure_unit;
