-- Phase-45 — Operator Confidence batch.
--
-- This migration is additive only. Every change is non-destructive so
-- the rollback path is a pure DROP/ALTER-DROP-COLUMN and never loses
-- pre-existing data.
--
-- Touch points:
--   1. audit_logs extension: 7 nullable columns + a partial index for
--      hash-chain validation lookups. No rename of existing columns;
--      callers that still use {actor, action, entity_type, entity_id,
--      detail, ip, user_agent} keep working unchanged.
--   2. schema_fingerprint: stores the sha256 of the canonical migrated
--      schema, regenerated in CI from a fresh testcontainers postgres.
--      Runtime compares the live DB fingerprint to the most recent row.
--   3. secret_rotation_log: append-only ledger of (secret_kind,
--      fingerprint_hmac, observed_at). NEVER stores the secret itself
--      or a raw hash — only an HMAC keyed by APP_SECRET_PEPPER so an
--      attacker who leaks this table cannot mount an offline guess.
--   4. slow_query_snapshot: 5-minute snapshot of pg_stat_statements
--      with normalized fingerprints. Hypertable so retention can be
--      managed.
--   5. gdpr_export_artifact: external-storage-only manifest for GDPR
--      data-subject exports. Stores path + sha256 + size; NEVER bytes.
--   6. export_jobs.storage_path + .storage_kind: new external-storage
--      path for exports too large to fit in the legacy file_data
--      BYTEA column. file_data remains for backward compatibility.

-- =====================================================================
-- 1. audit_logs extension
-- =====================================================================

ALTER TABLE audit_logs
    ADD COLUMN IF NOT EXISTS category      text,
    ADD COLUMN IF NOT EXISTS before_value  jsonb,
    ADD COLUMN IF NOT EXISTS after_value   jsonb,
    ADD COLUMN IF NOT EXISTS trace_id      text,
    ADD COLUMN IF NOT EXISTS prev_row_hash text,
    ADD COLUMN IF NOT EXISTS row_hash      text,
    ADD COLUMN IF NOT EXISTS success       boolean;

COMMENT ON COLUMN audit_logs.category IS
    'Phase-45: high-level grouping (auth, admin, data, config, security). NULL on legacy rows.';
COMMENT ON COLUMN audit_logs.before_value IS
    'Phase-45: REDACTED snapshot of the entity before the mutation. Use redaction allowlist; never raw struct.';
COMMENT ON COLUMN audit_logs.after_value IS
    'Phase-45: REDACTED snapshot of the entity after the mutation.';
COMMENT ON COLUMN audit_logs.trace_id IS
    'Phase-45: OTel trace id (W3C hex) that produced this audit row. Joins audit to Jaeger.';
COMMENT ON COLUMN audit_logs.prev_row_hash IS
    'Phase-45: tamper-evidence hash chain. SHA256 of the immediately-previous row''s row_hash. NULL on first row.';
COMMENT ON COLUMN audit_logs.row_hash IS
    'Phase-45: tamper-evidence hash chain. SHA256(prev_row_hash || canonical_serialization_of_this_row).';
COMMENT ON COLUMN audit_logs.success IS
    'Phase-45: did the audited mutation succeed? Distinct from "audit write succeeded".';

CREATE INDEX IF NOT EXISTS idx_audit_logs_category_ts
    ON audit_logs (category, ts DESC)
    WHERE category IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_audit_logs_trace_id
    ON audit_logs (trace_id)
    WHERE trace_id IS NOT NULL;

-- =====================================================================
-- 2. schema_fingerprint
-- =====================================================================

CREATE TABLE IF NOT EXISTS schema_fingerprint (
    id           bigint GENERATED ALWAYS AS IDENTITY,
    sha256_hash  text         NOT NULL,
    column_count integer      NOT NULL,
    index_count  integer      NOT NULL,
    table_count  integer      NOT NULL,
    git_sha      text,
    generated_at timestamptz  NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);
COMMENT ON TABLE schema_fingerprint IS
    'Phase-45: canonical schema fingerprint regenerated by CI from a clean migrated DB. Runtime compares the current live DB fingerprint to the most recent row; mismatch = drift.';
CREATE INDEX IF NOT EXISTS idx_schema_fingerprint_generated_at
    ON schema_fingerprint (generated_at DESC);

-- =====================================================================
-- 3. secret_rotation_log
-- =====================================================================

CREATE TABLE IF NOT EXISTS secret_rotation_log (
    id                bigint GENERATED ALWAYS AS IDENTITY,
    secret_kind       text         NOT NULL
                                   CHECK (secret_kind IN (
                                       'tesla_refresh_token',
                                       'mqtt_mtls_cert',
                                       'database_password',
                                       'session_jwk',
                                       'app_signing_key',
                                       'authentik_secret'
                                   )),
    fingerprint_hmac  text         NOT NULL,
    target_id         text,
    observed_at       timestamptz  NOT NULL DEFAULT now(),
    expires_at        timestamptz,
    PRIMARY KEY (id)
);
COMMENT ON TABLE secret_rotation_log IS
    'Phase-45: append-only ledger of secret rotations. fingerprint_hmac is HMAC-SHA256(secret, APP_SECRET_PEPPER) so leakage of this table does not enable offline guessing.';
COMMENT ON COLUMN secret_rotation_log.target_id IS
    'Optional discriminator: vehicle id for tesla_refresh_token, cert subject for mqtt_mtls_cert.';
COMMENT ON COLUMN secret_rotation_log.expires_at IS
    'When known (e.g. cert NotAfter); NULL for secrets with no defined expiry.';
CREATE INDEX IF NOT EXISTS idx_secret_rotation_kind_observed
    ON secret_rotation_log (secret_kind, observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_secret_rotation_target
    ON secret_rotation_log (secret_kind, target_id, observed_at DESC)
    WHERE target_id IS NOT NULL;

-- =====================================================================
-- 4. slow_query_snapshot (hypertable)
-- =====================================================================

CREATE TABLE IF NOT EXISTS slow_query_snapshot (
    ts                timestamptz NOT NULL DEFAULT now(),
    queryid           bigint      NOT NULL,
    query_fingerprint text        NOT NULL,
    calls             bigint      NOT NULL,
    total_time_ms     double precision NOT NULL,
    mean_time_ms      double precision NOT NULL,
    max_time_ms       double precision NOT NULL,
    rows_returned     bigint      NOT NULL,
    shared_blks_hit   bigint,
    shared_blks_read  bigint,
    PRIMARY KEY (ts, queryid)
);
SELECT create_hypertable('slow_query_snapshot', 'ts',
    chunk_time_interval => INTERVAL '7 days',
    if_not_exists => TRUE);
COMMENT ON TABLE slow_query_snapshot IS
    'Phase-45: 5-minute snapshot of pg_stat_statements with normalized fingerprints. Historical view of slow queries; live view comes straight from pg_stat_statements.';
CREATE INDEX IF NOT EXISTS idx_slow_query_snapshot_queryid_ts
    ON slow_query_snapshot (queryid, ts DESC);

-- =====================================================================
-- 5. gdpr_export_artifact
-- =====================================================================

CREATE TABLE IF NOT EXISTS gdpr_export_artifact (
    id              text        PRIMARY KEY,
    export_job_id   text        NOT NULL REFERENCES export_jobs(id) ON DELETE CASCADE,
    vehicle_id      bigint      NOT NULL,
    storage_kind    text        NOT NULL
                                CHECK (storage_kind IN ('local_fs', 's3')),
    storage_path    text        NOT NULL,
    sha256          text        NOT NULL,
    byte_count      bigint      NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    expires_at      timestamptz NOT NULL,
    downloaded_at   timestamptz,
    download_count  integer     NOT NULL DEFAULT 0
);
COMMENT ON TABLE gdpr_export_artifact IS
    'Phase-45: external-storage manifest for GDPR data-subject exports. NEVER stores bytes — only path/sha/size. file removal at expires_at is the worker job.';
CREATE INDEX IF NOT EXISTS idx_gdpr_artifact_vehicle_created
    ON gdpr_export_artifact (vehicle_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gdpr_artifact_expires
    ON gdpr_export_artifact (expires_at);

-- =====================================================================
-- 6. export_jobs external-storage columns
-- =====================================================================

ALTER TABLE export_jobs
    ADD COLUMN IF NOT EXISTS storage_kind text,
    ADD COLUMN IF NOT EXISTS storage_path text,
    ADD COLUMN IF NOT EXISTS sha256       text;

COMMENT ON COLUMN export_jobs.storage_kind IS
    'Phase-45: ''local_fs''|''s3''|NULL. NULL = legacy file_data path.';
COMMENT ON COLUMN export_jobs.storage_path IS
    'Phase-45: filesystem path or S3 key. NULL = legacy file_data path.';
COMMENT ON COLUMN export_jobs.sha256 IS
    'Phase-45: integrity hash for external-storage exports.';
