// Code generated by cmd/protogen-tesla; DO NOT EDIT.
//
// Decoder for the Tesla Fleet Telemetry Datum.Value oneof. Every variant the
// vendored proto declares is covered by an explicit case in DecodeValue; the
// "default" arm is reachable only if the upstream ftproto package adds a new
// variant we have not yet classified, in which case we return a descriptive
// error so the caller can surface a clear "needs codegen update" signal.
//
// The decoder honors Value.invalid=true BEFORE inspecting any other variant
// (per ADR-004): the producer marks a sample untrustworthy by setting the
// invalid bit irrespective of which oneof slot is populated, and the rest of
// the pipeline drops the field on ErrInvalid. Callers MUST NOT substitute a
// default or zero on ErrInvalid — the entire telemetry sample is suspect.
//
// The decoder also rejects the unset-oneof case with ErrUnsetValue. A Value
// arriving with no populated variant is a producer bug, not a "no change"
// signal; treating it silently as the zero value would corrupt downstream
// state. ErrUnsetValue forces the caller to make an explicit decision.
//
// Compound message variants (LocationValue, Doors, TireLocation, Time)
// return the typed structs from compounds.go (Location, Doors, TireLocation,
// Time). Flattening of those typed structs to atomic per-child signals
// happens in the codec package (Prompt 0020), not here.
package protomodel

import (
	"errors"
	"fmt"

	ftproto "github.com/teslamotors/fleet-telemetry/protos"
)

// ErrInvalid is returned by DecodeValue / DecodeDatum when the source Value
// has its invalid flag set to true. The Tesla Fleet Telemetry producer uses
// this flag to mark a sample as not trustworthy (e.g. sensor unavailable,
// transient fault, value out of expected range). The pipeline drops fields
// returning this error; callers MUST NOT substitute a default or zero
// value, and MUST NOT persist the sample under any other interpretation.
var ErrInvalid = errors.New("protomodel: value marked invalid")

// ErrUnsetValue is returned by DecodeValue when the Value has no populated
// oneof variant (or is nil). This is a producer bug — every populated
// Datum.value SHOULD have exactly one of the oneof slots set. The decoder
// surfaces this as a hard error rather than silently producing the zero
// value, so the caller can log it, drop the sample, and increment a metric
// rather than corrupting downstream state with an assumed default.
var ErrUnsetValue = errors.New("protomodel: oneof value is unset")

// DecodeValue extracts the populated oneof variant from v and returns it as
// a strict typed Go value.
//
// Returns:
//   - (nil, ErrInvalid)     when v.invalid==true (caller drops the sample);
//   - (nil, ErrUnsetValue)  when v is nil or no oneof variant is populated;
//   - (typed value, nil)    for any populated scalar/enum/compound variant.
//
// The returned `any` is one of:
//   - string  (string_value)
//   - int32   (int_value)
//   - int64   (long_value)
//   - float32 (float_value)
//   - float64 (double_value)
//   - bool    (boolean_value)
//   - Location, Doors, TireLocation, Time (the four compound message variants)
//   - a typed ftproto enum (e.g. ftproto.ChargingState, ftproto.ShiftState,
//     ftproto.SentryModeState, ...) for every named-enum variant.
//
// The caller MUST type-switch on the returned `any` to handle each kind; the
// concrete Go type is documented per variant above and locked in by the
// reflect-based table tests in datum_decoder_test.go.
func DecodeValue(v *ftproto.Value) (any, error) {
	if v == nil {
		return nil, ErrUnsetValue
	}
	// Honor the invalid flag BEFORE the oneof switch. The Tesla producer
	// emits Value{Value: &Value_Invalid{Invalid: true}} as the populated
	// variant; v.GetInvalid() returns true only in that case (not for the
	// rare Value{Value: &Value_Invalid{Invalid: false}} which would mean
	// "explicitly NOT invalid" and is treated as the unset-oneof case
	// further down).
	if v.GetInvalid() {
		return nil, ErrInvalid
	}
	switch x := v.GetValue().(type) {
	case nil:
		return nil, ErrUnsetValue
	case *ftproto.Value_StringValue:
		return x.StringValue, nil
	case *ftproto.Value_IntValue:
		return x.IntValue, nil
	case *ftproto.Value_LongValue:
		return x.LongValue, nil
	case *ftproto.Value_FloatValue:
		return x.FloatValue, nil
	case *ftproto.Value_DoubleValue:
		return x.DoubleValue, nil
	case *ftproto.Value_BooleanValue:
		return x.BooleanValue, nil
	case *ftproto.Value_Invalid:
		// v.GetInvalid() above already short-circuited the populated case;
		// reaching here means Invalid==false, which is treated as unset.
		return nil, ErrUnsetValue
	case *ftproto.Value_LocationValue:
		lv := x.LocationValue
		if lv == nil {
			return Location{}, nil
		}
		return Location{Latitude: lv.GetLatitude(), Longitude: lv.GetLongitude()}, nil
	case *ftproto.Value_DoorValue:
		d := x.DoorValue
		if d == nil {
			return Doors{}, nil
		}
		return Doors{
			DriverFront:    d.GetDriverFront(),
			DriverRear:     d.GetDriverRear(),
			PassengerFront: d.GetPassengerFront(),
			PassengerRear:  d.GetPassengerRear(),
			TrunkFront:     d.GetTrunkFront(),
			TrunkRear:      d.GetTrunkRear(),
		}, nil
	case *ftproto.Value_TimeValue:
		tv := x.TimeValue
		if tv == nil {
			return Time{}, nil
		}
		return Time{Hour: tv.GetHour(), Minute: tv.GetMinute(), Second: tv.GetSecond()}, nil
	case *ftproto.Value_TireLocationValue:
		tl := x.TireLocationValue
		if tl == nil {
			return TireLocation{}, nil
		}
		return TireLocation{
			FrontLeft:            tl.GetFrontLeft(),
			FrontRight:           tl.GetFrontRight(),
			RearLeft:             tl.GetRearLeft(),
			RearRight:            tl.GetRearRight(),
			SemiMiddleAxleLeft2:  tl.GetSemiMiddleAxleLeft_2(),
			SemiMiddleAxleRight2: tl.GetSemiMiddleAxleRight_2(),
			SemiRearAxleLeft:     tl.GetSemiRearAxleLeft(),
			SemiRearAxleRight:    tl.GetSemiRearAxleRight(),
			SemiRearAxleLeft2:    tl.GetSemiRearAxleLeft_2(),
			SemiRearAxleRight2:   tl.GetSemiRearAxleRight_2(),
		}, nil
	case *ftproto.Value_ChargingValue:
		return x.ChargingValue, nil
	case *ftproto.Value_ShiftStateValue:
		return x.ShiftStateValue, nil
	case *ftproto.Value_LaneAssistLevelValue:
		return x.LaneAssistLevelValue, nil
	case *ftproto.Value_ScheduledChargingModeValue:
		return x.ScheduledChargingModeValue, nil
	case *ftproto.Value_SentryModeStateValue:
		return x.SentryModeStateValue, nil
	case *ftproto.Value_SpeedAssistLevelValue:
		return x.SpeedAssistLevelValue, nil
	case *ftproto.Value_BmsStateValue:
		return x.BmsStateValue, nil
	case *ftproto.Value_BuckleStatusValue:
		return x.BuckleStatusValue, nil
	case *ftproto.Value_CarTypeValue:
		return x.CarTypeValue, nil
	case *ftproto.Value_ChargePortValue:
		return x.ChargePortValue, nil
	case *ftproto.Value_ChargePortLatchValue:
		return x.ChargePortLatchValue, nil
	case *ftproto.Value_DriveInverterStateValue:
		return x.DriveInverterStateValue, nil
	case *ftproto.Value_HvilStatusValue:
		return x.HvilStatusValue, nil
	case *ftproto.Value_WindowStateValue:
		return x.WindowStateValue, nil
	case *ftproto.Value_SeatFoldPositionValue:
		return x.SeatFoldPositionValue, nil
	case *ftproto.Value_TractorAirStatusValue:
		return x.TractorAirStatusValue, nil
	case *ftproto.Value_FollowDistanceValue:
		return x.FollowDistanceValue, nil
	case *ftproto.Value_ForwardCollisionSensitivityValue:
		return x.ForwardCollisionSensitivityValue, nil
	case *ftproto.Value_GuestModeMobileAccessValue:
		return x.GuestModeMobileAccessValue, nil
	case *ftproto.Value_TrailerAirStatusValue:
		return x.TrailerAirStatusValue, nil
	case *ftproto.Value_DetailedChargeStateValue:
		return x.DetailedChargeStateValue, nil
	case *ftproto.Value_HvacAutoModeValue:
		return x.HvacAutoModeValue, nil
	case *ftproto.Value_CabinOverheatProtectionModeValue:
		return x.CabinOverheatProtectionModeValue, nil
	case *ftproto.Value_CabinOverheatProtectionTemperatureLimitValue:
		return x.CabinOverheatProtectionTemperatureLimitValue, nil
	case *ftproto.Value_DefrostModeValue:
		return x.DefrostModeValue, nil
	case *ftproto.Value_ClimateKeeperModeValue:
		return x.ClimateKeeperModeValue, nil
	case *ftproto.Value_HvacPowerValue:
		return x.HvacPowerValue, nil
	case *ftproto.Value_FastChargerValue:
		return x.FastChargerValue, nil
	case *ftproto.Value_CableTypeValue:
		return x.CableTypeValue, nil
	case *ftproto.Value_TonneauTentModeValue:
		return x.TonneauTentModeValue, nil
	case *ftproto.Value_TonneauPositionValue:
		return x.TonneauPositionValue, nil
	case *ftproto.Value_PowershareTypeValue:
		return x.PowershareTypeValue, nil
	case *ftproto.Value_PowershareStateValue:
		return x.PowershareStateValue, nil
	case *ftproto.Value_PowershareStopReasonValue:
		return x.PowershareStopReasonValue, nil
	case *ftproto.Value_DisplayStateValue:
		return x.DisplayStateValue, nil
	case *ftproto.Value_DistanceUnitValue:
		return x.DistanceUnitValue, nil
	case *ftproto.Value_TemperatureUnitValue:
		return x.TemperatureUnitValue, nil
	case *ftproto.Value_PressureUnitValue:
		return x.PressureUnitValue, nil
	case *ftproto.Value_ChargeUnitPreferenceValue:
		return x.ChargeUnitPreferenceValue, nil
	case *ftproto.Value_TurnSignalStateValue:
		return x.TurnSignalStateValue, nil
	case *ftproto.Value_MediaStatusValue:
		return x.MediaStatusValue, nil
	case *ftproto.Value_SunroofInstalledStateValue:
		return x.SunroofInstalledStateValue, nil
	default:
		// A type the upstream ftproto package added that this codegen has
		// not yet classified. Returning a descriptive error keeps the
		// pipeline running (the field is dropped by the caller) while
		// surfacing a clear signal that codegen needs an update.
		return nil, fmt.Errorf("protomodel: unhandled Value oneof variant %T", x)
	}
}

// DecodeDatum extracts the field name and decoded Go value from d.
//
// Returns:
//   - ("", nil, ErrUnsetValue) when d is nil or carries no Value;
//   - (field name, nil, ErrInvalid) when d.value.invalid==true;
//   - (field name, typed value, nil) on success.
//
// `field` is the symbolic ftproto.Field name (e.g. "VehicleSpeed",
// "Location"), suitable for routing.yaml lookups, signal_log columns, and
// SSE topic keys. `value` is one of the documented Go types in DecodeValue.
func DecodeDatum(d *ftproto.Datum) (field string, value any, err error) {
	if d == nil {
		return "", nil, ErrUnsetValue
	}
	field = d.GetKey().String()
	value, err = DecodeValue(d.GetValue())
	return field, value, err
}
