// Package protomodel is the canonical Go binding for the vendored Tesla
// Fleet Telemetry vehicle_data.proto. It is the one place in the codebase
// that knows the proto's Field enum, the Datum.Value oneof shape, and the
// per-Field routing classification (Category, ValueKind, UnitKind).
//
// Layout:
//
//	types.go                 hand-written: ValueKind, UnitKind, SignalMeta
//	signal_metadata_gen.go   GENERATED: Field constants + Signals + lookup maps
//	enum_parsers_gen.go      GENERATED (later prompt): every other named enum
//	datum_decoder_gen.go     GENERATED (later prompt): Value, Datum, DecodeValue
//
// All files in this package suffixed _gen.go are GENERATED by the codegen
// binary at cmd/protogen-tesla and MUST NOT be edited by hand. To
// regenerate, run:
//
//	go run ./cmd/protogen-tesla --proto api/proto/tesla/vehicle_data.proto --out internal/tesla/protomodel
//
// CI runs the same command and fails the build on any diff against the
// committed *_gen.go files; that drift gate is what guarantees the
// generated artefacts always match the vendored proto bit-for-bit.
//
//go:generate go run ../../../cmd/protogen-tesla --proto ../../../api/proto/tesla/vehicle_data.proto --out .
package protomodel
