// Phase-46 / p46-slo — Live SLO board.
//
// One read-only endpoint:
//
//	GET /api/v1/admin/observability/slo
//	  Returns one row per SLO in slo/catalog.yaml with the current
//	  live SLI ratio (good/valid over the SLO window), the error
//	  budget remaining (0..1), and per-tier burn-rate evaluation
//	  for both the FastBurn (1h+5m, 14.4×) and SlowBurn (6h+30m, 6×)
//	  multi-window-multi-burn-rate tiers — same windows as the
//	  alerts generated by cmd/slogen.
//
// When PROM_BASE_URL is unset the endpoint still returns the catalog
// metadata so the SPA can render SLO names + targets with a
// "Prometheus not configured" banner instead of a blank panel.
//
// ADR-009 exception: this file is intentionally placed in
// internal/api/ rather than internal/handler/v1/ because it is the
// minimal surface a future page-builder iteration needs to render a
// /admin/observability/slo page and the rest of the live SLO
// machinery already lives in internal/slo/.
package api

import (
	"net/http"

	"github.com/ev-dev-labs/teslasync/internal/slo"
)

// SLOHandler exposes the live SLO board.
type SLOHandler struct {
	catalog *slo.Catalog
	tracker *slo.Tracker
}

// NewSLOHandler wires the handler. catalog may be nil when slo/catalog.yaml
// failed to load at boot — the handler then returns a 503 so the SPA can
// surface the misconfiguration honestly.
func NewSLOHandler(catalog *slo.Catalog, tracker *slo.Tracker) *SLOHandler {
	return &SLOHandler{catalog: catalog, tracker: tracker}
}

// Snapshot is the GET handler.
func (h *SLOHandler) Snapshot(w http.ResponseWriter, r *http.Request) {
	if h == nil || h.catalog == nil || h.tracker == nil {
		writeError(w, http.StatusServiceUnavailable, "SUBSYSTEM_NOT_CONFIGURED")
		return
	}
	snap, err := h.tracker.Snapshot(r.Context(), h.catalog)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, snap)
}
