import type {
  ClaimDraft,
  CommunicationsCatalogStatus,
  ServiceIntelligenceResponse,
  WarrantyOutlook,
} from '@/api/hooks/useServiceIntelligence';
import { OFFICIAL_NHTSA_COMMUNICATION_ARTIFACTS } from '@/api/hooks/useServiceIntelligence';

export const serviceReport: ServiceIntelligenceResponse = {
  vehicle_id: 7,
  generated_at: '2026-08-05T08:00:00Z',
  vehicle_context: {
    make: 'Tesla',
    model: 'Model 3',
    model_year: 2021,
    build_date: null,
    build_match_basis: 'Decoded context is not eligibility proof.',
    plant_city: null,
    plant_state: null,
    plant_country: null,
    firmware_version: null,
  },
  summary: {
    recall_candidates: 1,
    potentially_applicable_recalls: 1,
    manufacturer_communications: 1,
    symptom_matches: 2,
  },
  recall_findings: [{
    id: 'campaign-7',
    kind: 'recall',
    title: 'Returned campaign candidate',
    component: 'Battery',
    summary: 'Published campaign summary.',
    consequence: 'Published potential consequence.',
    remedy: 'Published remedy requires confirmation.',
    report_received_at: '2026-07-01',
    applicability: 'potentially_applicable',
    confidence: 0.72,
    confidence_label: 'medium',
    completion_status: 'unknown',
    hypothesis: 'Build overlap is a hypothesis, not confirmed eligibility.',
    match_factors: [{
      dimension: 'model_year',
      status: 'matched',
      weight: 0.4,
      detail: 'Decoded model year matched the publication.',
    }],
    symptom_matches: [],
    park_it: false,
    park_outside: true,
    over_the_air_update: true,
    source_document_url: 'https://example.org/campaign-7',
  }],
  communications: [{
    id: 'communication-7',
    nhtsa_id: '10000007',
    communication_number: 'SB-26-07',
    communication_type: 'Technical service bulletin',
    manufacturer: 'Tesla',
    model: 'Model 3',
    model_year: 2021,
    published_at: '2026-07-02',
    component: 'Battery',
    summary: 'Returned bulletin summary.',
    applicability: 'needs_review',
    confidence: 0.41,
    confidence_label: 'low',
    hypothesis: 'Bulletin overlap does not establish a fault.',
    match_factors: [],
    symptom_matches: [{
      finding_id: 'communication-7',
      signal: 'battery_observation',
      component: 'Battery',
      severity: 'info',
      observed_at: '2026-08-01T12:00:00Z',
      score: 0.3,
      evidence: 'A descriptive signal deviation.',
    }],
    source_document_url: 'https://example.org/bulletin-7',
  }],
  ranked_symptoms: [
    {
      finding_id: 'campaign-7',
      signal: 'first_server_rank',
      component: 'Battery',
      severity: 'info',
      observed_at: '2026-08-01T12:00:00Z',
      score: 0.2,
      evidence: 'First supplied symptom explanation.',
    },
    {
      finding_id: 'campaign-7',
      signal: 'second_server_rank',
      component: 'Battery',
      severity: 'warning',
      observed_at: '2026-08-02T12:00:00Z',
      score: 0.9,
      evidence: 'Second supplied symptom explanation.',
    },
  ],
  evidence: {
    schema_version: '1',
    items: [
      {
        id: 'maintenance',
        kind: 'maintenance',
        title: 'Returned maintenance evidence',
        summary: 'Recorded service history, not proof of recall completion.',
        source_name: 'Maintenance history',
        source_document_url: 'https://example.org/maintenance-7',
        observed_at: '2026-07-03',
        confidence: null,
        finding_id: null,
      },
      {
        id: 'signal',
        kind: 'signal_history',
        title: 'Returned signal evidence',
        summary: 'Observed association is not diagnosis.',
        source_name: 'Historical signals',
        source_document_url: null,
        observed_at: null,
        confidence: null,
        finding_id: 'campaign-7',
      },
    ],
    limitations: ['Campaign completion must be officially confirmed.'],
    disclaimer: 'Confirm these hypotheses with a qualified technician.',
  },
  sources: [
    {
      id: 'nhtsa_manufacturer_communications',
      name: 'Official communications index',
      status: 'stale',
      record_count: 1,
      fetched_at: '2026-07-02T10:00:00Z',
      checked_at: '2026-08-05T08:00:00Z',
      expires_at: null,
      from_cache: true,
      source_url: 'https://example.org/communications-index',
      detail: 'Retained official import remains available.',
    },
    {
      id: 'maintenance_history',
      name: 'Maintenance evidence source',
      status: 'unavailable',
      record_count: 0,
      fetched_at: null,
      checked_at: '2026-08-05T08:00:00Z',
      expires_at: null,
      from_cache: false,
      source_url: 'https://example.org/maintenance-source',
      detail: 'Maintenance retrieval is unavailable; absence is not completion evidence.',
    },
  ],
};

export const warrantyReport: WarrantyOutlook = {
  vehicle_id: 7,
  model: 'Model 3',
  model_year: 2021,
  coverages: [{
    name: 'Retained battery coverage',
    expires_at: '2029-01-01',
    days_remaining: 900,
    km_limit: null,
    km_remaining: null,
    status: 'active',
    basis: 'time',
  }],
  assumption: 'Warranty dates are model-year estimates, not confirmation.',
};

export const claimReport: ClaimDraft = {
  subject: 'Complete retained service request',
  issue: 'Inspect the recorded charging concern.',
  vehicle: 'Model 3 (2021)',
  coverages: [{ name: 'Retained battery coverage', status: 'active', days_remaining: 900 }],
  communications: ['SB-26-07: official bulletin overlap only.'],
  symptoms: ['first_server_rank: observed association only.'],
  evidence: ['Recorded maintenance: no completion proof.'],
  ask: 'Please diagnose the concern and confirm coverage.',
  body: [
    'Subject: Complete retained service request',
    'Inspect the recorded charging concern.',
    'Model 3 (2021)',
    'Retained battery coverage: 900 days',
    'SB-26-07: official bulletin overlap only.',
    'first_server_rank: observed association only.',
    'Recorded maintenance: no completion proof.',
    'Please diagnose the concern and confirm coverage.',
    'Auto-drafted from recorded evidence; not a diagnosis.',
  ].join('\n'),
  disclaimer: 'Auto-drafted from recorded evidence; not a diagnosis.',
};

export const catalogReport: CommunicationsCatalogStatus = {
  record_count: 321,
  latest_attempt: null,
  latest_successful: {
    id: 5,
    artifact_url: OFFICIAL_NHTSA_COMMUNICATION_ARTIFACTS[4].url,
    source_etag: null,
    source_last_modified: null,
    artifact_sha256: 'a'.repeat(64),
    status: 'succeeded',
    total_rows: 1000,
    imported_rows: 188,
    rejected_rows: 2,
    not_modified: true,
    error_detail: null,
    started_at: '2026-08-05T06:00:00Z',
    completed_at: '2026-08-05T07:00:00Z',
  },
};
