// React Native parity port of web/src/lib/recentPages.ts.
//
// The web module is a non-visual, framework-agnostic utility: a client-side
// LRU of recently visited routes plus pure classify/record/read/clear helpers.
// It contains no JSX, no Recharts/Leaflet, and no web UI component. Two pieces
// are browser-coupled and are ported behind the established native-parity
// `globalThis`-probe precedent (notificationSound / errorClassification) so the
// full public surface, every state name, the STORAGE_KEY, the synthetic
// LOCAL_EVENT name, and the entry/kind contracts are preserved verbatim:
//
//   * `localStorage` (load / save / clearRecentPages / __resetRecentPagesForTests)
//     is resolved via `getWebStorage()`, which prefers `globalThis.localStorage`
//     when present (the react-native-web target, keeping the exact STORAGE_KEY +
//     JSON payload) and otherwise reports "no store". A pure native runtime then
//     behaves exactly like the web source's non-browser path: `load()` returns
//     `[]`, writes/clears are skipped. Durable cross-restart history persistence
//     on a pure native runtime is intentionally unavailable (see
//     `nativeRecentPagesCapabilities`).
//   * The same-tab `window.dispatchEvent(new Event(LOCAL_EVENT))` notify bus and
//     the cross-tab `window.addEventListener('storage', …)` listener in
//     `subscribeRecentPages` are resolved via `getEventTarget()` / `getEventCtor()`.
//     When a global event target + Event constructor exist (react-native-web)
//     the LOCAL_EVENT dispatch/listen and the 'storage' listener are attached
//     verbatim; on a pure native runtime same-process fan-out folds into the
//     module `localListeners` set instead, and cross-surface 'storage' fan-out is
//     unavailable (LOCAL_EVENT is module-internal, never exported, so no consumer
//     can observe the substitution).
//
// The web source imports `ROUTE_REGISTRY` from `./routeRegistry`. That sibling
// module has not been ported into the native web-parity tree yet (the conversion
// loop reaches it separately), so — exactly like errorClassification.ts inlines
// its `./resilience` guards — the path+label pairs `resolvePageLabel` consumes
// are inlined below verbatim as `ROUTE_REGISTRY`. Only `path` and `label` are
// read by this module; the full `RouteEntry` shape (name/i18nKey/hidden) lives in
// the not-yet-ported routeRegistry module. No DOM elements, Recharts, Leaflet,
// react-router-dom, or web UI components are imported.

/**
 * Recently viewed pages.
 *
 * Client-side LRU of the user's most recently visited routes. Capped at
 * {@link RECENT_PAGES_MAX} entries. Surfaces in three places:
 *
 *   - Command palette "Recent" section when the input is empty.
 *   - "Recently viewed" widget on the dashboard.
 *   - Settings → Privacy → "Clear recent pages" button.
 *
 * Storage is intentionally client-side only. Recent-page history is a
 * privacy-sensitive surface (it leaks browsing patterns across devices)
 * so we keep it in the user's own `localStorage` and never sync to the
 * backend. The privacy section's clear button is the only kill switch
 * we need.
 *
 * The store is framework-agnostic — pure read/write/transform helpers
 * so it can be unit-tested without a DOM round-trip. Wire-up to React
 * lives in `App.tsx` (route effect) and the consumer surfaces.
 *
 * Native parity: the persistence and notify layers degrade to native-safe
 * equivalents on a pure native runtime — see the file header and
 * {@link nativeRecentPagesCapabilities}.
 */

/**
 * Path → label pair consumed by {@link resolvePageLabel}. The full route
 * registry (with `name`/`i18nKey`/`hidden`) lives in the not-yet-ported
 * `./routeRegistry` module; only `path` + `label` are read here, so the
 * data is inlined to keep this port self-contained and typecheck-clean.
 */
interface RouteLabelEntry {
  /** URL pathname starting with '/'. May contain :params. */
  path: string;
  /** Stable English label (also used as i18n fallback). */
  label: string;
}

/**
 * Inlined verbatim from `web/src/lib/routeRegistry.ts` (AUTOGENERATED there).
 * Only the `path` + `label` columns are reproduced — the exact data
 * {@link resolvePageLabel} matches against — so label resolution behaves
 * byte-for-byte like the web source.
 */
const ROUTE_REGISTRY: readonly RouteLabelEntry[] = [
  {path: '/', label: 'Dashboard'},
  {path: '/admin/feedback', label: 'Feedback Queue'},
  {path: '/admin/telemetry/coverage', label: 'Fleet Telemetry Coverage'},
  {path: '/alert-rules', label: 'Legacy Alert Rules Redirect'},
  {path: '/alert-studio', label: 'Legacy Alert Studio Redirect'},
  {path: '/alerts', label: 'Legacy Alerts Redirect'},
  {path: '/analytics', label: 'Analytics'},
  {path: '/anomaly-detection', label: 'Anomaly Dashboard'},
  {path: '/api-keys', label: 'API Keys'},
  {path: '/api-logs', label: 'Api Logs'},
  {path: '/api-playground', label: 'Api Playground'},
  {path: '/automations', label: 'Automations'},
  {path: '/automations/:id/edit', label: 'Automation Builder'},
  {path: '/automations/list', label: 'Automation List'},
  {path: '/automations/new', label: 'Automation Builder'},
  {path: '/backup', label: 'Backup Restore'},
  {path: '/battery', label: 'Battery Health'},
  {path: '/battery-cells', label: 'Battery Cells'},
  {path: '/battery-degradation', label: 'Battery Degradation'},
  {path: '/charging', label: 'Charging'},
  {path: '/charging-curve', label: 'Charging Curve'},
  {path: '/charging-heatmap', label: 'Charging Heatmap'},
  {path: '/charging/:id', label: 'Charge Detail'},
  {path: '/chatbot', label: 'Chatbot'},
  {path: '/climate-control', label: 'Climate Control'},
  {path: '/command-history', label: 'Command History'},
  {path: '/commands', label: 'Commands'},
  {path: '/cost-analysis', label: 'Cost Analysis'},
  {path: '/data-export', label: 'Data Export'},
  {path: '/data-repair', label: 'Data Repair'},
  {path: '/db-health', label: 'DB Health Dashboard'},
  {path: '/dev-tools', label: 'Dev Tools'},
  {path: '/digital-twin', label: 'Digital Twin'},
  {path: '/drive-score', label: 'Drive Score'},
  {path: '/drives', label: 'Drives'},
  {path: '/drives/:id', label: 'Drive Detail'},
  {path: '/drives/:id/replay', label: 'Trip Replay'},
  {path: '/drivetrain-health', label: 'Drivetrain Health'},
  {path: '/driving-dynamics', label: 'Driving Dynamics'},
  {path: '/efficiency', label: 'Efficiency'},
  {path: '/energy', label: 'Energy'},
  {path: '/energy-flow', label: 'Energy Flow'},
  {path: '/energy-products', label: 'Energy Products'},
  {path: '/exports', label: 'Exports'},
  {path: '/fleet-api', label: 'Fleet API'},
  {path: '/geofences', label: 'Geofences'},
  {path: '/glance', label: 'Glance'},
  {path: '/guard-mode', label: 'Guard Mode'},
  {path: '/lifetime-stats', label: 'Lifetime Stats'},
  {path: '/live', label: 'Live Map'},
  {path: '/live-monitor', label: 'Live Signal Monitor'},
  {path: '/locations', label: 'Locations'},
  {path: '/maintenance', label: 'Maintenance'},
  {path: '/me/activity', label: 'My Activity'},
  {path: '/media-player', label: 'Media Player'},
  {path: '/mileage', label: 'Mileage'},
  {path: '/mqtt-inspector', label: 'MQTT Inspector'},
  {path: '/navigation', label: 'Navigation Route'},
  {path: '/notifications', label: 'Legacy Notifications Redirect'},
  {path: '/notifications/alerts', label: 'Notifications Alerts'},
  {path: '/notifications/archived', label: 'Notifications Archived'},
  {path: '/notifications/audit', label: 'Audit Log'},
  {path: '/notifications/browser', label: 'Notifications Browser'},
  {path: '/notifications/channels', label: 'Notifications Channels'},
  {path: '/notifications/inbox', label: 'Notifications Inbox'},
  {path: '/notifications/quiet-hours', label: 'Notifications Quiet Hours'},
  {path: '/notifications/rules', label: 'Notifications Rules'},
  {path: '/notifications/studio', label: 'Notifications Studio'},
  {path: '/notifications/webhooks', label: 'Notifications Webhooks'},
  {path: '/onboarding', label: 'Onboarding'},
  {path: '/period-compare', label: 'Period Compare'},
  {path: '/power-flow', label: 'Power Flow Dashboard'},
  {path: '/powershare', label: 'Powershare'},
  {path: '/projected-range', label: 'Projected Range'},
  {path: '/quick-stats', label: 'Quick Stats'},
  {path: '/redis-signals', label: 'Redis Signal Viewer'},
  {path: '/regen-efficiency', label: 'Regen Efficiency'},
  {path: '/roadmap', label: 'Roadmap'},
  {path: '/route-efficiency', label: 'Route Efficiency'},
  {path: '/s/:token', label: 'Shared Drive'},
  {path: '/safety-settings', label: 'Safety Settings'},
  {path: '/search', label: 'Search'},
  {path: '/security-access', label: 'Security Access'},
  {path: '/settings', label: 'Settings'},
  {path: '/signal-diff', label: 'Signal Diff'},
  {path: '/signal-explorer', label: 'Signal Explorer'},
  {path: '/signal-gaps', label: 'Signal Gap Detector'},
  {path: '/signal-log', label: 'Signal Log Viewer'},
  {path: '/sleep-efficiency', label: 'Sleep Efficiency'},
  {path: '/smart-charge', label: 'Smart Charge'},
  {path: '/software-updates', label: 'Software Updates'},
  {path: '/speed-profile', label: 'Speed Profile'},
  {path: '/state-debugger', label: 'State Machine Debugger'},
  {path: '/statistics', label: 'Statistics'},
  {path: '/system-status', label: 'System Status'},
  {path: '/tco', label: 'True Cost Ownership'},
  {path: '/temperature-impact', label: 'Temperature Impact'},
  {path: '/tesla-account', label: 'Tesla Account'},
  {path: '/tesla-charging-history', label: 'Tesla Charging History'},
  {path: '/tesla-charging-sessions', label: 'Tesla Charging Sessions'},
  {path: '/timeline', label: 'Timeline'},
  {path: '/tire-pressure', label: 'Tire Pressure'},
  {path: '/trip-planner', label: 'Trip Planner'},
  {path: '/trips', label: 'Trips'},
  {path: '/trips/:id', label: 'Trip Detail'},
  {path: '/vampire-drain', label: 'Vampire Drain'},
  {path: '/vehicle-comparison', label: 'Fleet Compare'},
  {path: '/vehicles', label: 'Vehicles'},
  {path: '/vehicles/:id', label: 'Vehicle Detail'},
  {path: '/vehicles/:id/access', label: 'Vehicle Access'},
  {path: '/watch', label: 'Watch Face'},
  {path: '/weekly-digest', label: 'Weekly Digest'},
  {path: '/year-review/:year', label: 'Year Review'},
];

/** localStorage key. Versioned (`:v1`) so a future migration can re-key. */
const STORAGE_KEY = 'teslasync:recent-pages:v1';

/** Synthetic same-tab change event — `storage` only fires cross-tab. */
const LOCAL_EVENT = 'teslasync:recent-pages-local-changed';

const MAX_ENTRIES = 50;

export const RECENT_PAGES_STORAGE_KEY = STORAGE_KEY;
export const RECENT_PAGES_MAX = MAX_ENTRIES;

/**
 * Coarse category for a recorded page. Drives the icon shown in the
 * palette / widget and gives consumers a stable grouping key. New kinds
 * may be added without breaking forward compatibility — unknown kinds
 * read from storage are surfaced as `'page'` by consumers.
 */
export type RecentPageKind =
  | 'page'
  | 'vehicle'
  | 'drive'
  | 'trip'
  | 'charging'
  | 'geofence'
  | 'year-review';

export interface RecentEntry {
  /** Pathname (no search/hash). Used for both navigation and dedup. */
  path: string;
  /** Captured page title at recording time, suitable for display. */
  title: string;
  /** Coarse category for icon + grouping. */
  kind: RecentPageKind;
  /** Captured numeric/string id when path contains an `:id`-style param. */
  ref_id?: string;
  /** ms since epoch of the most recent visit. */
  visited_at: number;
}

/**
 * Path-pattern → kind table. Order matters: more specific patterns first.
 * The path classifier is intentionally registry-independent so adding a
 * new dynamic route doesn't require a registry round-trip.
 */
const PATH_PATTERNS: {test: RegExp; kind: RecentPageKind}[] = [
  {test: /^\/vehicles\/([^/]+)(?:\/|$)/, kind: 'vehicle'},
  {test: /^\/drives\/([^/]+)(?:\/|$)/, kind: 'drive'},
  {test: /^\/charging\/([^/]+)(?:\/|$)/, kind: 'charging'},
  {test: /^\/trips\/([^/]+)(?:\/|$)/, kind: 'trip'},
  {test: /^\/geofences\/([^/]+)(?:\/|$)/, kind: 'geofence'},
  {test: /^\/year-review\/([^/]+)(?:\/|$)/, kind: 'year-review'},
];

export interface PathClassification {
  kind: RecentPageKind;
  ref_id?: string;
}

/** Classify `path` into a {@link RecentPageKind} + optional ref_id. */
export function classifyPath(path: string): PathClassification {
  for (const p of PATH_PATTERNS) {
    const m = p.test.exec(path);
    if (m) return {kind: p.kind, ref_id: m[1]};
  }
  return {kind: 'page'};
}

/**
 * Routes that should never enter the recent list. Public-share tokens are
 * privacy-sensitive; onboarding/watch are transient flows that don't make
 * sense to "return to"; /search is dynamic-query oriented and would
 * pollute recents with stale searches; /me/activity is itself a history
 * surface.
 */
const SKIP_PREFIXES = ['/onboarding', '/s/', '/watch'];
const SKIP_EXACT = new Set<string>(['/search', '/me/activity']);

export function shouldRecordPath(path: string): boolean {
  if (typeof path !== 'string') return false;
  if (!path || path[0] !== '/') return false;
  if (SKIP_EXACT.has(path)) return false;
  for (const pre of SKIP_PREFIXES) {
    if (pre.endsWith('/')) {
      // Trailing slash means "match anything under this segment",
      // including the bare segment without a slash (e.g. `/s` is
      // never a real route, but `/s/abc` is).
      if (path === pre.slice(0, -1) || path.startsWith(pre)) return false;
    } else if (path === pre || path.startsWith(pre + '/')) {
      return false;
    }
  }
  return true;
}

// ── Native-safe persistence ───────────────────────────────────────────
// react-native-web exposes the real `localStorage`; a pure native runtime
// does not. We probe `globalThis` for it (the notificationSound / AIVoiceMode
// precedent) and treat its absence exactly like the web source's
// `typeof window === 'undefined' || typeof window.localStorage === 'undefined'`
// guard — reads return `[]` and writes/clears are skipped.

interface WebStorageLike {
  getItem(key: string): string | null;
  setItem(key: string, value: string): void;
  removeItem(key: string): void;
}

function getWebStorage(): WebStorageLike | undefined {
  const candidate = (globalThis as typeof globalThis & {localStorage?: unknown})
    .localStorage;
  if (candidate == null || typeof candidate !== 'object') return undefined;
  const storage = candidate as Partial<WebStorageLike>;
  if (
    typeof storage.getItem === 'function' &&
    typeof storage.setItem === 'function' &&
    typeof storage.removeItem === 'function'
  ) {
    return storage as WebStorageLike;
  }
  return undefined;
}

function hasStorage(): boolean {
  return getWebStorage() !== undefined;
}

function isValidEntry(e: unknown): e is RecentEntry {
  if (!e || typeof e !== 'object') return false;
  const r = e as Record<string, unknown>;
  return (
    typeof r.path === 'string' &&
    typeof r.title === 'string' &&
    typeof r.visited_at === 'number' &&
    Number.isFinite(r.visited_at) &&
    typeof r.kind === 'string'
  );
}

function load(): RecentEntry[] {
  const store = getWebStorage();
  if (!store) return [];
  let raw: string | null;
  try {
    raw = store.getItem(STORAGE_KEY);
  } catch {
    return [];
  }
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    const valid: RecentEntry[] = [];
    for (const item of parsed) {
      if (isValidEntry(item)) valid.push(item);
      if (valid.length >= MAX_ENTRIES) break;
    }
    return valid;
  } catch {
    return [];
  }
}

function save(entries: RecentEntry[]): void {
  const store = getWebStorage();
  if (!store) return;
  try {
    store.setItem(STORAGE_KEY, JSON.stringify(entries));
  } catch {
    // Quota exceeded / disabled storage — fail silently. Recents is
    // additive UX; dropping a write degrades gracefully.
    return;
  }
  notify();
}

// ── Native-safe change notification ───────────────────────────────────
// The web source bridges same-tab notify→subscribe with a synthetic
// `window.dispatchEvent(new Event(LOCAL_EVENT))` and additionally listens to
// the native cross-tab `storage` event. Both are resolved off `globalThis`:
// when a global event target + Event constructor exist (react-native-web) the
// LOCAL_EVENT dispatch/listen and the 'storage' listener are attached verbatim;
// on a pure native runtime same-process fan-out folds into `localListeners`
// instead (LOCAL_EVENT is module-internal so no consumer observes the swap).

interface RecentPagesStorageEventLike {
  key: string | null;
}

interface RecentPagesEventTargetLike {
  addEventListener(
    type: string,
    listener: (event: RecentPagesStorageEventLike) => void,
  ): void;
  removeEventListener(
    type: string,
    listener: (event: RecentPagesStorageEventLike) => void,
  ): void;
  dispatchEvent(event: object): boolean;
}

type RecentPagesEventCtor = new (type: string) => object;

function getEventTarget(): RecentPagesEventTargetLike | undefined {
  const scope = globalThis as typeof globalThis & {
    addEventListener?: unknown;
    removeEventListener?: unknown;
    dispatchEvent?: unknown;
  };
  if (
    typeof scope.addEventListener === 'function' &&
    typeof scope.removeEventListener === 'function' &&
    typeof scope.dispatchEvent === 'function'
  ) {
    return scope as unknown as RecentPagesEventTargetLike;
  }
  return undefined;
}

function getEventCtor(): RecentPagesEventCtor | undefined {
  const scope = globalThis as typeof globalThis & {Event?: unknown};
  return typeof scope.Event === 'function'
    ? (scope.Event as RecentPagesEventCtor)
    : undefined;
}

const localListeners = new Set<() => void>();

function notify(): void {
  const target = getEventTarget();
  const EventCtor = getEventCtor();
  if (target && EventCtor) {
    try {
      target.dispatchEvent(new EventCtor(LOCAL_EVENT));
    } catch {
      // Some test runtimes lack the Event constructor — silently skip.
    }
    return;
  }
  for (const cb of localListeners) {
    try {
      cb();
    } catch {
      // Never let a subscriber crash the bus.
    }
  }
}

export interface RecordPageViewInput {
  /** Pathname (no search/hash). */
  path: string;
  /** Display title captured at the time of the visit. */
  title: string;
  /** Override the auto-classified kind. */
  kind?: RecentPageKind;
  /** Override the auto-extracted ref id. */
  ref_id?: string;
  /** Test seam — defaults to `Date.now()`. */
  now?: number;
}

/**
 * Record a single visit to `path`. Moves the entry to the top of the
 * list, replacing any prior entry for the same path. No-op for paths
 * filtered by {@link shouldRecordPath}.
 */
export function recordPageView(input: RecordPageViewInput): void {
  const path = input?.path;
  if (!shouldRecordPath(path)) return;
  const cls = classifyPath(path);
  const visited_at =
    typeof input.now === 'number' && Number.isFinite(input.now)
      ? input.now
      : Date.now();
  const title = (input.title && input.title.trim()) || path;
  const entry: RecentEntry = {
    path,
    title,
    kind: input.kind ?? cls.kind,
    ref_id: input.ref_id ?? cls.ref_id,
    visited_at,
  };
  const remaining = load().filter(e => e.path !== path);
  remaining.unshift(entry);
  if (remaining.length > MAX_ENTRIES) remaining.length = MAX_ENTRIES;
  save(remaining);
}

/** Snapshot of the recent-page list, newest first. Optionally truncated. */
export function getRecentPages(limit?: number): RecentEntry[] {
  const all = load();
  if (typeof limit === 'number') {
    return all.slice(0, Math.max(0, limit));
  }
  return all;
}

/** Wipe all recent-page history. Fires a same-tab change event. */
export function clearRecentPages(): void {
  const store = getWebStorage();
  if (!store) {
    notify();
    return;
  }
  try {
    store.removeItem(STORAGE_KEY);
  } catch {
    // ignore — same rationale as save()
  }
  notify();
}

/**
 * Subscribe to recent-page list changes. Fires for changes made in the
 * same tab (via {@link LOCAL_EVENT}) AND in other tabs (via the native
 * `storage` event). Returns an unsubscribe function.
 *
 * Native parity: when no global event target exists (a pure native runtime)
 * same-process changes are delivered through the module `localListeners` set
 * instead; cross-surface `storage` fan-out is then unavailable.
 */
export function subscribeRecentPages(handler: () => void): () => void {
  const target = getEventTarget();
  if (target) {
    const onLocal = () => {
      try {
        handler();
      } catch {
        // Never let a subscriber crash the bus.
      }
    };
    const onStorage = (e: RecentPagesStorageEventLike) => {
      if (e.key !== null && e.key !== STORAGE_KEY) return;
      try {
        handler();
      } catch {
        // swallow
      }
    };
    target.addEventListener(LOCAL_EVENT, onLocal);
    target.addEventListener('storage', onStorage);
    return () => {
      target.removeEventListener(LOCAL_EVENT, onLocal);
      target.removeEventListener('storage', onStorage);
    };
  }
  localListeners.add(handler);
  return () => {
    localListeners.delete(handler);
  };
}

/**
 * Resolve a stable label for `path` from {@link ROUTE_REGISTRY}. Returns
 * null if no match is found so callers can fall back to the captured
 * document title or the raw path. Parameterized routes (e.g.
 * `/vehicles/:id`) match on a regex derived from the registry pattern.
 */
export function resolvePageLabel(path: string): string | null {
  if (!path) return null;
  for (const r of ROUTE_REGISTRY) {
    if (r.path === path) return r.label;
  }
  for (const r of ROUTE_REGISTRY) {
    if (!r.path.includes(':')) continue;
    const re = new RegExp(
      '^' +
        r.path.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace(/:[^/]+/g, '[^/]+') +
        '$',
    );
    if (re.test(path)) return r.label;
  }
  return null;
}

/** Test-only helper: wipe the entire list without firing events. */
export function __resetRecentPagesForTests(): void {
  if (!hasStorage()) return;
  const store = getWebStorage();
  try {
    store?.removeItem(STORAGE_KEY);
  } catch {
    // ignore
  }
}

/**
 * Explicit capability matrix for the native recent-pages surface.
 *
 * Each flag describes a *pure native runtime*. The react-native-web target may
 * light the corresponding browser API up at runtime (real `localStorage`, a
 * global `storage` event), in which case the `getWebStorage` / `getEventTarget`
 * probes transparently use it. On a pure native runtime these remain
 * unavailable and the module degrades to an in-memory (per-process) store with
 * same-process change notifications only.
 */
export const nativeRecentPagesCapabilities = {
  /** Durable cross-restart history persistence (localStorage) — web-only. */
  durableHistoryPersistenceAvailable: false,
  /** Cross-surface `storage` event fan-out — web-only. */
  crossTabStorageEventAvailable: false,
} as const;
