package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestEmitDeterministic verifies that running the emitter twice on the same
// proto produces byte-identical output. This is the core invariant the CI
// drift gate relies on: if two consecutive runs differ, the emitter has a
// non-deterministic source (map iteration order, time stamps, randomness)
// that would defeat the gate.
func TestEmitDeterministic(t *testing.T) {
	pf, err := ParseProtoFile(filepath.Join("testdata", "sample.proto"))
	if err != nil {
		t.Fatalf("parse sample.proto: %v", err)
	}
	dir1 := t.TempDir()
	dir2 := t.TempDir()
	if err := Emit(pf, "protomodel", dir1); err != nil {
		t.Fatalf("first emit: %v", err)
	}
	if err := Emit(pf, "protomodel", dir2); err != nil {
		t.Fatalf("second emit: %v", err)
	}
	files := []string{fileSignalMetadata, fileEnumParsers, fileDatumDecoder}
	for _, name := range files {
		a, err := os.ReadFile(filepath.Join(dir1, name))
		if err != nil {
			t.Fatalf("read first %s: %v", name, err)
		}
		b, err := os.ReadFile(filepath.Join(dir2, name))
		if err != nil {
			t.Fatalf("read second %s: %v", name, err)
		}
		if string(a) != string(b) {
			t.Errorf("emit is non-deterministic for %s\n--- first ---\n%s\n--- second ---\n%s", name, a, b)
		}
	}
}

// TestEmitMatchesGolden verifies that the emitter output matches the
// committed golden files in testdata/golden. The goldens were generated by
// running `protogen-tesla --proto testdata/sample.proto --out testdata/golden
// --package protomodel`. If you intentionally change the emitter output
// shape, regenerate the goldens with that command and commit the diff.
//
// Line endings are normalized to LF before comparison because git's
// core.autocrlf setting on Windows clients can convert LF→CRLF during
// checkout. The emitter always writes LF (Go convention via go/format).
// Byte-exact determinism is enforced by TestEmitDeterministic instead,
// which never round-trips through git.
func TestEmitMatchesGolden(t *testing.T) {
	pf, err := ParseProtoFile(filepath.Join("testdata", "sample.proto"))
	if err != nil {
		t.Fatalf("parse sample.proto: %v", err)
	}
	got := t.TempDir()
	if err := Emit(pf, "protomodel", got); err != nil {
		t.Fatalf("emit: %v", err)
	}
	goldenDir := filepath.Join("testdata", "golden")
	files := []string{fileSignalMetadata, fileEnumParsers, fileDatumDecoder}
	for _, name := range files {
		gotBytes, err := os.ReadFile(filepath.Join(got, name))
		if err != nil {
			t.Fatalf("read got %s: %v", name, err)
		}
		wantBytes, err := os.ReadFile(filepath.Join(goldenDir, name))
		if err != nil {
			t.Fatalf("read golden %s: %v", name, err)
		}
		gotLF := strings.ReplaceAll(string(gotBytes), "\r\n", "\n")
		wantLF := strings.ReplaceAll(string(wantBytes), "\r\n", "\n")
		if gotLF != wantLF {
			t.Errorf("%s does not match golden\n--- got ---\n%s\n--- want ---\n%s", name, gotLF, wantLF)
		}
	}
}

// TestParserHandlesAllProductionConstructs makes sure the parser can ingest
// the real vendored vehicle_data.proto in addition to the trimmed sample.
// The actual emitter output isn't compared (that lives in the codegen drift
// gate that runs `go generate ./...` and `git diff --exit-code`); we only
// assert the parser sees the structural elements the emitter relies on.
func TestParserHandlesAllProductionConstructs(t *testing.T) {
	pf, err := ParseProtoFile(filepath.Join("..", "..", "api", "proto", "tesla", "vehicle_data.proto"))
	if err != nil {
		t.Fatalf("parse vendored proto: %v", err)
	}
	field := pf.FindEnum("Field")
	if field == nil {
		t.Fatal("Field enum not parsed from vendored proto")
	}
	if len(field.Values) < 250 {
		t.Errorf("Field enum should have >=250 values, got %d", len(field.Values))
	}
	value := pf.FindMessage("Value")
	if value == nil {
		t.Fatal("Value message not parsed from vendored proto")
	}
	if len(value.Oneofs) != 1 {
		t.Fatalf("Value message should have exactly one oneof, got %d", len(value.Oneofs))
	}
	if len(value.Oneofs[0].Variants) < 50 {
		t.Errorf("Value oneof should have >=50 variants, got %d", len(value.Oneofs[0].Variants))
	}
	for _, name := range []string{"LocationValue", "Doors", "TireLocation", "Time"} {
		if pf.FindMessage(name) == nil {
			t.Errorf("compound message %s missing from parsed proto", name)
		}
	}
	for _, name := range []string{"ShiftState", "BMSStateValue", "DistanceUnit", "TemperatureUnit", "PressureUnit", "ChargeUnitPreference"} {
		if pf.FindEnum(name) == nil {
			t.Errorf("named enum %s missing from parsed proto", name)
		}
	}
}

// TestClassifierCoversAllFields ensures every Field name in the vendored
// proto has an explicit entry in the classifier table (i.e. classify()
// returns ok=true). The default fallback is intentionally the safe
// behaviour for *future* proto additions; allowing existing fields to
// fall through would silently demote them to "metadata" without anyone
// noticing.
func TestClassifierCoversAllFields(t *testing.T) {
	pf, err := ParseProtoFile(filepath.Join("..", "..", "api", "proto", "tesla", "vehicle_data.proto"))
	if err != nil {
		t.Fatalf("parse vendored proto: %v", err)
	}
	field := pf.FindEnum("Field")
	if field == nil {
		t.Fatal("Field enum not parsed from vendored proto")
	}
	for _, v := range field.Values {
		_, ok := classify(v.Name)
		if !ok {
			t.Errorf("Field %q (=%d) falls through to default classifier; add an explicit case", v.Name, v.Number)
		}
	}
}

// TestEnumTypeOfCoversAllEnumFields enforces that every Field whose
// classifier kind is "enum" also has an explicit enumTypeOf() entry, and
// that the resolved enum type name actually exists in the vendored proto.
// Without this, a future enum-classified Field would silently emit
// SignalMeta.EnumTypeName="" and the codec dispatcher would have nothing
// to look up — a bug that compiles cleanly and only surfaces at runtime.
func TestEnumTypeOfCoversAllEnumFields(t *testing.T) {
	pf, err := ParseProtoFile(filepath.Join("..", "..", "api", "proto", "tesla", "vehicle_data.proto"))
	if err != nil {
		t.Fatalf("parse vendored proto: %v", err)
	}
	field := pf.FindEnum("Field")
	if field == nil {
		t.Fatal("Field enum not parsed from vendored proto")
	}
	for _, v := range field.Values {
		c, _ := classify(v.Name)
		if c.kind != "enum" {
			continue
		}
		enumName := enumTypeOf(v.Name)
		if enumName == "" {
			t.Errorf("Field %q is classified as enum but enumTypeOf() returned empty; add a switch case", v.Name)
			continue
		}
		if pf.FindEnum(enumName) == nil {
			t.Errorf("Field %q maps to enum type %q which does not exist in the vendored proto", v.Name, enumName)
		}
	}
}

// TestSignalMetaCompoundKindMatchesValueKind asserts the
// IsCompound/ValueKind/CompoundKind invariants hold for every emitted
// SignalMeta row: ValueKindCompound iff IsCompound iff CompoundKind !=
// CompoundKindNone. Without this guard, the per-field MQTT JSON decoder
// could silently route a Compound to the atomic path (or vice versa)
// whenever a future Field is added with mismatched classifier output —
// the kind of bug that compiles cleanly and only surfaces as silently
// dropped or shape-mismatched signals at runtime.
func TestSignalMetaCompoundKindMatchesValueKind(t *testing.T) {
	pf, err := ParseProtoFile(filepath.Join("..", "..", "api", "proto", "tesla", "vehicle_data.proto"))
	if err != nil {
		t.Fatalf("parse vendored proto: %v", err)
	}
	field := pf.FindEnum("Field")
	if field == nil {
		t.Fatal("Field enum not parsed from vendored proto")
	}
	for _, v := range field.Values {
		c, _ := classify(v.Name)
		isCompoundClassifier := strings.HasPrefix(c.kind, "compound:")
		valueKindIsCompound := valueKindConstName(c.kind) == "ValueKindCompound"
		compoundKindNonZero := compoundKindConstName(c.kind) != "CompoundKindNone"
		if isCompoundClassifier != valueKindIsCompound {
			t.Errorf("Field %q: classifier %q -> ValueKindCompound? %v, but compound: prefix? %v", v.Name, c.kind, valueKindIsCompound, isCompoundClassifier)
		}
		if isCompoundClassifier != compoundKindNonZero {
			t.Errorf("Field %q: classifier %q -> CompoundKind != None? %v, but compound: prefix? %v", v.Name, c.kind, compoundKindNonZero, isCompoundClassifier)
		}
		if valueKindIsCompound && !compoundKindNonZero {
			t.Errorf("Field %q: ValueKindCompound but CompoundKindNone — codegen would emit an undecodable signal", v.Name)
		}
	}
}

// TestEnumPrefixMatchesEnumValuesForEveryEnumField asserts that, for every
// enum-classified Field, the longest-common-prefix computed by
// buildEnumPrefixMap (which is what populates SignalMeta.EnumStringPrefix)
// is actually a prefix of EVERY value name of the enum it points at AND is
// non-empty. The first invariant guards against a future irregular enum
// where a stray value breaks the LCP and the decoder would silently emit
// the un-trimmed proto name (e.g. "ShiftStateD" instead of "D"), corrupting
// the canonical-string contract (Rule 11 in
// .github/instructions/tesla-pipeline.instructions.md). The second
// invariant guards against the empty-string case which would make
// strings.TrimPrefix a no-op and leak the proto-cased name verbatim.
func TestEnumPrefixMatchesEnumValuesForEveryEnumField(t *testing.T) {
	pf, err := ParseProtoFile(filepath.Join("..", "..", "api", "proto", "tesla", "vehicle_data.proto"))
	if err != nil {
		t.Fatalf("parse vendored proto: %v", err)
	}
	field := pf.FindEnum("Field")
	if field == nil {
		t.Fatal("Field enum not parsed from vendored proto")
	}
	enumPrefix := buildEnumPrefixMap(pf)
	for _, v := range field.Values {
		c, _ := classify(v.Name)
		if c.kind != "enum" {
			continue
		}
		enumName := enumTypeOf(v.Name)
		prefix, ok := enumPrefix[enumName]
		if !ok {
			t.Errorf("Field %q -> enum %q: missing from buildEnumPrefixMap", v.Name, enumName)
			continue
		}
		if prefix == "" {
			t.Errorf("Field %q -> enum %q: empty EnumStringPrefix; trimmer would no-op and leak proto name", v.Name, enumName)
			continue
		}
		enumDef := pf.FindEnum(enumName)
		if enumDef == nil {
			t.Errorf("Field %q -> enum %q: not present in vendored proto", v.Name, enumName)
			continue
		}
		for _, ev := range enumDef.Values {
			if !strings.HasPrefix(ev.Name, prefix) {
				t.Errorf("Field %q -> enum %q: value %q does not start with computed prefix %q", v.Name, enumName, ev.Name, prefix)
			}
		}
	}
}
