import { lazy } from 'react';
import {
  BarChart3, CalendarRange, CalendarDays, Trophy, TrendingUp, Clock,
  AlertTriangle, GitBranch, PieChart as PieIcon, Calendar, Gauge,
} from 'lucide-react';
import type { WidgetDef } from '../types';

export const ANALYTICS_WIDGETS: WidgetDef[] = [
  {
    id: 'fleet-stats',
    name: 'Fleet Stats',
    description: 'Fleet-wide metrics and totals',
    icon: BarChart3,
    category: 'analytics',
    defaultSize: { cols: 4, rows: 2 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../FleetStatsWidget')),
  },
  {
    id: 'fleet-stats-bar',
    name: 'Fleet Stats Bar',
    description: 'Fleet-wide: total vehicles, online count, total miles today, total energy',
    icon: BarChart3,
    category: 'analytics',
    defaultSize: { cols: 4, rows: 2 },
    minSize: { cols: 3, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../FleetStatsBarWidget')),
  },
  {
    id: 'weekly-summary-card',
    name: 'Weekly Summary',
    description: 'This week vs last week: total miles, kWh, cost, efficiency',
    icon: CalendarRange,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../WeeklySummaryCardWidget')),
  },
  {
    id: 'weekly-digest',
    name: 'Weekly Digest',
    description: 'This week vs last week: distance, drives, energy, efficiency trends',
    icon: CalendarDays,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../WeeklyDigestWidget')),
  },
  {
    id: 'fsd-weekly',
    name: 'FSD This Week',
    description: 'This week vs last week: reported FSD distance and share. Unmeasured is not zero.',
    icon: Gauge,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../FsdWeeklyWidget')),
    help: {
      i18nKey: 'help.fsdWeekly.body',
      defaultValue:
        'Reported supervised-driving distance this Monday–Sunday versus last week. Unmeasured is not zero.',
    },
  },
  {
    id: 'monthly-mileage',
    name: 'Monthly Mileage',
    description: 'Bar chart of monthly driving distance over last 12 months',
    icon: BarChart3,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../MonthlyMileageWidget')),
  },
  {
    id: 'lifetime-stats',
    name: 'Lifetime Stats',
    description: 'All-time totals: distance, drives, energy, CO₂ saved, ownership days',
    icon: Trophy,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../LifetimeStatsWidget')),
  },
  {
    id: 'mileage-stats',
    name: 'Mileage Stats',
    description: 'Driving averages: daily, weekly, monthly distance + milestone projection',
    icon: TrendingUp,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../MileageStatsWidget')),
  },
  {
    id: 'state-timeline',
    name: 'State Timeline',
    description: 'Vehicle state distribution: driving, charging, asleep, idle breakdown',
    icon: Clock,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../StateTimelineWidget')),
  },
  {
    id: 'anomaly-detector',
    name: 'Anomaly Detector',
    description: 'Statistical outlier alerts: unusual battery, temp, or driving anomalies',
    icon: AlertTriangle,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../AnomalyDetectorWidget')),
  },
  {
    id: 'fsm-distribution',
    name: 'State Distribution',
    description: 'Donut chart of time in each state + recent state transitions feed',
    icon: GitBranch,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../FSMDistributionWidget')),
  },
  {
    id: 'cost-breakdown',
    name: 'Cost Breakdown',
    description: 'Charging cost by source: home vs Supercharger vs destination, gas savings',
    icon: PieIcon,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../CostBreakdownWidget')),
  },
  {
    id: 'year-review',
    name: 'Year in Review',
    description: 'Annual recap: total miles, drives, energy, highlights, achievements',
    icon: Calendar,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../YearReviewWidget')),
  },
  {
    id: 'analytics-summary',
    name: 'Analytics Summary',
    description: 'Fleet-wide snapshot: distance, efficiency, energy, cost per mile',
    icon: BarChart3,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../AnalyticsSummaryWidget')),
  },
  {
    id: 'recently-unlocked-achievements',
    name: 'Recently Unlocked',
    description: 'Most recently unlocked achievements — click to view in Lifetime Stats',
    icon: Trophy,
    category: 'analytics',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 4 },
    component: lazy(() => import('../RecentlyUnlockedAchievements')),
  },
];
