import { lazy } from 'react';
import {
  Battery, Gauge, TrendingUp, Activity, Navigation, Cpu, TrendingDown, HeartPulse,
} from 'lucide-react';
import type { WidgetDef } from '../types';

export const BATTERY_WIDGETS: WidgetDef[] = [
  {
    id: 'battery-gauge',
    name: 'Battery Level',
    description: 'Battery percentage with level gauge',
    icon: Battery,
    category: 'battery',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('../BatteryGaugeWidget')),
  },
  {
    // The id is persisted in users' saved dashboard layouts, so it stays
    // 'battery-radial-gauge' even though the widget is no longer a radial —
    // renaming it would silently drop the widget from every existing dashboard.
    id: 'battery-radial-gauge',
    name: 'Battery Level Gauge',
    description: 'Large battery percentage gauge with color gradient (green>amber>red)',
    icon: Battery,
    category: 'battery',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('../BatteryLinearGaugeWidget')),
  },
  {
    id: 'range-estimate',
    name: 'Range Estimate',
    description: 'Rated, ideal, and estimated range',
    icon: Gauge,
    category: 'battery',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('../RangeEstimateWidget')),
  },
  {
    id: 'range-bar',
    name: 'Range Bar',
    description: 'Horizontal bar showing rated, ideal, and estimated range with EPA comparison',
    icon: Gauge,
    category: 'battery',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../RangeBarWidget')),
  },
  {
    id: 'battery-degradation-trend',
    name: 'Battery Degradation Trend',
    description: 'Line chart showing max range capacity over months',
    icon: TrendingUp,
    category: 'battery',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../BatteryDegradationTrendWidget')),
  },
  {
    id: 'energy-flow',
    name: 'Energy Flow',
    description: 'Live power flow diagram',
    icon: Activity,
    category: 'battery',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../EnergyFlowWidget')),
  },
  {
    id: 'projected-range',
    name: 'Projected Range',
    description: 'Helix-predicted range based on driving habits, weather, elevation',
    icon: Navigation,
    category: 'battery',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('../ProjectedRangeWidget')),
  },
  {
    id: 'battery-cells',
    name: 'Battery Cells',
    description: 'Cell-level voltage heatmap, min/max/avg, temperature per module',
    icon: Cpu,
    category: 'battery',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../BatteryCellsWidget')),
  },
  {
    id: 'battery-degradation-forecast',
    name: 'Battery Forecast',
    description: 'Predictive degradation: when battery hits 80%, risk factors, recommendations',
    icon: TrendingDown,
    category: 'battery',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../BatteryDegradationForecastWidget')),
  },
  {
    id: 'battery-health-analytics',
    name: 'Battery Analytics',
    description: 'Deep battery health: cycles, charge depth, temp exposure, DC fast ratio',
    icon: HeartPulse,
    category: 'battery',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../BatteryHealthAnalyticsWidget')),
  },
];
