import { lazy } from 'react';
import {
  Zap, BarChart3, DollarSign, Calendar, TrendingUp, Sparkles, Plug, Gauge, Clock,
} from 'lucide-react';
import type { WidgetDef } from '../types';

export const CHARGING_WIDGETS: WidgetDef[] = [
  {
    id: 'charge-status',
    name: 'Charge Status',
    description: 'Current charge state, amps, time remaining',
    icon: Zap,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('../ChargeStatusWidget')),
  },
  {
    id: 'charge-status-live',
    name: 'Charge Status Live',
    description: 'Live charging: current amps/volts/power, time remaining, energy added',
    icon: Zap,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('../ChargeStatusLiveWidget')),
  },
  {
    id: 'charge-history',
    name: 'Charge History',
    description: 'Recent charging sessions chart',
    icon: BarChart3,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../ChargeHistoryWidget')),
  },
  {
    id: 'charge-session-chart',
    name: 'Charge Session Chart',
    description: 'Bar chart of recent charge sessions: energy per session, color-coded by charger type (home/SC/destination)',
    icon: Zap,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../ChargeSessionChartWidget')),
  },
  {
    id: 'charge-cost-tracker',
    name: 'Charge Cost Tracker',
    description: 'Monthly charging cost breakdown: total kWh, total cost, cost per mile, vs gas savings',
    icon: DollarSign,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../ChargeCostTrackerWidget')),
  },
  {
    id: 'charging-schedule',
    name: 'Charging Schedule',
    description: 'Shows scheduled charge time, departure time, charge limit',
    icon: Calendar,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../ChargingScheduleWidget')),
  },
  {
    id: 'cost-forecast',
    name: 'Cost Forecast',
    description: '6-month charging cost projection with seasonal trends',
    icon: TrendingUp,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../CostForecastWidget')),
  },
  {
    id: 'charging-optimizer',
    name: 'Charging Optimizer',
    description: 'Smart charging schedule: optimal time, target SOC, cost savings',
    icon: Sparkles,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../ChargingOptimizerWidget')),
  },
  {
    id: 'wall-connector',
    name: 'Wall Connector',
    description: 'Home charging stats from Tesla Wall Connector: daily kWh, session history',
    icon: Plug,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../WallConnectorWidget')),
  },
  {
    id: 'charging-telemetry',
    name: 'Charging Telemetry',
    description: 'Live charging metrics: voltage, amperage, power, phases, charger type',
    icon: Gauge,
    category: 'charging',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../ChargingTelemetryWidget')),
  },
  {
    id: 'supercharger-history',
    name: 'Supercharger History',
    description: 'Tesla Supercharger sessions: location, energy, cost from Tesla account',
    icon: Zap,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../SuperchargerHistoryWidget')),
  },
  {
    id: 'charge-plans',
    name: 'Charge Plans',
    description: 'Active charge plan, rate schedule: peak/off-peak hours with rates',
    icon: Clock,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../ChargePlansWidget')),
  },
  {
    id: 'charging-session-detail',
    name: 'Charge Session Detail',
    description: 'Last charge session power curve with SoC overlay, kWh added, peak power',
    icon: Zap,
    category: 'charging',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../ChargingSessionDetailWidget')),
  },
];
