import { lazy } from 'react';
import {
  Car, TrendingUp, List, Gauge, Grid3X3, Activity, RotateCcw, Route,
  Lightbulb, Navigation,
} from 'lucide-react';
import type { WidgetDef } from '../types';

export const DRIVING_WIDGETS: WidgetDef[] = [
  {
    id: 'recent-drives',
    name: 'Recent Drives',
    description: 'Last 5 drives with distance and efficiency',
    icon: Car,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../RecentDrivesWidget')),
  },
  {
    id: 'drive-score',
    name: 'Driving Score',
    description: 'Weekly efficiency and driving score',
    icon: TrendingUp,
    category: 'driving',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('../DriveScoreWidget')),
  },
  {
    id: 'recent-drives-list',
    name: 'Recent Drives List',
    description: 'Last 5-10 drives: distance, duration, efficiency, start/end locations',
    icon: List,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../RecentDrivesListWidget')),
  },
  {
    id: 'drive-score-gauge',
    name: 'Drive Score Gauge',
    description: 'Weekly score gauge (0-100) with efficiency, smoothness, and speed breakdown',
    icon: Gauge,
    category: 'driving',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('../DriveScoreGaugeWidget')),
  },
  {
    id: 'drive-efficiency-chart',
    name: 'Drive Efficiency Chart',
    description: 'Area chart of Wh/mi over last 30 days with rolling average overlay',
    icon: TrendingUp,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../DriveEfficiencyChartWidget')),
  },
  {
    id: 'speed-heatmap',
    name: 'Speed Heatmap',
    description: 'Heatmap: time-of-day vs day-of-week speed distribution',
    icon: Grid3X3,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../SpeedHeatmapWidget')),
  },
  {
    id: 'driving-dynamics',
    name: 'Driving Dynamics',
    description: 'Acceleration, braking, lateral g-forces with driving style indicator',
    icon: Gauge,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../DrivingDynamicsWidget')),
  },
  {
    id: 'speed-profile',
    name: 'Speed Profile',
    description: 'Speed distribution histogram with efficiency overlay — find your optimal speed',
    icon: Activity,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../SpeedProfileWidget')),
  },
  {
    id: 'regen-efficiency',
    name: 'Regen Braking',
    description: 'Regenerative braking recovery rate, total kWh recovered, max regen power',
    icon: RotateCcw,
    category: 'driving',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('../RegenEfficiencyWidget')),
    help: {
      i18nKey: 'help.regenEfficiency.body',
      defaultValue:
        'Energy recovered through regenerative braking divided by total energy used during driving. Higher is better — Tesla cars typically reach 15–30% recovery in mixed driving.',
    },
  },
  {
    id: 'route-efficiency',
    name: 'Route Efficiency',
    description: 'Recurring routes ranked by energy efficiency with weather/elevation impact',
    icon: Route,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../RouteEfficiencyWidget')),
  },
  {
    id: 'driving-coach',
    name: 'Driving Coach',
    description: 'Helix-powered driving tips: personalized efficiency recommendations',
    icon: Lightbulb,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../DrivingCoachWidget')),
  },
  {
    id: 'trip-summary',
    name: 'Trip Summary',
    description: 'Recent trips: start→end, distance, duration, drive segments, charge stops',
    icon: Navigation,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../TripSummaryWidget')),
  },
  {
    id: 'drive-telemetry',
    name: 'Drive Telemetry',
    description: 'Last drive replay: speed, power, battery over time with route',
    icon: Activity,
    category: 'driving',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../DriveTelemetryWidget')),
  },
];
