import { lazy } from 'react';
import {
  Workflow, BatteryWarning, Moon, Sun, Home, BatteryFull, TrendingUp, Zap,
} from 'lucide-react';
import type { WidgetDef } from '../types';

export const ENERGY_WIDGETS: WidgetDef[] = [
  {
    id: 'energy-flow-animated',
    name: 'Energy Flow Animated',
    description: 'Animated energy flow diagram: battery→drive, regen→battery, charger→battery',
    icon: Workflow,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('../EnergyFlowAnimatedWidget')),
  },
  {
    id: 'vampire-drain',
    name: 'Vampire Drain',
    description: 'Phantom drain rate: avg %/day, recent drain events',
    icon: BatteryWarning,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../VampireDrainWidget')),
  },
  {
    id: 'sleep-efficiency',
    name: 'Sleep Efficiency',
    description: 'How well the car sleeps: efficiency %, drain rate, wake events',
    icon: Moon,
    category: 'energy',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('../SleepEfficiencyWidget')),
  },
  {
    id: 'solar-production',
    name: 'Solar Production',
    description: 'Daily solar generation chart from Tesla Energy / Powerwall',
    icon: Sun,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../SolarProductionWidget')),
  },
  {
    id: 'live-power-flow',
    name: 'Live Power Flow',
    description: 'Real-time solar→battery→home→grid power routing diagram',
    icon: Workflow,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../LivePowerFlowWidget')),
  },
  {
    id: 'energy-site-info',
    name: 'Energy Site',
    description: 'Tesla Energy system: solar capacity, Powerwall count, gateway firmware',
    icon: Home,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../EnergySiteInfoWidget')),
  },
  {
    id: 'backup-history',
    name: 'Backup History',
    description: 'Power outage events: Powerwall backup triggers, duration, energy used',
    icon: BatteryFull,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../BackupHistoryWidget')),
  },
  {
    id: 'power-flow-history',
    name: 'Power Flow History',
    description: 'Historical solar/battery/grid/home power routing over 24 hours',
    icon: TrendingUp,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../PowerFlowHistoryWidget')),
  },
  {
    id: 'energy-stats',
    name: 'Energy Stats',
    description: 'Energy overview: daily usage chart, total used/charged, efficiency, CO₂ saved',
    icon: Zap,
    category: 'energy',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../EnergyStatsWidget')),
  },
];
