import { lazy } from 'react';
import { Shield, DoorOpen, Eye, ShieldAlert, AlertOctagon, Users } from 'lucide-react';
import type { WidgetDef } from '../types';

export const SECURITY_WIDGETS: WidgetDef[] = [
  {
    id: 'security-status',
    name: 'Security',
    description: 'Lock, sentry, doors, windows status',
    icon: Shield,
    category: 'security',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('../SecurityStatusWidget')),
  },
  {
    id: 'door-window-status',
    name: 'Door & Window Status',
    description: 'Grid showing 4 doors + 4 windows with open/closed/partial badges',
    icon: DoorOpen,
    category: 'security',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../DoorWindowStatusWidget')),
  },
  {
    id: 'sentry-event-log',
    name: 'Sentry Event Log',
    description: 'Recent sentry events with timestamps',
    icon: Eye,
    category: 'security',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../SentryEventLogWidget')),
  },
  {
    id: 'safety-features',
    name: 'Safety Features',
    description: 'ADAS status: autopilot, collision warning, lane departure, blind spot',
    icon: ShieldAlert,
    category: 'security',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../SafetyFeaturesWidget')),
  },
  {
    id: 'safety-history',
    name: 'Safety History',
    description: 'ADAS event timeline: collision warnings, AEB, lane departures, disengagements',
    icon: AlertOctagon,
    category: 'security',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../SafetyHistoryWidget')),
  },
  {
    id: 'guard-mode',
    name: 'Guard Mode',
    description: 'Anti-theft guard status, recent security events, panic button',
    icon: Shield,
    category: 'security',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../GuardModeWidget')),
  },
  {
    id: 'vehicle-access',
    name: 'Vehicle Access',
    description: 'Authorized drivers, pending invitations, mobile access status',
    icon: Users,
    category: 'security',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../VehicleAccessWidget')),
  },
];
