import { lazy } from 'react';
import {
  HeartPulse, Radio, MapPin, BarChart2, Server, AlertCircle,
  FileSearch, HardDrive, Download, Info, LayoutDashboard, Rocket,
} from 'lucide-react';
import type { WidgetDef } from '../types';

export const SYSTEM_WIDGETS: WidgetDef[] = [
  {
    id: 'onboarding-checklist',
    name: 'Setup Checklist',
    description: 'First-run setup checklist: connect Tesla, pick a theme, create an alert, and more',
    icon: Rocket,
    category: 'system',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 3 },
    maxSize: { cols: 4, rows: 8 },
    component: lazy(() => import('../OnboardingChecklistWidget')),
    help: {
      i18nKey: 'checklist.help',
      defaultValue:
        'Tracks the few things you need to configure before TeslaSync feels useful. Auto-completes each step as you do it; dismiss it once you’re done.',
    },
  },
  {
    id: 'uptime-monitor',
    name: 'Uptime Monitor',
    description: 'System health: DB, MQTT, Tesla API, Fleet Telemetry status',
    icon: HeartPulse,
    category: 'system',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../UptimeMonitorWidget')),
  },
  {
    id: 'mqtt-status',
    name: 'MQTT Status',
    description: 'Fleet Telemetry MQTT connection: status, message rate, throughput',
    icon: Radio,
    category: 'system',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('../MQTTStatusWidget')),
  },
  {
    id: 'quick-nav',
    name: 'Quick Navigation',
    description: 'Shortcut links to key pages',
    icon: MapPin,
    category: 'system',
    defaultSize: { cols: 4, rows: 2 },
    minSize: { cols: 2, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../QuickNavWidget')),
  },
  {
    id: 'api-usage',
    name: 'API Usage',
    description: 'API call volume, response times, error rates, top endpoints',
    icon: BarChart2,
    category: 'system',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../APIUsageWidget')),
  },
  {
    id: 'system-health',
    name: 'System Health',
    description: 'Server health: DB, MQTT, Tesla API status, memory, connections',
    icon: Server,
    category: 'system',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../SystemHealthWidget')),
  },
  {
    id: 'telemetry-errors',
    name: 'Telemetry Errors',
    description: 'Fleet Telemetry error monitor: VINs with errors, error types, counts',
    icon: AlertCircle,
    category: 'system',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../TelemetryErrorsWidget')),
  },
  {
    id: 'audit-log',
    name: 'Audit Log',
    description: 'Security audit trail: user actions, auth events, permission changes',
    icon: FileSearch,
    category: 'system',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../AuditLogWidget')),
  },
  {
    id: 'backup-monitor',
    name: 'Backup Monitor',
    description: 'Database backup status: last run, size, retention, success/fail history',
    icon: HardDrive,
    category: 'system',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../BackupMonitorWidget')),
  },
  {
    id: 'export-status',
    name: 'Export Status',
    description: 'Data export jobs: progress, format, size, success/fail status',
    icon: Download,
    category: 'system',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../ExportStatusWidget')),
  },
  {
    id: 'version-info',
    name: 'Version Info',
    description: 'TeslaSync version, build info, uptime, data capture rates',
    icon: Info,
    category: 'system',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../VersionInfoWidget')),
  },
  {
    id: 'dashboard-stats',
    name: 'Dashboard Stats',
    description: 'Meta-widget: dashboard usage, widgets placed, FSM current state',
    icon: LayoutDashboard,
    category: 'system',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../DashboardStatsWidget')),
  },
];
