import { lazy } from 'react';
import {
  Car, CreditCard, Monitor, MonitorSmartphone, Download, Hash,
  Cog, Zap, FileText, Watch, Wrench, ShieldCheck, ArrowUpCircle,
} from 'lucide-react';
import type { WidgetDef } from '../types';

export const VEHICLE_WIDGETS: WidgetDef[] = [
  {
    id: 'vehicle-hero',
    name: 'Vehicle Card',
    description: 'Vehicle name, model, state, battery at a glance',
    icon: Car,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 9 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../VehicleHeroWidget')),
  },
  {
    id: 'vehicle-hero-card',
    name: 'Vehicle Hero Card',
    description: 'Vehicle name, model, state badge (online/asleep/driving/charging), battery, range, temp',
    icon: CreditCard,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../VehicleHeroCardWidget')),
  },
  {
    id: 'vehicle-twin',
    name: 'Digital Twin',
    description: 'Visual car state: doors, windows, lights',
    icon: Monitor,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('../DigitalTwinWidget')),
  },
  {
    id: 'digital-twin-mini',
    name: 'Digital Twin Mini',
    description: 'Small version of vehicle digital twin SVG: doors, windows, lock, charge port',
    icon: Monitor,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../DigitalTwinMiniWidget')),
  },
  {
    id: 'software-update-status',
    name: 'Software Update',
    description: 'Current firmware version, update availability, download/install progress bar',
    icon: MonitorSmartphone,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../SoftwareUpdateStatusWidget')),
  },
  {
    id: 'software-update-history',
    name: 'Update History',
    description: 'Firmware update timeline: versions installed, dates, changelogs',
    icon: Download,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../SoftwareUpdateHistoryWidget')),
  },
  {
    id: 'odometer-counter',
    name: 'Odometer Counter',
    description: 'Animated odometer with rolling digit animation and distance breakdown',
    icon: Hash,
    category: 'vehicle',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('../OdometerCounterWidget')),
  },
  {
    id: 'drivetrain-health',
    name: 'Drivetrain Health',
    description: 'Motor temp, stator temp, inverter health, overall powertrain score',
    icon: Cog,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../DrivetrainHealthWidget')),
  },
  {
    id: 'motor-performance',
    name: 'Motor Performance',
    description: 'Live motor data: torque, stator temp, gear state, g-forces',
    icon: Zap,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../MotorPerformanceWidget')),
  },
  {
    id: 'motor-history',
    name: 'Motor History',
    description: 'Motor torque and stator temp over time with danger zone highlighting',
    icon: Cog,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 2, rows: 4 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../MotorHistoryWidget')),
  },
  {
    id: 'vehicle-specs',
    name: 'Vehicle Specs',
    description: 'Configuration reference: model, trim, paint, wheels, options',
    icon: FileText,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../VehicleSpecsWidget')),
  },
  {
    id: 'watch-summary',
    name: 'Watch Summary',
    description: 'Apple Watch-style compact view: battery, range, state, lock status',
    icon: Watch,
    category: 'vehicle',
    defaultSize: { cols: 1, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 2, rows: 40 },
    component: lazy(() => import('../WatchSummaryWidget')),
  },
  {
    id: 'maintenance-tracker',
    name: 'Maintenance',
    description: 'Upcoming maintenance reminders + recent service history',
    icon: Wrench,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../MaintenanceTrackerWidget')),
  },
  {
    id: 'warranty-status',
    name: 'Warranty Status',
    description: 'Warranty countdown: time remaining, mileage remaining, coverage types',
    icon: ShieldCheck,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 2 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 3, rows: 40 },
    component: lazy(() => import('../WarrantyStatusWidget')),
  },
  {
    id: 'subscriptions',
    name: 'Subscriptions',
    description: 'Tesla subscriptions: Premium Connectivity, FSD, expiry dates, renewal',
    icon: CreditCard,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../SubscriptionsWidget')),
  },
  {
    id: 'vehicle-upgrades',
    name: 'Upgrades & Sharing',
    description: 'Available OTA upgrades with pricing + active drive share links',
    icon: ArrowUpCircle,
    category: 'vehicle',
    defaultSize: { cols: 2, rows: 4 },
    minSize: { cols: 1, rows: 2 },
    maxSize: { cols: 4, rows: 40 },
    component: lazy(() => import('../VehicleUpgradesWidget')),
  },
];
