// Pure, framework-free model + projection for the ReleaseNotes shared surface — the native analogue of every
// decision the web component makes (web/src/components/feedback/ReleaseNotes.tsx) before it returns JSX. No
// Compose, no Android, no HTTP: every declaration here is unit-tested off-device in the
// :android:testReleaseUnitTest gate, keeping the composable a thin render layer.
//
// What the web source is (and therefore the COMPLETE branch set this surface reproduces):
//   • A compact, single-open collapsible release-notes accordion (the sidebar / about-page card form of the
//     changelog). Its only prop is `limit` (default 3), which caps how many newest-first releases it renders
//     from the build-time-generated `@/generated/changelog` catalog. Its only hook is `useTranslation`; the
//     changelog is a static compiled-in module, NOT a network query — so, exactly like the sibling
//     ChangelogModal (which shares that same catalog) and AlertBanner surfaces document, there is no
//     loading / error / stale / offline lifecycle to model. Inventing one would be fabricated state the web
//     source never has (honesty covenant: no scope narrowing, no silent drift). The genuinely reachable render
//     states are the two [ReleaseNotesRender] branches: Content (one or more releases as an accordion) and
//     Empty (a catalog capped to nothing — a friendly empty state, never a blank box).
//   • The accordion is SINGLE-open: the web holds one `expanded` version string (initialised to the first
//     release) and toggling a header sets it to that version or back to null, so opening one collapses any
//     other. That contract is reduced here in [ReleaseNotesModel.toggle] / [initialExpanded] / [isExpanded] so
//     the view owns a single lifted `expanded` value rather than per-entry state.
//
// Data source: this surface reads the SAME release catalog the web `@/generated/changelog` module exposes.
// On native that catalog already exists as the embedded [ChangelogCatalog] (the autogenerated native analogue
// shipped with the ChangelogModal surface). It is reused here through the [ReleaseNotesSource] seam (P1/S8)
// rather than copied, so there is exactly one native source of truth for the changelog and the two surfaces
// can never drift apart — the same single-module relationship the web has between ReleaseNotes and
// ChangelogModal. The view performs no HTTP and binds no data port other than this catalog seam.
//
// `InvalidPackageDeclaration` is suppressed: the mandated surface directory
// (com/teslasync/shared-surfaces/ReleaseNotes — the P3 prompt's allowed-files path) cannot form a valid Kotlin
// package (a hyphen and a PascalCase segment are illegal in a package identifier), so the package intentionally
// diverges from the path, exactly as the sibling AlertBanner / ChangelogModal surfaces do.
// `MatchingDeclarationName` is suppressed for the co-located supporting declarations.
@file:Suppress("MatchingDeclarationName", "InvalidPackageDeclaration")

package io.teslasync.android.sharedsurfaces.releasenotes

import io.teslasync.android.modalsdialogs.changelogmodal.ChangelogBadge
import io.teslasync.android.modalsdialogs.changelogmodal.ChangelogCatalog
import io.teslasync.android.modalsdialogs.changelogmodal.ChangelogRelease
import io.teslasync.shared.core.diagnostics.Logger

/** Diagnostics + registry identifiers for the surface (P1/S11). */
object ReleaseNotesRegistration {
    /** Stable surface id. */
    const val ID: String = "release-notes"

    /** Diagnostics surface slug emitted with the `view.opened` event (P1/S11). */
    const val SLUG: String = "ReleaseNotes"
}

/**
 * The reduced render state of the accordion — the two mutually-exclusive, genuinely reachable branches. The web
 * component always renders its container (it is controlled by `limit`), so there is no hidden surface — only
 * whether the body is the list or the friendly empty state.
 */
sealed interface ReleaseNotesRender {
    /** The catalog capped to no releases (`limit <= 0` or an empty catalog) — a friendly empty state. */
    data object Empty : ReleaseNotesRender

    /** One or more releases shown as a single-open accordion (web `releases.map(...)`). */
    data class Content(
        val count: Int,
    ) : ReleaseNotesRender
}

/** Native-only accessibility microcopy defaults (no web catalog key ⇒ these English fallbacks are used). */
object ReleaseNotesDefaults {
    /** Action label announced for a release header while collapsed (web relies on the DOM `aria-expanded`). */
    const val EXPAND_ACTION: String = "Expand"

    /** Action label announced for a release header while expanded. */
    const val COLLAPSE_ACTION: String = "Collapse"

    /** State description announced while a release is expanded — native equivalent of `aria-expanded="true"`. */
    const val EXPANDED_STATE: String = "Expanded"

    /** State description announced while a release is collapsed — native equivalent of `aria-expanded="false"`. */
    const val COLLAPSED_STATE: String = "Collapsed"
}

/** Resource name for a release header's expand action label (by-name; absent ⇒ the English default). */
const val KEY_EXPAND_ACTION: String = "translation_changelog_entry_expand"

/** Resource name for a release header's collapse action label (by-name; absent ⇒ default). */
const val KEY_COLLAPSE_ACTION: String = "translation_changelog_entry_collapse"

/** Resource name for a release header's expanded state description (by-name; absent ⇒ default). */
const val KEY_EXPANDED_STATE: String = "translation_changelog_entry_expanded"

/** Resource name for a release header's collapsed state description (by-name; absent ⇒ default). */
const val KEY_COLLAPSED_STATE: String = "translation_changelog_entry_collapsed"

/**
 * The localized accessibility affordance strings for a collapsible release header — resolved once at the render
 * boundary so the header's TalkBack action + state description track the open/closed toggle the way the web
 * `aria-expanded` does. The web source owns no text keys for these (it relies on the DOM), so they resolve
 * by-name with the English fallbacks above.
 */
data class ReleaseNotesEntryAffordances(
    val expandAction: String,
    val collapseAction: String,
    val expandedState: String,
    val collapsedState: String,
) {
    /** The TalkBack action label for the toggle in its current [expanded] state. */
    fun actionLabel(expanded: Boolean): String = if (expanded) collapseAction else expandAction

    /** The TalkBack state description for the current [expanded] state (web `aria-expanded`). */
    fun stateLabel(expanded: Boolean): String = if (expanded) expandedState else collapsedState
}

/**
 * The localized strings the composable renders — resolved once at the render boundary and handed to the
 * stateless content as a framework-free bundle so the view stays a thin render layer. The "What's New" heading
 * and badge labels resolve from the P1/S10 catalog (the web keys `changelog.releaseNotes.heading` +
 * `changelog.badges.*`); the empty hint reuses the shared `common.noData` key; the header a11y affordances
 * resolve by-name with the English defaults above.
 */
data class ReleaseNotesStrings(
    val heading: String,
    val emptyMessage: String,
    val badgeLabels: Map<ChangelogBadge, String>,
    val affordances: ReleaseNotesEntryAffordances,
) {
    /** The localized badge label for [badge], falling back to its enum name if unmapped. */
    fun badgeLabel(badge: ChangelogBadge): String = badgeLabels[badge] ?: badge.name
}

/**
 * The state-holder seam the surface binds to — the native analogue of the web's `@/generated/changelog` import
 * (P1/S8). The view reads the release catalog through this port instead of touching the embedded data directly,
 * so the data source stays injectable for tests and previews. The default ([DefaultReleaseNotesSource]) binds
 * the single embedded [ChangelogCatalog] the ChangelogModal surface also reads, so the two never drift.
 */
interface ReleaseNotesSource {
    /** All releases, newest first — the web `CHANGELOG`. */
    val releases: List<ChangelogRelease>
}

/**
 * The default [ReleaseNotesSource]: the embedded [ChangelogCatalog] (the autogenerated native analogue of the
 * web `@/generated/changelog` module). Framework-free, so the binding is exercised off-device.
 */
class DefaultReleaseNotesSource(
    override val releases: List<ChangelogRelease> = ChangelogCatalog.releases,
) : ReleaseNotesSource

/**
 * Pure, side-effect-free reducer — the native port of the web component's prop-and-state to render mapping.
 * Stateless so it is fully covered by the off-device unit gate.
 */
object ReleaseNotesModel {
    /** Default cap on rendered releases — the web `limit = 3` default prop. */
    const val DEFAULT_LIMIT: Int = 3

    /**
     * The newest-first releases actually rendered — the web `CHANGELOG.slice(0, limit)`. A non-positive [limit]
     * yields an empty list (JS `slice(0, n<=0)` ⇒ `[]`); a [limit] beyond the catalog size yields the whole
     * catalog.
     */
    fun visibleReleases(
        all: List<ChangelogRelease>,
        limit: Int,
    ): List<ChangelogRelease> = all.take(limit.coerceAtLeast(0))

    /**
     * The version expanded on first render — the web `useState(releases[0]?.version ?? null)`. Null when there
     * is nothing to show, so no header starts open.
     */
    fun initialExpanded(visible: List<ChangelogRelease>): String? = visible.firstOrNull()?.version

    /**
     * The next expanded version after a header tap — the web `setExpanded(isExpanded ? null : version)`.
     * Tapping the open header collapses it (null); tapping any other opens it (and, because the view holds one
     * value, collapses whatever was open).
     */
    fun toggle(
        current: String?,
        version: String,
    ): String? = if (current == version) null else version

    /** Whether [version] is the currently-expanded header — the web `expanded === release.version`. */
    fun isExpanded(
        current: String?,
        version: String,
    ): Boolean = current == version

    /**
     * Classifies the body into its [ReleaseNotesRender] state from the visible-release count. An empty list
     * renders the friendly empty state instead of a blank box.
     */
    fun classify(visibleCount: Int): ReleaseNotesRender =
        if (visibleCount == 0) ReleaseNotesRender.Empty else ReleaseNotesRender.Content(visibleCount)
}

/**
 * The one PII-safe diagnostic this surface emits (P1/S11). Carries only the surface [SLUG] — never a version,
 * date, or change text — so a diagnostics line can never leak the catalog's content.
 */
object ReleaseNotesDiagnostics {
    /** Diagnostics surface slug emitted with the `view.opened` event. */
    const val SLUG: String = ReleaseNotesRegistration.SLUG

    private const val VIEW_OPENED = "view.opened"
    private const val SURFACE_KEY = "surface"

    /** Emits the `view.opened` diagnostic for this surface. Call from the composable's first-composition effect. */
    fun recordViewOpened(logger: Logger) {
        logger.info(VIEW_OPENED, mapOf(SURFACE_KEY to SLUG))
    }
}

/**
 * Reproduces i18next's `t(key, default)` against the native i18n facade: returns the [lookup] result for
 * [resourceName] when it resolves to a non-blank string, otherwise the [fallback] default. [lookup] is a thin
 * seam over the Android string catalog in production (an optional by-name resource read) and a map in tests, so
 * the resolve-or-fallback decision stays pure and unit-tested.
 */
fun resolveOptional(
    lookup: (String) -> String?,
    resourceName: String,
    fallback: String,
): String = lookup(resourceName)?.takeIf { it.isNotBlank() } ?: fallback
