// Command aigen generates web/src/ai/features.ts from the Go feature
// registry (internal/ai/features.Registry). The Go registry is the
// single source of truth for AI feature metadata (Phase-50
// methodology principle P9, ADR-015 §I10).
//
// Usage:
//
//	go run ./tools/aigen           # writes web/src/ai/features.ts
//	go run ./tools/aigen --check   # exit 1 if file would change
//
// CI invokes the --check form so a PR that adds a feature in the Go
// registry but forgets to regenerate the TS mirror is rejected at
// merge time, not at runtime.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ev-dev-labs/teslasync/internal/ai/features"
)

const outputPath = "web/src/ai/features.ts"

func main() {
	check := flag.Bool("check", false, "exit 1 if the generated file would change")
	flag.Parse()

	if err := features.CoverageOK(); err != nil {
		fmt.Fprintf(os.Stderr, "aigen: registry CoverageOK failed: %v\n", err)
		os.Exit(1)
	}

	out := generate()

	abs, err := filepath.Abs(outputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "aigen: resolve %s: %v\n", outputPath, err)
		os.Exit(1)
	}

	if *check {
		existing, readErr := os.ReadFile(abs)
		if readErr != nil {
			fmt.Fprintf(os.Stderr,
				"aigen --check: %s does not exist or is unreadable: %v\n"+
					"  Run `make generate` (or `go run ./tools/aigen`) to refresh it.\n",
				outputPath, readErr)
			os.Exit(1)
		}
		if !bytes.Equal(existing, out) {
			fmt.Fprintf(os.Stderr,
				"aigen --check: %s is stale.\n"+
					"  The Go registry in internal/ai/features/registry.go has changed since the\n"+
					"  TS mirror was last generated. Run `make generate` (or\n"+
					"  `go run ./tools/aigen`) to regenerate, then commit the result.\n",
				outputPath)
			os.Exit(1)
		}
		fmt.Println("aigen: web/src/ai/features.ts is in sync with internal/ai/features registry")
		return
	}

	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "aigen: mkdir %s: %v\n", filepath.Dir(abs), err)
		os.Exit(1)
	}
	if err := os.WriteFile(abs, out, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "aigen: write %s: %v\n", outputPath, err)
		os.Exit(1)
	}
	fmt.Printf("aigen: wrote %s (%d bytes, %d features)\n", outputPath, len(out), len(features.IDs()))
}

// generate builds the canonical TS source for web/src/ai/features.ts.
// Output is byte-stable across Go map iteration order (we sort by
// feature ID) so `--check` produces deterministic results.
func generate() []byte {
	ids := features.IDs()

	var b bytes.Buffer
	b.WriteString("// Code generated by tools/aigen. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Source: internal/ai/features/registry.go\n")
	b.WriteString("// Regenerate with: make generate (or `go run ./tools/aigen`).\n")
	b.WriteString("//\n")
	b.WriteString("// This file is the TypeScript mirror of the Go AI feature registry.\n")
	b.WriteString("// Backend (internal/ai/features) and frontend (this file) cannot drift\n")
	b.WriteString("// because CI runs `go run ./tools/aigen --check` and fails the build\n")
	b.WriteString("// if a regeneration is required.\n")
	b.WriteString("//\n")
	b.WriteString("// Phase-50 / 0001 — F0 AI-Off Contract (ADR-015).\n")
	b.WriteString("\n")

	// AiFeatureId — typed key used by useAiEnabled / withAiFeature.
	if len(ids) == 0 {
		b.WriteString("export type AiFeatureId = never;\n\n")
	} else {
		quoted := make([]string, len(ids))
		for i, id := range ids {
			quoted[i] = fmt.Sprintf("%q", id)
		}
		fmt.Fprintf(&b, "export type AiFeatureId = %s;\n\n", strings.Join(quoted, " | "))
	}

	// AiFeatureMeta — minimal shape used by the Settings UI (F2).
	// Larger surface fields (Routes, JobNames, …) are deliberately
	// not emitted; the off-mode walker reads them server-side from
	// the Go registry.
	b.WriteString("export interface AiFeatureMeta {\n")
	b.WriteString("  readonly id: AiFeatureId;\n")
	b.WriteString("  readonly name: string;\n")
	b.WriteString("  readonly description: string;\n")
	b.WriteString("  readonly tier: string;\n")
	b.WriteString("  readonly defaultOn: boolean;\n")
	b.WriteString("  readonly needsRag: boolean;\n")
	b.WriteString("  readonly needsTools: boolean;\n")
	b.WriteString("  readonly needsStream: boolean;\n")
	b.WriteString("  readonly uiTestIds: readonly string[];\n")
	b.WriteString("}\n\n")

	// AI_FEATURES — the canonical map, keyed by AiFeatureId so a
	// typo at the call site is a tsc error rather than a silent
	// `undefined` lookup.
	b.WriteString("export const AI_FEATURES: Readonly<Record<AiFeatureId, AiFeatureMeta>> = Object.freeze({\n")
	for _, id := range ids {
		f, _ := features.Get(id)
		fmt.Fprintf(&b, "  %q: Object.freeze({\n", id)
		fmt.Fprintf(&b, "    id: %q,\n", f.ID)
		fmt.Fprintf(&b, "    name: %q,\n", f.Name)
		fmt.Fprintf(&b, "    description: %q,\n", f.Description)
		fmt.Fprintf(&b, "    tier: %q,\n", f.Tier)
		fmt.Fprintf(&b, "    defaultOn: %t,\n", f.DefaultOn)
		fmt.Fprintf(&b, "    needsRag: %t,\n", f.NeedsRAG)
		fmt.Fprintf(&b, "    needsTools: %t,\n", f.NeedsTools)
		fmt.Fprintf(&b, "    needsStream: %t,\n", f.NeedsStream)
		b.WriteString("    uiTestIds: Object.freeze([")
		for i, tid := range f.Routes.UITestIDs {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", tid)
		}
		b.WriteString("] as const),\n")
		b.WriteString("  }),\n")
	}
	b.WriteString("});\n\n")

	// AI_FEATURE_IDS — the deterministic list, useful for the
	// off-mode invariant test which iterates every known feature.
	b.WriteString("export const AI_FEATURE_IDS: readonly AiFeatureId[] = Object.freeze([\n")
	for _, id := range ids {
		fmt.Fprintf(&b, "  %q,\n", id)
	}
	b.WriteString("] as const);\n\n")

	// isKnownAiFeature — type-guard mirror of features.IsKnown.
	b.WriteString("export function isKnownAiFeature(id: string): id is AiFeatureId {\n")
	b.WriteString("  return Object.prototype.hasOwnProperty.call(AI_FEATURES, id);\n")
	b.WriteString("}\n")

	return b.Bytes()
}
