// AUTOGENERATED from web/src/generated/changelog.ts by gen-changelog-catalog.cjs — do not edit by hand.
// Native analogue of the web `@/generated/changelog` module: the same release catalog the web
// ChangelogModal renders, compiled into the app and surfaced through the [ChangelogSource] seam.
// Regenerate after editing the root CHANGELOG.md (re-run the web generator, then this script).
@file:Suppress("MatchingDeclarationName", "InvalidPackageDeclaration", "ktlint:standard:filename")

package io.teslasync.android.modalsdialogs.changelogmodal

private val release070: ChangelogRelease =
    ChangelogRelease(
        version = "0.7.0",
        date = "2026-03-29",
        badge = ChangelogBadge.Latest,
        changes =
            listOf(
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "Comprehensive Telemetry Expansion (228/228 Tesla Fields): New DB migration (000017): 78 new columns + 6 new " +
                        "tables for complete Tesla signal coverage",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "charging_telemetry: 55-column real-time charging data (pack voltage/current, cell voltages, BMS, powershare)",
                ),
                ChangelogChange(ChangelogChangeType.Added, "media_snapshots: now playing, volume, playback source"),
                ChangelogChange(ChangelogChangeType.Added, "vehicle_config_snapshots: trim, color, software updates"),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "location_snapshots: navigation destination, route, home/work/favorite detection",
                ),
                ChangelogChange(ChangelogChangeType.Added, "safety_snapshots: ADAS settings, collision warnings, FSD miles"),
                ChangelogChange(ChangelogChangeType.Added, "user_preference_snapshots: unit settings, time format"),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "Expanded motor_snapshots: quad-motor support (torque/speed/state/temps for F/R/REL/RER)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "Expanded climate_snapshots: seat heaters (5 positions), steering wheel heat, auto climate",
                ),
                ChangelogChange(ChangelogChangeType.Added, "Expanded security_events: lights, tonneau, seat belts, valet/service modes"),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "5 New UI Pages (51 total): **Energy Flow** \u2014 Pack voltage/current, cell balance, module temps, BMS " +
                        "status, powershare",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Drivetrain Health** \u2014 Quad-motor thermal monitoring, stator/heatsink/inverter temps",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Media Player** \u2014 Now playing, volume, playback history, source distribution",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Safety Settings** \u2014 ADAS configuration, collision warnings, FSD statistics",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Navigation** \u2014 Active route, destination, home/work/favorite indicators",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "4 New Grafana Dashboards (26 total): Energy Flow: pack voltage/current, charging power, cell spread, BMS",
                ),
                ChangelogChange(ChangelogChangeType.Added, "Drivetrain Thermal: stator/heatsink/inverter temps, motor currents"),
                ChangelogChange(ChangelogChangeType.Added, "Comfort & Media: seat heaters, HVAC modes, now playing, volume"),
                ChangelogChange(ChangelogChangeType.Added, "Vehicle Intelligence: config, software, safety, navigation, preferences"),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "4 New Tesla Fleet API Integrations: Nearby Charging Sites \u2014 show Superchargers near vehicle",
                ),
                ChangelogChange(ChangelogChangeType.Added, "Release Notes \u2014 firmware update release notes"),
                ChangelogChange(ChangelogChangeType.Added, "Recent Alerts \u2014 vehicle alerts from Tesla (recalls, service)"),
                ChangelogChange(ChangelogChangeType.Added, "Service Data \u2014 service history and status"),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "Enhanced Existing Pages: Dashboard: added media/entertainment and navigation live cards",
                ),
                ChangelogChange(ChangelogChangeType.Added, "VehicleDetail: added energy/charging pack data and media/nav panels"),
                ChangelogChange(ChangelogChangeType.Added, "Settings: Re-authorize and Disconnect buttons for Tesla account"),
                ChangelogChange(ChangelogChangeType.Changed, "Fleet telemetry config uses MQTT dispatcher (was HTTP)"),
                ChangelogChange(ChangelogChangeType.Changed, "Let's Encrypt ISRG Root X1 CA certificate auto-included in subscription"),
                ChangelogChange(ChangelogChangeType.Changed, "Added vehicle_location OAuth scope for location telemetry fields"),
                ChangelogChange(ChangelogChangeType.Changed, "Added prompt=consent to force OAuth scope re-approval"),
                ChangelogChange(ChangelogChangeType.Changed, "228/228 Tesla fields verified against official Available Data page"),
                ChangelogChange(ChangelogChangeType.Changed, "Key pairing via tesla.com/_ak link (replaced broken API call)"),
                ChangelogChange(ChangelogChangeType.Changed, ".well-known path bypasses Authentik authentication"),
                ChangelogChange(ChangelogChangeType.Changed, "Fixed fleet telemetry image: tesla/fleet-telemetry (Docker Hub, not GHCR)"),
                ChangelogChange(ChangelogChangeType.Changed, "Command proxy: writable filesystem fix"),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "Removed invalid fields: Latitude, Longitude (standalone), FrunkOpen, TrunkOpen, WindowState",
                ),
                ChangelogChange(ChangelogChangeType.Changed, "Added minimum_delta for SelfDrivingMilesSinceReset"),
                ChangelogChange(ChangelogChangeType.Changed, "Removed invalid alert_type \"security\""),
                ChangelogChange(ChangelogChangeType.Fixed, "Disconnect properly clears DB token + in-memory client state"),
                ChangelogChange(ChangelogChangeType.Fixed, "TokenRepo.Delete() method for clean disconnection"),
            ),
    )

private val release060: ChangelogRelease =
    ChangelogRelease(
        version = "0.6.0",
        date = "2026-03-28",
        badge = ChangelogBadge.Stable,
        changes =
            listOf(
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "10 New Pages: **Driving Dynamics** \u2014 Real-time motor torque gauges, G-force visualization, acceleration " +
                        "patterns, pedal usage tracking, stator temperature monitoring",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Climate Control** \u2014 HVAC power & fan speed monitoring, thermal comfort scoring, cabin/outside " +
                        "temperature trends, defrost and battery heater status",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Security & Access** \u2014 SVG vehicle visualization with lock/sentry/door/window status indicators, " +
                        "security event timeline, sentry activity charts",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Charging Curve** \u2014 Charge rate (kW) vs SOC% curve visualization, multi-session overlay comparison, " +
                        "charging speed degradation trend analysis",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Cost Analysis** \u2014 Monthly/yearly cost trends, cost-per-mile tracking, interactive gas vs electric " +
                        "savings calculator, lifetime savings counter",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Battery Cells** \u2014 Cell voltage spread gauge, module temperature balance, 4\u00d723 pack grid " +
                        "visualization, cell balance scoring, degradation correlation",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Drive Score** \u2014 Gamified 0-100 driving efficiency scoring with animated gauge, " +
                        "efficiency/smoothness/speed breakdown, improvement tips, score trends",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Weekly Digest** \u2014 Auto-generated weekly car summary with drive highlights, charging summary, fun facts, " +
                        "week-over-week comparison, notable events",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Maintenance Tracker** \u2014 Service schedule with 8 maintenance items, odometer-based progress bars, " +
                        "localStorage service log, annual cost estimates",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Data Export** \u2014 Export drives, charging, analytics in CSV/JSON format with date range filtering, export " +
                        "job management and download",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "Enhanced Existing Pages: **Dashboard** \u2014 New \"Live Telemetry\" section with real-time drivetrain, " +
                        "climate, security, and tire pressure cards",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Vehicle Detail** \u2014 4 comprehensive telemetry panels: powertrain, climate, security, tire pressure with " +
                        "3-second auto-refresh",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Charging** \u2014 Enhanced session cards with cable type badges, charger specs, charging efficiency, new " +
                        "charger specs breakdown panel",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "Backend \u2014 New Telemetry Storage: New database migration (000016): `motor_snapshots`, `climate_snapshots`, " +
                        "`security_events` tables",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "Telemetry handler now stores motor/powertrain signals (torque, RPM, G-forces, pedal, brake, gear)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "Telemetry handler now stores climate/HVAC signals (temps, power, fan speed, defrost, heater)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "Telemetry handler now stores security signals (locks, sentry, doors, windows, HomeLink)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "New API endpoints: `GET /motor`, `GET /climate`, `GET /security` (list + latest)",
                ),
                ChangelogChange(ChangelogChangeType.Added, "New `GET /drives/{id}/positions` endpoint for time-windowed route data"),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "Energy Stats API enriched with distance, efficiency (Wh/km), and CO\u2082 saved data",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "Testing & Data Generation: Continuous MQTT load test with 8 simulated vehicles on real US routes",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "Historical data generator: 145K+ records spanning 10 years (2016-2026) across all tables",
                ),
                ChangelogChange(
                    ChangelogChangeType.Fixed,
                    "**Unit conversion** \u2014 Fixed 14 pages hardcoding metric units; now respects user's km/mi and " +
                        "\u00b0C/\u00b0F preferences",
                ),
                ChangelogChange(
                    ChangelogChangeType.Fixed,
                    "**Mobile layout** \u2014 Fixed last panel getting cut off on all screens (h-screen \u2192 h-dvh + safe-area " +
                        "padding)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Fixed,
                    "**Map tiles** \u2014 Fixed invisible CARTO dark map tiles (brightness filter too aggressive)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Fixed,
                    "**Tire pressure** \u2014 Fixed bar\u2192PSI conversion, composite latest from history for partial snapshots",
                ),
                ChangelogChange(
                    ChangelogChangeType.Fixed,
                    "**Tire pressure signals** \u2014 Added TpmsPressureFl/Fr/Rl/Rr signal name variant recognition",
                ),
                ChangelogChange(
                    ChangelogChangeType.Fixed,
                    "**Energy API** \u2014 Fixed response missing total_distance_km, avg_efficiency_wh_km, co2_saved_kg fields",
                ),
                ChangelogChange(
                    ChangelogChangeType.Fixed,
                    "**Drive routes** \u2014 Fixed empty route map on DriveDetail by adding time-windowed position query",
                ),
                ChangelogChange(
                    ChangelogChangeType.Fixed,
                    "**Drive addresses** \u2014 Show lat/lon coordinates instead of \"Unknown\" for start/destination",
                ),
                ChangelogChange(
                    ChangelogChangeType.Fixed,
                    "**Sidebar nav** \u2014 Fixed raw i18n keys showing for new pages (fallback to label when translation missing)",
                ),
            ),
    )

private val release050: ChangelogRelease =
    ChangelogRelease(
        version = "0.5.0",
        date = "2026-03-23",
        badge = ChangelogBadge.Stable,
        changes =
            listOf(
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Sleep backoff for asleep vehicles** \u2014 When a vehicle returns 408 (asleep), polling now backs off " +
                        "exponentially using `WORKER_SLEEP_POLL_MULT` (default 4\u00d7): 60s \u2192 120s \u2192 240s \u2192 10 min cap. " +
                        "Previously, asleep vehicles were polled every 15s with no backoff.",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**API Suspend Toggle** \u2014 New toggle on the Settings page to suspend ALL Tesla Fleet API calls. Useful " +
                        "when a vehicle is in service. Persisted in DB (`api_suspended` column on `settings` table, migration 000011). " +
                        "Token refresh continues during suspension so re-auth isn't needed. All API entry points are blocked: worker " +
                        "polling, CurrentState, SyncFromTesla, Wake, SendCommand.",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**API Usage Dashboard fix** \u2014 `APIUsageHandler` now queries `api_call_logs` table for real monthly " +
                        "request counts, skipped polls (408/504), and estimated cost vs Tesla's \$10/month credit. Previously returned " +
                        "hardcoded zeros.",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Single-route ingress** \u2014 All traffic now routes through a single Traefik IngressRoute (or standard " +
                        "Ingress) pointing to `teslasync-web` (Nginx). Nginx serves static files AND proxies `/api/`, `/.well-known/`, " +
                        "`/healthz`, `/readyz`, `/metrics` to `teslasync-api` over the internal Kubernetes cluster network. API traffic " +
                        "no longer traverses the ingress controller \u2014 only the initial page load does.",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Nginx reverse proxy** \u2014 `teslasync-web` now acts as both static file server and reverse proxy. The " +
                        "`config.apiEndpoint` Helm value configures the Nginx `proxy_pass` target (defaults to auto-derived " +
                        "`http://<release>-api:<port>`) and is injected into the frontend at runtime via Nginx `sub_filter` as " +
                        "`window.__TESLASYNC_API_BASE__`.",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Single-route ingress** \u2014 All traffic now routes through one ingress path (`/`) to `teslasync-web`. " +
                        "Nginx proxies API paths internally to `teslasync-api` over the cluster network. Removed the separate `/api` " +
                        "ingress path.",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Helm chart v0.5.0** \u2014 Service exposure: `service.type`, `service.nodePort`, `service.loadBalancerIP`, " +
                        "`service.externalTrafficPolicy`, `service.annotations` (same for `web.service.*`)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**New config fields** \u2014 `config.apiEndpoint` (configures Nginx proxy_pass target and frontend API base " +
                        "URL via `sub_filter`), `config.webEndpoint` (public URL for CORS)",
                ),
                ChangelogChange(ChangelogChangeType.Changed, "**`tesla.redirectUri`** remains explicit (public-facing, Tesla calls it)"),
                ChangelogChange(ChangelogChangeType.Changed, "**CHANGELOG** \u2014 Added 0.5.0 release notes with architecture changes"),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**README** \u2014 Updated architecture diagram to show single-route ingress and Nginx proxy layer, updated " +
                        "deployment section",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Helm README** \u2014 Updated architecture diagram, rewrote ingress configuration for single-route pattern, " +
                        "added API Routing section, updated `config.apiEndpoint` description",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Kubernetes deployment guide** \u2014 Updated with single-route ingress examples for both Traefik " +
                        "IngressRoute and standard Ingress",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Architecture docs** \u2014 Updated high-level overview diagram and added traffic flow explanation",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Configuration guide** \u2014 Added Kubernetes/Helm configuration section explaining `config.apiEndpoint` " +
                        "dual purpose",
                ),
                ChangelogChange(ChangelogChangeType.Changed, "**.env.example** \u2014 Added sleep backoff and API suspend comments"),
                ChangelogChange(
                    ChangelogChangeType.Fixed,
                    "**SPA routing fix** \u2014 Replaced Go `fileServer` catch-all with `r.NotFound()` SPA fallback. Go Dockerfile " +
                        "now includes a `web-builder` stage so the Go container bundles frontend assets. Router auto-detects static dir " +
                        "(`/web/dist` in Docker, `./web/dist` local).",
                ),
                ChangelogChange(
                    ChangelogChangeType.Fixed,
                    "**Traefik IngressRoute fix** \u2014 `PathPrefix('/api')` matched frontend routes `/api-logs` and `/api-keys`. " +
                        "Fixed to `PathPrefix('/api/')` (trailing slash).",
                ),
            ),
    )

private val release040: ChangelogRelease =
    ChangelogRelease(
        version = "0.4.0",
        date = "2026-03-23",
        badge = ChangelogBadge.Stable,
        changes =
            listOf(
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Developer Tools page** \u2014 25+ built-in utilities accessible from sidebar nav",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Tesla Fleet API tools** \u2014 Region detection, partner registration, API connectivity test, token " +
                        "inspector",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Public key management** \u2014 Generate ECDSA P-256 keypairs in-app, auto-serve at `.well-known` path, " +
                        "upload existing keys, fingerprint display",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Infrastructure diagnostics** \u2014 Database stats, migration status, MQTT test, env check, runtime info",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Client-side utilities** \u2014 VIN decoder, JWT decoder, timestamp converter, Base64, URL encoder, JSON " +
                        "formatter, UUID generator, SHA-256 hash, byte converter, color converter, cron parser, HTTP status reference, " +
                        "Tesla API endpoint reference, regex tester, Unix permission calculator",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Status UI** \u2014 Fleet Telemetry card in System Status page (enabled/disabled with details)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Signal display** \u2014 Shows supported signals, endpoint, protocol, host:port when enabled",
                ),
                ChangelogChange(ChangelogChangeType.Changed, "**Setup hints** \u2014 Displays configuration instructions when disabled"),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Fleet Telemetry config** \u2014 New `FleetTelemetryConfig` with `FLEET_TELEMETRY_ENABLED`, " +
                        "`FLEET_TELEMETRY_HOST`, `FLEET_TELEMETRY_PORT` env vars",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Source tagging** \u2014 API call logs now distinguish `tesla_api` vs `fleet_telemetry` sources",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Database migration** \u2014 Migration 000009 adds `source` column with index to `api_call_logs`",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Telemetry logging** \u2014 Incoming fleet telemetry ingests logged with `source: fleet_telemetry`",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**`TESLA_API_BASE_URL`** \u2014 Configurable Fleet API region (NA/EU/CN) via env var, docker-compose, and Helm",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Fleet Telemetry env vars** \u2014 `FLEET_TELEMETRY_ENABLED`, `FLEET_TELEMETRY_HOST`, `FLEET_TELEMETRY_PORT`",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**README** \u2014 Updated features, API endpoints, highlights for Developer Tools",
                ),
                ChangelogChange(ChangelogChangeType.Changed, "**CHANGELOG** \u2014 Added 0.4.0 release notes"),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**.env.example** \u2014 Added `TESLA_API_BASE_URL` and fleet telemetry env vars",
                ),
                ChangelogChange(ChangelogChangeType.Changed, "**Fleet Telemetry guide** \u2014 Updated with status UI documentation"),
            ),
    )

private val release030: ChangelogRelease =
    ChangelogRelease(
        version = "0.3.0",
        date = "2026-03-22",
        badge = ChangelogBadge.Stable,
        changes =
            listOf(
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Microservice split** \u2014 Dedicated notification worker container (`teslasync-notification-worker`)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Event-driven design** \u2014 Domain event bus via MQTT (`drive.started`, `charge.completed`, etc.)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Pod renaming** \u2014 Backend deployment renamed from `teslasync` to `teslasync-api` for clarity",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Redis caching layer** \u2014 Two-tier cache (in-memory L1 + Redis L2) with automatic fallback",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Notification scheduling** \u2014 One-time or cron-based recurring notifications",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Notification preferences** \u2014 Per-event-type enable/disable per channel",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Notification analytics** \u2014 Delivery rates, latency tracking, per-channel metrics",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Async delivery** \u2014 MQTT-backed queue with 3x retry and exponential backoff",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Metrics tracking** \u2014 Automatic delivery success/failure recording per channel/day",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Version endpoint** \u2014 `/api/v1/system/version` returns app version, chart version, Go version, OS/arch, " +
                        "uptime, goroutines",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Update checker** \u2014 `/api/v1/system/update-check` checks GitHub releases (cached 1hr)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Circuit breaker state** \u2014 Exposed in `/api/v1/system/status` with counts",
                ),
                ChangelogChange(ChangelogChangeType.Changed, "**API log retention** \u2014 Automatic cleanup of logs >30 days"),
                ChangelogChange(ChangelogChangeType.Changed, "**Notification log retention** \u2014 Automatic cleanup of logs >90 days"),
                ChangelogChange(ChangelogChangeType.Changed, "**Version badge** \u2014 Sidebar shows actual Helm chart version"),
                ChangelogChange(ChangelogChangeType.Changed, "**Update notification** \u2014 Banner when newer release is available"),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Circuit breaker UX** \u2014 Friendly \"Tesla API unavailable, auto-retry in Xs\" with countdown",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Settings page** \u2014 Shows live version info, Go version, encryption status",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**ErrorBoundary** \u2014 Enhanced to detect circuit breaker and network errors separately",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**3 Docker images** \u2014 api, web, notification-worker (all built and pushed in release workflow)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**GoReleaser** \u2014 Notification worker binary added for cross-platform builds",
                ),
                ChangelogChange(ChangelogChangeType.Changed, "**CI pipeline** \u2014 Both binaries built and tested"),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Architecture docs** \u2014 Updated package tree, event-driven diagrams, notification worker sequence",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Configuration docs** \u2014 Redis, encryption, CORS, system env vars documented",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Fleet Telemetry guide** \u2014 Expanded from 129 to 423 lines with MQTT integration, Home Assistant examples",
                ),
                ChangelogChange(ChangelogChangeType.Changed, "**README** \u2014 Updated highlights, service count, new API endpoints"),
                ChangelogChange(
                    ChangelogChangeType.Security,
                    "**AES-256-GCM encryption** \u2014 Encrypt Tesla tokens and sensitive data at rest (`ENCRYPTION_KEY`)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Security,
                    "**Command whitelist** \u2014 Only 21 known Tesla commands accepted, rejects unknown",
                ),
                ChangelogChange(
                    ChangelogChangeType.Security,
                    "**Request body size limit** \u2014 Global 1MB `MaxBytesReader` middleware prevents DoS",
                ),
                ChangelogChange(ChangelogChangeType.Security, "**CORS hardened** \u2014 Configurable origins via `CORS_ORIGINS` env var"),
                ChangelogChange(
                    ChangelogChangeType.Security,
                    "**Input validation** \u2014 Geofence coordinates, alert rule types/severity, settings values, import rows",
                ),
                ChangelogChange(
                    ChangelogChangeType.Security,
                    "**Per-route rate limiting** \u2014 Commands: 20/min, exports: 10/min, reads: 100/min",
                ),
                ChangelogChange(
                    ChangelogChangeType.Security,
                    "**Default credentials removed** \u2014 `.env.example` uses `changeme` " +
                        "placeholders", // parity:allow verbatim CHANGELOG.md release text
                ),
                ChangelogChange(
                    ChangelogChangeType.Security,
                    "**Nginx hardened** \u2014 Added HSTS, Permissions-Policy, proxy timeouts, body size limits",
                ),
            ),
    )

private val release010: ChangelogRelease =
    ChangelogRelease(
        version = "0.1.0",
        date = "2026-03-21",
        badge = ChangelogBadge.Stable,
        changes =
            listOf(
                ChangelogChange(ChangelogChangeType.Added, "**29 interactive dashboard pages** with glassmorphism UI"),
                ChangelogChange(ChangelogChangeType.Added, "**5 color themes** \u00d7 4 display modes (dark, light, OLED, midnight)"),
                ChangelogChange(ChangelogChangeType.Added, "**Real-time SSE streaming** with auto-reconnect and event buffering"),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**14 remote vehicle commands** (lock, unlock, climate, sentry, charge, frunk, trunk, horn, flash)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**Smart Insights Engine** \u2014 auto-generated recommendations from driving/charging data",
                ),
                ChangelogChange(ChangelogChangeType.Added, "**Drive Score** rating system (0-100 animated gauge)"),
                ChangelogChange(ChangelogChangeType.Added, "**16 Grafana dashboards** with verified SQL queries"),
                ChangelogChange(ChangelogChangeType.Added, "**Futuristic tire pressure visualization** with animated car SVG"),
                ChangelogChange(ChangelogChangeType.Added, "**Smart charging optimizer** with cost comparison by charger type"),
                ChangelogChange(ChangelogChangeType.Added, "**Monthly statistics tables** with inline spark bars"),
                ChangelogChange(ChangelogChangeType.Added, "**Charging cost analytics** \u2014 cost per kWh tracking, location comparison"),
                ChangelogChange(ChangelogChangeType.Added, "**State timeline bars** \u2014 Gantt-style vehicle state visualization"),
                ChangelogChange(ChangelogChangeType.Added, "**Software update timeline** \u2014 version progression chart"),
                ChangelogChange(ChangelogChangeType.Added, "**Projected range calculator** with weather/driving condition adjustments"),
                ChangelogChange(ChangelogChangeType.Added, "**Vehicle comparison page** \u2014 side-by-side metrics with radar chart"),
                ChangelogChange(ChangelogChangeType.Added, "**Total cost of ownership calculator** \u2014 EV vs gas comparison"),
                ChangelogChange(ChangelogChangeType.Added, "**Trip planner** with range estimation and charging stop calculation"),
                ChangelogChange(ChangelogChangeType.Added, "**PDF report generation** for drives and monthly summaries"),
                ChangelogChange(ChangelogChangeType.Added, "**Global search** across vehicles, drives, locations in command palette"),
                ChangelogChange(ChangelogChangeType.Added, "**Fleet efficiency leaderboard** with rankings"),
                ChangelogChange(ChangelogChangeType.Added, "**Onboarding wizard** \u2014 4-step first-time setup"),
                ChangelogChange(ChangelogChangeType.Added, "**API key management** with HMAC-SHA256 authentication"),
                ChangelogChange(ChangelogChangeType.Added, "**Inbound webhook API** for external system integration"),
                ChangelogChange(
                    ChangelogChangeType.Added,
                    "**7-channel notifications** (Discord, Slack, Telegram, Email, Webhook, ntfy, Pushover)",
                ),
                ChangelogChange(ChangelogChangeType.Added, "**12 configurable alert types** with quiet hours and digest mode"),
                ChangelogChange(ChangelogChangeType.Added, "**Data privacy controls** \u2014 anonymize locations, GDPR export"),
                ChangelogChange(ChangelogChangeType.Added, "**Unit preferences** \u2014 km/mi, \u00b0C/\u00b0F applied across all pages"),
                ChangelogChange(ChangelogChangeType.Changed, "**PostgreSQL 17** with native partitioning (replaced TimescaleDB)"),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Helm chart v0.3.0** \u2014 embedded/external services, IngressRoute, HPA, PDB",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**14 GitHub Actions workflows** \u2014 CI, Docker, security, quality, release",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Tesla Fleet API billing optimization** \u2014 adaptive polling (\$3/month vs \$192)",
                ),
                ChangelogChange(
                    ChangelogChangeType.Changed,
                    "**Docker Compose** \u2014 6 services (API, Web, PostgreSQL, Redis, MQTT, Grafana)",
                ),
                ChangelogChange(ChangelogChangeType.Changed, "**127 automated tests** (84 Go + 43 frontend)"),
                ChangelogChange(ChangelogChangeType.Changed, "**E2E test suite** with 25+ endpoint checks"),
                ChangelogChange(ChangelogChangeType.Changed, "**SBOM generation** + container image signing"),
                ChangelogChange(ChangelogChangeType.Changed, "**Dependabot** for Go, npm, Docker, Actions dependencies"),
                ChangelogChange(ChangelogChangeType.Changed, "**VitePress docs site** with Mermaid diagrams and automotive animations"),
                ChangelogChange(ChangelogChangeType.Changed, "**54-endpoint API reference** with JSON examples"),
                ChangelogChange(ChangelogChangeType.Changed, "**Complete database schema** documentation (21 tables)"),
                ChangelogChange(ChangelogChangeType.Changed, "**Technology stack** rationale"),
                ChangelogChange(ChangelogChangeType.Changed, "**Troubleshooting guide** + FAQ"),
                ChangelogChange(ChangelogChangeType.Changed, "**Roadmap** with 4 release tiers"),
                ChangelogChange(ChangelogChangeType.Security, "**CodeQL** SAST for Go + JavaScript"),
                ChangelogChange(ChangelogChangeType.Security, "**govulncheck** for Go CVE scanning"),
                ChangelogChange(ChangelogChangeType.Security, "**HMAC webhook signatures**"),
                ChangelogChange(ChangelogChangeType.Security, "**API key auth middleware**"),
                ChangelogChange(ChangelogChangeType.Security, "**Rate limiting** (100 req/min per IP)"),
                ChangelogChange(ChangelogChangeType.Security, "**Security headers** (HSTS, CSP, X-Frame-Options)"),
            ),
    )

/**
 * The embedded release catalog — the native counterpart of the web `@/generated/changelog`
 * `CHANGELOG` + `LATEST_VERSION` exports. Provided as the default [ChangelogSource] data so the
 * surface renders the real "what's new" history out of the box, exactly as the web modal does.
 */
object ChangelogCatalog {
    /** Highest released version — the web `LATEST_VERSION`. */
    const val LATEST_VERSION: String = "0.7.0"

    /** All releases, newest first — the web `CHANGELOG`. */
    val releases: List<ChangelogRelease> =
        listOf(
            release070,
            release060,
            release050,
            release040,
            release030,
            release010,
        )
}
