using System.Globalization;
using System.Text;
using System.Text.Json;

namespace TeslaSync.TokenGen;

/// <summary>
/// Pure, deterministic transform from the neutral <c>tokens.json</c> token set
/// into a Fluent/WinUI <c>Tokens.xaml</c> ResourceDictionary. Kept free of any
/// IO so it can be exercised by both the CLI and a round-trip check.
/// </summary>
internal static class TokenGenerator
{
    private const string Indent = "    ";

    private static readonly string[] TypographyRoles =
    [
        "display", "title", "section", "panel", "body", "bodySm", "caption", "label",
    ];

    private static readonly string[] SpacingKeys =
    [
        "none", "xs", "sm", "md", "lg", "xl", "2xl", "3xl", "4xl",
    ];

    private static readonly string[] RadiusKeys = ["sm", "md", "lg", "pill"];

    private static readonly (string Key, string Json)[] ColorRoles =
    [
        ("Bg", "bg"),
        ("Surface", "surface"),
        ("SurfaceGlass", "surfaceGlass"),
        ("TextPrimary", "textPrimary"),
        ("TextSecondary", "textSecondary"),
        ("TextMuted", "textMuted"),
        ("Accent", "accent"),
        ("Border", "border"),
    ];

    private static readonly (string Key, string Json)[] StatusRoles =
    [
        ("Success", "success"),
        ("Warning", "warning"),
        ("Danger", "danger"),
        ("Info", "info"),
    ];

    private static readonly (string XamlKey, string JsonTheme)[] ThemeMap =
    [
        ("Default", "dark"),
        ("Light", "light"),
        ("HighContrast", "highContrast"),
    ];

    private static readonly (string Key, string Json)[] ChartSeries =
    [
        ("Battery", "battery"),
        ("Energy", "energy"),
        ("Speed", "speed"),
        ("Regen", "regen"),
        ("Temperature", "temperature"),
        ("Power", "power"),
    ];

    public static string Generate(string tokensJson)
    {
        using JsonDocument doc = JsonDocument.Parse(tokensJson);
        JsonElement root = doc.RootElement;

        var sb = new StringBuilder();
        sb.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        sb.Append("<!--\n");
        sb.Append("    AUTO-GENERATED by apps/windows/TeslaSync.TokenGen from apps/design/tokens.json.\n");
        sb.Append("    Do not edit by hand; re-run the generator (P2/W1-0001, ADR-005/ADR-012).\n");
        sb.Append("    Fluent/WinUI design tokens: typography, spacing, radii, motion, elevation,\n");
        sb.Append("    materials (Mica/Acrylic), status colors and the brand chart palette.\n");
        sb.Append("-->\n");
        sb.Append("<ResourceDictionary\n");
        sb.Append("    xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\"\n");
        sb.Append("    xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\"\n");
        sb.Append("    xmlns:media=\"using:Microsoft.UI.Xaml.Media\">\n\n");

        AppendTypography(sb, root.GetProperty("typography"));
        AppendSpacing(sb, root.GetProperty("spacing"));
        AppendRadius(sb, root.GetProperty("radius"));
        AppendMotion(sb, root.GetProperty("motion"));
        AppendElevation(sb, root.GetProperty("elevation"));
        AppendChart(sb, root.GetProperty("chart"));

        AppendThemeDictionaries(sb, root.GetProperty("color"));

        sb.Append("</ResourceDictionary>\n");
        return sb.ToString();
    }

    private static void AppendTypography(StringBuilder sb, JsonElement typography)
    {
        JsonElement fontFamily = typography.GetProperty("fontFamily");
        JsonElement weights = typography.GetProperty("weights");

        sb.Append(Indent).Append("<!-- Typography -->\n");
        sb.Append(Indent)
          .Append("<FontFamily x:Key=\"TsTypeFontFamilySans\">")
          .Append(EscapeXml(fontFamily.GetProperty("sans").GetString() ?? "Segoe UI"))
          .Append("</FontFamily>\n");
        sb.Append(Indent)
          .Append("<FontFamily x:Key=\"TsTypeFontFamilyMono\">")
          .Append(EscapeXml(fontFamily.GetProperty("mono").GetString() ?? "Consolas"))
          .Append("</FontFamily>\n");

        foreach (string role in TypographyRoles)
        {
            JsonElement r = typography.GetProperty(role);
            string name = Pascal(role);
            AppendDouble(sb, $"TsType{name}FontSize", r.GetProperty("size").GetDouble());
            AppendDouble(sb, $"TsType{name}LineHeight", r.GetProperty("lineHeight").GetDouble());
            AppendDouble(sb, $"TsType{name}LetterSpacing", r.GetProperty("letterSpacing").GetDouble());

            string weightName = r.GetProperty("weight").GetString() ?? "regular";
            double weightValue = weights.GetProperty(weightName).GetDouble();
            AppendDouble(sb, $"TsType{name}FontWeight", weightValue);
        }

        foreach (JsonProperty w in weights.EnumerateObject())
        {
            AppendDouble(sb, $"TsTypeWeight{Pascal(w.Name)}", w.Value.GetDouble());
        }

        sb.Append('\n');
    }

    private static void AppendSpacing(StringBuilder sb, JsonElement spacing)
    {
        JsonElement scale = spacing.GetProperty("scale");
        sb.Append(Indent).Append("<!-- Spacing scale -->\n");
        foreach (string key in SpacingKeys)
        {
            AppendDouble(sb, $"TsSpace{Pascal(key)}", scale.GetProperty(key).GetDouble());
        }

        sb.Append('\n');
    }

    private static void AppendRadius(StringBuilder sb, JsonElement radius)
    {
        sb.Append(Indent).Append("<!-- Corner radii -->\n");
        foreach (string key in RadiusKeys)
        {
            double value = radius.GetProperty(key).GetDouble();
            sb.Append(Indent)
              .Append("<CornerRadius x:Key=\"TsRadius")
              .Append(Pascal(key))
              .Append("\">")
              .Append(Num(value))
              .Append("</CornerRadius>\n");
        }

        sb.Append('\n');
    }

    private static void AppendMotion(StringBuilder sb, JsonElement motion)
    {
        sb.Append(Indent).Append("<!-- Motion: durations and easing control points -->\n");
        foreach (JsonProperty d in motion.GetProperty("durations").EnumerateObject())
        {
            double ms = d.Value.GetDouble();
            sb.Append(Indent)
              .Append("<Duration x:Key=\"TsMotion")
              .Append(Pascal(d.Name))
              .Append("Duration\">")
              .Append(DurationString(ms))
              .Append("</Duration>\n");
        }

        foreach (JsonProperty e in motion.GetProperty("easing").EnumerateObject())
        {
            sb.Append(Indent)
              .Append("<x:String x:Key=\"TsMotion")
              .Append(Pascal(e.Name))
              .Append("Easing\">")
              .Append(EscapeXml(e.Value.GetString() ?? string.Empty))
              .Append("</x:String>\n");
        }

        sb.Append('\n');
    }

    private static void AppendElevation(StringBuilder sb, JsonElement elevation)
    {
        sb.Append(Indent).Append("<!-- Elevation levels and Fluent material mapping -->\n");
        JsonElement levels = elevation.GetProperty("levels");
        JsonElement material = elevation.GetProperty("material");

        foreach (JsonProperty level in levels.EnumerateObject())
        {
            string name = Pascal(level.Name);
            AppendDouble(sb, $"TsElevation{name}Z", level.Value.GetProperty("z").GetDouble());
            string fluent = material.GetProperty(level.Name).GetProperty("fluent").GetString() ?? "Solid";
            sb.Append(Indent)
              .Append("<x:String x:Key=\"TsElevation")
              .Append(name)
              .Append("Material\">")
              .Append(EscapeXml(fluent))
              .Append("</x:String>\n");
        }

        sb.Append(Indent).Append("<!-- Root/transient surface backdrops: Mica for the app root, Acrylic for overlays -->\n");
        sb.Append(Indent).Append("<x:String x:Key=\"TsMaterialRootBackdrop\">Mica</x:String>\n");
        sb.Append(Indent).Append("<x:String x:Key=\"TsMaterialOverlayBackdrop\">Acrylic</x:String>\n");
        sb.Append('\n');
    }

    private static void AppendChart(StringBuilder sb, JsonElement chart)
    {
        sb.Append(Indent).Append("<!-- Brand chart palette (theme-invariant, color-blind safe) -->\n");
        JsonElement categorical = chart.GetProperty("categorical");
        int index = 1;
        foreach (JsonElement c in categorical.EnumerateArray())
        {
            string key = $"TsChart{index:00}Brush";
            AppendBrush(sb, key, ConvertColor(c.GetString() ?? "#000000"));
            index++;
        }

        JsonElement series = chart.GetProperty("series");
        foreach ((string key, string json) in ChartSeries)
        {
            AppendBrush(sb, $"TsChart{key}Brush", ConvertColor(series.GetProperty(json).GetString() ?? "#000000"));
        }

        sb.Append('\n');
    }

    private static void AppendThemeDictionaries(StringBuilder sb, JsonElement color)
    {
        sb.Append(Indent).Append("<ResourceDictionary.ThemeDictionaries>\n");

        foreach ((string xamlKey, string jsonTheme) in ThemeMap)
        {
            JsonElement theme = color.GetProperty(jsonTheme);
            string i2 = Indent + Indent;
            sb.Append(i2)
              .Append("<!-- ")
              .Append(Pascal(jsonTheme))
              .Append(" theme -->\n");
            sb.Append(i2).Append("<ResourceDictionary x:Key=\"").Append(xamlKey).Append("\">\n");

            string i3 = i2 + Indent;
            foreach ((string key, string json) in ColorRoles)
            {
                string col = ConvertColor(theme.GetProperty(json).GetString() ?? "#000000");
                AppendColor(sb, i3, $"TsColor{key}Color", col);
                AppendBrush(sb, i3, $"TsColor{key}Brush", col);
            }

            JsonElement status = theme.GetProperty("status");
            foreach ((string key, string json) in StatusRoles)
            {
                string col = ConvertColor(status.GetProperty(json).GetString() ?? "#000000");
                AppendColor(sb, i3, $"TsColor{key}Color", col);
                AppendBrush(sb, i3, $"TsColor{key}Brush", col);
            }

            string surface = ConvertColor(theme.GetProperty("surface").GetString() ?? "#000000");
            sb.Append(i3)
              .Append("<media:AcrylicBrush x:Key=\"TsMaterialOverlayBrush\" TintColor=\"")
              .Append(surface)
              .Append("\" TintOpacity=\"0.6\" FallbackColor=\"")
              .Append(surface)
              .Append("\" />\n");
            sb.Append(i3)
              .Append("<media:AcrylicBrush x:Key=\"TsMaterialModalBrush\" TintColor=\"")
              .Append(surface)
              .Append("\" TintOpacity=\"0.8\" FallbackColor=\"")
              .Append(surface)
              .Append("\" />\n");

            sb.Append(i2).Append("</ResourceDictionary>\n");
        }

        sb.Append(Indent).Append("</ResourceDictionary.ThemeDictionaries>\n");
    }

    private static void AppendDouble(StringBuilder sb, string key, double value)
    {
        sb.Append(Indent)
          .Append("<x:Double x:Key=\"")
          .Append(key)
          .Append("\">")
          .Append(Num(value))
          .Append("</x:Double>\n");
    }

    private static void AppendBrush(StringBuilder sb, string key, string color)
        => AppendBrush(sb, Indent, key, color);

    private static void AppendBrush(StringBuilder sb, string indent, string key, string color)
    {
        sb.Append(indent)
          .Append("<SolidColorBrush x:Key=\"")
          .Append(key)
          .Append("\" Color=\"")
          .Append(color)
          .Append("\" />\n");
    }

    private static void AppendColor(StringBuilder sb, string indent, string key, string color)
    {
        sb.Append(indent)
          .Append("<Color x:Key=\"")
          .Append(key)
          .Append("\">")
          .Append(color)
          .Append("</Color>\n");
    }

    private static string Num(double value)
        => value == Math.Floor(value)
            ? ((long)value).ToString(CultureInfo.InvariantCulture)
            : value.ToString("0.###", CultureInfo.InvariantCulture);

    private static string DurationString(double milliseconds)
    {
        var ts = TimeSpan.FromMilliseconds(milliseconds);
        return string.Create(
            CultureInfo.InvariantCulture,
            $"0:0:{ts.TotalSeconds.ToString("0.###", CultureInfo.InvariantCulture)}");
    }

    /// <summary>
    /// Normalizes a neutral token color (<c>#rrggbb</c>, <c>rgb(...)</c> or
    /// <c>rgba(...)</c>) into a WinUI <c>#AARRGGBB</c>/<c>#RRGGBB</c> literal.
    /// </summary>
    internal static string ConvertColor(string raw)
    {
        string value = raw.Trim();
        if (value.StartsWith('#'))
        {
            return value.ToUpperInvariant();
        }

        if (value.StartsWith("rgba(", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("rgb(", StringComparison.OrdinalIgnoreCase))
        {
            int open = value.IndexOf('(');
            int close = value.IndexOf(')');
            string inner = value[(open + 1)..close];
            string[] parts = inner.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);

            byte r = ParseByte(parts[0]);
            byte g = ParseByte(parts[1]);
            byte b = ParseByte(parts[2]);
            byte a = parts.Length > 3
                ? (byte)Math.Round(double.Parse(parts[3], CultureInfo.InvariantCulture) * 255.0)
                : (byte)255;

            return string.Create(CultureInfo.InvariantCulture, $"#{a:X2}{r:X2}{g:X2}{b:X2}");
        }

        throw new FormatException($"Unsupported color literal: '{raw}'");
    }

    private static byte ParseByte(string value)
        => (byte)Math.Clamp(int.Parse(value, CultureInfo.InvariantCulture), 0, 255);

    private static string Pascal(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }

        return char.ToUpperInvariant(value[0]) + value[1..];
    }

    private static string EscapeXml(string value)
        => value
            .Replace("&", "&amp;", StringComparison.Ordinal)
            .Replace("<", "&lt;", StringComparison.Ordinal)
            .Replace(">", "&gt;", StringComparison.Ordinal);
}
