// Package slo serves the live SLO board at
// GET /api/v1/admin/observability/slo (ADR-009 exception).
//
// The handler returns one row per SLO declared in slo/catalog.yaml with
// the current live SLI ratio (good/valid over the SLO window), the error
// budget remaining (0..1), and per-tier burn-rate evaluation for both
// the FastBurn (1h+5m, 14.4x) and SlowBurn (6h+30m, 6x)
// multi-window-multi-burn-rate tiers — same windows as the alerts
// generated by cmd/slogen.
//
// When PROM_BASE_URL is unset the endpoint still returns the catalog
// metadata so the SPA can render SLO names + targets with a
// "Prometheus not configured" banner instead of a blank panel.
//
// Layer: handler
package slo
