//
//  LayoutBreadcrumbs.Routes.swift
//  TeslaSync — P4 shared surface · 0170 · LayoutBreadcrumbs (Apple)
//
//  The route catalog — the native peer of the web `ROUTE_META` map (lib/routeMeta.ts) that
//  `useBreadcrumbs` walks to compose the trail. The web `ROUTE_META` is derived from the autogenerated
//  `ROUTE_REGISTRY` (lib/routeRegistry.ts) — every registered frontend route gets a baseline breadcrumb
//  entry (its i18n key + English fallback label) — merged with the explicit `PARENT_OVERRIDES` that opt a
//  nested / detail route into a parent chain. This file ports both verbatim: all 113 registered routes in
//  the same declaration order (so "the first registered pattern that matches" resolves identically to the
//  web `Object.keys(ROUTE_META)` iteration) and the 12 parent links that make a route render a >= 2-item
//  trail. Everything else is a single-item entry that ``BreadcrumbOverridesTrailView`` self-suppresses,
//  exactly like the web top-level pages.
//
//  The entries are DATA (kept in sync with the generated web registry), not i18n keys themselves — the
//  `i18nKey` column is resolved at the display boundary through the app catalog with the English label as
//  the fallback (web `t(meta.i18nKey, meta.defaultLabel)`), wired by ``LayoutBreadcrumbsStrings/routeLabel``.
//

import Foundation

// MARK: - LayoutBreadcrumbsRouteCatalog (web ROUTE_META = ROUTE_REGISTRY + PARENT_OVERRIDES)

/// The breadcrumb route catalog — the native peer of `ROUTE_META`. ``table`` is the ordered, indexed
/// ``BreadcrumbOverridesRouteTable`` the projection matches against; ``entries`` is the flat list (every
/// registered route, in declaration order). The 12 `parent:` links are the verbatim port of the web
/// `PARENT_OVERRIDES` — they are the only routes that compose a rendered (multi-item) breadcrumb.
public enum LayoutBreadcrumbsRouteCatalog {
    /// Every registered route, in the web `ROUTE_REGISTRY` declaration order.
    public static let entries: [BreadcrumbOverridesRouteMeta] = [
        route("/", "routes.dashboard", "Dashboard"),
        route("/admin/feedback", "routes.feedbackQueue", "Feedback Queue"),
        route("/admin/telemetry/coverage", "routes.fleetTelemetryCoverage", "Fleet Telemetry Coverage"),
        route("/alert-rules", "routes.legacyAlertRulesRedirect", "Legacy Alert Rules Redirect"),
        route("/alert-studio", "routes.legacyAlertStudioRedirect", "Legacy Alert Studio Redirect"),
        route("/alerts", "routes.legacyAlertsRedirect", "Legacy Alerts Redirect"),
        route("/analytics", "routes.analytics", "Analytics"),
        route("/anomaly-detection", "routes.anomalyDashboard", "Anomaly Dashboard"),
        route("/api-keys", "routes.aPIKeys", "API Keys"),
        route("/api-logs", "routes.apiLogs", "Api Logs"),
        route("/api-playground", "routes.apiPlayground", "Api Playground"),
        route("/automations", "routes.automations", "Automations"),
        route("/automations/:id/edit", "routes.automationBuilder", "Automation Builder", parent: "/automations"),
        route("/automations/list", "routes.automationList", "Automation List"),
        route("/automations/new", "routes.automationBuilder", "Automation Builder", parent: "/automations"),
        route("/backup", "routes.backupRestore", "Backup Restore"),
        route("/battery", "routes.batteryHealth", "Battery Health"),
        route("/battery-cells", "routes.batteryCells", "Battery Cells"),
        route("/battery-degradation", "routes.batteryDegradation", "Battery Degradation"),
        route("/charging", "routes.charging", "Charging"),
        route("/charging-curve", "routes.chargingCurve", "Charging Curve"),
        route("/charging-heatmap", "routes.chargingHeatmap", "Charging Heatmap"),
        route("/charging/:id", "routes.chargeDetail", "Charge Detail", parent: "/charging"),
        route("/chatbot", "routes.chatbot", "Chatbot"),
        route("/climate-control", "routes.climateControl", "Climate Control"),
        route("/command-history", "routes.commandHistory", "Command History"),
        route("/commands", "routes.commands", "Commands"),
        route("/cost-analysis", "routes.costAnalysis", "Cost Analysis"),
        route("/data-export", "routes.dataExport", "Data Export"),
        route("/data-repair", "routes.dataRepair", "Data Repair"),
        route("/db-health", "routes.dBHealthDashboard", "DB Health Dashboard"),
        route("/dev-tools", "routes.devTools", "Dev Tools"),
        route("/digital-twin", "routes.digitalTwin", "Digital Twin"),
        route("/drive-score", "routes.driveScore", "Drive Score"),
        route("/drives", "routes.drives", "Drives"),
        route("/drives/:id", "routes.driveDetail", "Drive Detail", parent: "/drives"),
        route("/drives/:id/replay", "routes.tripReplay", "Trip Replay", parent: "/drives/:id"),
        route("/drivetrain-health", "routes.drivetrainHealth", "Drivetrain Health"),
        route("/driving-dynamics", "routes.drivingDynamics", "Driving Dynamics"),
        route("/efficiency", "routes.efficiency", "Efficiency"),
        route("/energy", "routes.energy", "Energy"),
        route("/energy-flow", "routes.energyFlow", "Energy Flow"),
        route("/energy-products", "routes.energyProducts", "Energy Products"),
        route("/exports", "routes.exports", "Exports"),
        route("/fleet-api", "routes.fleetAPI", "Fleet API"),
        route("/geofences", "routes.geofences", "Geofences"),
        route("/glance", "routes.glance", "Glance"),
        route("/guard-mode", "routes.guardMode", "Guard Mode"),
        route("/lifetime-stats", "routes.lifetimeStats", "Lifetime Stats"),
        route("/live", "routes.liveMap", "Live Map"),
        route("/live-monitor", "routes.liveSignalMonitor", "Live Signal Monitor"),
        route("/locations", "routes.locations", "Locations"),
        route("/maintenance", "routes.maintenance", "Maintenance"),
        route("/me/activity", "routes.myActivity", "My Activity", parent: "/"),
        route("/media-player", "routes.mediaPlayer", "Media Player"),
        route("/mileage", "routes.mileage", "Mileage"),
        route("/mqtt-inspector", "routes.mQTTInspector", "MQTT Inspector"),
        route("/navigation", "routes.navigationRoute", "Navigation Route"),
        route("/notifications", "routes.legacyNotificationsRedirect", "Legacy Notifications Redirect"),
        route("/notifications/alerts", "routes.notificationsAlerts", "Notifications Alerts"),
        route(
            "/notifications/archived",
            "routes.notificationsArchived",
            "Notifications Archived",
            parent: "/notifications/inbox"
        ),
        route("/notifications/audit", "routes.notificationsAudit", "Audit Log"),
        route("/notifications/browser", "routes.notificationsBrowser", "Notifications Browser"),
        route("/notifications/channels", "routes.notificationsChannels", "Notifications Channels"),
        route("/notifications/inbox", "routes.notificationsInbox", "Notifications Inbox"),
        route("/notifications/quiet-hours", "routes.notificationsQuietHours", "Notifications Quiet Hours"),
        route("/notifications/rules", "routes.notificationsRules", "Notifications Rules"),
        route(
            "/notifications/studio",
            "routes.notificationsStudio",
            "Notifications Studio",
            parent: "/notifications/inbox"
        ),
        route("/notifications/webhooks", "routes.notificationsWebhooks", "Notifications Webhooks"),
        route("/onboarding", "routes.onboarding", "Onboarding"),
        route("/period-compare", "routes.periodCompare", "Period Compare"),
        route("/power-flow", "routes.powerFlowDashboard", "Power Flow Dashboard"),
        route("/powershare", "routes.powershare", "Powershare"),
        route("/projected-range", "routes.projectedRange", "Projected Range"),
        route("/quick-stats", "routes.quickStats", "Quick Stats"),
        route("/redis-signals", "routes.redisSignalViewer", "Redis Signal Viewer"),
        route("/regen-efficiency", "routes.regenEfficiency", "Regen Efficiency"),
        route("/roadmap", "routes.roadmap", "Roadmap"),
        route("/route-efficiency", "routes.routeEfficiency", "Route Efficiency"),
        route("/s/:token", "routes.sharedDrive", "Shared Drive"),
        route("/safety-settings", "routes.safetySettings", "Safety Settings"),
        route("/search", "routes.search", "Search"),
        route("/security-access", "routes.securityAccess", "Security Access"),
        route("/settings", "routes.settings", "Settings"),
        route("/signal-diff", "routes.signalDiff", "Signal Diff"),
        route("/signal-explorer", "routes.signalExplorer", "Signal Explorer"),
        route("/signal-gaps", "routes.signalGapDetector", "Signal Gap Detector"),
        route("/signal-log", "routes.signalLogViewer", "Signal Log Viewer"),
        route("/sleep-efficiency", "routes.sleepEfficiency", "Sleep Efficiency"),
        route("/smart-charge", "routes.smartCharge", "Smart Charge"),
        route("/software-updates", "routes.softwareUpdates", "Software Updates"),
        route("/speed-profile", "routes.speedProfile", "Speed Profile"),
        route("/state-debugger", "routes.stateMachineDebugger", "State Machine Debugger"),
        route("/statistics", "routes.statistics", "Statistics"),
        route("/system-status", "routes.systemStatus", "System Status"),
        route("/tco", "routes.trueCostOwnership", "True Cost Ownership"),
        route("/temperature-impact", "routes.temperatureImpact", "Temperature Impact"),
        route("/tesla-account", "routes.teslaAccount", "Tesla Account"),
        route("/tesla-charging-history", "routes.teslaChargingHistory", "Tesla Charging History"),
        route("/tesla-charging-sessions", "routes.teslaChargingSessions", "Tesla Charging Sessions"),
        route("/timeline", "routes.timeline", "Timeline"),
        route("/tire-pressure", "routes.tirePressure", "Tire Pressure"),
        route("/trip-planner", "routes.tripPlanner", "Trip Planner"),
        route("/trips", "routes.trips", "Trips"),
        route("/trips/:id", "routes.tripDetail", "Trip Detail", parent: "/trips"),
        route("/vampire-drain", "routes.vampireDrain", "Vampire Drain"),
        route("/vehicle-comparison", "routes.fleetCompare", "Fleet Compare"),
        route("/vehicles", "routes.vehicles", "Vehicles"),
        route("/vehicles/:id", "routes.vehicleDetail", "Vehicle Detail", parent: "/vehicles"),
        route("/vehicles/:id/access", "routes.vehicleAccess", "Vehicle Access", parent: "/vehicles/:id"),
        route("/watch", "routes.watchFace", "Watch Face"),
        route("/weekly-digest", "routes.weeklyDigest", "Weekly Digest"),
        route("/year-review/:year", "routes.yearReview", "Year Review", parent: "/analytics")
    ]

    /// The ordered, indexed route table the projection matches against — web `ROUTE_META`.
    public static let table = BreadcrumbOverridesRouteTable(entries)

    /// Compact factory keeping each catalog row on one line within the line-length budget — `pattern`,
    /// `i18nKey`, English `defaultLabel`, and the optional `parent` pattern (web `PARENT_OVERRIDES`).
    private static func route(
        _ pattern: String,
        _ i18nKey: String,
        _ defaultLabel: String,
        parent: String? = nil
    ) -> BreadcrumbOverridesRouteMeta {
        BreadcrumbOverridesRouteMeta(
            pattern: pattern,
            i18nKey: i18nKey,
            defaultLabel: defaultLabel,
            parent: parent
        )
    }
}
