package trip

import (
	"context"
	"net/http"
	"strconv"
	"time"

	"github.com/rs/zerolog/log"

	"github.com/ev-dev-labs/teslasync/internal/api/apiparams"
	"github.com/ev-dev-labs/teslasync/internal/api/httpx"
	"github.com/ev-dev-labs/teslasync/internal/database"
	tripdb "github.com/ev-dev-labs/teslasync/internal/database/trip"
)

// tripRepository is the narrow port the handler depends on. Declared at the
// call site so handler tests can inject an in-memory fake without touching
// Postgres. *tripdb.TripRepo satisfies this interface.
type tripRepository interface {
	GetAll(ctx context.Context, limit, offset int, startTime, endTime time.Time) ([]*tripdb.TripSummary, error)
	GetByVehicle(ctx context.Context, vehicleID int64, limit, offset int, startTime, endTime time.Time) ([]*tripdb.TripSummary, error)
}

// Compile-time guard that the production repo still satisfies the port. If a
// method signature drifts this fails at build time rather than at runtime.
var _ tripRepository = (*tripdb.TripRepo)(nil)

// Handler serves GET /trips.
type Handler struct {
	repo tripRepository
}

// NewHandler wires the production repo. Panics on a nil db (fail-fast at
// startup) so a misconfigured router crashes before serving traffic.
func NewHandler(db *database.DB) *Handler {
	if db == nil {
		panic("trip: NewHandler requires non-nil db")
	}
	return newHandler(tripdb.NewTripRepo(db))
}

// newHandler injects an arbitrary tripRepository. Kept unexported so the public
// surface stays db-based while handler tests can supply a fake.
func newHandler(repo tripRepository) *Handler {
	if repo == nil {
		panic("trip: newHandler requires non-nil repo")
	}
	return &Handler{repo: repo}
}

type tripSummaryResponse struct {
	ID             int64      `json:"id"`
	VehicleID      int64      `json:"vehicle_id"`
	Name           *string    `json:"name"`
	StartedAt      time.Time  `json:"started_at"`
	EndedAt        *time.Time `json:"ended_at"`
	StartDate      time.Time  `json:"start_date"`
	EndDate        *time.Time `json:"end_date"`
	CreatedByUser  *int64     `json:"created_by_user,omitempty"`
	AutoGenerated  bool       `json:"auto_generated"`
	Notes          *string    `json:"notes,omitempty"`
	TotalDistanceM float64    `json:"total_distance_m"`
	TotalEnergyWh  float64    `json:"total_energy_wh"`
	TotalDurationS int64      `json:"total_duration_s"`
	TotalCost      float64    `json:"total_cost"`
	DriveCount     int64      `json:"drive_count"`
	ChargeCount    int64      `json:"charge_count"`
	CreatedAt      time.Time  `json:"created_at"`
}

func tripSummaryDTO(in *tripdb.TripSummary) tripSummaryResponse {
	var name *string
	if in.Trip.Name != "" {
		v := in.Trip.Name
		name = &v
	}
	return tripSummaryResponse{
		ID:             in.Trip.ID,
		VehicleID:      in.Trip.VehicleID,
		Name:           name,
		StartedAt:      in.Trip.StartedAt,
		EndedAt:        in.Trip.EndedAt,
		StartDate:      in.Trip.StartedAt,
		EndDate:        in.Trip.EndedAt,
		CreatedByUser:  in.Trip.CreatedByUser,
		AutoGenerated:  in.Trip.AutoGenerated,
		Notes:          in.Trip.Notes,
		TotalDistanceM: in.TotalDistanceM,
		TotalEnergyWh:  in.TotalEnergyWh,
		TotalDurationS: in.TotalDurationS,
		TotalCost:      in.TotalCost,
		DriveCount:     in.DriveCount,
		ChargeCount:    in.ChargeCount,
		CreatedAt:      in.Trip.StartedAt,
	}
}

func tripSummaryDTOs(in []*tripdb.TripSummary) []tripSummaryResponse {
	out := make([]tripSummaryResponse, 0, len(in))
	for _, t := range in {
		out = append(out, tripSummaryDTO(t))
	}
	return out
}

func (h *Handler) List(w http.ResponseWriter, r *http.Request) {
	limit, offset := apiparams.Pagination(r)
	startTime, endTime := apiparams.ParseDateRange(r)
	vehicleIDStr := r.URL.Query().Get("vehicle_id")

	if vehicleIDStr != "" {
		vehicleID, err := strconv.ParseInt(vehicleIDStr, 10, 64)
		if err != nil || vehicleID <= 0 {
			httpx.WriteError(w, http.StatusBadRequest, "invalid vehicle_id")
			return
		}
		trips, err := h.repo.GetByVehicle(r.Context(), vehicleID, limit, offset, startTime, endTime)
		if err != nil {
			log.Error().Err(err).
				Int64("vehicle_id", vehicleID).
				Int("limit", limit).
				Int("offset", offset).
				Msg("failed to get trips by vehicle")
			httpx.WriteError(w, http.StatusInternalServerError, "failed to get trips")
			return
		}
		httpx.WriteJSON(w, http.StatusOK, tripSummaryDTOs(trips))
		return
	}

	trips, err := h.repo.GetAll(r.Context(), limit, offset, startTime, endTime)
	if err != nil {
		log.Error().Err(err).
			Int("limit", limit).
			Int("offset", offset).
			Msg("failed to get trips")
		httpx.WriteError(w, http.StatusInternalServerError, "failed to get trips")
		return
	}
	httpx.WriteJSON(w, http.StatusOK, tripSummaryDTOs(trips))
}
