package trip

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	tripdb "github.com/ev-dev-labs/teslasync/internal/database/trip"
	"github.com/ev-dev-labs/teslasync/internal/models"
)

// fakeTripRepo is an in-memory tripRepository double. It records the arguments
// each method was called with so the handler tests can assert routing (GetAll
// vs GetByVehicle) and parameter propagation (pagination + date range) without
// touching Postgres.
type fakeTripRepo struct {
	allCalled       int
	byVehicleCalled int

	gotVehicleID int64
	gotLimit     int
	gotOffset    int
	gotStart     time.Time
	gotEnd       time.Time

	out []*tripdb.TripSummary
	err error
}

func (f *fakeTripRepo) GetAll(_ context.Context, limit, offset int, startTime, endTime time.Time) ([]*tripdb.TripSummary, error) {
	f.allCalled++
	f.gotLimit, f.gotOffset, f.gotStart, f.gotEnd = limit, offset, startTime, endTime
	return f.out, f.err
}

func (f *fakeTripRepo) GetByVehicle(_ context.Context, vehicleID int64, limit, offset int, startTime, endTime time.Time) ([]*tripdb.TripSummary, error) {
	f.byVehicleCalled++
	f.gotVehicleID = vehicleID
	f.gotLimit, f.gotOffset, f.gotStart, f.gotEnd = limit, offset, startTime, endTime
	return f.out, f.err
}

func ptrString(s string) *string     { return &s }
func ptrTime(t time.Time) *time.Time { return &t }
func ptrInt64(i int64) *int64        { return &i }

func doList(h *Handler, target string) *httptest.ResponseRecorder {
	rec := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, target, nil)
	h.List(rec, req)
	return rec
}

// sampleSummary is a fully-populated fixture used across the DTO assertions.
func sampleSummary(start, end time.Time) *tripdb.TripSummary {
	return &tripdb.TripSummary{
		Trip: models.Trip{
			ID:            11,
			VehicleID:     7,
			Name:          "May 2026 Summary",
			StartedAt:     start,
			EndedAt:       &end,
			CreatedByUser: ptrInt64(3),
			AutoGenerated: true,
			Notes:         ptrString("road trip"),
		},
		TotalDistanceM: 123456.0,
		TotalEnergyWh:  45000.0,
		TotalDurationS: 7200,
		DriveCount:     4,
		ChargeCount:    2,
		TotalCost:      12.34,
	}
}

// ---- routing: GetAll vs GetByVehicle -------------------------------------

func TestHandler_List_GetAll_NoVehicleFilter(t *testing.T) {
	t.Parallel()

	start := time.Date(2026, 5, 1, 8, 0, 0, 0, time.UTC)
	end := time.Date(2026, 5, 31, 18, 0, 0, 0, time.UTC)
	fake := &fakeTripRepo{out: []*tripdb.TripSummary{sampleSummary(start, end)}}
	h := newHandler(fake)

	rec := doList(h, "/trips")

	if rec.Code != http.StatusOK {
		t.Fatalf("status: got %d, want 200. body=%s", rec.Code, rec.Body.String())
	}
	if fake.allCalled != 1 {
		t.Errorf("GetAll called %d times, want 1", fake.allCalled)
	}
	if fake.byVehicleCalled != 0 {
		t.Errorf("GetByVehicle must not be called without vehicle_id; called=%d", fake.byVehicleCalled)
	}
	if ct := rec.Header().Get("Content-Type"); ct != "application/json; charset=utf-8" {
		t.Errorf("content-type: got %q", ct)
	}

	var resp []tripSummaryResponse
	if err := json.Unmarshal(rec.Body.Bytes(), &resp); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if len(resp) != 1 {
		t.Fatalf("expected 1 trip, got %d", len(resp))
	}
}

func TestHandler_List_GetByVehicle_Filter(t *testing.T) {
	t.Parallel()

	fake := &fakeTripRepo{out: nil}
	h := newHandler(fake)

	rec := doList(h, "/trips?vehicle_id=7")

	if rec.Code != http.StatusOK {
		t.Fatalf("status: got %d, want 200. body=%s", rec.Code, rec.Body.String())
	}
	if fake.byVehicleCalled != 1 {
		t.Errorf("GetByVehicle called %d times, want 1", fake.byVehicleCalled)
	}
	if fake.allCalled != 0 {
		t.Errorf("GetAll must not be called when vehicle_id present; called=%d", fake.allCalled)
	}
	if fake.gotVehicleID != 7 {
		t.Errorf("GetByVehicle vehicleID: got %d, want 7", fake.gotVehicleID)
	}
}

// ---- pagination + date-range propagation ---------------------------------

func TestHandler_List_ParamPropagation(t *testing.T) {
	t.Parallel()

	// end is sent as an exclusive next-midnight instant; ParseDateRange
	// subtracts 1µs so a BETWEEN filter stays inclusive.
	startInstant := time.Date(2026, 5, 1, 0, 0, 0, 0, time.UTC)
	endInstant := time.Date(2026, 5, 10, 0, 0, 0, 0, time.UTC)
	wantEnd := endInstant.Add(-time.Microsecond)

	cases := []struct {
		name       string
		target     string
		wantAll    bool // expect GetAll (true) or GetByVehicle (false)
		wantVeh    int64
		wantLimit  int
		wantOffset int
	}{
		{
			name:       "get_all_with_paging_and_range",
			target:     "/trips?limit=25&offset=5&start=2026-05-01T00:00:00Z&end=2026-05-10T00:00:00Z",
			wantAll:    true,
			wantLimit:  25,
			wantOffset: 5,
		},
		{
			name:       "get_by_vehicle_with_paging_and_range",
			target:     "/trips?vehicle_id=42&limit=10&offset=3&start=2026-05-01T00:00:00Z&end=2026-05-10T00:00:00Z",
			wantAll:    false,
			wantVeh:    42,
			wantLimit:  10,
			wantOffset: 3,
		},
		{
			name:       "defaults_when_paging_absent",
			target:     "/trips",
			wantAll:    true,
			wantLimit:  50, // apiparams.Pagination default
			wantOffset: 0,
		},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			fake := &fakeTripRepo{}
			h := newHandler(fake)

			rec := doList(h, tc.target)
			if rec.Code != http.StatusOK {
				t.Fatalf("status: got %d, want 200. body=%s", rec.Code, rec.Body.String())
			}
			if fake.gotLimit != tc.wantLimit {
				t.Errorf("limit: got %d, want %d", fake.gotLimit, tc.wantLimit)
			}
			if fake.gotOffset != tc.wantOffset {
				t.Errorf("offset: got %d, want %d", fake.gotOffset, tc.wantOffset)
			}
			if tc.wantAll {
				if fake.allCalled != 1 || fake.byVehicleCalled != 0 {
					t.Fatalf("routing: allCalled=%d byVehicleCalled=%d, want 1/0", fake.allCalled, fake.byVehicleCalled)
				}
			} else {
				if fake.byVehicleCalled != 1 || fake.allCalled != 0 {
					t.Fatalf("routing: byVehicleCalled=%d allCalled=%d, want 1/0", fake.byVehicleCalled, fake.allCalled)
				}
				if fake.gotVehicleID != tc.wantVeh {
					t.Errorf("vehicleID: got %d, want %d", fake.gotVehicleID, tc.wantVeh)
				}
			}

			// Range params only present in the first two cases.
			if strings.Contains(tc.target, "start=") {
				if !fake.gotStart.Equal(startInstant) {
					t.Errorf("start: got %v, want %v", fake.gotStart, startInstant)
				}
				if !fake.gotEnd.Equal(wantEnd) {
					t.Errorf("end: got %v, want %v (exclusive→inclusive)", fake.gotEnd, wantEnd)
				}
			} else if !fake.gotStart.IsZero() || !fake.gotEnd.IsZero() {
				t.Errorf("range must be zero when unspecified; got start=%v end=%v", fake.gotStart, fake.gotEnd)
			}
		})
	}
}

// ---- empty / nil result → JSON [] ----------------------------------------

func TestHandler_List_EmptyResultSerialisesAsArray(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name string
		out  []*tripdb.TripSummary
	}{
		{"nil_slice", nil},
		{"empty_slice", []*tripdb.TripSummary{}},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			fake := &fakeTripRepo{out: tc.out}
			h := newHandler(fake)

			rec := doList(h, "/trips")
			if rec.Code != http.StatusOK {
				t.Fatalf("status: got %d, want 200", rec.Code)
			}
			body := strings.TrimSpace(rec.Body.String())
			if body != "[]" {
				t.Errorf("empty result must serialise as [] not null; got %q", body)
			}
		})
	}
}

// ---- repo error paths → 500 ----------------------------------------------

func TestHandler_List_RepoError(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name   string
		target string
	}{
		{"get_all_error", "/trips"},
		{"get_by_vehicle_error", "/trips?vehicle_id=9"},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			fake := &fakeTripRepo{err: errors.New("db exploded")}
			h := newHandler(fake)

			rec := doList(h, tc.target)
			if rec.Code != http.StatusInternalServerError {
				t.Fatalf("status: got %d, want 500. body=%s", rec.Code, rec.Body.String())
			}
			var body map[string]string
			if err := json.Unmarshal(rec.Body.Bytes(), &body); err != nil {
				t.Fatalf("decode error body: %v", err)
			}
			if body["error"] != "failed to get trips" {
				t.Errorf("error message: got %q, want 'failed to get trips'", body["error"])
			}
			if body["code"] != "INTERNAL_ERROR" {
				t.Errorf("error code: got %q, want INTERNAL_ERROR", body["code"])
			}
		})
	}
}

// ---- invalid vehicle_id → 400, repo untouched ----------------------------

func TestHandler_List_InvalidVehicleID(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name   string
		target string
	}{
		{"non_numeric", "/trips?vehicle_id=abc"},
		{"zero", "/trips?vehicle_id=0"},
		{"negative", "/trips?vehicle_id=-1"},
		{"overflow", "/trips?vehicle_id=99999999999999999999999999"},
		{"float", "/trips?vehicle_id=1.5"},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			fake := &fakeTripRepo{}
			h := newHandler(fake)

			rec := doList(h, tc.target)
			if rec.Code != http.StatusBadRequest {
				t.Fatalf("status: got %d, want 400. body=%s", rec.Code, rec.Body.String())
			}
			if fake.allCalled != 0 || fake.byVehicleCalled != 0 {
				t.Errorf("repo must not be called for invalid vehicle_id; all=%d byVehicle=%d",
					fake.allCalled, fake.byVehicleCalled)
			}
			var body map[string]string
			if err := json.Unmarshal(rec.Body.Bytes(), &body); err != nil {
				t.Fatalf("decode error body: %v", err)
			}
			if body["error"] != "invalid vehicle_id" {
				t.Errorf("error message: got %q, want 'invalid vehicle_id'", body["error"])
			}
			if body["code"] != "BAD_REQUEST" {
				t.Errorf("error code: got %q, want BAD_REQUEST", body["code"])
			}
		})
	}
}

// ---- full DTO shape over the wire ----------------------------------------

func TestHandler_List_ResponseShape(t *testing.T) {
	t.Parallel()

	start := time.Date(2026, 5, 1, 8, 0, 0, 0, time.UTC)
	end := time.Date(2026, 5, 31, 18, 0, 0, 0, time.UTC)
	fake := &fakeTripRepo{out: []*tripdb.TripSummary{sampleSummary(start, end)}}
	h := newHandler(fake)

	rec := doList(h, "/trips?vehicle_id=7")
	if rec.Code != http.StatusOK {
		t.Fatalf("status: got %d, want 200. body=%s", rec.Code, rec.Body.String())
	}

	var resp []tripSummaryResponse
	if err := json.Unmarshal(rec.Body.Bytes(), &resp); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if len(resp) != 1 {
		t.Fatalf("expected 1 trip, got %d", len(resp))
	}
	got := resp[0]

	if got.ID != 11 || got.VehicleID != 7 {
		t.Errorf("id/vehicle_id: got %d/%d, want 11/7", got.ID, got.VehicleID)
	}
	if got.Name == nil || *got.Name != "May 2026 Summary" {
		t.Errorf("name: got %v", got.Name)
	}
	// start_date and started_at are aliases of Trip.StartedAt.
	if !got.StartedAt.Equal(start) || !got.StartDate.Equal(start) {
		t.Errorf("started_at/start_date: got %v/%v, want %v", got.StartedAt, got.StartDate, start)
	}
	if got.EndedAt == nil || !got.EndedAt.Equal(end) {
		t.Errorf("ended_at: got %v, want %v", got.EndedAt, end)
	}
	if got.EndDate == nil || !got.EndDate.Equal(end) {
		t.Errorf("end_date: got %v, want %v", got.EndDate, end)
	}
	// created_at is derived from started_at (SI trips table has no audit column).
	if !got.CreatedAt.Equal(start) {
		t.Errorf("created_at must equal started_at; got %v, want %v", got.CreatedAt, start)
	}
	if got.CreatedByUser == nil || *got.CreatedByUser != 3 {
		t.Errorf("created_by_user: got %v, want 3", got.CreatedByUser)
	}
	if !got.AutoGenerated {
		t.Errorf("auto_generated: got false, want true")
	}
	if got.Notes == nil || *got.Notes != "road trip" {
		t.Errorf("notes: got %v", got.Notes)
	}
	if got.TotalDistanceM != 123456.0 {
		t.Errorf("total_distance_m: got %v, want 123456.0", got.TotalDistanceM)
	}
	if got.TotalEnergyWh != 45000.0 {
		t.Errorf("total_energy_wh: got %v, want 45000.0", got.TotalEnergyWh)
	}
	if got.TotalDurationS != 7200 {
		t.Errorf("total_duration_s: got %d, want 7200", got.TotalDurationS)
	}
	if got.TotalCost != 12.34 {
		t.Errorf("total_cost: got %v, want 12.34", got.TotalCost)
	}
	if got.DriveCount != 4 || got.ChargeCount != 2 {
		t.Errorf("counts: got drives=%d charges=%d, want 4/2", got.DriveCount, got.ChargeCount)
	}
}

// ---- conversion-only unit tests ------------------------------------------

func TestTripSummaryDTO_NameNullability(t *testing.T) {
	t.Parallel()

	start := time.Date(2026, 1, 2, 3, 4, 5, 0, time.UTC)

	t.Run("empty_name_becomes_nil", func(t *testing.T) {
		t.Parallel()
		in := &tripdb.TripSummary{Trip: models.Trip{ID: 1, Name: "", StartedAt: start}}
		got := tripSummaryDTO(in)
		if got.Name != nil {
			t.Errorf("empty name must map to nil pointer, got %q", *got.Name)
		}
	})

	t.Run("non_empty_name_becomes_ptr", func(t *testing.T) {
		t.Parallel()
		in := &tripdb.TripSummary{Trip: models.Trip{ID: 1, Name: "Weekend", StartedAt: start}}
		got := tripSummaryDTO(in)
		if got.Name == nil || *got.Name != "Weekend" {
			t.Errorf("non-empty name must map to ptr, got %v", got.Name)
		}
	})
}

func TestTripSummaryDTO_DerivedAndNullableFields(t *testing.T) {
	t.Parallel()

	start := time.Date(2026, 2, 3, 4, 5, 6, 0, time.UTC)

	// In-progress trip: no end, no owner, no notes.
	in := &tripdb.TripSummary{
		Trip: models.Trip{
			ID:            5,
			VehicleID:     2,
			Name:          "In Progress",
			StartedAt:     start,
			EndedAt:       nil,
			CreatedByUser: nil,
			AutoGenerated: false,
			Notes:         nil,
		},
	}
	got := tripSummaryDTO(in)

	if !got.CreatedAt.Equal(start) || !got.StartDate.Equal(start) || !got.StartedAt.Equal(start) {
		t.Errorf("start/created aliases must all equal StartedAt; got created=%v start_date=%v started=%v",
			got.CreatedAt, got.StartDate, got.StartedAt)
	}
	if got.EndedAt != nil || got.EndDate != nil {
		t.Errorf("open trip must keep ended_at/end_date nil; got %v/%v", got.EndedAt, got.EndDate)
	}
	if got.CreatedByUser != nil {
		t.Errorf("created_by_user must pass through nil; got %v", got.CreatedByUser)
	}
	if got.Notes != nil {
		t.Errorf("notes must pass through nil; got %v", got.Notes)
	}
	if got.AutoGenerated {
		t.Errorf("auto_generated must pass through false")
	}
}

func TestTripSummaryDTOs_NilAndOrder(t *testing.T) {
	t.Parallel()

	t.Run("nil_input_returns_non_nil_empty", func(t *testing.T) {
		t.Parallel()
		out := tripSummaryDTOs(nil)
		if out == nil {
			t.Fatal("must return non-nil slice so JSON encodes as [] not null")
		}
		if len(out) != 0 {
			t.Errorf("expected empty slice, got len %d", len(out))
		}
	})

	t.Run("preserves_order", func(t *testing.T) {
		t.Parallel()
		now := time.Now().UTC()
		in := []*tripdb.TripSummary{
			{Trip: models.Trip{ID: 3, StartedAt: now}},
			{Trip: models.Trip{ID: 1, StartedAt: now}},
			{Trip: models.Trip{ID: 2, StartedAt: now}},
		}
		out := tripSummaryDTOs(in)
		if len(out) != 3 {
			t.Fatalf("expected 3, got %d", len(out))
		}
		wantIDs := []int64{3, 1, 2}
		for i, want := range wantIDs {
			if out[i].ID != want {
				t.Errorf("order[%d]: got id %d, want %d", i, out[i].ID, want)
			}
		}
	})
}

// ---- constructor fail-fast contracts -------------------------------------

func TestNewHandler_NilDBPanics(t *testing.T) {
	t.Parallel()

	defer func() {
		if recover() == nil {
			t.Fatal("expected NewHandler(nil) to panic")
		}
	}()
	_ = NewHandler(nil)
}

func TestNewHandler_NilRepoPanics(t *testing.T) {
	t.Parallel()

	defer func() {
		if recover() == nil {
			t.Fatal("expected newHandler(nil) to panic")
		}
	}()
	_ = newHandler(nil)
}
