import { useTranslation } from 'react-i18next';
import { ShieldAlert } from 'lucide-react';
import { GlassPanel, PanelTitle, Text, Caption } from '@/components/ui';
import { Skeleton, EmptyState, QueryError } from '@/components/feedback';
import { fmtNumber } from '@/lib/numberFormat';
import type { EvidenceQuality } from '../lib/rootCauseIntelligence';
import { QualityBadge } from './QualityBadge';

export interface RootCauseInterpretationPanelProps {
  summary: string;
  limitations: string[];
  quality: EvidenceQuality;
  hasChosenSignal: boolean;
  isLoading: boolean;
  isError: boolean;
  error?: unknown;
  onRetry?: () => void;
  className?: string;
}

/**
 * "Reading the result" panel: the hedged natural-language summary, the
 * evidence-quality band, and the explicit list of limitations the pure
 * engine attaches to every analysis. Nothing here is a diagnosis — the
 * copy is generated by `rootCauseIntelligence.ts` precisely so this panel
 * never has to invent its own (potentially over-confident) framing.
 */
export function RootCauseInterpretationPanel({
  summary,
  limitations,
  quality,
  hasChosenSignal,
  isLoading,
  isError,
  error,
  onRetry,
  className,
}: RootCauseInterpretationPanelProps) {
  const { t } = useTranslation();

  return (
    <GlassPanel className={className ?? 'p-4 sm:p-5'}>
      <PanelTitle className="mb-3 flex items-center gap-2">
        <ShieldAlert className="h-4 w-4 text-cyan-300" aria-hidden="true" />
        {t('rootCauseIntelligence.interpretation.title', 'Interpretation & Limits')}
      </PanelTitle>
      {isError ? (
        <QueryError error={error} onRetry={onRetry} />
      ) : isLoading ? (
        <Skeleton height={96} />
      ) : !hasChosenSignal ? (
        <EmptyState /* no-action: the interpretation follows from the analysis of a chosen focal signal above. */
          icon={<ShieldAlert className="h-8 w-8" />}
          message={t('rootCauseIntelligence.interpretation.pickOne', 'Choose a signal above to see how its evidence should be read.')}
        />
      ) : (
        <div className="space-y-3">
          <div className="flex flex-wrap items-center gap-2">
            <QualityBadge band={quality.band} />
            <Caption>
              {t('rootCauseIntelligence.interpretation.coverage', '{{withEvidence}} of {{considered}} related signals corroborated · {{samples}} focal samples', {
                withEvidence: quality.candidatesWithEvidence,
                considered: quality.candidatesConsidered,
                samples: quality.focalSampleCount,
              })}
            </Caption>
          </div>
          <Text variant="body">{summary}</Text>
          {limitations.length > 0 && (
            <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-2)] p-3">
              <Text variant="body" weight="semibold" className="mb-1.5 block">
                {t('rootCauseIntelligence.interpretation.limitationsTitle', 'Limitations')}
              </Text>
              <ul className="list-disc space-y-1 pl-5">
                {limitations.map((note) => (
                  <li key={note}>
                    <Text variant="bodySm">{note}</Text>
                  </li>
                ))}
              </ul>
            </div>
          )}
          <Caption>
            {t('rootCauseIntelligence.interpretation.overallScore', 'Overall evidence score {{n}} of 1.00', { n: fmtNumber(quality.overallScore, 2) })}
          </Caption>
        </div>
      )}
    </GlassPanel>
  );
}
