// AUTO-GENERATED by scripts/gen-page-registry.mjs — DO NOT EDIT BY HAND.
// Static-import registry of every web-parity route page (features/*/pages/*Page.tsx
// with a default export), keyed by file basename. Re-run: node scripts/gen-page-registry.mjs
import type {ComponentType} from 'react';

import ActiveSessionsPage from '../web-parity/features/settings/pages/ActiveSessionsPage';
import AlertRulesPage from '../web-parity/features/notifications/pages/AlertRulesPage';
import AlertsListPage from '../web-parity/features/notifications/pages/AlertsListPage';
import AlertStudioPage from '../web-parity/features/notifications/pages/AlertStudioPage';
import AnalyticsPage from '../web-parity/features/analytics/pages/AnalyticsPage';
import AnomalyDashboardPage from '../web-parity/features/diagnostics/pages/AnomalyDashboardPage';
import APIKeysPage from '../web-parity/features/admin/pages/APIKeysPage';
import ApiLogsPage from '../web-parity/features/admin/pages/ApiLogsPage';
import ApiPlaygroundPage from '../web-parity/features/admin/pages/ApiPlaygroundPage';
import ArchivedPage from '../web-parity/features/notifications/pages/ArchivedPage';
import AuditLogPage from '../web-parity/features/admin/pages/AuditLogPage';
import AutomationBuilderPage from '../web-parity/features/automations/pages/AutomationBuilderPage';
import AutomationCard from '../web-parity/features/automations/pages/AutomationCard';
import AutomationListPage from '../web-parity/features/automations/pages/AutomationListPage';
import AutomationsListPage from '../web-parity/features/automations/pages/AutomationsListPage';
import BackupRestorePage from '../web-parity/features/admin/pages/BackupRestorePage';
import BatteryCellsPage from '../web-parity/features/battery/pages/BatteryCellsPage';
import BatteryDegradationPage from '../web-parity/features/battery/pages/BatteryDegradationPage';
import BatteryHealthPage from '../web-parity/features/battery/pages/BatteryHealthPage';
import BrowserNotificationsPage from '../web-parity/features/notifications/pages/BrowserNotificationsPage';
import ChannelsPage from '../web-parity/features/notifications/pages/ChannelsPage';
import ChargingCurvePage from '../web-parity/features/charging/pages/ChargingCurvePage';
import ChargingDetailPage from '../web-parity/features/charging/pages/ChargingDetailPage';
import ChargingHeatmapPage from '../web-parity/features/charging/pages/ChargingHeatmapPage';
import ChargingListPage from '../web-parity/features/charging/pages/ChargingListPage';
import ChatbotPage from '../web-parity/features/system/pages/ChatbotPage';
import ClimateControlPage from '../web-parity/features/vehicle-systems/pages/ClimateControlPage';
import CommandHistoryPage from '../web-parity/features/system/pages/CommandHistoryPage';
import CommandsPage from '../web-parity/features/system/pages/CommandsPage';
import ConditionBuilder from '../web-parity/features/automations/pages/ConditionBuilder';
import CostAnalysisPage from '../web-parity/features/charging/pages/CostAnalysisPage';
import DashboardPage from '../web-parity/features/dashboard/pages/DashboardPage';
import DashboardsPage from '../web-parity/features/power-user/pages/DashboardsPage';
import DataExportPage from '../web-parity/features/system/pages/DataExportPage';
import DataRepairPage from '../web-parity/features/system/pages/DataRepairPage';
import DBHealthPage from '../web-parity/features/system/pages/DBHealthPage';
import DevToolsPage from '../web-parity/features/admin/pages/DevToolsPage';
import DiagnosticPage from '../web-parity/features/system/pages/DiagnosticPage';
import DigitalTwinPage from '../web-parity/features/vehicles/pages/DigitalTwinPage';
import DiskForecastPage from '../web-parity/features/admin/pages/DiskForecastPage';
import DLQInspectorPage from '../web-parity/features/admin/pages/DLQInspectorPage';
import DriveDetailPage from '../web-parity/features/driving/pages/DriveDetailPage';
import DriveScorePage from '../web-parity/features/driving/pages/DriveScorePage';
import DrivesListPage from '../web-parity/features/driving/pages/DrivesListPage';
import DrivetrainHealthPage from '../web-parity/features/driving/pages/DrivetrainHealthPage';
import DrivingDynamicsPage from '../web-parity/features/driving/pages/DrivingDynamicsPage';
import EfficiencyPage from '../web-parity/features/driving/pages/EfficiencyPage';
import EnergyFlowPage from '../web-parity/features/battery/pages/EnergyFlowPage';
import EnergyPage from '../web-parity/features/battery/pages/EnergyPage';
import EnergyProductsPage from '../web-parity/features/battery/pages/EnergyProductsPage';
import ExplorePage from '../web-parity/features/explore/pages/ExplorePage';
import ExportsPage from '../web-parity/features/exports/pages/ExportsPage';
import FeatureFlagsPage from '../web-parity/features/admin/pages/FeatureFlagsPage';
import FeedbackQueuePage from '../web-parity/features/admin/pages/FeedbackQueuePage';
import FleetAPIPage from '../web-parity/features/admin/pages/FleetAPIPage';
import FleetComparePage from '../web-parity/features/analytics/pages/FleetComparePage';
import FleetTelemetryCoveragePage from '../web-parity/features/admin/pages/FleetTelemetryCoveragePage';
import GasPriceAutoPollPage from '../web-parity/features/admin/pages/GasPriceAutoPollPage';
import GDPRExportPage from '../web-parity/features/admin/pages/GDPRExportPage';
import GeofencesPage from '../web-parity/features/maps/pages/GeofencesPage';
import GlancePage from '../web-parity/features/dashboard/pages/GlancePage';
import GrafanaPanelPage from '../web-parity/features/power-user/pages/GrafanaPanelPage';
import GuardModePage from '../web-parity/features/vehicle-systems/pages/GuardModePage';
import HelixPage from '../web-parity/features/settings/pages/HelixPage';
import HelpPage from '../web-parity/features/system/pages/HelpPage';
import InboxPage from '../web-parity/features/notifications/pages/InboxPage';
import IncidentTimelinePage from '../web-parity/features/system/pages/IncidentTimelinePage';
import IngestXRayPage from '../web-parity/features/admin/pages/IngestXRayPage';
import LifetimeStatsPage from '../web-parity/features/analytics/pages/LifetimeStatsPage';
import LiveLogsPage from '../web-parity/features/admin/pages/LiveLogsPage';
import LiveSignalInspectorPage from '../web-parity/features/admin/pages/LiveSignalInspectorPage';
import LiveSignalMonitorPage from '../web-parity/features/telemetry/pages/LiveSignalMonitorPage';
import LocationsPage from '../web-parity/features/maps/pages/LocationsPage';
import MaintenancePage from '../web-parity/features/vehicle-systems/pages/MaintenancePage';
import MapOverviewPage from '../web-parity/features/maps/pages/MapOverviewPage';
import MediaPlayerPage from '../web-parity/features/vehicle-systems/pages/MediaPlayerPage';
import MileagePage from '../web-parity/features/analytics/pages/MileagePage';
import MQTTInspectorPage from '../web-parity/features/telemetry/pages/MQTTInspectorPage';
import MyActivityPage from '../web-parity/features/system/pages/MyActivityPage';
import NavigationRoutePage from '../web-parity/features/maps/pages/NavigationRoutePage';
import NotFoundPage from '../web-parity/features/system/pages/NotFoundPage';
import OnboardingPage from '../web-parity/features/onboarding/pages/OnboardingPage';
import PeriodComparePage from '../web-parity/features/analytics/pages/PeriodComparePage';
import PowerFlowDashboardPage from '../web-parity/features/battery/pages/PowerFlowDashboardPage';
import PowersharePage from '../web-parity/features/charging/pages/PowersharePage';
import PrivacyPage from '../web-parity/features/settings/pages/PrivacyPage';
import ProjectedRangePage from '../web-parity/features/battery/pages/ProjectedRangePage';
import QuickStatsPage from '../web-parity/features/dashboard/pages/QuickStatsPage';
import QuietHoursPage from '../web-parity/features/notifications/pages/QuietHoursPage';
import RbacMatrixPage from '../web-parity/features/admin/pages/RbacMatrixPage';
import RedisSignalViewerPage from '../web-parity/features/admin/pages/RedisSignalViewerPage';
import RegenEfficiencyPage from '../web-parity/features/driving/pages/RegenEfficiencyPage';
import RoadmapPage from '../web-parity/features/system/pages/RoadmapPage';
import RouteEfficiencyPage from '../web-parity/features/driving/pages/RouteEfficiencyPage';
import SafetyPage from '../web-parity/features/settings/pages/SafetyPage';
import SafetySettingsPage from '../web-parity/features/vehicle-systems/pages/SafetySettingsPage';
import ScheduledExportsPanel from '../web-parity/features/system/pages/ScheduledExportsPanel';
import SchemaDriftPage from '../web-parity/features/admin/pages/SchemaDriftPage';
import SearchPage from '../web-parity/features/system/pages/SearchPage';
import SecretRotationPage from '../web-parity/features/admin/pages/SecretRotationPage';
import SecurityAccessPage from '../web-parity/features/admin/pages/SecurityAccessPage';
import SettingsPage from '../web-parity/features/settings/pages/SettingsPage';
import SharedDrivePage from '../web-parity/features/sharing/pages/SharedDrivePage';
import SharingTripsPage from '../web-parity/features/sharing/pages/SharingTripsPage';
import SignalDiffPage from '../web-parity/features/telemetry/pages/SignalDiffPage';
import SignalExplorerPage from '../web-parity/features/telemetry/pages/SignalExplorerPage';
import SignalGapDetectorPage from '../web-parity/features/telemetry/pages/SignalGapDetectorPage';
import SignalLogViewerPage from '../web-parity/features/telemetry/pages/SignalLogViewerPage';
import SignalsWorkspacePage from '../web-parity/features/telemetry/pages/SignalsWorkspacePage';
import SleepEfficiencyPage from '../web-parity/features/battery/pages/SleepEfficiencyPage';
import SlowQueriesPage from '../web-parity/features/admin/pages/SlowQueriesPage';
import SmartChargePage from '../web-parity/features/charging/pages/SmartChargePage';
import SoftwareUpdatesPage from '../web-parity/features/vehicle-systems/pages/SoftwareUpdatesPage';
import SpeedProfilePage from '../web-parity/features/driving/pages/SpeedProfilePage';
import SqlPlaygroundPage from '../web-parity/features/power-user/pages/SqlPlaygroundPage';
import StateMachineDebuggerPage from '../web-parity/features/system/pages/StateMachineDebuggerPage';
import StatisticsPage from '../web-parity/features/analytics/pages/StatisticsPage';
import StatusApiDocsPage from '../web-parity/features/system/pages/StatusApiDocsPage';
import SystemPage from '../web-parity/features/admin/pages/SystemPage';
import SystemStatusPage from '../web-parity/features/system/pages/SystemStatusPage';
import TemperatureImpactPage from '../web-parity/features/maps/pages/TemperatureImpactPage';
import TeslaAccountPage from '../web-parity/features/system/pages/TeslaAccountPage';
import TeslaChargingHistoryPage from '../web-parity/features/charging/pages/TeslaChargingHistoryPage';
import TeslaChargingSessionsMap from '../web-parity/features/charging/pages/TeslaChargingSessionsMap';
import TeslaChargingSessionsPage from '../web-parity/features/charging/pages/TeslaChargingSessionsPage';
import TeslaFeatureFlagsPage from '../web-parity/features/admin/pages/TeslaFeatureFlagsPage';
import TeslaOrdersPage from '../web-parity/features/admin/pages/TeslaOrdersPage';
import TeslaRegionPage from '../web-parity/features/admin/pages/TeslaRegionPage';
import TimelinePage from '../web-parity/features/analytics/pages/TimelinePage';
import TirePressurePage from '../web-parity/features/vehicle-systems/pages/TirePressurePage';
import TripDetailPage from '../web-parity/features/trips/pages/TripDetailPage';
import TripListPage from '../web-parity/features/trips/pages/TripListPage';
import TripPlannerPage from '../web-parity/features/driving/pages/TripPlannerPage';
import TripReplayPage from '../web-parity/features/driving/pages/TripReplayPage';
import TrueCostPage from '../web-parity/features/analytics/pages/TrueCostPage';
import TwoFactorAuthPage from '../web-parity/features/settings/pages/TwoFactorAuthPage';
import UsersPage from '../web-parity/features/admin/pages/UsersPage';
import VampireDrainPage from '../web-parity/features/battery/pages/VampireDrainPage';
import VehicleAccessPage from '../web-parity/features/vehicles/pages/VehicleAccessPage';
import VehicleCostPage from '../web-parity/features/admin/pages/VehicleCostPage';
import VehicleDetailPage from '../web-parity/features/vehicles/pages/VehicleDetailPage';
import VehicleListPage from '../web-parity/features/vehicles/pages/VehicleListPage';
import WatchFacePage from '../web-parity/features/watch/pages/WatchFacePage';
import WebhooksPage from '../web-parity/features/notifications/pages/WebhooksPage';
import WeeklyDigestPage from '../web-parity/features/analytics/pages/WeeklyDigestPage';
import YearReviewPage from '../web-parity/features/analytics/pages/YearReviewPage';

export const WEB_PARITY_PAGES: Record<string, ComponentType<any>> = {
  ActiveSessionsPage,
  AlertRulesPage,
  AlertsListPage,
  AlertStudioPage,
  AnalyticsPage,
  AnomalyDashboardPage,
  APIKeysPage,
  ApiLogsPage,
  ApiPlaygroundPage,
  ArchivedPage,
  AuditLogPage,
  AutomationBuilderPage,
  AutomationCard,
  AutomationListPage,
  AutomationsListPage,
  BackupRestorePage,
  BatteryCellsPage,
  BatteryDegradationPage,
  BatteryHealthPage,
  BrowserNotificationsPage,
  ChannelsPage,
  ChargingCurvePage,
  ChargingDetailPage,
  ChargingHeatmapPage,
  ChargingListPage,
  ChatbotPage,
  ClimateControlPage,
  CommandHistoryPage,
  CommandsPage,
  ConditionBuilder,
  CostAnalysisPage,
  DashboardPage,
  DashboardsPage,
  DataExportPage,
  DataRepairPage,
  DBHealthPage,
  DevToolsPage,
  DiagnosticPage,
  DigitalTwinPage,
  DiskForecastPage,
  DLQInspectorPage,
  DriveDetailPage,
  DriveScorePage,
  DrivesListPage,
  DrivetrainHealthPage,
  DrivingDynamicsPage,
  EfficiencyPage,
  EnergyFlowPage,
  EnergyPage,
  EnergyProductsPage,
  ExplorePage,
  ExportsPage,
  FeatureFlagsPage,
  FeedbackQueuePage,
  FleetAPIPage,
  FleetComparePage,
  FleetTelemetryCoveragePage,
  GasPriceAutoPollPage,
  GDPRExportPage,
  GeofencesPage,
  GlancePage,
  GrafanaPanelPage,
  GuardModePage,
  HelixPage,
  HelpPage,
  InboxPage,
  IncidentTimelinePage,
  IngestXRayPage,
  LifetimeStatsPage,
  LiveLogsPage,
  LiveSignalInspectorPage,
  LiveSignalMonitorPage,
  LocationsPage,
  MaintenancePage,
  MapOverviewPage,
  MediaPlayerPage,
  MileagePage,
  MQTTInspectorPage,
  MyActivityPage,
  NavigationRoutePage,
  NotFoundPage,
  OnboardingPage,
  PeriodComparePage,
  PowerFlowDashboardPage,
  PowersharePage,
  PrivacyPage,
  ProjectedRangePage,
  QuickStatsPage,
  QuietHoursPage,
  RbacMatrixPage,
  RedisSignalViewerPage,
  RegenEfficiencyPage,
  RoadmapPage,
  RouteEfficiencyPage,
  SafetyPage,
  SafetySettingsPage,
  ScheduledExportsPanel,
  SchemaDriftPage,
  SearchPage,
  SecretRotationPage,
  SecurityAccessPage,
  SettingsPage,
  SharedDrivePage,
  SharingTripsPage,
  SignalDiffPage,
  SignalExplorerPage,
  SignalGapDetectorPage,
  SignalLogViewerPage,
  SignalsWorkspacePage,
  SleepEfficiencyPage,
  SlowQueriesPage,
  SmartChargePage,
  SoftwareUpdatesPage,
  SpeedProfilePage,
  SqlPlaygroundPage,
  StateMachineDebuggerPage,
  StatisticsPage,
  StatusApiDocsPage,
  SystemPage,
  SystemStatusPage,
  TemperatureImpactPage,
  TeslaAccountPage,
  TeslaChargingHistoryPage,
  TeslaChargingSessionsMap,
  TeslaChargingSessionsPage,
  TeslaFeatureFlagsPage,
  TeslaOrdersPage,
  TeslaRegionPage,
  TimelinePage,
  TirePressurePage,
  TripDetailPage,
  TripListPage,
  TripPlannerPage,
  TripReplayPage,
  TrueCostPage,
  TwoFactorAuthPage,
  UsersPage,
  VampireDrainPage,
  VehicleAccessPage,
  VehicleCostPage,
  VehicleDetailPage,
  VehicleListPage,
  WatchFacePage,
  WebhooksPage,
  WeeklyDigestPage,
  YearReviewPage,
};

export const WEB_PARITY_PAGE_COUNT = 146;
