package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

const (
	defaultAlertsOut    = "helm/teslasync/files/prometheus/alerting-rules.yaml"
	burnAlertRunbookURL = "docs/runbooks/phase-44-respond-to-burn-alert.md"
)

// burnTier describes one of the two MW-MBR alert tiers per the Google
// SRE workbook. Each tier checks its long-window burn rate AND a much
// shorter window's burn rate; the alert only fires when both are above
// the threshold, suppressing flaps from short outages or recoveries.
type burnTier struct {
	name        string // suffix appended to SLO name (FastBurn / SlowBurn).
	severity    string // routing label: "page" pages on-call; "ticket" opens a JIRA-style ticket.
	longWindow  string
	shortWindow string
	burnRate    float64
	for_        string // alert `for:` clause (sustain duration before firing).
	summary     string
}

var burnTiers = []burnTier{
	{
		name:        "FastBurn",
		severity:    "page",
		longWindow:  "1h",
		shortWindow: "5m",
		burnRate:    14.4,
		for_:        "2m",
		summary:     "fast burn: error budget consumed at >=14.4x sustainable rate over the last 1h",
	},
	{
		name:        "SlowBurn",
		severity:    "ticket",
		longWindow:  "6h",
		shortWindow: "30m",
		burnRate:    6,
		for_:        "15m",
		summary:     "slow burn: error budget consumed at >=6x sustainable rate over the last 6h",
	},
}

func runGenerateAlerts(args []string) error {
	fs := flag.NewFlagSet("generate alerts", flag.ContinueOnError)
	catalog := fs.String("catalog", "slo/catalog.yaml", "path to SLO catalog YAML")
	out := fs.String("out", defaultAlertsOut, "output path for alerting rules")
	check := fs.Bool("check", false, "exit non-zero if the committed file would change; never writes")
	if err := fs.Parse(args); err != nil {
		return err
	}
	cat, err := loadCatalog(*catalog)
	if err != nil {
		return err
	}
	rendered := renderAlerts(cat)
	if err := writeFileIdempotent(*out, rendered, *check); err != nil {
		return err
	}
	if *check {
		fmt.Fprintf(os.Stdout, "ok %s is current (%d SLOs, %d alerts)\n", *out, len(cat.SLOs), len(cat.SLOs)*len(burnTiers))
		return nil
	}
	fmt.Fprintf(os.Stdout, "wrote %s (%d SLOs, %d alerts)\n", *out, len(cat.SLOs), len(cat.SLOs)*len(burnTiers))
	return nil
}

func renderAlerts(cat *Catalog) string {
	var b strings.Builder
	b.WriteString("# DO NOT EDIT. Regenerated by `go run ./cmd/slogen generate alerts`.\n")
	b.WriteString("# Source: slo/catalog.yaml\n")
	b.WriteString("# Multi-window multi-burn-rate per Google SRE Workbook ch. 5.\n")
	b.WriteString("groups:\n")
	for _, s := range cat.SLOs {
		fmt.Fprintf(&b, "  - name: slo_%s_burn\n", s.Name)
		b.WriteString("    rules:\n")
		for _, t := range burnTiers {
			emitBurnAlert(&b, s, t)
		}
	}
	return b.String()
}

func emitBurnAlert(b *strings.Builder, s SLO, t burnTier) {
	threshold := errorBudgetBurnThreshold(s.Objective, t.burnRate)
	expr := fmt.Sprintf(
		"(1 - %s) > %s and (1 - %s) > %s",
		burnRatioExpr(s, t.longWindow), threshold,
		burnRatioExpr(s, t.shortWindow), threshold,
	)
	fmt.Fprintf(b, "      - alert: SLO%s%s\n", camelCase(s.Name), t.name)
	fmt.Fprintf(b, "        expr: %s\n", quoteScalar(expr))
	fmt.Fprintf(b, "        for: %s\n", t.for_)
	b.WriteString("        labels:\n")
	fmt.Fprintf(b, "          severity: %s\n", t.severity)
	fmt.Fprintf(b, "          slo: %q\n", s.Name)
	fmt.Fprintf(b, "          owner: %q\n", s.Owner)
	fmt.Fprintf(b, "          burn_rate: %q\n", trimFloat(t.burnRate))
	fmt.Fprintf(b, "          long_window: %q\n", t.longWindow)
	fmt.Fprintf(b, "          short_window: %q\n", t.shortWindow)
	b.WriteString("        annotations:\n")
	fmt.Fprintf(b, "          summary: %q\n", fmt.Sprintf("SLO %s %s", s.Name, t.summary))
	fmt.Fprintf(b, "          description: %q\n", fmt.Sprintf(
		"Error budget for SLO %q (objective %s%%, owner %s) is burning at >=%sx the sustainable rate "+
			"on both the %s and %s windows.",
		s.Name, formatObjective(s.Objective), s.Owner, trimFloat(t.burnRate), t.longWindow, t.shortWindow,
	))
	fmt.Fprintf(b, "          runbook_url: %q\n", burnAlertRunbookURL)
}

// burnRatioExpr returns the SLI ratio for a window. When a matching
// recording rule exists (5m/1h/6h/30d) the alert references it for
// efficiency; otherwise the SLI expression is rewritten inline against
// the requested window.
func burnRatioExpr(s SLO, window string) string {
	for _, rw := range recordingWindows {
		if rw.expr == window {
			return fmt.Sprintf("slo:%s:%s", s.Name, rw.suffix)
		}
	}
	return ratioExpr(s, window)
}

// errorBudgetBurnThreshold computes the bad-event ratio threshold for a
// burn rate over an SLO objective. Threshold = (1 - objective/100) *
// burnRate. Returned as a fixed-precision string so codegen output is
// stable across runs.
func errorBudgetBurnThreshold(objective, burnRate float64) string {
	budget := (100 - objective) / 100
	return fmt.Sprintf("%.6f", budget*burnRate)
}

func camelCase(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

func trimFloat(f float64) string {
	return fmt.Sprintf("%g", f)
}
