package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Recording-rule windows. Each SLO produces one rule per window so that
// burn-rate alerts (prompt 0032) and Grafana panels (prompt 0033) can
// query short and long windows without rewriting the SLI expression.
var recordingWindows = []struct {
	suffix string
	expr   string
}{
	{"ratio_rate5m", "5m"},
	{"ratio_rate1h", "1h"},
	{"ratio_rate6h", "6h"},
	{"ratio_rate30d", "30d"},
}

const defaultRecordingOut = "helm/teslasync/files/prometheus/recording-rules.yaml"

func runGenerate(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("missing target (recording|alerts|dashboards)")
	}
	target := args[0]
	switch target {
	case "recording":
		return runGenerateRecording(args[1:])
	case "alerts":
		return runGenerateAlerts(args[1:])
	case "dashboards":
		return runGenerateDashboards(args[1:])
	default:
		return fmt.Errorf("unknown generate target %q", target)
	}
}

func runGenerateRecording(args []string) error {
	fs := flag.NewFlagSet("generate recording", flag.ContinueOnError)
	catalog := fs.String("catalog", "slo/catalog.yaml", "path to SLO catalog YAML")
	out := fs.String("out", defaultRecordingOut, "output path for recording rules")
	check := fs.Bool("check", false, "exit non-zero if the committed file would change; never writes")
	if err := fs.Parse(args); err != nil {
		return err
	}

	cat, err := loadCatalog(*catalog)
	if err != nil {
		return err
	}
	rendered := renderRecordingRules(cat)
	if err := writeFileIdempotent(*out, rendered, *check); err != nil {
		return err
	}
	if *check {
		fmt.Fprintf(os.Stdout, "ok %s is current (%d SLOs, %d rules)\n", *out, len(cat.SLOs), len(cat.SLOs)*len(recordingWindows))
		return nil
	}
	fmt.Fprintf(os.Stdout, "wrote %s (%d SLOs, %d rules)\n", *out, len(cat.SLOs), len(cat.SLOs)*len(recordingWindows))
	return nil
}

func loadCatalog(path string) (*Catalog, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	cat, err := parseCatalog(string(raw))
	if err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	if err := validateCatalog(cat); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return cat, nil
}

// renderRecordingRules serialises the catalogue to a Prometheus rules
// YAML document. Output is deterministic: SLOs ordered as in the
// catalogue, windows ordered by `recordingWindows` declaration.
func renderRecordingRules(cat *Catalog) string {
	var b strings.Builder
	b.WriteString("# DO NOT EDIT. Regenerated by `go run ./cmd/slogen generate recording`.\n")
	b.WriteString("# Source: slo/catalog.yaml\n")
	b.WriteString("groups:\n")

	// SLOs render in catalogue order (which is also their declaration
	// order in catalog.yaml). The parser preserves this; no resort.
	for _, s := range cat.SLOs {
		fmt.Fprintf(&b, "  - name: slo_%s\n", s.Name)
		b.WriteString("    interval: 30s\n")
		b.WriteString("    rules:\n")
		for _, w := range recordingWindows {
			fmt.Fprintf(&b, "      - record: slo:%s:%s\n", s.Name, w.suffix)
			fmt.Fprintf(&b, "        expr: %s\n", quoteScalar(ratioExpr(s, w.expr)))
			b.WriteString("        labels:\n")
			fmt.Fprintf(&b, "          slo: %q\n", s.Name)
			fmt.Fprintf(&b, "          window: %q\n", w.expr)
			fmt.Fprintf(&b, "          owner: %q\n", s.Owner)
			fmt.Fprintf(&b, "          objective: %q\n", formatObjective(s.Objective))
		}
	}
	return b.String()
}

// ratioExpr re-windows the catalogue's SLI good/valid expressions to the
// requested duration. The SLI expressions are written for `[5m]` (the
// default recording window); the codegen substitutes `[5m]` with the
// target window for every recording rule.
func ratioExpr(s SLO, window string) string {
	good := rewriteWindow(s.SLI.GoodEvents, window)
	valid := rewriteWindow(s.SLI.ValidEvents, window)
	// Preserve the real good/valid ratio at any non-zero traffic rate. A
	// one-request-per-second denominator floor turns healthy low-volume APIs
	// into false outages. Windows with no valid events are explicitly healthy
	// (1) because no reliability budget was consumed.
	//
	// The numerator is coalesced to `0 * valid` so a numerator that selects
	// NOTHING (e.g. a latency SLI pinned to an `le=` histogram bucket that
	// does not exist) cannot fall through to the vector(1) tail and report a
	// permanent, fabricated 100 %. With traffic present such an SLI now reads
	// 0 and fails loudly. Mirrors internal/slo.nonZeroTrafficRatioExpr.
	return fmt.Sprintf(
		"(((((%s) or on() (0 * (%s)))) / (%s)) and on() ((%s) > 0)) or on() vector(1)",
		good, valid, valid, valid,
	)
}

// rewriteWindow swaps the literal `[5m]` and the subquery `[5m:30s]` for
// the requested window. The substitutions are surgical (substring match
// of the bracket form) so PromQL function calls and label filters are
// unaffected.
func rewriteWindow(expr, window string) string {
	expr = strings.ReplaceAll(expr, "[5m:30s]", "["+window+":30s]")
	expr = strings.ReplaceAll(expr, "[5m]", "["+window+"]")
	return expr
}

func formatObjective(o float64) string {
	// Strip trailing zeros so 99.5 -> "99.5" and 99 -> "99".
	s := fmt.Sprintf("%g", o)
	return s
}

// quoteScalar produces a YAML double-quoted scalar. Backslash and
// double-quote in the expression are escaped per the YAML spec (also
// per Go's strconv quoting, which is a strict superset for printable
// ASCII plus the sequences we need).
func quoteScalar(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		ch := s[i]
		switch ch {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		default:
			b.WriteByte(ch)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// errStaleArtifact reports that a committed generated file no longer matches
// what the generator produces. Returned only in check mode.
var errStaleArtifact = errors.New("generated artifact is stale")

// writeFileIdempotent writes data only if it differs from disk. The
// behaviour is required by the prompt's idempotency check: a second
// invocation must leave the file's bytes (and mtime, since unchanged
// writes are skipped) unchanged.
//
// CLEAN-05: when check is true the function never touches the filesystem. It
// compares instead, so CI can prove the committed artefacts are current
// without mutating the worktree (`scripts/check-generated-freshness.mjs`).
func writeFileIdempotent(path, data string, check bool) error {
	existing, readErr := os.ReadFile(path)
	if readErr == nil && string(existing) == data {
		return nil
	}
	if check {
		if readErr != nil {
			return fmt.Errorf("%w: %s is missing or unreadable: %v", errStaleArtifact, path, readErr)
		}
		return fmt.Errorf("%w: %s — regenerate with `go run ./cmd/slogen generate ...` and commit the diff", errStaleArtifact, path)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(data), 0o644)
}
