// Phase 44 / Prompt 0081 — metric-coverage audit.
//
// Static audit that the RED middleware is wired in front of every route
// declared in internal/api/router.go and that the three metric series
// (requests_total / errors_total / duration_seconds) are actually defined.
//
// Why static: spinning up the entire teslasync HTTP server in CI just to
// scrape /metrics would require Postgres + Redis + Mosquitto + a real Tesla
// API mock — overkill for a coverage check. Instead we walk router.go and
// count chi route declarations, then verify MetricsMiddleware is registered
// before the first route subtree.
//
// Failure modes (any of these adds MISSING_METRIC to the report so the
// prompt gate blocks):
//   - middleware.go missing one of the three metric names
//   - router.go does not call r.Use(MetricsMiddleware) before route mounts
//   - any router.Mount() call appears before the middleware
//   - zero routes detected (means the regex broke and we silently passed)
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	routerPath     = "internal/api/router.go"
	middlewarePath = "internal/api/middleware.go"
	defaultReport  = "docs/runbooks/phase-44-metric-coverage-audit.md"
	minRoutes      = 100
)

var requiredMetrics = []string{
	"red_http_requests_total",
	"red_http_request_errors_total",
	"red_http_request_duration_seconds",
}

// chi route registration verbs. Includes Mount because subrouters DO inherit
// parent middleware in chi, but we still count their declaration for a
// coverage signal.
var routeRE = regexp.MustCompile(`(?m)^\s*r(?:outer)?\.(?:Get|Post|Put|Patch|Delete|Head|Options|Method|Mount|Handle|HandleFunc)\s*\(`)

func main() {
	var reportPath string
	flag.StringVar(&reportPath, "report", defaultReport, "report path")
	flag.Parse()

	findings := []string{}
	statuses := map[string]string{}

	// 1. Verify metric definitions in middleware.go.
	mw, err := os.ReadFile(middlewarePath)
	if err != nil {
		findings = append(findings, fmt.Sprintf("MISSING_METRIC: cannot read %s: %v", middlewarePath, err))
	} else {
		for _, m := range requiredMetrics {
			if !strings.Contains(string(mw), m) {
				findings = append(findings, fmt.Sprintf("MISSING_METRIC: %s not declared in %s", m, middlewarePath))
				statuses[m] = "MISSING"
			} else {
				statuses[m] = "OK"
			}
		}
	}

	// 2. Verify MetricsMiddleware is registered before the first route.
	rt, err := os.ReadFile(routerPath)
	if err != nil {
		findings = append(findings, fmt.Sprintf("MISSING_METRIC: cannot read %s: %v", routerPath, err))
	}
	rtBody := string(rt)
	mwIdx := strings.Index(rtBody, "MetricsMiddleware")
	firstRouteMatch := routeRE.FindStringIndex(rtBody)
	if mwIdx < 0 {
		findings = append(findings, fmt.Sprintf("MISSING_METRIC: r.Use(MetricsMiddleware) not registered in %s", routerPath))
	}
	if firstRouteMatch == nil {
		findings = append(findings, fmt.Sprintf("MISSING_METRIC: zero routes detected in %s — regex broken or file empty", routerPath))
	} else if mwIdx >= 0 && mwIdx > firstRouteMatch[0] {
		findings = append(findings, fmt.Sprintf("MISSING_METRIC: MetricsMiddleware appears AFTER the first route declaration — earlier routes will skip RED metrics"))
	}

	// 3. Count routes for an honest coverage figure.
	routeCount := len(routeRE.FindAllStringIndex(rtBody, -1))
	if routeCount < minRoutes {
		findings = append(findings, fmt.Sprintf("MISSING_METRIC: only %d routes detected in %s (expected ≥%d) — middleware coverage may be incomplete", routeCount, routerPath, minRoutes))
	}

	report := renderReport(routeCount, statuses, findings)
	if err := os.MkdirAll(filepath.Dir(reportPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir failed: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(reportPath, []byte(report), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write failed: %v\n", err)
		os.Exit(1)
	}
	fmt.Print(report)

	if len(findings) > 0 {
		fmt.Fprintf(os.Stderr, "metric-coverage-audit: %d gap(s) — see report\n", len(findings))
		os.Exit(2)
	}
	fmt.Fprintln(os.Stderr, "metric-coverage-audit: OK")
}

func renderReport(routeCount int, statuses map[string]string, findings []string) string {
	var b strings.Builder
	b.WriteString("# Phase 44 — Metric coverage audit\n\n")
	b.WriteString("Static audit of `internal/api/router.go` and `internal/api/middleware.go` to confirm every route is covered by the RED middleware.\n\n")
	b.WriteString("Generated by `cmd/metric-coverage-audit`. To re-run:\n\n")
	b.WriteString("```powershell\ngo run ./cmd/metric-coverage-audit -report docs/runbooks/phase-44-metric-coverage-audit.md\n```\n\n")
	b.WriteString("## Required metric series\n\n")
	for _, m := range requiredMetrics {
		s := statuses[m]
		if s == "" {
			s = "UNCHECKED"
		}
		fmt.Fprintf(&b, "- `%s` — %s\n", m, s)
	}
	b.WriteString("\n## Route coverage\n\n")
	fmt.Fprintf(&b, "- Routes detected in router.go: **%d** (threshold ≥ %d)\n", routeCount, minRoutes)
	b.WriteString("- Coverage strategy: chi `r.Use(MetricsMiddleware)` is registered at the root router so every subsequently-declared route inherits the RED middleware.\n\n")
	b.WriteString("## Findings\n\n")
	if len(findings) == 0 {
		b.WriteString("No gaps found. All routes inherit the RED middleware.\n")
	} else {
		for _, f := range findings {
			fmt.Fprintf(&b, "- %s\n", f)
		}
	}
	return b.String()
}
