// Native parity port of web/src/features/explore/pages/ExplorePage.tsx.
//
// The web page is the Explore / Feature Hub: a "front door" to every feature in
// the app. It re-uses the sidebar `navSections` verbatim, decorates each entry
// with a 1-line description (featureCatalog), and renders the whole catalog as a
// categorized, filterable card grid. This port reproduces the same catalog data,
// the same gating predicates, the same search/filter/group/highlight behaviour,
// the same recently-visited strip, the same section-anchor strip, and the same
// "did you mean" empty state using React Native primitives instead of DOM /
// react-router / react-i18next / lucide / web UI components.
//
// Behaviour preserved verbatim:
//   * `RECENT_LIMIT = 6`.
//   * Gating: `vehicleCount = vehicles?.length ?? 0`, `isForwardAuth`, and the
//     `visibleCatalog` filter (`minVehicles`/`requiresAuth` predicates) — same
//     predicates the sidebar uses, via the ported `useVehicles()` /
//     `useIsForwardAuth()` hooks (API paths `/vehicles`, `/system/auth-mode`).
//   * `query`, `visibleCatalog`, `filtered`, `grouped`, `updateQuery`, `recent`,
//     `visibleByTo`, `recentResolved`, `totalFeatures`, `matchCount`, `subtitle`
//     — same names, same memo deps, same bodies.
//   * `buildFeatureCatalog` / `filterFeatureCatalog` / `groupFeatureCatalog` /
//     `FeatureCatalogEntry` and the full DESCRIPTIONS map — inlined verbatim from
//     the not-yet-ported `../featureCatalog` (the web read its icon/color from
//     navSections; the native navSections carries `to`/`label`/`requiresAuth`
//     only, so per-item icon/color collapse to a per-section SemanticIcon).
//   * `closestRoutes` / Levenshtein engine + the EmptyResult merge/dedupe/sort —
//     inlined verbatim from `@/lib/closestRoute`; the web `ROUTE_REGISTRY` (an
//     autogenerated list) is sourced from navSections (documented in sidecar).
//   * `Highlight` token-splitter (escapeRegExp + non-/g RegExp split), `slugify`.
//   * `navSections`, `RecentEntry`, `getRecentPages`, `subscribeRecentPages` are
//     imported from the already-ported CommandPalette — the SAME shared in-memory
//     recent-pages registry the web command palette maintains (web semantics).
//
// Platform dependency swaps (no DOM, lucide, Recharts, Leaflet, react-router, or
// web UI components in native output — contract rule 4):
//   * `useTranslation` (react-i18next) -> `useNativeT`, a `t(key, fallback,
//     vars?)` returning the English fallback with `{{var}}` interpolation.
//   * `useNavigate` (react-router) -> optional `onNavigate?(to)` prop (default
//     no-op); native hosts wire routing. URL-driven `?q=` state (`useSearchParams`)
//     -> local `useState`. Both are browser-only (documented).
//   * `usePageTitle` (document.title) -> the header renders the title; the
//     document side effect is a no-op on native.
//   * The global `/`-to-focus `document.addEventListener('keydown')` shortcut and
//     the sticky search panel are browser-only and omitted (documented); the
//     TextInput ref is preserved for programmatic focus.
//   * `<a href>` anchors / section `#anchor` jumps -> `Pressable`s calling
//     `onNavigate`; anchor scroll-to is browser-only (the chips remain tappable).
//   * `Icons.search` (lucide) -> `<SemanticIcon name="search">`; the per-card
//     lucide icon -> a per-section `<SemanticIcon>`.
//   * `PageContainer`/`GlassPanel`/`Input`/`VisuallyHidden`/`cn` -> a native
//     ScrollView layout, the shared native GlassPanel, a native TextInput, an
//     `accessibilityLabel`, and StyleSheet styling.

import React, {
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import {
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';

import {AppText} from '../../../../components/ui/AppText';
import {GlassPanel} from '../../../../components/ui/GlassPanel';
import {
  SemanticIcon,
  type SemanticIconName,
} from '../../../../components/icons/SemanticIcon';
import {colors, spacing, typography} from '../../../../theme/tokens';
import {useVehicles} from '../../../api/hooks/useVehicles';
import {useIsForwardAuth} from '../../../api/hooks/useAuthMode';
import {
  navSections,
  getRecentPages,
  subscribeRecentPages,
  type RecentEntry,
} from '../../../components/ui/CommandPalette';

const RECENT_LIMIT = 6;

/* ── i18n swap (react-i18next -> English-fallback shim) ─────────────────────── */

type TVars = Record<string, string | number>;
type NativeT = (key: string, fallback: string, vars?: TVars) => string;

function interpolate(template: string, vars?: TVars): string {
  if (!vars) {
    return template;
  }
  return template.replace(/\{\{\s*(\w+)\s*\}\}/g, (_m, name: string) =>
    Object.prototype.hasOwnProperty.call(vars, name)
      ? String(vars[name])
      : `{{${name}}}`,
  );
}

function useNativeT(): NativeT {
  return useMemo<NativeT>(
    () => (_key, fallback, vars) => interpolate(fallback, vars),
    [],
  );
}

// Native no-op for the web `usePageTitle` (which set `document.title`). There is
// no document on native; the page header still renders the title.
function useNativePageTitle(_title: string): void {
  // Intentionally empty — see note above.
}

/* ── featureCatalog (inlined from ../featureCatalog, native-safe) ──────────── */

interface FeatureCatalogEntry {
  to: string;
  label: string;
  /** Section title from navSections (e.g. "Home", "Driving"). */
  section: string;
  /** Per-section SemanticIcon (web carried a per-item lucide icon + color). */
  icon: SemanticIconName;
  /** 1-line description shown under the label on a feature card. */
  description: string;
  /** Optional gating from navSections — surfaced so the page can hide rows. */
  minVehicles?: number;
  requiresAuth?: boolean;
}

// Per-section icon (the native navSections drops the web's per-item icon/color,
// so a representative SemanticIcon per section preserves the leading-glyph intent).
const SECTION_ICONS: Record<string, SemanticIconName> = {
  Home: 'home',
  Vehicles: 'vehicle',
  Driving: 'drive',
  Charging: 'charging',
  Battery: 'battery',
  Energy: 'bolt',
  Service: 'maintenance',
  Cabin: 'climate',
  Reports: 'analytics',
  Commands: 'terminal',
  Automation: 'workflow',
  Notifications: 'notifications',
  Security: 'security',
  Account: 'user',
  Settings: 'settings',
  Integrations: 'link',
  Data: 'database',
  Diagnostics: 'stethoscope',
  About: 'info',
};

// Plain-prose descriptions keyed by route (≤ 90 chars). Routes without a key fall
// back to `Open ${label}.` so the page never blanks out (web behaviour verbatim).
const DESCRIPTIONS: Record<string, string> = {
  // ── Home ───────────────────────────────────────────────────────────
  '/': 'Your daily summary — battery, last drive, charging, and alerts at a glance.',
  '/explore':
    'Browse and search every feature in TeslaSync with a 1-line description for each.',
  '/live': 'Real-time map of where your vehicle is right now.',
  '/timeline': 'Hour-by-hour history of drives, charges, and events.',
  '/weekly-digest': 'A printable weekly recap of usage, range, and cost.',

  // ── Vehicles ───────────────────────────────────────────────────────
  '/vehicles': 'Manage every Tesla on your account — VIN, options, status.',
  '/digital-twin':
    'A live 3D model of your car mirroring doors, lights, and motion.',
  '/vehicle-comparison': 'Side-by-side stats for two or more of your vehicles.',
  '/locations': 'Frequent destinations — home, work, favorite Superchargers.',

  // ── Driving ────────────────────────────────────────────────────────
  '/drives': 'Every drive with route, energy used, and efficiency.',
  '/trips': 'Multi-leg trips grouped into a single journey.',
  '/trip-planner':
    'Plan a route with charging stops and ETA before you leave.',
  '/navigation': 'Send a destination to the car or save it for later.',
  '/geofences': 'Trigger automations when the car enters or leaves a zone.',
  '/mileage': 'Odometer log with monthly and yearly totals.',
  '/lifetime-stats': 'Every drive ever — distance, energy, and time totals.',
  '/drive-score':
    'Smoothness rating per drive (acceleration, braking, cornering).',
  '/speed-profile': 'Speed-vs-time chart for any drive.',
  '/driving-dynamics':
    'G-forces, lateral and longitudinal acceleration analysis.',
  '/regen-efficiency': 'How much energy regenerative braking recaptures.',
  '/route-efficiency': 'Compare actual vs predicted Wh/mile for a route.',

  // ── Charging ───────────────────────────────────────────────────────
  '/charging': 'All charging sessions — Supercharger, home, third-party.',
  '/tesla-charging-history':
    'Tesla-provided charging history pulled from your account.',
  '/charging-curve': 'Power vs SOC curve for any charging session.',
  '/charging-heatmap': 'When and where you charge, visualised as a heatmap.',
  '/smart-charge': 'Schedule charging for off-peak or solar-surplus windows.',
  '/powershare': 'Use your vehicle as a backup home battery (V2H).',

  // ── Battery ────────────────────────────────────────────────────────
  '/battery': 'Pack health: SoH, full-charge capacity, and degradation curve.',
  '/battery-cells': 'Per-cell voltage and temperature spread.',
  '/battery-degradation': 'Capacity loss over time vs fleet average.',
  '/projected-range':
    'Range forecast adjusted for weather, terrain, and driving style.',
  '/vampire-drain': 'Standby energy loss while parked and asleep.',
  '/sleep-efficiency':
    'How quickly the car drops into low-power sleep when parked.',

  // ── Energy ─────────────────────────────────────────────────────────
  '/energy': 'Daily kWh in and out of the pack.',
  '/energy-flow':
    'Animated flow diagram showing where the energy is going right now.',
  '/power-flow': 'Live power draw and regen at the wheels.',
  '/energy-products': 'Solar production and Powerwall stats from your Tesla account.',

  // ── Service ────────────────────────────────────────────────────────
  '/tire-pressure': 'Current and historical pressure per tire.',
  '/drivetrain-health': 'Motor temperatures, inverter status, and fault codes.',
  '/software-updates': 'Available firmware updates and changelog.',
  '/maintenance':
    'Tire rotations, brake fluid, cabin filter — overdue items first.',

  // ── Cabin ──────────────────────────────────────────────────────────
  '/climate-control': 'Pre-heat, pre-cool, or run Dog Mode remotely.',
  '/media-player': 'See what is playing and control playback.',

  // ── Reports ────────────────────────────────────────────────────────
  '/statistics': 'Bar and pie charts across every metric in the system.',
  '/analytics': 'Long-range trends and correlations you can drill into.',
  '/period-compare': 'Pick two date ranges and see what changed.',
  '/efficiency': 'Wh/mile broken down by speed, climate, and elevation.',
  '/temperature-impact':
    'How outside temperature affects range and efficiency.',
  '/cost-analysis': 'Electricity cost per drive and per mile.',
  '/tco': 'Total cost of ownership — energy, insurance, service, depreciation.',

  // ── Commands ───────────────────────────────────────────────────────
  '/commands': 'Send a remote command (wake, lock, climate, port, …).',
  '/command-history': 'Audit log of every command sent and its result.',

  // ── Automation ─────────────────────────────────────────────────────
  '/automations': 'Trigger actions on geofence, time, or vehicle state.',
  '/notifications/studio':
    'Build a custom alert rule with conditions and channels.',
  '/notifications/rules': 'Manage existing alert rules.',

  // ── Notifications ──────────────────────────────────────────────────
  '/notifications/inbox': 'Recent alerts and system messages.',
  '/notifications/alerts':
    'Active and acknowledged alerts grouped by severity.',
  '/notifications/channels': 'Where alerts are sent — email, SMS, push, webhook.',
  '/notifications/webhooks':
    'POST alerts to your own URL for downstream automation.',
  '/notifications/browser': 'Enable browser push notifications for this device.',
  '/notifications/quiet-hours': 'Mute non-critical alerts during set times.',

  // ── Security ───────────────────────────────────────────────────────
  '/security-access': 'Manage who can drive, charge, and unlock your vehicle.',
  '/safety-settings':
    'Speed limit, valet mode, and safety-related preferences.',
  '/guard-mode': 'Sentry Mode, dashcam, and event-recording settings.',

  // ── Account ────────────────────────────────────────────────────────
  '/tesla-account': 'Linked Tesla account, refresh-token status, and re-auth.',
  '/tesla-orders': 'Active orders on your Tesla account.',
  '/fleet-api': 'Fleet API rate-limit usage and registration details.',
  '/tesla-region': 'Switch Fleet API region (NA, EU, China).',
  '/tesla-features':
    'Tesla feature-flag previews exposed by your firmware version.',
  '/account/2fa': 'Enroll or disable two-factor authentication on your account.',
  '/account/sessions': 'Browser and device sessions — revoke any of them.',
  '/account/privacy': 'Recently viewed pages, cookies, and analytics consent.',
  '/me/activity': 'Your recent page views and actions in this app.',

  // ── Settings ───────────────────────────────────────────────────────
  '/settings': 'Units, theme, locale, density, and every app preference.',
  '/chatbot': 'Ask Helix anything about your car or this app.',
  '/dev-tools': 'In-app developer surface — flags, debuggers, and inspectors.',

  // ── Integrations ───────────────────────────────────────────────────
  '/api-keys': 'Issue and revoke API keys for external integrations.',
  '/gas-price': 'Compare your $/mile against gasoline at current prices.',

  // ── Data ───────────────────────────────────────────────────────────
  '/data-export': 'Export drives, charging sessions, and signals to CSV.',
  '/backup': 'Take a full backup of the database or restore from one.',
  '/data-repair': 'Re-derive trips, sessions, and analytics from raw signals.',

  // ── Diagnostics ────────────────────────────────────────────────────
  '/system-status':
    'Health of every dependent service — MQTT, Redis, DB, Tesla API.',
  '/db-health': 'Database size, query latency, and replication lag.',
  '/anomaly-detection':
    'Auto-detected outliers in charging, range, and drives.',
  '/signals': 'Live values for every telemetry signal the car publishes.',
  '/admin/live-signals': 'Inspect a single signal in real time with history.',
  '/admin/ingest-xray': 'See every payload as it lands from Fleet Telemetry.',
  '/admin/dlq': 'Dead-letter queue — messages that failed to ingest.',
  '/admin/flags': 'Runtime feature flags — toggle without redeploy.',
  '/admin/schema-drift':
    'Detect divergence between code models and the live DB schema.',
  '/admin/slow-queries': 'Top slow SQL queries with explain plans.',
  '/admin/vehicle-cost': 'Per-vehicle infrastructure cost attribution.',
  '/admin/disk-forecast': 'When will the database run out of disk?',
  '/admin/secret-rotation': 'Track and rotate secrets, tokens, and credentials.',
  '/admin/audit-log': 'Every privileged action with actor, target, and timestamp.',
  '/admin/gdpr-exports': 'Generate and download a complete user-data export.',
  '/state-debugger':
    'Inspect the per-vehicle finite-state machine in real time.',
  '/mqtt-inspector': 'Subscribe to any MQTT topic and watch messages flow.',
  '/redis-signals': 'Dump the Redis live-signal cache for a vehicle.',
  '/admin/telemetry/coverage':
    'Which Fleet Telemetry fields are wired vs missing.',
  '/api-logs': 'Recent HTTP requests with status, duration, and payload size.',
  '/api-playground': 'Try any API endpoint with parameter forms.',

  // ── About ──────────────────────────────────────────────────────────
  '/roadmap': 'Upcoming features grouped by quarter.',
};

// Build the flat catalog from navSections + DESCRIPTIONS. Anything without a
// description gets a visible `Open ${label}.` fallback (test-asserted on web).
function buildFeatureCatalog(): FeatureCatalogEntry[] {
  const out: FeatureCatalogEntry[] = [];
  for (const section of navSections) {
    for (const item of section.items) {
      out.push({
        to: item.to,
        label: item.label,
        section: section.title,
        icon: SECTION_ICONS[section.title] ?? 'layoutGrid',
        description: DESCRIPTIONS[item.to] ?? `Open ${item.label}.`,
        requiresAuth: item.requiresAuth,
      });
    }
  }
  return out;
}

// Group a flat catalog by section, preserving navSections order.
function groupFeatureCatalog(
  entries: FeatureCatalogEntry[],
): {section: string; entries: FeatureCatalogEntry[]}[] {
  const order = navSections.map(s => s.title);
  const buckets = new Map<string, FeatureCatalogEntry[]>();
  for (const e of entries) {
    const bucket = buckets.get(e.section);
    if (bucket) {
      bucket.push(e);
    } else {
      buckets.set(e.section, [e]);
    }
  }
  return order
    .filter(title => buckets.has(title))
    .map(title => ({section: title, entries: buckets.get(title)!}));
}

// Case-insensitive AND-token match against label, section, description, and path.
function filterFeatureCatalog(
  entries: FeatureCatalogEntry[],
  query: string,
): FeatureCatalogEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    return entries;
  }
  const tokens = q.split(/\s+/);
  return entries.filter(e => {
    const haystack =
      `${e.label} ${e.section} ${e.description} ${e.to}`.toLowerCase();
    return tokens.every(tok => haystack.includes(tok));
  });
}

/* ── closestRoute (inlined from @/lib/closestRoute, pure logic) ─────────────── */

interface RouteEntry {
  path: string;
  name: string;
  label: string;
  i18nKey: string;
  hidden?: boolean;
}

interface RouteSuggestion extends RouteEntry {
  distance: number;
}

// The web combined an autogenerated ROUTE_REGISTRY (which carried hidden/internal
// routes too) with the catalog labels. Native sources the registry from
// navSections — the same data the catalog is built from (documented in sidecar).
const ROUTE_REGISTRY: readonly RouteEntry[] = navSections.flatMap(section =>
  section.items.map(item => ({
    path: item.to,
    name: item.label.replace(/\s+/g, ''),
    label: item.label,
    i18nKey: '',
  })),
);

function normalizeRoute(s: string): string {
  return s.toLowerCase().replace(/[\s\-_/]+/g, '');
}

// Iterative two-row Levenshtein. O(m*n) time, O(min(m,n)) space.
function levenshtein(a: string, b: string): number {
  if (a === b) {
    return 0;
  }
  if (!a.length) {
    return b.length;
  }
  if (!b.length) {
    return a.length;
  }
  if (a.length > b.length) {
    const tmp = a;
    a = b;
    b = tmp;
  }
  const m = a.length;
  const n = b.length;
  let prev: number[] = new Array(m + 1);
  let curr: number[] = new Array(m + 1);
  for (let i = 0; i <= m; i++) {
    prev[i] = i;
  }
  for (let j = 1; j <= n; j++) {
    curr[0] = j;
    for (let i = 1; i <= m; i++) {
      const cost = a.charCodeAt(i - 1) === b.charCodeAt(j - 1) ? 0 : 1;
      curr[i] = Math.min(curr[i - 1] + 1, prev[i] + 1, prev[i - 1] + cost);
    }
    const tmp = prev;
    prev = curr;
    curr = tmp;
  }
  return prev[m];
}

function closestRoutes(
  query: string,
  registry: readonly RouteEntry[],
  limit = 5,
): RouteSuggestion[] {
  const q = normalizeRoute(query);
  if (!q) {
    return [];
  }
  const scored: RouteSuggestion[] = [];
  for (const r of registry) {
    if (r.hidden) {
      continue;
    }
    const pathDist = levenshtein(q, normalizeRoute(r.path));
    const labelDist = levenshtein(q, normalizeRoute(r.label));
    const distance = Math.min(pathDist, labelDist);
    if (distance <= 6) {
      scored.push({...r, distance});
    }
  }
  scored.sort((a, b) => a.distance - b.distance || a.path.localeCompare(b.path));
  return scored.slice(0, limit);
}

/* ── Native PageContainer ───────────────────────────────────────────────────── */

function PageContainer({
  title,
  subtitle,
  children,
}: {
  title: string;
  subtitle?: string;
  children: ReactNode;
}) {
  return (
    <ScrollView
      style={styles.screen}
      contentContainerStyle={styles.screenContent}>
      <View style={styles.headerText}>
        <AppText variant="display" weight="bold">
          {title}
        </AppText>
        {subtitle ? (
          <AppText tone="muted" style={styles.subtitle}>
            {subtitle}
          </AppText>
        ) : null}
      </View>
      <View style={styles.body}>{children}</View>
    </ScrollView>
  );
}

/* ── Page ──────────────────────────────────────────────────────────────────── */

export default function ExplorePage({
  onNavigate,
}: {onNavigate?: (to: string) => void} = {}) {
  const t = useNativeT();
  // The web read `?q=` from the URL (useSearchParams); native keeps it local.
  const [query, setQuery] = useState('');
  // Preserved for parity (web focused this on "/"); the global keydown shortcut
  // is browser-only and omitted.
  const inputRef = useRef<TextInput | null>(null);

  useNativePageTitle(t('explore.pageTitle', 'Explore features'));

  const navigate = useMemo(
    () => (to: string) => {
      // react-router navigation is browser-only; native hosts wire onNavigate.
      onNavigate?.(to);
    },
    [onNavigate],
  );

  // Gating — same predicates the sidebar uses.
  const {data: vehicles} = useVehicles();
  const isForwardAuth = useIsForwardAuth();
  const vehicleCount = vehicles?.length ?? 0;

  // ── Catalog ─────────────────────────────────────────────────────────
  const visibleCatalog = useMemo(() => {
    const all = buildFeatureCatalog();
    return all.filter(entry => {
      if (entry.minVehicles && vehicleCount < entry.minVehicles) {
        return false;
      }
      if (entry.requiresAuth && !isForwardAuth) {
        return false;
      }
      return true;
    });
  }, [vehicleCount, isForwardAuth]);

  const filtered = useMemo(
    () => filterFeatureCatalog(visibleCatalog, query),
    [visibleCatalog, query],
  );
  const grouped = useMemo(() => groupFeatureCatalog(filtered), [filtered]);

  const updateQuery = (next: string) => {
    setQuery(next);
  };

  // ── Recently visited ────────────────────────────────────────────────
  // useState + useEffect (not useSyncExternalStore) because getRecentPages()
  // returns a freshly-allocated array each call.
  const [recent, setRecent] = useState<RecentEntry[]>(() =>
    getRecentPages(RECENT_LIMIT),
  );
  useEffect(() => {
    const unsubscribe = subscribeRecentPages(() => {
      setRecent(getRecentPages(RECENT_LIMIT));
    });
    return unsubscribe;
  }, []);
  const visibleByTo = useMemo(() => {
    const map = new Map<string, FeatureCatalogEntry>();
    for (const e of visibleCatalog) {
      map.set(e.to, e);
    }
    return map;
  }, [visibleCatalog]);
  const recentResolved = useMemo(
    () =>
      recent
        .map(r => visibleByTo.get(r.path))
        .filter((x): x is FeatureCatalogEntry => Boolean(x))
        .slice(0, RECENT_LIMIT),
    [recent, visibleByTo],
  );

  // The web focused the search box on "/" via a document keydown listener — a
  // browser-only shortcut with no native document; omitted (the ref remains for
  // programmatic focus).

  const totalFeatures = visibleCatalog.length;
  const matchCount = filtered.length;

  const subtitle = query
    ? t(
        'explore.subtitle.filtered',
        '{{matches}} of {{total}} features match "{{query}}"',
        {matches: matchCount, total: totalFeatures, query},
      )
    : t('explore.subtitle.all', 'Every feature in TeslaSync — {{total}} in total.', {
        total: totalFeatures,
      });

  return (
    <PageContainer title={t('explore.title', 'Explore features')} subtitle={subtitle}>
      <View style={styles.stack}>
        {/* Recently visited — only when not filtering. */}
        {!query && recentResolved.length > 0 ? (
          <RecentStrip entries={recentResolved} onNavigate={to => navigate(to)} />
        ) : null}

        {/* Search panel (the web kept this sticky; sticky is browser-only). */}
        <View testID="explore-search-panel">
          <GlassPanel style={styles.searchPanel}>
            <View style={styles.searchRow}>
              <SemanticIcon name="search" size="sm" decorative style={styles.searchIcon} />
              <TextInput
                ref={inputRef}
                testID="explore-search"
                value={query}
                onChangeText={updateQuery}
                placeholder={t(
                  'explore.searchPlaceholder',
                  'Filter features by name, section, or description (press / to focus)',
                )}
                placeholderTextColor={colors.textMuted}
                accessibilityLabel={t('explore.searchLabel', 'Filter features')}
                autoCapitalize="none"
                autoCorrect={false}
                style={styles.searchInput}
              />
            </View>
            {grouped.length > 0 ? (
              <SectionAnchorStrip
                groups={grouped.map(g => ({
                  section: g.section,
                  count: g.entries.length,
                }))}
              />
            ) : null}
          </GlassPanel>
        </View>

        {grouped.length === 0 ? (
          <EmptyResult
            query={query}
            catalog={visibleCatalog}
            onPickSuggestion={to => {
              updateQuery('');
              navigate(to);
            }}
            onClear={() => updateQuery('')}
          />
        ) : (
          <View style={styles.sectionList}>
            {grouped.map(({section, entries}) => (
              <SectionBand
                key={section}
                section={section}
                entries={entries}
                query={query}
                onNavigate={to => navigate(to)}
              />
            ))}
          </View>
        )}
      </View>
    </PageContainer>
  );
}

/* ── Recently visited ───────────────────────────────────────────────────────── */

function RecentStrip({
  entries,
  onNavigate,
}: {
  entries: FeatureCatalogEntry[];
  onNavigate: (to: string) => void;
}) {
  const t = useNativeT();
  return (
    <View testID="explore-recent-strip">
      <View style={styles.stripHeader}>
        <AppText variant="caption" tone="secondary" weight="semibold" style={styles.kicker}>
          {t('explore.recent.heading', 'Recently visited')}
        </AppText>
        <AppText variant="caption" tone="muted">
          {String(entries.length)}
        </AppText>
      </View>
      <View style={styles.chipWrap}>
        {entries.map(entry => (
          <Pressable
            key={entry.to}
            testID={`explore-recent-${entry.to}`}
            accessibilityRole="link"
            onPress={() => onNavigate(entry.to)}
            style={({pressed}) => [styles.recentChip, pressed && styles.pressed]}>
            <SemanticIcon name={entry.icon} size="sm" decorative style={styles.chipIcon} />
            <AppText variant="caption">{entry.label}</AppText>
          </Pressable>
        ))}
      </View>
    </View>
  );
}

/* ── Anchor strip ───────────────────────────────────────────────────────────── */

function SectionAnchorStrip({
  groups,
}: {
  groups: {section: string; count: number}[];
}) {
  // The web rendered `#anchor` links that scrolled to a section; native has no
  // anchor scroll, so these stay informational count chips.
  return (
    <View style={styles.anchorWrap} testID="explore-anchor-strip">
      {groups.map(({section, count}) => (
        <View key={section} style={styles.anchorChip}>
          <AppText variant="caption" tone="secondary">
            {section}
          </AppText>
          <AppText variant="caption" tone="muted" style={styles.anchorCount}>
            {String(count)}
          </AppText>
        </View>
      ))}
    </View>
  );
}

/* ── Section band ───────────────────────────────────────────────────────────── */

function SectionBand({
  section,
  entries,
  query,
  onNavigate,
}: {
  section: string;
  entries: FeatureCatalogEntry[];
  query: string;
  onNavigate: (to: string) => void;
}) {
  return (
    <View testID={`explore-section-${slugify(section)}`}>
      <View style={styles.bandHeader}>
        <AppText variant="caption" tone="secondary" weight="semibold" style={styles.kicker}>
          {section}
        </AppText>
        <AppText variant="caption" tone="muted">
          {String(entries.length)}
        </AppText>
      </View>
      <View style={styles.cardGrid}>
        {entries.map(entry => (
          <FeatureCard
            key={entry.to}
            entry={entry}
            query={query}
            onNavigate={onNavigate}
          />
        ))}
      </View>
    </View>
  );
}

/* ── Feature card ───────────────────────────────────────────────────────────── */

function FeatureCard({
  entry,
  query,
  onNavigate,
}: {
  entry: FeatureCatalogEntry;
  query: string;
  onNavigate: (to: string) => void;
}) {
  return (
    <Pressable
      testID={`explore-card-${entry.to}`}
      accessibilityRole="link"
      accessibilityLabel={`${entry.label}. ${entry.description}`}
      onPress={() => onNavigate(entry.to)}
      style={({pressed}) => [styles.card, pressed && styles.pressed]}>
      <View style={styles.cardRow}>
        <SemanticIcon name={entry.icon} size="md" decorative style={styles.cardIcon} />
        <View style={styles.cardText}>
          <AppText weight="semibold" style={styles.cardTitle}>
            <Highlight text={entry.label} query={query} />
          </AppText>
          <AppText
            variant="caption"
            tone="secondary"
            numberOfLines={2}
            style={styles.cardDesc}>
            <Highlight text={entry.description} query={query} />
          </AppText>
        </View>
      </View>
    </Pressable>
  );
}

/* ── Highlight match in text ────────────────────────────────────────────────── */

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Wraps query-token matches in a highlighted <Text> without touching markup.
function Highlight({text, query}: {text: string; query: string}) {
  const tokens = useMemo(
    () =>
      query
        .trim()
        .toLowerCase()
        .split(/\s+/)
        .filter(tok => tok.length > 0),
    [query],
  );

  const tokenSet = useMemo(() => new Set(tokens), [tokens]);

  const splitter = useMemo(() => {
    if (tokens.length === 0) {
      return null;
    }
    const escaped = tokens.map(escapeRegExp).join('|');
    return new RegExp(`(${escaped})`, 'i');
  }, [tokens]);

  if (tokens.length === 0 || !splitter) {
    return <>{text}</>;
  }

  const parts = text.split(splitter);
  return (
    <>
      {parts.map((part, i) => {
        const isMatch = tokenSet.has(part.toLowerCase());
        if (!isMatch) {
          return <Text key={i}>{part}</Text>;
        }
        return (
          <Text key={i} style={styles.mark}>
            {part}
          </Text>
        );
      })}
    </>
  );
}

/* ── Empty state ────────────────────────────────────────────────────────────── */

function EmptyResult({
  query,
  catalog,
  onPickSuggestion,
  onClear,
}: {
  query: string;
  catalog: FeatureCatalogEntry[];
  onPickSuggestion: (to: string) => void;
  onClear: () => void;
}) {
  const t = useNativeT();
  const visiblePaths = useMemo(
    () => new Set(catalog.map(c => c.to)),
    [catalog],
  );
  const suggestions = useMemo(() => {
    const fromRegistry = closestRoutes(query, ROUTE_REGISTRY, 5);
    const fromLabels = closestRoutes(
      query,
      catalog.map(c => ({
        path: c.to,
        name: c.label.replace(/\s+/g, ''),
        label: c.label,
        i18nKey: '',
      })),
      5,
    );
    const seen = new Set<string>();
    const merged: RouteSuggestion[] = [];
    for (const r of [...fromRegistry, ...fromLabels]) {
      if (!visiblePaths.has(r.path)) {
        continue;
      }
      if (seen.has(r.path)) {
        continue;
      }
      seen.add(r.path);
      merged.push(r);
    }
    merged.sort((a, b) => a.distance - b.distance);
    return merged.slice(0, 5);
  }, [query, catalog, visiblePaths]);

  return (
    <GlassPanel style={styles.emptyPanel} testID="explore-empty">
      <SemanticIcon name="search" size="md" decorative style={styles.emptyIcon} />
      <AppText variant="title" weight="semibold" style={styles.emptyTitle}>
        {t('explore.empty.title', 'No features match "{{query}}"', {query})}
      </AppText>
      <AppText tone="secondary" style={styles.emptyBody}>
        {t(
          'explore.empty.body',
          'Try a different word, or open the command palette (⌘K) to search across pages, settings, and actions.',
        )}
      </AppText>

      {suggestions.length > 0 ? (
        <View style={styles.suggestions} testID="explore-empty-suggestions">
          <AppText variant="caption" tone="muted" style={styles.suggestionsKicker}>
            {t('explore.empty.didYouMean', 'Did you mean')}
          </AppText>
          <View style={styles.suggestionList}>
            {suggestions.map(s => (
              <Pressable
                key={s.path}
                accessibilityRole="button"
                onPress={() => onPickSuggestion(s.path)}
                style={({pressed}) => [
                  styles.suggestionRow,
                  pressed && styles.pressed,
                ]}>
                <AppText>{s.label}</AppText>
                <AppText variant="caption" tone="muted">
                  {s.path}
                </AppText>
              </Pressable>
            ))}
          </View>
        </View>
      ) : null}

      <Pressable
        accessibilityRole="button"
        onPress={onClear}
        style={({pressed}) => [styles.clearButton, pressed && styles.pressed]}>
        <AppText>{t('explore.empty.clear', 'Clear filter')}</AppText>
      </Pressable>
    </GlassPanel>
  );
}

/* ── helpers ────────────────────────────────────────────────────────────────── */

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

/* ── styles ─────────────────────────────────────────────────────────────────── */

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screenContent: {
    padding: spacing.lg,
    gap: spacing.lg,
  },
  headerText: {
    gap: spacing.xs,
  },
  subtitle: {
    marginTop: spacing.xs,
  },
  body: {
    gap: spacing.lg,
  },
  stack: {
    gap: spacing.lg,
  },
  stripHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  kicker: {
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  recentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceRaised,
  },
  chipIcon: {
    width: 22,
    height: 22,
    borderRadius: 8,
  },
  searchPanel: {
    padding: spacing.md,
    gap: spacing.md,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  searchIcon: {
    width: 26,
    height: 26,
    borderRadius: 8,
  },
  searchInput: {
    flex: 1,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.textPrimary,
    fontSize: typography.body,
  },
  anchorWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  anchorChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceRaised,
  },
  anchorCount: {
    fontVariant: ['tabular-nums'],
  },
  sectionList: {
    gap: spacing.xl,
  },
  bandHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  cardGrid: {
    gap: spacing.md,
  },
  card: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceRaised,
    padding: spacing.md,
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  cardIcon: {
    marginTop: 2,
  },
  cardText: {
    flex: 1,
    gap: spacing.xs,
  },
  cardTitle: {
    color: colors.textPrimary,
  },
  cardDesc: {
    lineHeight: 18,
  },
  mark: {
    backgroundColor: colors.accentSoft,
    color: colors.textPrimary,
  },
  pressed: {
    opacity: 0.7,
  },
  emptyPanel: {
    padding: spacing.xl,
    alignItems: 'center',
    gap: spacing.sm,
  },
  emptyIcon: {
    marginBottom: spacing.xs,
  },
  emptyTitle: {
    textAlign: 'center',
  },
  emptyBody: {
    textAlign: 'center',
  },
  suggestions: {
    alignSelf: 'stretch',
    marginTop: spacing.md,
    gap: spacing.sm,
  },
  suggestionsKicker: {
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  suggestionList: {
    gap: spacing.xs,
  },
  suggestionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 10,
    backgroundColor: colors.surfaceRaised,
  },
  clearButton: {
    marginTop: spacing.md,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 10,
    backgroundColor: colors.surfaceHover,
  },
});
