export { PrivacyKpiCards } from './PrivacyKpiCards'
export { RecentPagesPanel } from './RecentPagesPanel'
export { ConsentControlPanel } from './ConsentControlPanel'
export { PrivacyGuaranteesPanel } from './PrivacyGuaranteesPanel'
export { describeConsent, type ConsentPresentation } from './consentMeta'
