// Code generated by cmd/protogen-tesla; DO NOT EDIT.

package protomodel

import "errors"

// ErrInvalidDatum is returned by DecodeValue when the source Datum's invalid
// flag is set, meaning the producer marked this telemetry sample as not
// trustworthy. Callers MUST drop the value (do not store assumed defaults).
var ErrInvalidDatum = errors.New("protomodel: datum value is invalid")

// LocationValue is a Datum value compound type. Compounds are flattened to typed
// atomic children at the codec boundary; downstream consumers see only
// primitives and never observe nested map shapes (per ADR-004).
type LocationValue struct {
	Latitude  float64
	Longitude float64
}

// Value is a dynamic Datum value. Exactly one of the *Value pointers will be
// non-nil for a populated Datum; an Invalid==true value indicates the producer
// rejected this sample and DecodeValue will return ErrInvalidDatum.
type Value struct {
	StringValue     *string
	IntValue        *int32
	LocationValue   *LocationValue
	ShiftStateValue *ShiftState
	Invalid         *bool
}

// Datum is a single (Field, Value) pair from a Payload. The Key matches the
// proto Field enum number; Value carries the dynamic oneof payload.
type Datum struct {
	Key   Field
	Value *Value
}

// Payload holds a collection of Datums emitted at a single timestamp. Vin may
// be empty when the payload was emitted before the producer knew the VIN
// (e.g. during the bootstrap window).
type Payload struct {
	Data      []Datum
	CreatedAt int64 // unix nanos; google.protobuf.Timestamp converted at decode
	Vin       string
	IsResend  bool
}

// DecodeValue extracts the populated oneof variant from v and returns it as
// the caller-friendly Go value. Returns:
//   - (nil, nil) when v is nil or no variant is populated;
//   - (nil, ErrInvalidDatum) when v.Invalid is set to true;
//   - (underlying value, nil) for any populated scalar/enum/compound variant.
//
// The returned any is one of: string, int32, int64, float32, float64, bool,
// or a *<MessageName> / <EnumName> for compound and enum variants.
func DecodeValue(v *Value) (any, error) {
	if v == nil {
		return nil, nil
	}
	if v.Invalid != nil && *v.Invalid {
		return nil, ErrInvalidDatum
	}
	if v.StringValue != nil {
		return *v.StringValue, nil
	}
	if v.IntValue != nil {
		return *v.IntValue, nil
	}
	if v.LocationValue != nil {
		return v.LocationValue, nil
	}
	if v.ShiftStateValue != nil {
		return *v.ShiftStateValue, nil
	}
	return nil, nil
}
