// Code generated by cmd/protogen-tesla; DO NOT EDIT.

package protomodel

import "fmt"

// Field is the proto3 Field enum identifier for a Tesla telemetry signal.
// Numeric values match the Tesla Fleet Telemetry vehicle_data.proto Field
// enum exactly; do not reorder or repurpose values.
type Field int32

const (
	Field_Unknown      Field = 0
	Field_VehicleSpeed Field = 4
	Field_Gear         Field = 10
	Field_Location     Field = 21
	Field_VehicleName  Field = 64
)

// Name returns the protobuf field name for this Field. Returns the empty
// string when f is not a known Field value.
func (f Field) Name() string {
	switch f {
	case Field_Unknown:
		return "Unknown"
	case Field_VehicleSpeed:
		return "VehicleSpeed"
	case Field_Gear:
		return "Gear"
	case Field_Location:
		return "Location"
	case Field_VehicleName:
		return "VehicleName"
	}
	return ""
}

// String implements fmt.Stringer; identical to Name plus a fallback for
// unknown numeric values.
func (f Field) String() string {
	if n := f.Name(); n != "" {
		return n
	}
	return fmt.Sprintf("Field(%d)", int32(f))
}

// ParseField parses a protobuf field name (e.g. "VehicleSpeed") and returns
// the corresponding Field constant. Returns an error if the name is not a
// known Field value.
func ParseField(s string) (Field, error) {
	switch s {
	case "Unknown":
		return Field_Unknown, nil
	case "VehicleSpeed":
		return Field_VehicleSpeed, nil
	case "Gear":
		return Field_Gear, nil
	case "Location":
		return Field_Location, nil
	case "VehicleName":
		return Field_VehicleName, nil
	}
	return Field(0), fmt.Errorf("protomodel: unknown Field name %q", s)
}

// SignalMeta describes the routing classification of a telemetry signal.
// Category and UnitKind drive routing.yaml lookups and unit-history queries
// respectively; ValueKind tells the codec which Value oneof variant to expect.
type SignalMeta struct {
	Field         Field
	Name          string
	Category      string
	ValueKind     string
	IsCompound    bool
	UnitKind      string
	IsSettingUnit bool
}

// SignalMetaByField is the canonical metadata table keyed by Field. Every
// Field value declared in the proto is present, including the Unknown,
// Deprecated_*, Experimental_*, and Semitruck* sentinel values.
var SignalMetaByField = map[Field]SignalMeta{
	Field_Unknown:      {Field: Field_Unknown, Name: "Unknown", Category: "metadata", ValueKind: "string", IsCompound: false, UnitKind: "none", IsSettingUnit: false},
	Field_VehicleSpeed: {Field: Field_VehicleSpeed, Name: "VehicleSpeed", Category: "driving", ValueKind: "float", IsCompound: false, UnitKind: "none", IsSettingUnit: false},
	Field_Gear:         {Field: Field_Gear, Name: "Gear", Category: "driving", ValueKind: "enum", IsCompound: false, UnitKind: "none", IsSettingUnit: false},
	Field_Location:     {Field: Field_Location, Name: "Location", Category: "location", ValueKind: "compound:LocationValue", IsCompound: true, UnitKind: "none", IsSettingUnit: false},
	Field_VehicleName:  {Field: Field_VehicleName, Name: "VehicleName", Category: "config", ValueKind: "string", IsCompound: false, UnitKind: "none", IsSettingUnit: false},
}
