// Phase-50 / 0014 — U4 Anomaly explanation narration.
// Phase-50 / W1 (slice 0065) — wired the Generate button to
// POST /api/v1/ai/anomalies/explain.

import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

interface InnerSectionProps {
  vehicleId?: number
}

function InnerSection({ vehicleId }: InnerSectionProps) {
  const { t } = useTranslation()
  // Default analysis window: the last 30 days. Matches the dashboard's
  // default detector window so the AI narration explains the same set
  // the deterministic table is already showing.
  const body = useMemo(
    () => ({ vehicle_id: vehicleId ?? 0, days: 30 }),
    [vehicleId],
  )
  const stream = useAiStream({
    url: '/ai/anomalies/explain',
    body,
    onEvent: () => {},
  })
  const canGenerate = vehicleId != null && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('anomaly.aiExplanation.title', 'AI explanation')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('anomaly.aiExplanation.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'anomaly.aiExplanation.description',
                'Get a plain-language explanation of the anomalies the detector has already identified above.',
              )}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={!canGenerate}
            aria-disabled={!canGenerate ? 'true' : 'false'}
            onClick={() => stream.start()}
            title={t(
              'anomaly.aiExplanation.description',
              'Get a plain-language explanation of the anomalies the detector has already identified above.',
            )}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('anomaly.aiExplanation.generateButton', 'Generate explanation')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIAnomalyExplanationsInner'

export const AIAnomalyExplanations = withAiFeature(
  'anomaly-explanations',
  InnerSection,
)
AIAnomalyExplanations.displayName = 'AIAnomalyExplanations'
