// Phase-50 / 0014 — U4 Anomaly explanation narration.
//
// AIAnomalyExplanations is the visible AI surface for the anomaly
// dashboard. It is rendered conditionally via
// withAiFeature('anomaly-explanations', …) so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the anomaly-explanations
//     toggle is on, it renders an opt-in section with a Generate
//     button that would call POST /api/v1/ai/anomalies/explain.
//
// The component does NOT replace the deterministic Z-score detector
// or the static safe-range explanation strings emitted by the
// baseline anomaly handler. The detector + safe-range messages
// remain the canonical baseline visible to every user; this AI
// section is opt-in narrative prose layered alongside.
//
// The actual SSE call wiring lands in a future slice (the slice
// prompt is explicit that the F0 contract requires only the
// rendered-or-absent invariant). The current component shows the
// UI affordance with a "coming soon" disabled button so the
// off-mode test has a concrete UI test ID to assert against and the
// on-mode positive control proves the gate actually fires.

import { useTranslation } from 'react-i18next'

import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'

/**
 * InnerSection is the always-rendered body of the AI narration card.
 * The surrounding {@link withAiFeature} HOC handles the visibility
 * gate; this component only describes the surface's appearance.
 *
 * Visual contract:
 *   - One GlassPanel sized to fit alongside the anomaly dashboard's
 *     existing detected-anomalies section.
 *   - Cyan AI badge in the header (matches the chatbot brand colour).
 *   - Generate button is disabled until the SSE wiring lands.
 *   - Title attribute carries the long-form explanation so a user
 *     hovering for a tooltip understands the privacy contract.
 */
function InnerSection() {
  const { t } = useTranslation()
  return (
    <GlassPanel>
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-white/90">
              {t('anomaly.aiExplanation.title', 'AI explanation')}
            </h3>
            <span
              className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
              title={t(
                'chatbot.llm.indicatorTooltip',
                'Responses are generated by an LLM with redacted vehicle context.',
              )}
              aria-label={t('chatbot.llm.indicator', 'AI mode')}
            >
              <span
                className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                aria-hidden="true"
              />
              {t('anomaly.aiExplanation.badge', 'AI')}
            </span>
          </div>
          <p className="text-sm text-white/60">
            {t(
              'anomaly.aiExplanation.description',
              'Get a plain-language explanation of the anomalies the detector has already identified above.',
            )}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          disabled
          aria-disabled="true"
          title={t(
            'anomaly.aiExplanation.description',
            'Get a plain-language explanation of the anomalies the detector has already identified above.',
          )}
        >
          {t('anomaly.aiExplanation.generateButton', 'Generate explanation')}
        </Button>
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIAnomalyExplanationsInner'

/**
 * AIAnomalyExplanations renders the LLM anomaly explanation section
 * only when the anomaly-explanations feature is enabled. The wrapping
 * div from {@link withAiFeature} carries
 * `data-testid="ai-feature-anomaly-explanations-root"`, which the
 * off-mode invariant test asserts against.
 */
export const AIAnomalyExplanations = withAiFeature(
  'anomaly-explanations',
  InnerSection,
)
AIAnomalyExplanations.displayName = 'AIAnomalyExplanations'
