// Phase-50 / 0024 — D4 Auto trip naming.
//
// AIAutoTripNameSuggestion is the visible AI surface for the Trip
// Detail page. It is rendered conditionally via
// withAiFeature('auto-trip-naming', …) so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the auto-trip-naming
//     toggle is on, it renders an opt-in section with a Suggest
//     button that would call
//     POST /api/v1/ai/trips/{tripID}/name/draft.
//
// The component does NOT replace the deterministic stat cards,
// KVList of trip metadata, drive list, or the manual trip-name
// field rendered by TripDetailPage. That baseline content remains
// the canonical view visible to every user; this AI section is
// opt-in propose-only naming layered alongside.
//
// The actual SSE call + structured proposal rendering land in a
// future slice (the slice prompt is explicit that the F0 contract
// requires only the rendered-or-absent invariant). The current
// component shows the UI affordance with a disabled "Suggest a
// name" button so the off-mode test has a concrete UI test ID to
// assert against and the on-mode positive control proves the gate
// actually fires.

import { useTranslation } from 'react-i18next'

import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'

interface InnerSectionProps {
  /**
   * tripId surfaced by the parent TripDetailPage. Optional because
   * `useParams()` returns `string | undefined`; when absent we
   * still render the section (the gate has already passed) but
   * the Suggest button stays disabled because the backend call
   * needs a trip in scope.
   */
  tripId?: string
}

/**
 * InnerSection is the always-rendered body of the AI auto-trip-name
 * card. The surrounding {@link withAiFeature} HOC handles the
 * visibility gate; this component only describes the surface's
 * appearance.
 *
 * Visual contract:
 *   - One GlassPanel sized to sit above the trip-detail stat cards
 *     on TripDetailPage.
 *   - Cyan AI badge in the header (matches the chatbot brand
 *     colour).
 *   - Suggest button is disabled until the SSE wiring lands AND
 *     when no tripId is available from the parent route.
 *   - Title attribute carries the long-form explanation so a user
 *     hovering for a tooltip understands the privacy contract —
 *     only the vehicle name may be narrated; lat/long, street
 *     addresses, and place names remain tagged by the per-feature
 *     redaction policy. The save action requires explicit user
 *     confirmation — the AI never persists anything.
 */
function InnerSection({ tripId }: InnerSectionProps) {
  const { t } = useTranslation()
  const buttonDisabled = !tripId
  return (
    <GlassPanel>
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-white/90">
              {t('trips.detail.aiSuggestName.title', 'Suggest a trip name')}
            </h3>
            <span
              className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
              title={t(
                'chatbot.llm.indicatorTooltip',
                'Responses are generated by an LLM with redacted vehicle context.',
              )}
              aria-label={t('chatbot.llm.indicator', 'AI mode')}
            >
              <span
                className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                aria-hidden="true"
              />
              {t('trips.detail.aiSuggestName.badge', 'AI')}
            </span>
          </div>
          <p className="text-sm text-white/60">
            {t(
              'trips.detail.aiSuggestName.description',
              'Get a short, propose-only name suggestion grounded in this trip\u2019s route context (start and end places, drive count, distance, time window). The suggestion is never saved automatically \u2014 review the proposed name in the panel and click Save to apply it.',
            )}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          disabled={buttonDisabled}
          aria-disabled={buttonDisabled ? 'true' : 'false'}
          title={t(
            'trips.detail.aiSuggestName.description',
            'Get a short, propose-only name suggestion grounded in this trip\u2019s route context (start and end places, drive count, distance, time window). The suggestion is never saved automatically \u2014 review the proposed name in the panel and click Save to apply it.',
          )}
        >
          {t('trips.detail.aiSuggestName.generateButton', 'Suggest a name')}
        </Button>
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIAutoTripNameSuggestionInner'

/**
 * AIAutoTripNameSuggestion renders the LLM auto-trip-name section
 * only when the auto-trip-naming feature is enabled. The wrapping
 * div from {@link withAiFeature} carries
 * `data-testid="ai-feature-auto-trip-naming-root"`, which the
 * off-mode invariant test asserts against.
 */
export const AIAutoTripNameSuggestion = withAiFeature(
  'auto-trip-naming',
  InnerSection,
)
AIAutoTripNameSuggestion.displayName = 'AIAutoTripNameSuggestion'
