// Phase-50 / 0024 — D4 Auto trip naming.
// Phase-50 / W1 (slice 0065) — wired the Suggest button to
// POST /api/v1/ai/trips/{tripID}/name/draft (empty body).

import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

interface InnerSectionProps {
  tripId?: string
}

function InnerSection({ tripId }: InnerSectionProps) {
  const { t } = useTranslation()
  const url = useMemo(
    () =>
      tripId
        ? `/ai/trips/${encodeURIComponent(tripId)}/name/draft`
        : '/ai/trips/0/name/draft',
    [tripId],
  )
  const body = useMemo(() => ({}), [])
  const stream = useAiStream({ url, body, onEvent: () => {} })
  const canGenerate = !!tripId && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('trips.detail.aiSuggestName.title', 'Suggest a trip name')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('trips.detail.aiSuggestName.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'trips.detail.aiSuggestName.description',
                'Get a short, propose-only name suggestion grounded in this trip\u2019s route context (start and end places, drive count, distance, time window). The suggestion is never saved automatically \u2014 review the proposed name in the panel and click Save to apply it.',
              )}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={!canGenerate}
            aria-disabled={!canGenerate ? 'true' : 'false'}
            onClick={() => stream.start()}
            title={t(
              'trips.detail.aiSuggestName.description',
              'Get a short, propose-only name suggestion grounded in this trip\u2019s route context (start and end places, drive count, distance, time window). The suggestion is never saved automatically \u2014 review the proposed name in the panel and click Save to apply it.',
            )}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('trips.detail.aiSuggestName.generateButton', 'Suggest a name')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIAutoTripNameSuggestionInner'

export const AIAutoTripNameSuggestion = withAiFeature('auto-trip-naming', InnerSection)
AIAutoTripNameSuggestion.displayName = 'AIAutoTripNameSuggestion'
