// Phase-50 / 0027 — C2 Battery health forecast narrative.
//
// AIBatteryHealthForecastNarrative is the visible AI surface for
// the Battery Health page. It is rendered conditionally via
// withAiFeature('battery-health-forecast-narrative', …) so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the
//     battery-health-forecast-narrative toggle is on, it renders an
//     opt-in section with a Narrate button that would call
//     POST /api/v1/ai/battery/health/narrate.
//
// The component does NOT replace the deterministic Capacity Trend
// & Prediction chart, hero metric cards, range trend chart, charge
// level distribution, insights panel, or recommendations panel
// rendered by BatteryHealthPage. That baseline content remains the
// canonical view visible to every user; this AI section is opt-in
// read-only narration layered alongside.
//
// The actual SSE call + structured narration rendering land in a
// future slice (the slice prompt is explicit that the F0 contract
// requires only the rendered-or-absent invariant). The current
// component shows the UI affordance with a disabled "Narrate
// forecast" button so the off-mode test has a concrete UI test ID
// to assert against and the on-mode positive control proves the
// gate actually fires.

import { useTranslation } from 'react-i18next'

import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'

interface InnerSectionProps {
  /**
   * vehicleId surfaced by the parent BatteryHealthPage. Optional
   * because the active-vehicle context may be unresolved at first
   * paint; when absent we still render the section (the gate has
   * already passed) but the Narrate button stays disabled because
   * the backend call needs a vehicle in scope.
   */
  vehicleId?: string | number
}

/**
 * InnerSection is the always-rendered body of the AI battery-health
 * forecast narrator card. The surrounding {@link withAiFeature} HOC
 * handles the visibility gate; this component only describes the
 * surface's appearance.
 *
 * Visual contract:
 *   - One GlassPanel sized to sit above the battery hero metric
 *     cards on BatteryHealthPage.
 *   - Cyan AI badge in the header (matches the chatbot brand
 *     colour).
 *   - Narrate button is disabled until the SSE wiring lands AND
 *     when no vehicleId is available from the active-vehicle
 *     context.
 *   - Title attribute carries the long-form explanation so a user
 *     hovering for a tooltip understands the privacy contract —
 *     only the vehicle name may be narrated; lat/long, street
 *     addresses, place names, and charging-location identifiers
 *     remain tagged by the per-feature redaction policy. The
 *     narrator never changes the deterministic forecast — it only
 *     explains the drivers.
 */
function InnerSection({ vehicleId }: InnerSectionProps) {
  const { t } = useTranslation()
  const buttonDisabled = !vehicleId
  return (
    <GlassPanel>
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-white/90">
              {t('battery.aiNarrative.title', 'Explain the battery health forecast')}
            </h3>
            <span
              className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
              title={t(
                'chatbot.llm.indicatorTooltip',
                'Responses are generated by an LLM with redacted vehicle context.',
              )}
              aria-label={t('chatbot.llm.indicator', 'AI mode')}
            >
              <span
                className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                aria-hidden="true"
              />
              {t('battery.aiNarrative.badge', 'AI')}
            </span>
          </div>
          <p className="text-sm text-white/60">
            {t(
              'battery.aiNarrative.description',
              'Ask the AI narrator to explain which charging habits and risk factors drive your deterministic battery-health forecast. The narrator never changes the forecast \u2014 it grounds every sentence in the same numbers the chart below renders.',
            )}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          disabled={buttonDisabled}
          aria-disabled={buttonDisabled ? 'true' : 'false'}
          title={t(
            'battery.aiNarrative.description',
            'Ask the AI narrator to explain which charging habits and risk factors drive your deterministic battery-health forecast. The narrator never changes the forecast \u2014 it grounds every sentence in the same numbers the chart below renders.',
          )}
        >
          {t('battery.aiNarrative.generateButton', 'Narrate forecast')}
        </Button>
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIBatteryHealthForecastNarrativeInner'

/**
 * AIBatteryHealthForecastNarrative renders the LLM battery-health
 * forecast narrator section only when the
 * battery-health-forecast-narrative feature is enabled. The wrapping
 * div from {@link withAiFeature} carries
 * `data-testid="ai-feature-battery-health-forecast-narrative-root"`,
 * which the off-mode invariant test asserts against.
 */
export const AIBatteryHealthForecastNarrative = withAiFeature(
  'battery-health-forecast-narrative',
  InnerSection,
)
AIBatteryHealthForecastNarrative.displayName = 'AIBatteryHealthForecastNarrative'
