// Phase-50 / 0019 — N5 Per-charging-session diagnosis.
//
// AIChargingDiagnosis is the visible AI surface for the charging
// detail page. It is rendered conditionally via
// withAiFeature('charging-diagnosis', …) so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the charging-diagnosis
//     toggle is on, it renders an opt-in section with a Generate
//     button that would call POST /api/v1/ai/charging/{sessionID}/diagnose.
//
// The component does NOT replace the deterministic per-charging-session
// flag badges (trickle, expensive, low-power, interrupted),
// hero gauges, charge curve, or any other section already rendered
// by ChargingDetailPage. Those baseline panels remain the canonical
// view visible to every user; this AI section is opt-in narrative
// prose layered alongside.
//
// The actual SSE call wiring lands in a future slice (the slice
// prompt is explicit that the F0 contract requires only the
// rendered-or-absent invariant). The current component shows the
// UI affordance with a "coming soon" disabled button so the
// off-mode test has a concrete UI test ID to assert against and the
// on-mode positive control proves the gate actually fires.

import { useTranslation } from 'react-i18next'

import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'

interface InnerSectionProps {
  /**
   * sessionId surfaced by the parent ChargingDetailPage. Optional
   * because the charging detail route's `useParams<{id}>()` returns
   * `string | undefined`; when absent we still render the section
   * (the gate has already passed) but the Generate button stays
   * disabled.
   */
  sessionId?: string
}

/**
 * InnerSection is the always-rendered body of the AI diagnosis card.
 * The surrounding {@link withAiFeature} HOC handles the visibility
 * gate; this component only describes the surface's appearance.
 *
 * Visual contract:
 *   - One GlassPanel sized to fit alongside ChargingDetailPage's
 *     existing flag badges / hero gauges / charge curve.
 *   - Cyan AI badge in the header (matches the chatbot brand colour).
 *   - Generate button is disabled until the SSE wiring lands AND when
 *     no sessionId is available from the parent route.
 *   - Title attribute carries the long-form explanation so a user
 *     hovering for a tooltip understands the privacy contract.
 */
function InnerSection({ sessionId }: InnerSectionProps) {
  const { t } = useTranslation()
  const buttonDisabled = !sessionId
  return (
    <GlassPanel>
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-white/90">
              {t('charging.detail.aiDiagnosis.title', 'Charging diagnosis')}
            </h3>
            <span
              className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
              title={t(
                'chatbot.llm.indicatorTooltip',
                'Responses are generated by an LLM with redacted vehicle context.',
              )}
              aria-label={t('chatbot.llm.indicator', 'AI mode')}
            >
              <span
                className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                aria-hidden="true"
              />
              {t('charging.detail.aiDiagnosis.badge', 'AI')}
            </span>
          </div>
          <p className="text-sm text-white/60">
            {t(
              'charging.detail.aiDiagnosis.description',
              'Get a 2-4 paragraph plain-language explanation of any flags raised on this charging session — trickle, expensive, low-power, or interrupted — generated from the same deterministic aggregation metrics shown above.',
            )}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          disabled={buttonDisabled}
          aria-disabled={buttonDisabled ? 'true' : 'false'}
          title={t(
            'charging.detail.aiDiagnosis.description',
            'Get a 2-4 paragraph plain-language explanation of any flags raised on this charging session — trickle, expensive, low-power, or interrupted — generated from the same deterministic aggregation metrics shown above.',
          )}
        >
          {t('charging.detail.aiDiagnosis.generateButton', 'Generate diagnosis')}
        </Button>
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIChargingDiagnosisInner'

/**
 * AIChargingDiagnosis renders the LLM charging diagnosis section
 * only when the charging-diagnosis feature is enabled. The wrapping
 * div from {@link withAiFeature} carries
 * `data-testid="ai-feature-charging-diagnosis-root"`, which the
 * off-mode invariant test asserts against.
 */
export const AIChargingDiagnosis = withAiFeature('charging-diagnosis', InnerSection)
AIChargingDiagnosis.displayName = 'AIChargingDiagnosis'
