// Phase-50 / 0019 — N5 Per-charging-session diagnosis.
// Phase-50 / W1 (slice 0065) — wired the Generate button to
// POST /api/v1/ai/charging/{sessionID}/diagnose (empty body).

import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

interface InnerSectionProps {
  /**
   * sessionId surfaced by the parent ChargingDetailPage. Optional
   * because the charging detail route's `useParams<{id}>()` returns
   * `string | undefined`; when absent we still render the section
   * (the gate has already passed) but the Generate button stays
   * disabled.
   */
  sessionId?: string
}

function InnerSection({ sessionId }: InnerSectionProps) {
  const { t } = useTranslation()
  const url = useMemo(
    () =>
      sessionId
        ? `/ai/charging/${encodeURIComponent(sessionId)}/diagnose`
        : '/ai/charging/0/diagnose',
    [sessionId],
  )
  const body = useMemo(() => ({}), [])
  const stream = useAiStream({ url, body, onEvent: () => {} })
  const canGenerate = !!sessionId && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('charging.detail.aiDiagnosis.title', 'Charging diagnosis')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('charging.detail.aiDiagnosis.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'charging.detail.aiDiagnosis.description',
                'Get a 2-4 paragraph plain-language explanation of any flags raised on this charging session — trickle, expensive, low-power, or interrupted — generated from the same deterministic aggregation metrics shown above.',
              )}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={!canGenerate}
            aria-disabled={!canGenerate ? 'true' : 'false'}
            onClick={() => stream.start()}
            title={t(
              'charging.detail.aiDiagnosis.description',
              'Get a 2-4 paragraph plain-language explanation of any flags raised on this charging session — trickle, expensive, low-power, or interrupted — generated from the same deterministic aggregation metrics shown above.',
            )}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('charging.detail.aiDiagnosis.generateButton', 'Generate diagnosis')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIChargingDiagnosisInner'

export const AIChargingDiagnosis = withAiFeature('charging-diagnosis', InnerSection)
AIChargingDiagnosis.displayName = 'AIChargingDiagnosis'
