// AIChatbotIndicator is the visible AI surface for the chatbot page.
// It is rendered conditionally via withAiFeature('chatbot-llm', …) so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the chatbot-llm toggle is on,
//     it renders a small badge that tells the user the responses are
//     generated by an LLM (so the user knows redaction + tools are
//     active).
//
// The indicator does NOT replace the chatbot's send/receive plumbing.
// In off mode the page uses POST /chatbot (heuristic baseline). The
// AI route at POST /api/v1/ai/chatbot is wired by ChatbotPage.tsx,
// which calls useAiStream when the chatbot-llm feature is enabled.
// This indicator file is allowlisted in
// internal/ai/features.SPAWiringIndicatorOnly because the wiring
// lives on the page, not here — but it remains subject to the W1-A
// no-placeholder rule.

import { useTranslation } from 'react-i18next'

import { HelixMark } from '@/components/branding/HelixMark'
import { withAiFeature } from '@/components/ai/withAiFeature'

/**
 * InnerIndicator is the always-rendered body of the AI badge. The
 * surrounding {@link withAiFeature} HOC handles the visibility gate;
 * this component only describes the marker's appearance.
 *
 * Visual contract:
 *   - One small inline-flex chip in the chatbot page header.
 *   - Cyan accent (matches the chatbot brand colour).
 *   - Title attribute carries the long-form explanation so a user
 *     hovering for a tooltip understands what AI mode means.
 *   - `role="img"` + `aria-label` present the icon-and-label chip as a
 *     single labelled graphic (matching the CarAnimation / Avatar
 *     convention). Without an explicit role, `aria-label` on a
 *     roleless generic <span> is not reliably surfaced to the
 *     accessibility tree, so the decorative {@link HelixMark} could be
 *     the only thing an AT sees — and it is `aria-hidden`. The title
 *     then acts as the accessible description.
 */
function InnerIndicator() {
  const { t } = useTranslation()
  return (
    <span
      className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
      role="img"
      title={t(
        'helix.tooltip',
        'Helix grounds responses in redacted TeslaSync data, application knowledge, and explicit tool evidence.',
      )}
      aria-label={t('helix.ariaLabel', 'Helix')}
    >
      <HelixMark
        className="h-3.5 w-3.5 text-cyan-300"
        aria-hidden="true"
      />
      {t('helix.badge', 'Helix')}
    </span>
  )
}
InnerIndicator.displayName = 'InnerIndicator'

/**
 * AIChatbotIndicator renders the LLM-mode badge only when the
 * chatbot-llm feature is enabled. The wrapping div from
 * {@link withAiFeature} carries `data-testid="ai-feature-chatbot-llm-root"`,
 * which the off-mode invariant test asserts against.
 */
export const AIChatbotIndicator = withAiFeature('chatbot-llm', InnerIndicator)
AIChatbotIndicator.displayName = 'AIChatbotIndicator'
