// Phase-50 / 0012 — U2 Weekly digest narration.
//
// AIDigestNarration is the visible AI surface for the weekly-digest
// page. It is rendered conditionally via withAiFeature('digest-narration', …)
// so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the digest-narration toggle
//     is on, it renders an opt-in section with a Generate button that
//     would call POST /api/v1/ai/digests/weekly/narrate.
//
// The component does NOT replace the deterministic template digest
// (DrivingSection, ChargingSection, BatteryHealthSection, etc.). The
// template digest remains the canonical baseline visible to every
// user; this AI section is opt-in narrative prose layered alongside.
//
// The actual SSE call wiring lands in a future slice (the slice
// prompt is explicit that the F0 contract requires only the
// rendered-or-absent invariant). The current component shows the
// UI affordance with a "coming soon" disabled button so the
// off-mode test has a concrete UI test ID to assert against and the
// on-mode positive control proves the gate actually fires.

import { useTranslation } from 'react-i18next'

import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'

/**
 * InnerSection is the always-rendered body of the AI narration card.
 * The surrounding {@link withAiFeature} HOC handles the visibility
 * gate; this component only describes the surface's appearance.
 *
 * Visual contract:
 *   - One GlassPanel inside the digest page's space-y-8 stack.
 *   - Cyan AI badge in the header (matches the chatbot brand colour).
 *   - Generate button is disabled until the SSE wiring lands.
 *   - Title attribute carries the long-form explanation so a user
 *     hovering for a tooltip understands the privacy contract.
 */
function InnerSection() {
  const { t } = useTranslation()
  return (
    <GlassPanel>
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-white/90">
              {t('analytics.weeklyDigest.aiNarration.title', 'AI narration')}
            </h3>
            <span
              className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
              title={t(
                'chatbot.llm.indicatorTooltip',
                'Responses are generated by an LLM with redacted vehicle context.',
              )}
              aria-label={t('chatbot.llm.indicator', 'AI mode')}
            >
              <span
                className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                aria-hidden="true"
              />
              {t('analytics.weeklyDigest.aiNarration.badge', 'AI')}
            </span>
          </div>
          <p className="text-sm text-white/60">
            {t(
              'analytics.weeklyDigest.aiNarration.description',
              'Get a short, AI-written recap of your week from the digest data above.',
            )}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          disabled
          aria-disabled="true"
          title={t(
            'analytics.weeklyDigest.aiNarration.description',
            'Get a short, AI-written recap of your week from the digest data above.',
          )}
        >
          {t('analytics.weeklyDigest.aiNarration.generateButton', 'Generate narration')}
        </Button>
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIDigestNarrationInner'

/**
 * AIDigestNarration renders the LLM digest section only when the
 * digest-narration feature is enabled. The wrapping div from
 * {@link withAiFeature} carries
 * `data-testid="ai-feature-digest-narration-root"`, which the
 * off-mode invariant test asserts against.
 */
export const AIDigestNarration = withAiFeature('digest-narration', InnerSection)
AIDigestNarration.displayName = 'AIDigestNarration'
