// Phase-50 / 0012 — U2 Weekly digest narration.
// Phase-50 / W1 (slice 0065) — wired the Generate button to
// POST /api/v1/ai/digests/weekly/narrate.
//
// AIDigestNarration is the visible AI surface for the weekly-digest
// page. It is rendered conditionally via withAiFeature('digest-narration', …)
// so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is on AND the digest-narration toggle is on, it
//     renders an opt-in section that streams a narrated recap.
//
// The component does NOT replace the deterministic template digest
// (DrivingSection, ChargingSection, BatteryHealthSection, etc.). The
// template digest remains the canonical baseline visible to every
// user; this AI section is opt-in narrative prose layered alongside.

import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

interface InnerSectionProps {
  vehicleId?: number
}

function InnerSection({ vehicleId }: InnerSectionProps) {
  const { t } = useTranslation()
  const body = useMemo(
    () => ({ vehicle_id: vehicleId ?? 0, week_offset_weeks: 0 }),
    [vehicleId],
  )
  const stream = useAiStream({
    url: '/ai/digests/weekly/narrate',
    body,
    onEvent: () => {},
  })
  const canGenerate = vehicleId != null && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('analytics.weeklyDigest.aiNarration.title', 'AI narration')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('analytics.weeklyDigest.aiNarration.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'analytics.weeklyDigest.aiNarration.description',
                'Get a short, AI-written recap of your week from the digest data above.',
              )}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={!canGenerate}
            aria-disabled={!canGenerate ? 'true' : 'false'}
            onClick={() => stream.start()}
            title={t(
              'analytics.weeklyDigest.aiNarration.description',
              'Get a short, AI-written recap of your week from the digest data above.',
            )}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('analytics.weeklyDigest.aiNarration.generateButton', 'Generate narration')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIDigestNarrationInner'

export const AIDigestNarration = withAiFeature('digest-narration', InnerSection)
AIDigestNarration.displayName = 'AIDigestNarration'
