// Phase-50 / 0018 — N4 Per-drive coaching narrative.
// Phase-50 / W1 (slice 0065) — wired the Generate button to the SSE
// endpoint at POST /api/v1/ai/drives/{driveID}/coach (empty body).
//
// AIDriveCoaching is the visible AI surface for the drive detail
// page. It is rendered conditionally via
// withAiFeature('drive-coaching', …) so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When AI is on AND the drive-coaching toggle is on, this
//     component renders the opt-in panel with the Generate button.
//
// The component does NOT replace the deterministic per-drive stat
// cards, hero gauges, energy summary, or any other section already
// rendered by DriveDetailPage. Those baseline panels remain the
// canonical view visible to every user; this AI section is opt-in
// narrative prose layered alongside.

import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

interface InnerSectionProps {
  /**
   * driveID surfaced by the parent DriveDetailPage. Optional because
   * the drive detail route's `useParams<{id}>()` returns
   * `string | undefined`; when absent we still render the section
   * (the gate has already passed) but the Generate button stays
   * disabled.
   */
  driveId?: string
}

/**
 * InnerSection is the always-rendered body of the AI narration card
 * when AI is on. The surrounding {@link withAiFeature} HOC handles
 * the visibility gate; this component only describes the surface's
 * appearance + the SSE call.
 *
 * SSE contract: POST /api/v1/ai/drives/{driveID}/coach with empty
 * body. The handler parses driveID from the URL and streams the
 * coaching narrative as `delta` text frames terminated by `done`.
 * `useAiStream` accumulates delta payloads into `stream.text` for us
 * — no manual onEvent handling needed for narrative output.
 */
function InnerSection({ driveId }: InnerSectionProps) {
  const { t } = useTranslation()
  const url = useMemo(
    () => (driveId ? `/ai/drives/${encodeURIComponent(driveId)}/coach` : '/ai/drives/0/coach'),
    [driveId],
  )
  const body = useMemo(() => ({}), [])
  const stream = useAiStream({ url, body, onEvent: () => {} })
  const canGenerate = !!driveId && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('driveDetail.aiCoaching.title', 'Drive coaching')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('driveDetail.aiCoaching.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'driveDetail.aiCoaching.description',
                'Get a 2-4 paragraph plain-language coaching summary of this drive — efficiency, regen use, and notable braking or acceleration moments — generated from the same per-drive metrics shown above.',
              )}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={!canGenerate}
            aria-disabled={!canGenerate ? 'true' : 'false'}
            onClick={() => stream.start()}
            title={t(
              'driveDetail.aiCoaching.description',
              'Get a 2-4 paragraph plain-language coaching summary of this drive — efficiency, regen use, and notable braking or acceleration moments — generated from the same per-drive metrics shown above.',
            )}
          >
            {stream.state === 'streaming'
              ? t('driveDetail.aiCoaching.generating', 'Generating…')
              : t('driveDetail.aiCoaching.generateButton', 'Generate coaching')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIDriveCoachingInner'

/**
 * AIDriveCoaching renders the LLM drive coaching section only when
 * the drive-coaching feature is enabled. The wrapping div from
 * {@link withAiFeature} carries
 * `data-testid="ai-feature-drive-coaching-root"`, which the off-mode
 * invariant test asserts against.
 */
export const AIDriveCoaching = withAiFeature('drive-coaching', InnerSection)
AIDriveCoaching.displayName = 'AIDriveCoaching'
