// Phase-50 / 0018 — N4 Per-drive coaching narrative.
//
// AIDriveCoaching is the visible AI surface for the drive detail
// page. It is rendered conditionally via
// withAiFeature('drive-coaching', …) so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the drive-coaching toggle
//     is on, it renders an opt-in section with a Generate button
//     that would call POST /api/v1/ai/drives/{driveID}/coach.
//
// The component does NOT replace the deterministic per-drive stat
// cards, hero gauges, energy summary, or any other section already
// rendered by DriveDetailPage. Those baseline panels remain the
// canonical view visible to every user; this AI section is opt-in
// narrative prose layered alongside.
//
// The actual SSE call wiring lands in a future slice (the slice
// prompt is explicit that the F0 contract requires only the
// rendered-or-absent invariant). The current component shows the
// UI affordance with a "coming soon" disabled button so the
// off-mode test has a concrete UI test ID to assert against and the
// on-mode positive control proves the gate actually fires.

import { useTranslation } from 'react-i18next'

import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'

interface InnerSectionProps {
  /**
   * driveID surfaced by the parent DriveDetailPage. Optional because
   * the drive detail route's `useParams<{id}>()` returns
   * `string | undefined`; when absent we still render the section
   * (the gate has already passed) but the Generate button stays
   * disabled.
   */
  driveId?: string
}

/**
 * InnerSection is the always-rendered body of the AI narration card.
 * The surrounding {@link withAiFeature} HOC handles the visibility
 * gate; this component only describes the surface's appearance.
 *
 * Visual contract:
 *   - One GlassPanel sized to fit alongside DriveDetailPage's existing
 *     stat cards / hero gauges / energy summary.
 *   - Cyan AI badge in the header (matches the chatbot brand colour).
 *   - Generate button is disabled until the SSE wiring lands AND when
 *     no driveId is available from the parent route.
 *   - Title attribute carries the long-form explanation so a user
 *     hovering for a tooltip understands the privacy contract.
 */
function InnerSection({ driveId }: InnerSectionProps) {
  const { t } = useTranslation()
  const buttonDisabled = !driveId
  return (
    <GlassPanel>
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-white/90">
              {t('driveDetail.aiCoaching.title', 'Drive coaching')}
            </h3>
            <span
              className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
              title={t(
                'chatbot.llm.indicatorTooltip',
                'Responses are generated by an LLM with redacted vehicle context.',
              )}
              aria-label={t('chatbot.llm.indicator', 'AI mode')}
            >
              <span
                className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                aria-hidden="true"
              />
              {t('driveDetail.aiCoaching.badge', 'AI')}
            </span>
          </div>
          <p className="text-sm text-white/60">
            {t(
              'driveDetail.aiCoaching.description',
              'Get a 2-4 paragraph plain-language coaching summary of this drive — efficiency, regen use, and notable braking or acceleration moments — generated from the same per-drive metrics shown above.',
            )}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          disabled={buttonDisabled}
          aria-disabled={buttonDisabled ? 'true' : 'false'}
          title={t(
            'driveDetail.aiCoaching.description',
            'Get a 2-4 paragraph plain-language coaching summary of this drive — efficiency, regen use, and notable braking or acceleration moments — generated from the same per-drive metrics shown above.',
          )}
        >
          {t('driveDetail.aiCoaching.generateButton', 'Generate coaching')}
        </Button>
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIDriveCoachingInner'

/**
 * AIDriveCoaching renders the LLM drive coaching section only when
 * the drive-coaching feature is enabled. The wrapping div from
 * {@link withAiFeature} carries
 * `data-testid="ai-feature-drive-coaching-root"`, which the off-mode
 * invariant test asserts against.
 */
export const AIDriveCoaching = withAiFeature('drive-coaching', InnerSection)
AIDriveCoaching.displayName = 'AIDriveCoaching'
