// Phase-50 / 0064 — ML3 Charging-curve fingerprint clustering
// statistical model. Wires the "Train charging-curve clusters"
// button to POST /api/v1/ai/ml/charging-curves/cluster. The
// narration walks the user through the per-cluster (L1 overnight /
// L2 workplace / DC fast / unknown) LEARNED charging envelope
// (mean peak power plus stddev / p5 / p95 per cluster, mean avg
// power / total energy / duration / ramp shape) returned by
// train_charge_curve_clusters AND the deterministic rule-label
// fallback per cluster (when fewer than
// mlchargingcurves.DefaultMinSessionsPerCluster=3 sessions exist
// in the lookback window), then summarises the
// currently-effective baseline via query_charge_curve_clusters.
//
// The AI never persists state — it is read-only narration over
// the learned envelope; the canonical Charging Curve page at
// /charging/curves with the existing rule-based session labels
// (web/src/features/charging/components/charging-curve/helpers.ts)
// is unchanged (ADR-015 §I3 + §I8 propose-only contract).
//
// Sibling distinction: this is the ML3-tier *statistical
// clustering* model. The C3-tier *charging-curve-fingerprint-
// clustering* slice 0028 is a separate LLM narrator over the C3
// aggregator's output; both surfaces coexist on /charging/curves
// with independent per-feature toggles and independent test IDs.

import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

interface InnerSectionProps {
  vehicleId?: number
}

function InnerSection({ vehicleId }: InnerSectionProps) {
  const { t } = useTranslation()
  // Default learning window: the last 90 days. Charging sessions
  // are O(0.1–1/day) per vehicle (the prompt's
  // DefaultMinSessionsPerCluster=3 acknowledges this), so a 90-day
  // window is what the trainer needs to cover representative
  // L1/L2/DC behaviour. The Go trainer clamps the upper bound at
  // mlchargingcurves.MaxLookbackDays=365, so wider values are
  // silently capped server-side. Mirrors the SPA Charging Curve
  // page's default lookback for parity with the baseline charts.
  const body = useMemo(
    () => ({ vehicle_id: vehicleId ?? 0, lookback_days: 90 }),
    [vehicleId],
  )
  const stream = useAiStream({
    url: '/ai/ml/charging-curves/cluster',
    body,
    onEvent: () => {},
  })
  // Computed disabled — never literal-true. P12/W1-A enforces this
  // statically at slice 0065+, but the explicit boolean expression
  // also keeps the on-mode wiring test honest: a regression that
  // pins the button as always-disabled would silently falsify the
  // double-submit guard test.
  const canGenerate = vehicleId != null && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t(
                  'charging.aiMlClustering.title',
                  'Learn per-vehicle charging-curve clusters',
                )}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('charging.aiMlClustering.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'charging.aiMlClustering.description',
                'Compute per-cluster (L1 overnight / L2 workplace / DC fast) learned charging envelope from this vehicle’s recent sessions and walk through how each cluster compares to the deterministic rule-label baseline used by the Charging Curve page today.',
              )}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={!canGenerate}
            aria-disabled={!canGenerate ? 'true' : 'false'}
            onClick={() => stream.start()}
            title={t(
              'charging.aiMlClustering.description',
              'Compute per-cluster (L1 overnight / L2 workplace / DC fast) learned charging envelope from this vehicle’s recent sessions and walk through how each cluster compares to the deterministic rule-label baseline used by the Charging Curve page today.',
            )}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t(
                  'charging.aiMlClustering.generateButton',
                  'Train charging-curve clusters',
                )}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIMLChargingCurveClusteringInner'

export const AIMLChargingCurveClustering = withAiFeature(
  'ml-charging-curve-clustering',
  InnerSection,
)
AIMLChargingCurveClustering.displayName = 'AIMLChargingCurveClustering'
