// Phase-50 / 0018 — N4 Natural-language drive search & replay.
// Phase-50 / W1 (slice 0065) — wired the Search button to
// POST /api/v1/ai/drives/search (feature id: nl-drive-search-replay).

import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel, Textarea } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

function InnerSection() {
  const { t } = useTranslation()
  const [prompt, setPrompt] = useState('')
  const body = useMemo(() => ({ prompt }), [prompt])
  const stream = useAiStream({
    url: '/ai/drives/search',
    body,
    onEvent: () => {},
  })
  const canSearch = prompt.trim().length > 0 && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-start justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('drives.aiSearch.title', 'Find a drive in natural language')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('drives.aiSearch.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'drives.aiSearch.description',
                'Describe a drive (for example "last Friday\'s trip to the coast") and jump straight to its replay \u2014 the assistant only narrates your own drives.',
              )}
            </p>
          </div>
        </div>
        <Textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder={t(
            'drives.aiSearch.placeholder',
            'e.g. last Friday\'s trip to the coast',
          )}
          rows={3}
        />
        <div className="flex justify-end">
          <Button
            variant="outline"
            size="sm"
            disabled={!canSearch}
            aria-disabled={!canSearch ? 'true' : 'false'}
            onClick={() => stream.start()}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('drives.aiSearch.searchButton', 'Search with AI')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AINLDriveSearchInner'

export const AINLDriveSearch = withAiFeature('nl-drive-search-replay', InnerSection)
AINLDriveSearch.displayName = 'AINLDriveSearch'
