// Phase-50 / 0016 — N2 Natural-language automation builder.
//
// AINLAutomationBuilder is the visible AI surface for the
// AutomationBuilder page. It is rendered conditionally via
// withAiFeature('nl-automation-builder', …) so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the nl-automation-builder
//     toggle is on, it renders an opt-in section with a "Draft
//     automation" affordance that would call
//     POST /api/v1/ai/automations/draft.
//
// The component does NOT replace the deterministic
// AutomationBuilderPage form or the canonical AutomationHandler.Create
// path. The manual builder remains the canonical baseline visible to
// every user; this AI section is opt-in natural-language drafting
// layered alongside.
//
// The actual SSE call wiring lands in a follow-up slice (the slice
// prompt is explicit that the off-mode contract requires only the
// rendered-or-absent invariant). The current component shows the
// UI affordance with a "coming soon" disabled button so the
// off-mode test has a concrete UI test ID to assert against and the
// on-mode positive control proves the gate actually fires.
//
// PROPOSE-only contract (ADR-015 §I3 baseline-intact):
//
// Even when fully wired, the AI side panel will only PROPOSE a
// draft Automation graph into the same form fields the manual
// builder renders. The user must explicitly click the canonical Save
// button for the typed POST /api/v1/automations handler to fire —
// the LLM never persists state by itself.

import { useTranslation } from 'react-i18next'

import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'

/**
 * InnerSection is the always-rendered body of the AI automation
 * builder card. The surrounding {@link withAiFeature} HOC handles
 * the visibility gate; this component only describes the surface's
 * appearance.
 *
 * Visual contract:
 *   - One GlassPanel sized to fit alongside the AutomationBuilder's
 *     existing form.
 *   - Cyan AI badge in the header (matches the chatbot brand colour).
 *   - "Draft automation" button is disabled until the SSE wiring
 *     lands.
 *   - Title attribute carries the long-form description so a user
 *     hovering for a tooltip understands the propose-only contract.
 */
function InnerSection() {
  const { t } = useTranslation()
  return (
    <GlassPanel>
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-white/90">
              {t('automations.builder.aiBuilder.title', 'Draft from natural language')}
            </h3>
            <span
              className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
              title={t(
                'chatbot.llm.indicatorTooltip',
                'Responses are generated by an LLM with redacted vehicle context.',
              )}
              aria-label={t('chatbot.llm.indicator', 'AI mode')}
            >
              <span
                className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                aria-hidden="true"
              />
              {t('automations.builder.aiBuilder.badge', 'AI')}
            </span>
          </div>
          <p className="text-sm text-white/60">
            {t(
              'automations.builder.aiBuilder.description',
              'Describe the automation you want and get a typed graph draft you can review and save below.',
            )}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          disabled
          aria-disabled="true"
          title={t(
            'automations.builder.aiBuilder.description',
            'Describe the automation you want and get a typed graph draft you can review and save below.',
          )}
        >
          {t('automations.builder.aiBuilder.draftButton', 'Draft automation')}
        </Button>
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AINLAutomationBuilderInner'

/**
 * AINLAutomationBuilder renders the LLM automation-graph drafting
 * section only when the nl-automation-builder feature is enabled.
 * The wrapping div from {@link withAiFeature} carries
 * `data-testid="ai-feature-nl-automation-builder-root"`, which the
 * off-mode invariant test
 * (TestNLAutomationBuilderAIOffHidesPanelAndManualBuilderWorks)
 * asserts against.
 */
export const AINLAutomationBuilder = withAiFeature(
  'nl-automation-builder',
  InnerSection,
)
AINLAutomationBuilder.displayName = 'AINLAutomationBuilder'
