// Phase-50 / 0015 — N1 NL alert builder.
// Phase-50 / W1 (slice 0065) — wired the Draft button to
// POST /api/v1/ai/alerts/rules/draft.

import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel, Textarea } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

interface InnerSectionProps {
  vehicleId?: number
}

function InnerSection({ vehicleId }: InnerSectionProps) {
  const { t } = useTranslation()
  const [prompt, setPrompt] = useState('')
  const body = useMemo(
    () => ({ vehicle_id: vehicleId ?? 0, prompt }),
    [vehicleId, prompt],
  )
  const stream = useAiStream({
    url: '/ai/alerts/rules/draft',
    body,
    onEvent: () => {},
  })
  const canDraft =
    vehicleId != null && prompt.trim().length > 0 && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-start justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('notifications.alertStudio.aiBuilder.title', 'Draft from natural language')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('notifications.alertStudio.aiBuilder.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'notifications.alertStudio.aiBuilder.description',
                'Describe the alert you want and get a typed AlertRule draft you can review and save below.',
              )}
            </p>
          </div>
        </div>
        <Textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder={t(
            'notifications.alertStudio.aiBuilder.placeholder',
            'e.g. alert me if battery cell voltage spread is over 50 mV',
          )}
          rows={3}
        />
        <div className="flex justify-end">
          <Button
            variant="outline"
            size="sm"
            disabled={!canDraft}
            aria-disabled={!canDraft ? 'true' : 'false'}
            onClick={() => stream.start()}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('notifications.alertStudio.aiBuilder.draftButton', 'Draft alert')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AINLAlertBuilderInner'

export const AINLAlertBuilder = withAiFeature('nl-alert-builder', InnerSection)
AINLAlertBuilder.displayName = 'AINLAlertBuilder'
