// Phase-50 / 0017 — N3 Natural-language search.
// Phase-50 / W1 (slice 0065) — wired the Search button to
// POST /api/v1/ai/search/query.

import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel, Textarea } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

function InnerSection() {
  const { t } = useTranslation()
  const [prompt, setPrompt] = useState('')
  const body = useMemo(() => ({ prompt }), [prompt])
  const stream = useAiStream({
    url: '/ai/search/query',
    body,
    onEvent: () => {},
  })
  const canSearch = prompt.trim().length > 0 && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-start justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('search.aiSearch.title', 'Search with natural language')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('search.aiSearch.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'search.aiSearch.description',
                'Describe what you are looking for and the assistant will surface drives, charging sessions, and alerts that match \u2014 citing each entity by name.',
              )}
            </p>
          </div>
        </div>
        <Textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder={t(
            'search.aiSearch.placeholder',
            'e.g. drives last weekend over 200 km with phantom drain',
          )}
          rows={3}
        />
        <div className="flex justify-end">
          <Button
            variant="outline"
            size="sm"
            disabled={!canSearch}
            aria-disabled={!canSearch ? 'true' : 'false'}
            onClick={() => stream.start()}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('search.aiSearch.searchButton', 'Search with AI')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AINLSearchInner'

export const AINLSearch = withAiFeature('nl-search', InnerSection)
AINLSearch.displayName = 'AINLSearch'
