// Phase-50 / 0015 — N1 Natural-language alert builder.
//
// AINLAlertBuilder is the visible AI surface for the AlertStudio
// page. It is rendered conditionally via
// withAiFeature('nl-alert-builder', …) so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the nl-alert-builder
//     toggle is on, it renders an opt-in section with a "Draft alert"
//     affordance that would call POST /api/v1/ai/alerts/rules/draft.
//
// The component does NOT replace the deterministic AlertStudio form
// or the canonical AlertHandler.CreateRule path. The manual builder
// remains the canonical baseline visible to every user; this AI
// section is opt-in natural-language drafting layered alongside.
//
// The actual SSE call wiring lands in a follow-up slice (the slice
// prompt is explicit that the off-mode contract requires only the
// rendered-or-absent invariant). The current component shows the
// UI affordance with a "coming soon" disabled button so the
// off-mode test has a concrete UI test ID to assert against and the
// on-mode positive control proves the gate actually fires.
//
// PROPOSE-only contract (ADR-015 §I3 baseline-intact):
//
// Even when fully wired, the AI side panel will only PROPOSE a
// draft AlertRule into the same form fields the manual builder
// renders. The user must explicitly click the canonical Save button
// for the typed POST /api/v1/alerts/rules handler to fire — the
// LLM never persists state by itself.

import { useTranslation } from 'react-i18next'

import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'

/**
 * InnerSection is the always-rendered body of the AI alert-builder
 * card. The surrounding {@link withAiFeature} HOC handles the
 * visibility gate; this component only describes the surface's
 * appearance.
 *
 * Visual contract:
 *   - One GlassPanel sized to fit alongside the AlertStudio's
 *     existing form.
 *   - Cyan AI badge in the header (matches the chatbot brand colour).
 *   - "Draft alert" button is disabled until the SSE wiring lands.
 *   - Title attribute carries the long-form description so a user
 *     hovering for a tooltip understands the propose-only contract.
 */
function InnerSection() {
  const { t } = useTranslation()
  return (
    <GlassPanel>
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-white/90">
              {t('notifications.alertStudio.aiBuilder.title', 'Draft from natural language')}
            </h3>
            <span
              className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
              title={t(
                'chatbot.llm.indicatorTooltip',
                'Responses are generated by an LLM with redacted vehicle context.',
              )}
              aria-label={t('chatbot.llm.indicator', 'AI mode')}
            >
              <span
                className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                aria-hidden="true"
              />
              {t('notifications.alertStudio.aiBuilder.badge', 'AI')}
            </span>
          </div>
          <p className="text-sm text-white/60">
            {t(
              'notifications.alertStudio.aiBuilder.description',
              'Describe the alert you want and get a typed AlertRule draft you can review and save below.',
            )}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          disabled
          aria-disabled="true"
          title={t(
            'notifications.alertStudio.aiBuilder.description',
            'Describe the alert you want and get a typed AlertRule draft you can review and save below.',
          )}
        >
          {t('notifications.alertStudio.aiBuilder.draftButton', 'Draft alert')}
        </Button>
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AINLAlertBuilderInner'

/**
 * AINLAlertBuilder renders the LLM alert-rule drafting section only
 * when the nl-alert-builder feature is enabled. The wrapping div
 * from {@link withAiFeature} carries
 * `data-testid="ai-feature-nl-alert-builder-root"`, which the
 * off-mode invariant test
 * (TestNLAlertBuilderAIOffHidesPanelAndManualFormWorks) asserts
 * against.
 */
export const AINLAlertBuilder = withAiFeature(
  'nl-alert-builder',
  InnerSection,
)
AINLAlertBuilder.displayName = 'AINLAlertBuilder'
