// Phase-50 / 0021 — D1 Natural-language drive search and replay.
//
// AINLDriveSearch is the visible AI surface for the Drives list
// page (web/src/features/driving/pages/DrivesListPage.tsx). It is
// rendered conditionally via withAiFeature('nl-drive-search-replay', …)
// so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the nl-drive-search-replay
//     toggle is on, it renders an opt-in section with a "Search with AI"
//     affordance that would call POST /api/v1/ai/drives/search.
//
// The component does NOT replace the deterministic typed search +
// filter form on the Drives list page (SearchInput, FilterBar,
// RangePicker, VehicleSelect). The typed filters remain the
// canonical baseline visible to every user; this AI section is
// opt-in natural-language drive search layered alongside.
//
// The actual SSE call wiring lands in a follow-up slice (the slice
// prompt is explicit that the off-mode contract requires only the
// rendered-or-absent invariant). The current component shows the
// UI affordance with a "coming soon" disabled button so the off-mode
// test has a concrete UI test ID to assert against and the on-mode
// positive control proves the gate actually fires.
//
// READ-only contract (ADR-015 §I3 baseline-intact):
//
// Even when fully wired, the AI side panel will only NARRATE drives
// from the calling user's own drive_summary / route_segment /
// location_summary corpora and surface a {replayURL} link back to
// the existing TripReplayPage at /drives/:id/replay — no new
// entity-detail surface is introduced by this slice.

import { useTranslation } from 'react-i18next'

import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'

/**
 * InnerSection is the always-rendered body of the AI drive-search
 * card. The surrounding {@link withAiFeature} HOC handles the
 * visibility gate; this component only describes the surface's
 * appearance.
 *
 * Visual contract:
 *   - One GlassPanel sized to fit alongside the DrivesListPage's
 *     existing typed-filter form.
 *   - Cyan AI badge in the header (matches the chatbot brand colour).
 *   - "Search with AI" button is disabled until the SSE wiring
 *     lands — preserves the baseline-intact invariant: no half-
 *     wired button can accidentally fire a no-op request that
 *     would confuse the user.
 *   - Title attribute carries the long-form description so a user
 *     hovering for a tooltip understands the read-only contract.
 */
function InnerSection() {
  const { t } = useTranslation()
  return (
    <GlassPanel>
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-white/90">
              {t('drives.aiSearch.title', 'Find a drive in natural language')}
            </h3>
            <span
              className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
              title={t(
                'chatbot.llm.indicatorTooltip',
                'Responses are generated by an LLM with redacted vehicle context.',
              )}
              aria-label={t('chatbot.llm.indicator', 'AI mode')}
            >
              <span
                className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                aria-hidden="true"
              />
              {t('drives.aiSearch.badge', 'AI')}
            </span>
          </div>
          <p className="text-sm text-white/60">
            {t(
              'drives.aiSearch.description',
              'Describe a drive (for example "last Friday\'s trip to the coast") and jump straight to its replay — the assistant only narrates your own drives.',
            )}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          disabled
          aria-disabled="true"
          title={t(
            'drives.aiSearch.description',
            'Describe a drive (for example "last Friday\'s trip to the coast") and jump straight to its replay — the assistant only narrates your own drives.',
          )}
        >
          {t('drives.aiSearch.searchButton', 'Search with AI')}
        </Button>
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AINLDriveSearchInner'

/**
 * AINLDriveSearch renders the LLM natural-language drive-search
 * section only when the nl-drive-search-replay feature is enabled.
 * The wrapping div from {@link withAiFeature} carries
 * `data-testid="ai-feature-nl-drive-search-replay-root"`, which
 * the off-mode invariant test
 * (TestNLDriveSearchReplayAIOffUsesTypedFiltersOnly) asserts
 * against.
 */
export const AINLDriveSearch = withAiFeature('nl-drive-search-replay', InnerSection)
AINLDriveSearch.displayName = 'AINLDriveSearch'
