// Phase-50 / 0063 — ML2 Range-prediction model.
// Wires the "Train range model" button to
// POST /api/v1/ai/ml/range/train. The narration walks the user
// through the per-bucket (temp_bucket × speed_bucket) learned
// Wh/km envelope returned by train_range_model (and the
// deterministic linear-fallback for any bucket with too few
// drives), then summarises the currently-effective heuristic
// baseline via query_range_prediction. The AI never persists state
// — it is read-only narration over the learned envelope; the
// canonical Projected Range page at /projected-range
// (RangeProjectionHandler at GET /api/v1/vehicles/{id}/range/projection)
// is unchanged (ADR-015 §I3 + §I8 propose-only contract).

import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

interface InnerSectionProps {
  vehicleId?: number
}

function InnerSection({ vehicleId }: InnerSectionProps) {
  const { t } = useTranslation()
  // Default learning window: the last 14 days. Wide enough to
  // capture a representative weekly cadence (commuting + weekend
  // long drives), narrow enough that a recent owner-behaviour
  // change (new commute, summer→winter) is reflected in the
  // learned per-bucket Wh/km within a couple of weeks. The trainer
  // clamps the upper bound at mlrange.MaxDays=30, so wider values
  // are silently capped server-side.
  const body = useMemo(
    () => ({ vehicle_id: vehicleId ?? 0, days: 14 }),
    [vehicleId],
  )
  const stream = useAiStream({
    url: '/ai/ml/range/train',
    body,
    onEvent: () => {},
  })
  // Computed disabled — never literal-true. P12/W1-A enforces this
  // statically at slice 0065+, but the explicit boolean expression
  // also keeps the on-mode wiring test honest: a regression that
  // pins the button as always-disabled would silently falsify the
  // double-submit guard test.
  const canGenerate = vehicleId != null && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('range.aiPredict.title', 'Learn per-vehicle range model')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('range.aiPredict.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'range.aiPredict.description',
                'Compute per-bucket (temperature × speed) learned Wh/km from this vehicle’s recent drives and walk through how each bucket compares to the static heuristic curve the projection uses today.',
              )}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={!canGenerate}
            aria-disabled={!canGenerate ? 'true' : 'false'}
            onClick={() => stream.start()}
            title={t(
              'range.aiPredict.description',
              'Compute per-bucket (temperature × speed) learned Wh/km from this vehicle’s recent drives and walk through how each bucket compares to the static heuristic curve the projection uses today.',
            )}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('range.aiPredict.generateButton', 'Train range model')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIRangePredictionInner'

export const AIRangePrediction = withAiFeature(
  'range-prediction-model',
  InnerSection,
)
AIRangePrediction.displayName = 'AIRangePrediction'
