// Phase-50 / 0020 — N6 RAG-backed app help.
//
// AIRAGHelp is the visible AI surface for the global Help page
// (web/src/features/system/pages/HelpPage.tsx). It is rendered
// conditionally via withAiFeature('rag-help', …) so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the rag-help toggle is on,
//     it renders an opt-in section with an "Ask the help assistant"
//     affordance that would call POST /api/v1/ai/help/query.
//
// The component does NOT replace the deterministic /help SPA page —
// the curated docs links + tooltips + i18n help copy remain the
// canonical baseline visible to every user; this AI section is
// opt-in natural-language help layered alongside.
//
// The actual SSE call wiring lands in a follow-up slice (the slice
// prompt is explicit that the off-mode contract requires only the
// rendered-or-absent invariant). The current component shows the
// UI affordance with a "coming soon" disabled button so the off-mode
// test has a concrete UI test ID to assert against and the on-mode
// positive control proves the gate actually fires.
//
// READ-only contract (ADR-015 §I3 baseline-intact):
//
// Even when fully wired, the AI side panel will only NARRATE an
// answer grounded in the application's own docs / runbooks / i18n
// strings (a global non-PII corpus). It never writes any record,
// never mutates a setting, and never performs an action on the
// user's behalf — the cited entities link back to the same SPA
// pages (/docs/*, /system-status, /search, /onboarding, /chatbot)
// the deterministic baseline already exposes — no new entity-detail
// surface is introduced by this slice.

import { useTranslation } from 'react-i18next'

import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'

/**
 * InnerSection is the always-rendered body of the AI help card.
 * The surrounding {@link withAiFeature} HOC handles the visibility
 * gate; this component only describes the surface's appearance.
 *
 * Visual contract:
 *   - One GlassPanel sized to fit alongside the HelpPage's
 *     existing curated-link grid.
 *   - Cyan AI badge in the header (matches the chatbot brand colour).
 *   - "Ask the help assistant" button is disabled until the SSE
 *     wiring lands — preserves the baseline-intact invariant: no
 *     half-wired button can accidentally fire a no-op request that
 *     would confuse the user.
 *   - Title attribute carries the long-form description so a user
 *     hovering for a tooltip understands the read-only contract.
 */
function InnerSection() {
  const { t } = useTranslation()
  return (
    <GlassPanel>
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-white/90">
              {t('help.aiHelp.title', 'Ask the help assistant')}
            </h3>
            <span
              className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
              title={t(
                'chatbot.llm.indicatorTooltip',
                'Responses are generated by an LLM with redacted vehicle context.',
              )}
              aria-label={t('chatbot.llm.indicator', 'AI mode')}
            >
              <span
                className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                aria-hidden="true"
              />
              {t('help.aiHelp.badge', 'AI')}
            </span>
          </div>
          <p className="text-sm text-white/60">
            {t(
              'help.aiHelp.description',
              'Ask a natural-language question about the application and the assistant will answer using the project\u2019s own documentation, runbooks, and i18n strings \u2014 with explicit citations to each source.',
            )}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          disabled
          aria-disabled="true"
          title={t(
            'help.aiHelp.description',
            'Ask a natural-language question about the application and the assistant will answer using the project\u2019s own documentation, runbooks, and i18n strings \u2014 with explicit citations to each source.',
          )}
        >
          {t('help.aiHelp.askButton', 'Ask the assistant')}
        </Button>
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIRAGHelpInner'

/**
 * AIRAGHelp renders the LLM-backed app help section only when the
 * rag-help feature is enabled. The wrapping div from
 * {@link withAiFeature} carries `data-testid="ai-feature-rag-help-root"`,
 * which the off-mode invariant test
 * (TestRagHelpAIOffHidesAssistantAndDocsLinksWork) asserts against.
 */
export const AIRAGHelp = withAiFeature('rag-help', InnerSection)
AIRAGHelp.displayName = 'AIRAGHelp'
