// Phase-50 / 0020 — N6 RAG-backed app help.
// Phase-50 / W1 (slice 0065) — wired the Ask button to
// POST /api/v1/ai/help/query.

import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel, Textarea } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

function InnerSection() {
  const { t } = useTranslation()
  const [prompt, setPrompt] = useState('')
  const body = useMemo(() => ({ prompt }), [prompt])
  const stream = useAiStream({
    url: '/ai/help/query',
    body,
    onEvent: () => {},
  })
  const canAsk = prompt.trim().length > 0 && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-start justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('help.aiHelp.title', 'Ask the help assistant')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('help.aiHelp.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'help.aiHelp.description',
                'Ask a natural-language question about the application and the assistant will answer using the project\u2019s own documentation, runbooks, and i18n strings \u2014 with explicit citations to each source.',
              )}
            </p>
          </div>
        </div>
        <Textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder={t(
            'help.aiHelp.placeholder',
            'e.g. How do I enable energy cost forecasting?',
          )}
          rows={3}
        />
        <div className="flex justify-end">
          <Button
            variant="outline"
            size="sm"
            disabled={!canAsk}
            aria-disabled={!canAsk ? 'true' : 'false'}
            onClick={() => stream.start()}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('help.aiHelp.askButton', 'Ask the assistant')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIRAGHelpInner'

export const AIRAGHelp = withAiFeature('rag-help', InnerSection)
AIRAGHelp.displayName = 'AIRAGHelp'
