// Phase-50 / 0023 — D3 Route-efficiency suggestions.
//
// AIRouteEfficiencySuggestions is the visible AI surface for the
// Route Efficiency analytics page. It is rendered conditionally
// via withAiFeature('route-efficiency-suggestions', …) so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the
//     route-efficiency-suggestions toggle is on, it renders an
//     opt-in section with a Generate button that would call
//     POST /api/v1/ai/routes/{routeID}/efficiency/suggest.
//
// The component does NOT replace the deterministic RouteCards or
// kWh/100mi metric bars already rendered by RouteEfficiencyPage.
// That baseline content remains the canonical view visible to
// every user; this AI section is opt-in narrative prose layered
// alongside.
//
// The actual SSE call wiring lands in a future slice (the slice
// prompt is explicit that the F0 contract requires only the
// rendered-or-absent invariant). The current component shows the
// UI affordance with a disabled "Generate" button so the off-mode
// test has a concrete UI test ID to assert against and the on-mode
// positive control proves the gate actually fires.

import { useTranslation } from 'react-i18next'

import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'

interface InnerSectionProps {
  /**
   * vehicleId surfaced by the parent RouteEfficiencyPage. Optional
   * because RouteEfficiencyPage's `useSelectedVehicle()` returns
   * `string | undefined`; when absent we still render the section
   * (the gate has already passed) but the Generate button stays
   * disabled because the backend call needs a vehicle in scope.
   */
  vehicleId?: string
}

/**
 * InnerSection is the always-rendered body of the AI suggestions
 * card. The surrounding {@link withAiFeature} HOC handles the
 * visibility gate; this component only describes the surface's
 * appearance.
 *
 * Visual contract:
 *   - One GlassPanel sized to sit above the route comparison cards
 *     on RouteEfficiencyPage.
 *   - Cyan AI badge in the header (matches the chatbot brand colour).
 *   - Generate button is disabled until the SSE wiring lands AND
 *     when no vehicleId is available from the parent route.
 *   - Title attribute carries the long-form explanation so a user
 *     hovering for a tooltip understands the privacy contract —
 *     only the vehicle name may be narrated; lat/long, street
 *     addresses, and place names remain tagged by the per-feature
 *     redaction policy.
 */
function InnerSection({ vehicleId }: InnerSectionProps) {
  const { t } = useTranslation()
  const buttonDisabled = !vehicleId
  return (
    <GlassPanel>
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-white/90">
              {t('routeEfficiency.aiSuggestions.title', 'Route-efficiency suggestions')}
            </h3>
            <span
              className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
              title={t(
                'chatbot.llm.indicatorTooltip',
                'Responses are generated by an LLM with redacted vehicle context.',
              )}
              aria-label={t('chatbot.llm.indicator', 'AI mode')}
            >
              <span
                className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                aria-hidden="true"
              />
              {t('routeEfficiency.aiSuggestions.badge', 'AI')}
            </span>
          </div>
          <p className="text-sm text-white/60">
            {t(
              'routeEfficiency.aiSuggestions.description',
              'Get a short plain-language suggestion for lower-consumption habits and route choices grounded in your own historical route data — the dominant route, its kWh/100mi figure, a comparison across your other routes, and one or two concrete, non-mutating ideas you can try yourself.',
            )}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          disabled={buttonDisabled}
          aria-disabled={buttonDisabled ? 'true' : 'false'}
          title={t(
            'routeEfficiency.aiSuggestions.description',
            'Get a short plain-language suggestion for lower-consumption habits and route choices grounded in your own historical route data — the dominant route, its kWh/100mi figure, a comparison across your other routes, and one or two concrete, non-mutating ideas you can try yourself.',
          )}
        >
          {t('routeEfficiency.aiSuggestions.generateButton', 'Generate suggestions')}
        </Button>
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIRouteEfficiencySuggestionsInner'

/**
 * AIRouteEfficiencySuggestions renders the LLM route-efficiency
 * narration section only when the route-efficiency-suggestions
 * feature is enabled. The wrapping div from {@link withAiFeature}
 * carries
 * `data-testid="ai-feature-route-efficiency-suggestions-root"`,
 * which the off-mode invariant test asserts against.
 */
export const AIRouteEfficiencySuggestions = withAiFeature(
  'route-efficiency-suggestions',
  InnerSection,
)
AIRouteEfficiencySuggestions.displayName = 'AIRouteEfficiencySuggestions'
