// Phase-50 / 0023 — D3 Route-efficiency suggestions.
// Phase-50 / W1 (slice 0065) — wired the Generate button to
// POST /api/v1/ai/routes/{routeID}/efficiency/suggest (empty body).
// The {routeID} URL slot is filled with the parent page's
// vehicleId — per slice 0023 the backend treats this as an
// "opaque anchor", not a foreign key to a routes table.

import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

interface InnerSectionProps {
  vehicleId?: string
}

function InnerSection({ vehicleId }: InnerSectionProps) {
  const { t } = useTranslation()
  const url = useMemo(
    () =>
      vehicleId
        ? `/ai/routes/${encodeURIComponent(vehicleId)}/efficiency/suggest`
        : '/ai/routes/0/efficiency/suggest',
    [vehicleId],
  )
  const body = useMemo(() => ({}), [])
  const stream = useAiStream({ url, body, onEvent: () => {} })
  const canGenerate = !!vehicleId && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('routeEfficiency.aiSuggestions.title', 'Route-efficiency suggestions')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('routeEfficiency.aiSuggestions.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'routeEfficiency.aiSuggestions.description',
                'Get a short plain-language suggestion for lower-consumption habits and route choices grounded in your own historical route data — the dominant route, its kWh/100mi figure, a comparison across your other routes, and one or two concrete, non-mutating ideas you can try yourself.',
              )}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={!canGenerate}
            aria-disabled={!canGenerate ? 'true' : 'false'}
            onClick={() => stream.start()}
            title={t(
              'routeEfficiency.aiSuggestions.description',
              'Get a short plain-language suggestion for lower-consumption habits and route choices grounded in your own historical route data — the dominant route, its kWh/100mi figure, a comparison across your other routes, and one or two concrete, non-mutating ideas you can try yourself.',
            )}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('routeEfficiency.aiSuggestions.generateButton', 'Generate suggestions')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIRouteEfficiencySuggestionsInner'

export const AIRouteEfficiencySuggestions = withAiFeature(
  'route-efficiency-suggestions',
  InnerSection,
)
AIRouteEfficiencySuggestions.displayName = 'AIRouteEfficiencySuggestions'
