// Phase-50 / 0026 — C1 Smart-charge schedule suggestion.
// Phase-50 / W1 (slice 0065) — wired the Draft button to
// POST /api/v1/ai/charging/schedule/draft.

import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

interface InnerSectionProps {
  vehicleId?: string | number
  targetSoc?: number
  currentSoc?: number
  departBy?: string
  ratePlanId?: string
  maxAmps?: number
  batteryCapacityKwh?: number
  chargerVoltage?: number
  preferOffPeak?: boolean
}

function InnerSection({
  vehicleId,
  targetSoc,
  currentSoc,
  departBy,
  ratePlanId,
  maxAmps,
  batteryCapacityKwh,
  chargerVoltage,
  preferOffPeak,
}: InnerSectionProps) {
  const { t } = useTranslation()
  const numericVehicleId =
    typeof vehicleId === 'number' ? vehicleId : Number(vehicleId)
  const body = useMemo(() => {
    // depart_by must be ISO; the SmartChargePage feeds a datetime-local
    // string which we normalize the same way the deterministic Optimize
    // call does.
    const departIso = (() => {
      if (!departBy) return new Date().toISOString()
      const d = new Date(departBy)
      return Number.isNaN(d.getTime()) ? new Date().toISOString() : d.toISOString()
    })()
    return {
      vehicle_id: numericVehicleId || 0,
      target_soc: targetSoc ?? 80,
      depart_by: departIso,
      rate_plan_id: ratePlanId ?? '',
      max_amps: maxAmps ?? 32,
      battery_capacity_kwh: batteryCapacityKwh ?? 75,
      charger_voltage: chargerVoltage ?? 240,
      prefer_off_peak: preferOffPeak ?? true,
      current_soc: currentSoc ?? 20,
    }
  }, [
    numericVehicleId,
    targetSoc,
    departBy,
    ratePlanId,
    maxAmps,
    batteryCapacityKwh,
    chargerVoltage,
    preferOffPeak,
    currentSoc,
  ])
  const stream = useAiStream({
    url: '/ai/charging/schedule/draft',
    body,
    onEvent: () => {},
  })
  const haveInputs = !!vehicleId && !!ratePlanId
  const canGenerate = haveInputs && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('chargePlanner.aiAgent.title', 'Draft a schedule with the AI agent')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('chargePlanner.aiAgent.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'chargePlanner.aiAgent.description',
                'Ask the AI agent to propose a time-of-use-optimized charge schedule grounded in your selected rate plan and target departure. The schedule is never saved automatically \u2014 review the proposed window and click Schedule below to apply it.',
              )}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={!canGenerate}
            aria-disabled={!canGenerate ? 'true' : 'false'}
            onClick={() => stream.start()}
            title={t(
              'chargePlanner.aiAgent.description',
              'Ask the AI agent to propose a time-of-use-optimized charge schedule grounded in your selected rate plan and target departure. The schedule is never saved automatically \u2014 review the proposed window and click Schedule below to apply it.',
            )}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('chargePlanner.aiAgent.generateButton', 'Draft a schedule')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AISmartChargeScheduleSuggestionInner'

export const AISmartChargeScheduleSuggestion = withAiFeature(
  'smart-charge-schedule-suggestion',
  InnerSection,
)
AISmartChargeScheduleSuggestion.displayName = 'AISmartChargeScheduleSuggestion'
