// Phase-50 / 0022 — D2 Speed-profile insights.
//
// AISpeedProfileInsights is the visible AI surface for the drive
// detail page's speed-profile section. It is rendered conditionally
// via withAiFeature('speed-profile-insights', …) so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the speed-profile-insights
//     toggle is on, it renders an opt-in section with a Generate
//     button that would call
//     POST /api/v1/ai/drives/{driveID}/speed-profile/insights.
//
// The component does NOT replace the deterministic
// SpeedHistogramChart + summary metrics already rendered by
// DriveDetailPage. That baseline chart remains the canonical view
// visible to every user; this AI section is opt-in narrative prose
// layered alongside.
//
// The actual SSE call wiring lands in a future slice (the slice
// prompt is explicit that the F0 contract requires only the
// rendered-or-absent invariant). The current component shows the UI
// affordance with a disabled "Generate" button so the off-mode test
// has a concrete UI test ID to assert against and the on-mode
// positive control proves the gate actually fires.

import { useTranslation } from 'react-i18next'

import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'

interface InnerSectionProps {
  /**
   * driveID surfaced by the parent DriveDetailPage. Optional because
   * the drive detail route's `useParams<{id}>()` returns
   * `string | undefined`; when absent we still render the section
   * (the gate has already passed) but the Generate button stays
   * disabled.
   */
  driveId?: string
}

/**
 * InnerSection is the always-rendered body of the AI insights card.
 * The surrounding {@link withAiFeature} HOC handles the visibility
 * gate; this component only describes the surface's appearance.
 *
 * Visual contract:
 *   - One GlassPanel sized to sit beside DriveDetailPage's
 *     SpeedHistogramChart.
 *   - Cyan AI badge in the header (matches the chatbot brand colour).
 *   - Generate button is disabled until the SSE wiring lands AND when
 *     no driveId is available from the parent route.
 *   - Title attribute carries the long-form explanation so a user
 *     hovering for a tooltip understands the privacy contract — only
 *     the vehicle name may be narrated; precise route coordinates
 *     remain tagged by the per-feature redaction policy.
 */
function InnerSection({ driveId }: InnerSectionProps) {
  const { t } = useTranslation()
  const buttonDisabled = !driveId
  return (
    <GlassPanel>
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-white/90">
              {t('driveDetail.aiSpeedProfile.title', 'Speed-profile insights')}
            </h3>
            <span
              className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
              title={t(
                'chatbot.llm.indicatorTooltip',
                'Responses are generated by an LLM with redacted vehicle context.',
              )}
              aria-label={t('chatbot.llm.indicator', 'AI mode')}
            >
              <span
                className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                aria-hidden="true"
              />
              {t('driveDetail.aiSpeedProfile.badge', 'AI')}
            </span>
          </div>
          <p className="text-sm text-white/60">
            {t(
              'driveDetail.aiSpeedProfile.description',
              'Get a short plain-language interpretation of this drive’s speed regime distribution — city / suburban / highway buckets, outliers, and how the speed envelope compares to a typical drive — generated from the same per-drive aggregates shown in the chart.',
            )}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          disabled={buttonDisabled}
          aria-disabled={buttonDisabled ? 'true' : 'false'}
          title={t(
            'driveDetail.aiSpeedProfile.description',
            'Get a short plain-language interpretation of this drive’s speed regime distribution — city / suburban / highway buckets, outliers, and how the speed envelope compares to a typical drive — generated from the same per-drive aggregates shown in the chart.',
          )}
        >
          {t('driveDetail.aiSpeedProfile.generateButton', 'Generate insights')}
        </Button>
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AISpeedProfileInsightsInner'

/**
 * AISpeedProfileInsights renders the LLM speed-profile narration
 * section only when the speed-profile-insights feature is enabled.
 * The wrapping div from {@link withAiFeature} carries
 * `data-testid="ai-feature-speed-profile-insights-root"`, which the
 * off-mode invariant test asserts against.
 */
export const AISpeedProfileInsights = withAiFeature('speed-profile-insights', InnerSection)
AISpeedProfileInsights.displayName = 'AISpeedProfileInsights'
