// Phase-50 / 0022 — D2 Speed-profile insights.
// Phase-50 / W1 (slice 0065) — wired the Generate button to
// POST /api/v1/ai/drives/{driveID}/speed-profile/insights.

import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

interface InnerSectionProps {
  driveId?: string
}

function InnerSection({ driveId }: InnerSectionProps) {
  const { t } = useTranslation()
  const url = useMemo(
    () =>
      driveId
        ? `/ai/drives/${encodeURIComponent(driveId)}/speed-profile/insights`
        : '/ai/drives/0/speed-profile/insights',
    [driveId],
  )
  const body = useMemo(() => ({}), [])
  const stream = useAiStream({ url, body, onEvent: () => {} })
  const canGenerate = !!driveId && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('driveDetail.aiSpeedProfile.title', 'Speed-profile insights')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('driveDetail.aiSpeedProfile.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'driveDetail.aiSpeedProfile.description',
                'Get a short plain-language interpretation of this drive’s speed regime distribution — city / suburban / highway buckets, outliers, and how the speed envelope compares to a typical drive — generated from the same per-drive aggregates shown in the chart.',
              )}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={!canGenerate}
            aria-disabled={!canGenerate ? 'true' : 'false'}
            onClick={() => stream.start()}
            title={t(
              'driveDetail.aiSpeedProfile.description',
              'Get a short plain-language interpretation of this drive’s speed regime distribution — city / suburban / highway buckets, outliers, and how the speed envelope compares to a typical drive — generated from the same per-drive aggregates shown in the chart.',
            )}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('driveDetail.aiSpeedProfile.generateButton', 'Generate insights')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AISpeedProfileInsightsInner'

export const AISpeedProfileInsights = withAiFeature('speed-profile-insights', InnerSection)
AISpeedProfileInsights.displayName = 'AISpeedProfileInsights'
