// Phase-50 / 0025 — D5 Trip planner LLM agent.
// Phase-50 / W1 (slice 0065) — wired the Draft button to
// POST /api/v1/ai/trips/plan/draft.

import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

interface TripLocationLike {
  lat: number
  lng: number
  name?: string
}

interface InnerSectionProps {
  vehicleId?: string | number
  origin?: TripLocationLike | null
  destination?: TripLocationLike | null
  currentSoc?: number
  minArrivalSoc?: number
  chargeLimitSoc?: number
  speedFactor?: number
}

function InnerSection({
  vehicleId,
  origin,
  destination,
  currentSoc,
  minArrivalSoc,
  chargeLimitSoc,
  speedFactor,
}: InnerSectionProps) {
  const { t } = useTranslation()
  const numericVehicleId =
    typeof vehicleId === 'number' ? vehicleId : Number(vehicleId)
  const body = useMemo(
    () => ({
      vehicle_id: numericVehicleId || 0,
      origin: origin
        ? {
            lat: origin.lat,
            lng: origin.lng,
            name: origin.name ?? '',
          }
        : { lat: 0, lng: 0, name: '' },
      destination: destination
        ? {
            lat: destination.lat,
            lng: destination.lng,
            name: destination.name ?? '',
          }
        : { lat: 0, lng: 0, name: '' },
      current_soc: currentSoc ?? 80,
      charge_limit_soc: chargeLimitSoc ?? 90,
      min_arrival_soc: minArrivalSoc ?? 20,
      speed_factor: speedFactor ?? 1.0,
    }),
    [
      numericVehicleId,
      origin,
      destination,
      currentSoc,
      chargeLimitSoc,
      minArrivalSoc,
      speedFactor,
    ],
  )
  const stream = useAiStream({
    url: '/ai/trips/plan/draft',
    body,
    onEvent: () => {},
  })
  const haveInputs =
    !!vehicleId && origin != null && destination != null
  const canGenerate = haveInputs && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('tripPlanner.aiAgent.title', 'Draft a plan with the AI agent')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('tripPlanner.aiAgent.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'tripPlanner.aiAgent.description',
                'Ask the AI agent to draft a trip plan grounded in your past charging history along the corridor. The plan is never saved automatically \u2014 review the proposed plan and click Plan in the form below to save it.',
              )}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={!canGenerate}
            aria-disabled={!canGenerate ? 'true' : 'false'}
            onClick={() => stream.start()}
            title={t(
              'tripPlanner.aiAgent.description',
              'Ask the AI agent to draft a trip plan grounded in your past charging history along the corridor. The plan is never saved automatically \u2014 review the proposed plan and click Plan in the form below to save it.',
            )}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('tripPlanner.aiAgent.generateButton', 'Draft a plan')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AITripPlannerLLMAgentInner'

export const AITripPlannerLLMAgent = withAiFeature(
  'trip-planner-llm-agent',
  InnerSection,
)
AITripPlannerLLMAgent.displayName = 'AITripPlannerLLMAgent'
