// Phase-50 / 0013 — U3 Year-in-review narration.
// Phase-50 / W1 (slice 0065) — wired the Generate button to
// POST /api/v1/ai/analytics/year-in-review/narrate.

import { useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { AiOutputPanel } from '@/components/ai/AiOutputPanel'
import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'
import { useAiStream } from '@/hooks/useAiStream'

interface InnerSectionProps {
  vehicleId?: number
}

function InnerSection({ vehicleId }: InnerSectionProps) {
  const { t } = useTranslation()
  // Default to the previous calendar year — the year-in-review page is
  // typically reviewed in January for the year that just ended. If the
  // user is browsing it during the active year, they can re-fire the
  // request after picking a year filter in a future iteration.
  const defaultYear = new Date().getFullYear() - 1
  const body = useMemo(
    () => ({ vehicle_id: vehicleId ?? 0, year: defaultYear }),
    [vehicleId, defaultYear],
  )
  const stream = useAiStream({
    url: '/ai/analytics/year-in-review/narrate',
    body,
    onEvent: () => {},
  })
  const canGenerate = vehicleId != null && stream.state !== 'streaming'
  return (
    <GlassPanel>
      <div className="space-y-4">
        <div className="flex items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-white/90">
                {t('yearReview.aiNarration.title', 'AI narration')}
              </h3>
              <span
                className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
                title={t(
                  'chatbot.llm.indicatorTooltip',
                  'Responses are generated by an LLM with redacted vehicle context.',
                )}
                aria-label={t('chatbot.llm.indicator', 'AI mode')}
              >
                <span
                  className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                  aria-hidden="true"
                />
                {t('yearReview.aiNarration.badge', 'AI')}
              </span>
            </div>
            <p className="text-sm text-white/60">
              {t(
                'yearReview.aiNarration.description',
                'Get a short, AI-written recap of your year from the slide data above.',
              )}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={!canGenerate}
            aria-disabled={!canGenerate ? 'true' : 'false'}
            onClick={() => stream.start()}
            title={t(
              'yearReview.aiNarration.description',
              'Get a short, AI-written recap of your year from the slide data above.',
            )}
          >
            {stream.state === 'streaming'
              ? t('ai.common.generating', 'Generating…')
              : t('yearReview.aiNarration.generateButton', 'Generate narration')}
          </Button>
        </div>
        <AiOutputPanel text={stream.text} state={stream.state} error={stream.error} />
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIYearReviewNarrationInner'

export const AIYearReviewNarration = withAiFeature('yir-narration', InnerSection)
AIYearReviewNarration.displayName = 'AIYearReviewNarration'
