// Phase-50 / 0013 — U3 Year-in-review narration.
//
// AIYearReviewNarration is the visible AI surface for the year-in-review
// page. It is rendered conditionally via withAiFeature('yir-narration', …)
// so:
//
//   - When ai_mode='off' it does not render at all (ADR-015 §I5 + §I6).
//   - When ai_mode is 'local'/'cloud' AND the yir-narration toggle
//     is on, it renders an opt-in section with a Generate button that
//     would call POST /api/v1/ai/analytics/year-in-review/narrate.
//
// The component does NOT replace the deterministic template year-in-
// review slide deck (SLIDE_DEFS in features/analytics/components/review/
// slides.ts). The template slides remain the canonical baseline visible
// to every user; this AI section is opt-in narrative prose layered
// alongside.
//
// The actual SSE call wiring lands in a future slice (the slice
// prompt is explicit that the F0 contract requires only the
// rendered-or-absent invariant). The current component shows the
// UI affordance with a "coming soon" disabled button so the
// off-mode test has a concrete UI test ID to assert against and the
// on-mode positive control proves the gate actually fires.

import { useTranslation } from 'react-i18next'

import { withAiFeature } from '@/components/ai/withAiFeature'
import { Button, GlassPanel } from '@/components/ui'

/**
 * InnerSection is the always-rendered body of the AI narration card.
 * The surrounding {@link withAiFeature} HOC handles the visibility
 * gate; this component only describes the surface's appearance.
 *
 * Visual contract:
 *   - One GlassPanel sized to fit alongside the year-in-review slide
 *     overlay.
 *   - Cyan AI badge in the header (matches the chatbot brand colour).
 *   - Generate button is disabled until the SSE wiring lands.
 *   - Title attribute carries the long-form explanation so a user
 *     hovering for a tooltip understands the privacy contract.
 */
function InnerSection() {
  const { t } = useTranslation()
  return (
    <GlassPanel>
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-semibold text-white/90">
              {t('yearReview.aiNarration.title', 'AI narration')}
            </h3>
            <span
              className="inline-flex items-center gap-1.5 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-2.5 py-1 text-xs font-medium text-cyan-300"
              title={t(
                'chatbot.llm.indicatorTooltip',
                'Responses are generated by an LLM with redacted vehicle context.',
              )}
              aria-label={t('chatbot.llm.indicator', 'AI mode')}
            >
              <span
                className="inline-block h-1.5 w-1.5 rounded-full bg-cyan-300"
                aria-hidden="true"
              />
              {t('yearReview.aiNarration.badge', 'AI')}
            </span>
          </div>
          <p className="text-sm text-white/60">
            {t(
              'yearReview.aiNarration.description',
              'Get a short, AI-written recap of your year from the slide data above.',
            )}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          disabled
          aria-disabled="true"
          title={t(
            'yearReview.aiNarration.description',
            'Get a short, AI-written recap of your year from the slide data above.',
          )}
        >
          {t('yearReview.aiNarration.generateButton', 'Generate narration')}
        </Button>
      </div>
    </GlassPanel>
  )
}
InnerSection.displayName = 'AIYearReviewNarrationInner'

/**
 * AIYearReviewNarration renders the LLM year-in-review section only
 * when the yir-narration feature is enabled. The wrapping div from
 * {@link withAiFeature} carries
 * `data-testid="ai-feature-yir-narration-root"`, which the off-mode
 * invariant test asserts against.
 */
export const AIYearReviewNarration = withAiFeature('yir-narration', InnerSection)
AIYearReviewNarration.displayName = 'AIYearReviewNarration'
