package main

import (
	"fmt"
	"os"

	gowebpush "github.com/SherClockHolmes/webpush-go"
)

// runVAPIDKeygen handles the `teslasync vapid-keygen` subcommand. It
// generates a fresh VAPID keypair (offline, no DB or config touched) and
// prints the values to stdout in env-file syntax so an operator can copy
// them straight into `.env` or a Helm secret.
//
// VAPID keys are intentionally OPERATOR-managed, not auto-generated by the
// API server, because rotating them invalidates every existing browser
// subscription. Pinning the keys via env vars and persisting them with
// the rest of the deployment's secrets is the safest model.
//
// Wired ahead of config.Load() in main() so it runs without needing a DB
// or any other startup wiring.
func runVAPIDKeygen() {
	priv, pub, err := gowebpush.GenerateVAPIDKeys()
	if err != nil {
		fmt.Fprintf(os.Stderr, "vapid-keygen: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("# Add the following to your .env, docker-compose env, or Helm secret.")
	fmt.Println("# The PUBLIC key is also exposed unauthenticated via /api/v1/push/public-key.")
	fmt.Println("# The PRIVATE key MUST stay secret; rotating it invalidates every browser subscription.")
	fmt.Printf("TESLASYNC_VAPID_PUBLIC_KEY=%s\n", pub)
	fmt.Printf("TESLASYNC_VAPID_PRIVATE_KEY=%s\n", priv)
	fmt.Printf("TESLASYNC_VAPID_SUBJECT=mailto:admin@example.com  # change to a real contact\n")
	os.Exit(0)
}
