export const navSearchKeywords: Record<string, string[]> = {
  '/': ['home', 'overview', 'start', 'summary'],
  '/action-center': ['action center', 'decision inbox', 'recommendations', 'priorities', 'findings', 'snooze'],
  '/live': ['map', 'location', 'tracking', 'realtime', 'vehicle position'],
  '/vehicles': ['cars', 'fleet', 'garage', 'vehicle list'],
  '/vehicle-management': ['vehicle management', 'fleet api management', 'options', 'specs', 'warranty', 'pricing', 'enterprise roles', 'payer'],
  '/period-compare': ['comparison', 'period', 'time', 'this month vs last month', 'trends'],
  '/weekly-digest': ['digest', 'weekly', 'summary', 'report'],
  '/navigation': ['route', 'directions', 'map', 'nav'],
  '/drives': ['drive history', 'sessions', 'trips'],
  '/trips': ['trip history', 'journeys', 'routes'],
  '/journeys': ['journey autopilot', 'plan trip', 'live trip', 'replan'],
  '/trip-planner': ['plan trip', 'route planner', 'range planning'],
  '/arrival-reliability': ['arrival reliability', 'travel time', 'route uncertainty', 'on time'],
  '/destination-transitions': ['destination transitions', 'mobility graph', 'next destination'],
  '/journey-fragmentation': ['journey fragmentation', 'trip chains', 'stopovers'],
  '/seasonal-efficiency': ['seasonal efficiency', 'annual trend', 'energy seasonality'],
  '/drive-score': ['score', 'driving score', 'safe driving'],
  '/fsd': ['fsd', 'full self driving', 'supervised self-driving', 'autopilot distance', 'self driving miles', 'autonomy usage'],
  '/speed-profile': ['speed', 'profile', 'velocity'],
  '/driving-dynamics': ['dynamics', 'handling', 'performance', 'acceleration'],
  '/regen-efficiency': ['regen', 'regenerative', 'braking', 'recovery'],
  '/battery': ['battery', 'health', 'range', 'capacity', 'soh'],
  '/battery-cells': ['cells', 'cell voltage', 'battery module'],
  '/battery-degradation': ['degradation', 'battery loss', 'range loss', 'aging'],
  '/cycle-stress': ['battery cycles', 'cycle stress', 'depth of discharge', 'rainflow'],
  '/charging': ['charge', 'charging sessions', 'plug', 'charger'],
  '/tesla-charging-history': ['supercharger', 'tesla charging', 'charge cost', 'invoice', 'receipt'],
  '/charging-heatmap': ['charging patterns', 'heatmap', 'schedule', 'when charging'],
  '/charging-curve': ['curve', 'charging speed', 'kw', 'power curve'],
  '/smart-charge': ['smart charging', 'schedule', 'automation'],
  '/charge-interruption': ['charge interruption', 'charging failure', 'interrupted session'],
  '/charger-resilience': ['charger resilience', 'site dependency', 'charging diversity'],
  '/charge-departure-alignment': ['charge alignment', 'departure readiness', 'next drive'],
  '/charging-thermal-tax': ['charging thermal tax', 'battery heater', 'thermal overhead'],
  '/powershare': ['power share', 'home backup', 'v2h'],
  '/energy': ['energy usage', 'consumption', 'kwh'],
  '/energy-flow': ['flow', 'energy graph', 'power path'],
  '/power-flow': ['power', 'flow', 'dashboard'],
  '/energy-products': ['powerwall', 'solar', 'home energy'],
  '/efficiency': ['efficiency', 'wh per mile', 'consumption'],
  '/route-efficiency': ['route', 'efficiency', 'trip energy'],
  '/projected-range': ['range', 'forecast', 'projection'],
  '/mileage': ['odometer', 'miles', 'distance'],
  '/temperature-impact': ['temperature', 'weather', 'climate impact'],
  '/cost-analysis': ['cost', 'money', 'expense', 'savings'],
  '/tco': ['ownership', 'total cost', 'tco'],
  '/digital-twin': ['digital twin', 'vehicle state', 'doors', 'windows', 'lights'],
  '/tire-pressure': ['tires', 'tpms', 'pressure'],
  '/climate-control': ['climate', 'temperature', 'hvac', 'ac', 'heat'],
  '/hvac-cycling': ['hvac cycling', 'compressor duty', 'short cycling'],
  '/comfort-consistency': ['comfort consistency', 'setpoint', 'cabin stability'],
  '/preconditioning-effectiveness': ['preconditioning', 'cabin readiness', 'departure climate'],
  '/tire-differential-drift': ['tire drift', 'pressure trend', 'tpms differential'],
  '/drivetrain-health': ['motor', 'drive unit', 'health'],
  '/vampire-drain': ['vampire', 'phantom drain', 'idle drain'],
  '/sleep-efficiency': ['sleep', 'standby', 'idle'],
  '/software-updates': ['software', 'firmware', 'ota'],
  '/maintenance': ['service', 'maintenance', 'repairs'],
  '/analytics': ['analytics', 'insights', 'charts'],
  '/statistics': ['stats', 'numbers', 'metrics'],
  '/signal-entropy': ['signal entropy', 'telemetry variability', 'information density'],
  '/signal-trend': ['signal trend', 'theil sen', 'mann kendall', 'telemetry slope'],
  '/signal-change-points': ['signal change points', 'page hinkley', 'telemetry shift'],
  '/signal-deadband': ['signal deadband', 'noise floor', 'telemetry retention'],
  '/signal-mutual-information': ['mutual information', 'nonlinear coupling', 'signal dependence'],
  '/lifetime-stats': ['lifetime', 'all time', 'totals'],
  '/vehicle-comparison': ['compare vehicles', 'fleet comparison', 'side by side', 'two vehicles'],
  '/timeline': ['timeline', 'events', 'history'],
  '/day-log': ['day log', 'what happened today', 'daily events', 'drive start', 'charge start'],
  '/activity': ['activity', 'drives', 'charging', 'alerts', 'software updates', 'annotations', 'operations timeline'],
  '/locations': ['places', 'locations', 'visited'],
  '/commands': ['commands', 'control', 'remote'],
  '/command-history': ['command log', 'remote history'],
  '/automations': ['automation', 'rules', 'workflows'],
  '/notifications': ['notifications', 'messages', 'inbox'],
  '/notifications/inbox': ['inbox', 'notifications', 'messages'],
  '/notifications/archived': ['archived', 'notifications'],
  '/notifications/channels': ['channels', 'discord', 'slack', 'telegram', 'email', 'ntfy', 'pushover', 'webhook'],
  '/notifications/webhooks': ['webhooks', 'hmac', 'http endpoint'],
  '/notifications/browser': ['browser notifications', 'desktop push', 'permission'],
  '/notifications/quiet-hours': ['quiet hours', 'do not disturb', 'dnd', 'schedule'],
  '/notifications/rules': ['alert rules', 'rules', 'conditions'],
  '/notifications/studio': ['alert studio', 'studio', 'rule builder'],
  '/notifications/packs': ['alert packs', 'rule packs', 'curated alert templates'],
  '/notifications/health': ['alert fatigue', 'notification burn rate', 'notification latency', 'delivery slo', 'error budget', 'apdex', 'tail latency'],
  '/geofences': ['geofence', 'zones', 'places'],
  '/guard-mode': ['guard', 'sentry', 'security'],
  '/chatbot': ['ai', 'assistant', 'chat'],
  '/media-player': ['media', 'music', 'player'],
  '/tesla-account': ['account', 'tesla login', 'oauth'],
  '/system-status': ['system', 'status', 'health', 'admin', 'administration', 'overview'],
  '/tesla-api-usage': ['tesla', 'fleet api', 'signals', 'commands', 'wakes', 'usage', 'spend'],
  '/physics-cockpit': ['physics', 'cockpit', 'gear', 'charge port', 'bms', 'trip meter', 'fsd counter'],
  '/tesla-physics': ['tesla physics', 'physics', 'exclusive', 'tesla language'],
  '/tesla-physics/clocks': ['event time', 'ingest time', 'display time', 'three clocks'],
  '/tesla-physics/life-tape': ['life tape', 'neutral rolling', 'confirmed park', 'unknown gap'],
  '/tesla-physics/contradictions': ['contradiction', 'park with speed', 'complete latched'],
  '/tesla-physics/meters': ['trip meter', 'odometer', 'fsd counter', 'null is not zero'],
  '/tesla-physics/unknown': ['unknown os', 'unknown hours', 'budget'],
  '/tesla-physics/car-kept-living': ['mqtt', 'queue', 'replay', 'event time', 'carbon'],
  '/tesla-physics/logbook': ['tesla language', 'park', 'drive', 'disconnected'],
  '/tesla-physics/firmware-epochs': ['firmware', 'this vin', 'correlation'],
  '/tesla-physics/charge-port': ['charge port', 'latch', 'complete unplug'],
  '/tesla-physics/black-box': ['black box', '90 seconds', 'park', 'unplug'],
  '/tesla-physics/dictionary': ['owner dictionary', 'park dwell', 'etiquette'],
  '/tesla-physics/vault': ['resale', 'service vault', 'session certificate'],
  '/tesla-physics/modes': ['valet', 'service', 'transport', 'unknown mode'],
  '/tesla-physics/nervous-system': ['bms', 'gear', 'latch', 'silent'],
  '/tesla-physics/range': ['rated range', 'typical range', 'no true range'],
  '/science': ['science lab', 'electrochemistry', 'arrhenius', 'lab notebook'],
  '/outage': ['outage', 'mqtt', 'replay', 'carbon', 'queue', 'unknown gap'],
  '/api-logs': ['api logs', 'requests', 'debug'],
  '/fleet-api': ['fleet api', 'tesla api'],
  '/tesla-features': ['feature flags', 'tesla features', 'feature config', 'flags'],
  '/tesla-region': ['region', 'tesla region', 'fleet api endpoint', 'api region'],
  '/tesla-orders': ['orders', 'tesla orders', 'active orders', 'delivery', 'vehicle delivery'],
  '/gas-price': ['gas price', 'fuel', 'eia', 'gasoline', 'auto poll', 'comparison'],
  '/settings': ['settings', 'preferences', 'configuration'],
  '/settings/fleet-setup': ['fleet setup', 'onboarding', 'tesla oauth', 'telemetry subscribe', 'fleet telemetry'],
  '/api-keys': ['keys', 'tokens', 'api key'],
  '/notifications/audit': ['audit', 'audit log', 'activity log', 'admin'],
  '/data-export': ['export', 'download', 'csv'],
  '/backup': ['backup', 'restore'],
  '/data-repair': ['repair', 'data repair', 'fix sessions'],
  '/dev-tools': ['developer', 'tools', 'debug'],
  '/api-playground': ['playground', 'api test'],
  '/roadmap': ['roadmap', 'plans'],
  '/signals': ['signals', 'live monitor', 'signal log', 'signal explorer', 'signal diff', 'gap detector', 'telemetry workspace'],
  '/account/2fa': ['2fa', 'two factor', 'two-factor', 'mfa', 'totp', 'authenticator', 'security', 'account', 'verify', 'enroll'],
  '/account/sessions': ['sessions', 'devices', 'sign out', 'logout', 'revoke', 'active sessions', 'security', 'account'],
  '/account/privacy': ['privacy', 'recent pages', 'recently viewed', 'cookies', 'consent', 'gdpr', 'analytics', 'tracking', 'account'],
  '/integrations/helix': ['helix', 'ai', 'assistant', 'llm', 'gpt', 'openai', 'anthropic', 'integration', 'provider', 'cost cap', 'api key'],
  '/live-monitor': ['live signals', 'monitor', 'telemetry'],
  '/signal-log': ['signals', 'signal log', 'telemetry log'],
  '/signal-explorer': ['explore signals', 'signal explorer'],
  '/signal-diff': ['diff', 'signal compare'],
  '/signal-gaps': ['gaps', 'missing signals'],
  '/state-debugger': ['state machine', 'debugger', 'fsm'],
  '/mqtt-inspector': ['mqtt', 'broker', 'telemetry stream'],
  '/redis-signals': ['redis', 'cache', 'signals'],
  '/db-health': ['database', 'db', 'postgres'],
  '/anomaly-detection': ['anomaly', 'outliers', 'analytics', 'detection'],
  '/diagnostics/root-cause': ['root cause', 'evidence graph', 'hypothesis', 'signal explanation', 'diagnostics'],
  '/diagnostics/service-evidence': ['service evidence', 'evidence pack', 'integrity', 'service export'],
  '/dashcam': ['dashcam', 'sentry', 'clips', 'redaction', 'incident reconstruction'],
  '/energy-orchestrator': ['whole home energy', 'solar', 'powerwall', 'tariff', 'panel limit', 'departure'],
  '/service-intelligence': ['recall', 'service intelligence', 'tsb', 'firmware', 'symptoms'],
  '/benchmarks/privacy': ['private benchmarks', 'differential privacy', 'cohort', 'degradation comparison'],
  '/intelligence-packs': ['intelligence packs', 'marketplace', 'signed analytics', 'sandbox', 'community'],
  '/resale-vault': ['warranty', 'resale', 'vehicle history', 'signed report', 'selective disclosure'],
  '/fleet-operations': ['fleet operations', 'drivers', 'reservations', 'cost centers', 'work orders'],
  '/intelligence/twin-lab': ['twin lab', 'counterfactual', 'uncertainty', 'sensitivity', 'vehicle simulation'],
  '/intelligence/firmware-canary': ['firmware canary', 'rollout', 'matched cohort', 'regression', 'hold'],
  '/intelligence/component-survival': ['component survival', 'event free', 'competing risks', 'intervention'],
  '/intelligence/road-hazards': ['road hazards', 'hazard mesh', 'crash cluster', 'airbag', 'coarse cell'],
  '/intelligence/behavioral-sentinel': ['behavioral sentinel', 'command anomaly', 'identity change', 'integrity'],
  '/intelligence/charging-forensics': ['charging forensics', 'billing', 'loss', 'cost discrepancy', 'trust'],
  '/intelligence/journey-assurance': ['journey assurance', 'departure readiness', 'uncertainty', 'arrival energy'],
  '/intelligence/charging-site-twin': ['charging site twin', 'queue', 'reliability', 'site simulation'],
  '/intelligence/federated-learning': ['federated learning', 'model card', 'privacy budget', 'local training'],
  '/intelligence/emergency-resilience': ['emergency resilience', 'reserve', 'evacuation', 'backup energy'],
  '/intelligence/causal-lab': ['causal experiment', 'treatment', 'control', 'effect estimate'],
  '/intelligence/tco-optimizer': ['tco optimizer', 'ownership cost', 'portfolio', 'replacement scenario'],
  '/ownership/insurance-telematics': ['insurance telematics', 'underwriting', 'premium', 'risk score', 'safe driving discount', 'harsh braking'],
  '/ownership/tariff-lab': ['tariff lab', 'utility rate', 'time of use', 'price band', 'arbitrage', 'electricity plan', 'rate comparison'],
  '/ownership/charging-reconciliation': ['charging reconciliation', 'invoice', 'dispute', 'billing variance', 'overcharge', 'statement audit'],
  '/ownership/driver-attribution': ['driver attribution', 'fingerprint', 'who drove', 'behaviour cluster', 'driver profile', 'cost split'],
  '/ownership/warranty-command': ['warranty', 'coverage', 'claim readiness', 'expiry', 'deductible', 'capacity floor'],
  '/ownership/data-governance': ['data governance', 'retention policy', 'disk usage', 'purge plan', 'legal hold', 'storage'],
  '/ownership/model-trust': ['model trust', 'prediction accuracy', 'calibration', 'forecast error', 'bias', 'drift', 'skill score'],
  '/ownership/jurisdiction-compliance': ['jurisdiction', 'road usage charge', 'apportionment', 'mileage tax', 'filing', 'registration'],
  '/ownership/consumables-lifecycle': ['consumables', 'wear parts', 'tires', 'filters', 'brake pads', 'wipers', 'replacement due'],
  '/ownership/subscription-roi': ['subscription roi', 'connectivity', 'premium features', 'cancel', 'break even', 'recurring cost'],
}
