import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';

vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key: string, opts?: { defaultValue?: string; field?: string } | string) => {
      if (typeof opts === 'string') return opts || key;
      if (opts && typeof opts === 'object') {
        if (key === 'a11y.helpFor' && opts.field) {
          return `Help for ${opts.field}`;
        }
        if ('defaultValue' in opts && opts.defaultValue) {
          return opts.defaultValue;
        }
      }
      return key;
    },
  }),
}));

import { HelpIcon } from '../HelpIcon';

describe('HelpIcon', () => {
  it('renders nothing when neither i18nKey nor content is supplied', () => {
    const { container } = render(<HelpIcon />);
    expect(container.firstChild).toBeNull();
  });

  it('renders nothing when i18nKey resolves to an empty string and content is empty', () => {
    const { container } = render(<HelpIcon content="" />);
    expect(container.firstChild).toBeNull();
  });

  it('renders a focusable <button type="button"> trigger', () => {
    render(<HelpIcon content="Hello" />);
    const trigger = screen.getByRole('button');
    expect(trigger.tagName).toBe('BUTTON');
    expect(trigger.getAttribute('type')).toBe('button');
  });

  it('uses a11y.helpFor template when `for` is provided', () => {
    render(<HelpIcon content="x" for="cooldown" />);
    expect(screen.getByRole('button', { name: 'Help for cooldown' })).toBeInTheDocument();
  });

  it('falls back to the generic "More info" label when `for` is omitted', () => {
    render(<HelpIcon content="x" />);
    expect(screen.getByRole('button', { name: 'More info' })).toBeInTheDocument();
  });

  it('honours an explicit ariaLabel override', () => {
    render(<HelpIcon content="x" ariaLabel="Custom help label" />);
    expect(
      screen.getByRole('button', { name: 'Custom help label' }),
    ).toBeInTheDocument();
  });

  it('exposes the help text via role="tooltip" and wires aria-describedby on the trigger', () => {
    render(<HelpIcon content="Cooldown protects against alert spam." for="cooldown" />);
    const tooltip = screen.getByRole('tooltip');
    expect(tooltip).toHaveTextContent('Cooldown protects against alert spam.');
    const trigger = screen.getByRole('button');
    // Tooltip composes its own id-based aria-describedby; we can at least
    // assert the attribute is wired (the exact id is generated by useId).
    const describedBy = trigger.getAttribute('aria-describedby');
    expect(describedBy).toBeTruthy();
    // The id space includes the tooltip id (the shared Tooltip primitive
    // appends its useId() to whatever describedby the trigger already had).
    expect(describedBy?.split(/\s+/)).toContain(tooltip.id);
  });

  it('translates the i18nKey via the i18n mock and falls back to content', () => {
    render(
      <HelpIcon
        i18nKey="help.fields.alertStudio.cooldown"
        content="Cooldown helper text"
        for="cooldown"
      />,
    );
    expect(screen.getByRole('tooltip')).toHaveTextContent('Cooldown helper text');
  });

  it('blurs the trigger on Escape so the focus-within tooltip dismisses', () => {
    render(<HelpIcon content="x" for="cooldown" />);
    const trigger = screen.getByRole('button');
    trigger.focus();
    expect(document.activeElement).toBe(trigger);
    fireEvent.keyDown(trigger, { key: 'Escape' });
    expect(document.activeElement).not.toBe(trigger);
  });

  it('exposes data-help-for on the trigger so audits can correlate icons to fields', () => {
    render(<HelpIcon content="x" for="my-field-id" />);
    const trigger = screen.getByRole('button');
    expect(trigger.getAttribute('data-help-for')).toBe('my-field-id');
  });
});
