// <auto-generated path="web/src/features/dashboard/widgets/registry/*, web/src/features/dashboard/hooks/useDashboardLayout.ts" />
// Faithful transcription of the web dashboard widget registry (WIDGET_REGISTRY, 118 widgets across 16
// categories) and the layout presets (DASHBOARD_PRESETS, 10 presets) the web WidgetPicker
// (web/src/features/dashboard/components/WidgetPicker.tsx) imports. Regenerated by tmp_gen_catalog.js from the
// web source; do not hand-edit — change the web registry and re-run the generator. Each entry carries only the
// fields the picker reads (id, name, description, category, default grid size); the runtime icon resolves
// through MiniGridWidgetIcons.GlyphFor (the native getWidgetDef(id).icon), so no icon column is duplicated here.
namespace TeslaSync.App.FeatureViews;

/// <summary>
/// The static dashboard widget catalogue + layout presets the <see cref="WidgetPicker"/> browses — the native
/// projection of the web module constants <c>WIDGET_REGISTRY</c>
/// (web/src/features/dashboard/widgets/registry) and <c>DASHBOARD_PRESETS</c>
/// (web/src/features/dashboard/hooks/useDashboardLayout.ts). The web component imports these directly as
/// module-level data (not via a hook), so the native surface seeds its default model from the same fixed
/// catalogue. Pure data (no WinUI types) so the picker projection is asserted headlessly.
/// </summary>
public static class WidgetPickerCatalog
{
    /// <summary>Total widgets in the catalogue (web <c>WIDGET_REGISTRY.length</c>).</summary>
    public const int WidgetCount = 118;

    /// <summary>
    /// Every catalogue widget, in web registry order (category by category). Mirrors
    /// <c>WIDGET_REGISTRY</c> row-for-row: id, display name, description, category and default grid span.
    /// </summary>
    public static IReadOnlyList<WidgetCatalogEntry> DefaultWidgets { get; } = new WidgetCatalogEntry[]
    {
        // vehicle (web registry/vehicle.ts)
        new("vehicle-hero", "Vehicle Card", "Vehicle name, model, state, battery at a glance", WidgetCategory.Vehicle, 2, 9),
        new("vehicle-hero-card", "Vehicle Hero Card", "Vehicle name, model, state badge (online/asleep/driving/charging), battery, range, temp", WidgetCategory.Vehicle, 2, 2),
        new("vehicle-twin", "Digital Twin", "Visual car state: doors, windows, lights", WidgetCategory.Vehicle, 2, 4),
        new("digital-twin-mini", "Digital Twin Mini", "Small version of vehicle digital twin SVG: doors, windows, lock, charge port", WidgetCategory.Vehicle, 2, 4),
        new("software-update-status", "Software Update", "Current firmware version, update availability, download/install progress bar", WidgetCategory.Vehicle, 2, 2),
        new("software-update-history", "Update History", "Firmware update timeline: versions installed, dates, changelogs", WidgetCategory.Vehicle, 2, 4),
        new("odometer-counter", "Odometer Counter", "Animated odometer with rolling digit animation and distance breakdown", WidgetCategory.Vehicle, 1, 2),
        new("drivetrain-health", "Drivetrain Health", "Motor temp, stator temp, inverter health, overall powertrain score", WidgetCategory.Vehicle, 2, 4),
        new("motor-performance", "Motor Performance", "Live motor data: torque, stator temp, gear state, g-forces", WidgetCategory.Vehicle, 2, 4),
        new("motor-history", "Motor History", "Motor torque and stator temp over time with danger zone highlighting", WidgetCategory.Vehicle, 2, 4),
        new("vehicle-specs", "Vehicle Specs", "Configuration reference: model, trim, paint, wheels, options", WidgetCategory.Vehicle, 2, 4),
        new("watch-summary", "Watch Summary", "Apple Watch-style compact view: battery, range, state, lock status", WidgetCategory.Vehicle, 1, 2),
        new("maintenance-tracker", "Maintenance", "Upcoming maintenance reminders + recent service history", WidgetCategory.Vehicle, 2, 4),
        new("warranty-status", "Warranty Status", "Warranty countdown: time remaining, mileage remaining, coverage types", WidgetCategory.Vehicle, 2, 2),
        new("subscriptions", "Subscriptions", "Tesla subscriptions: Premium Connectivity, FSD, expiry dates, renewal", WidgetCategory.Vehicle, 2, 4),
        new("vehicle-upgrades", "Upgrades & Sharing", "Available OTA upgrades with pricing + active drive share links", WidgetCategory.Vehicle, 2, 4),

        // battery (web registry/battery.ts)
        new("battery-gauge", "Battery Level", "Battery percentage with radial gauge", WidgetCategory.Battery, 1, 2),
        new("battery-radial-gauge", "Battery Radial Gauge", "Large radial gauge showing battery percentage with color gradient (green>amber>red)", WidgetCategory.Battery, 1, 2),
        new("range-estimate", "Range Estimate", "Rated, ideal, and estimated range", WidgetCategory.Battery, 1, 2),
        new("range-bar", "Range Bar", "Horizontal bar showing rated, ideal, and estimated range with EPA comparison", WidgetCategory.Battery, 2, 2),
        new("battery-degradation-trend", "Battery Degradation Trend", "Line chart showing max range capacity over months", WidgetCategory.Battery, 2, 4),
        new("energy-flow", "Energy Flow", "Live power flow diagram", WidgetCategory.Battery, 2, 4),
        new("projected-range", "Projected Range", "Helix-predicted range based on driving habits, weather, elevation", WidgetCategory.Battery, 2, 2),
        new("battery-cells", "Battery Cells", "Cell-level voltage heatmap, min/max/avg, temperature per module", WidgetCategory.Battery, 2, 4),
        new("battery-degradation-forecast", "Battery Forecast", "Predictive degradation: when battery hits 80%, risk factors, recommendations", WidgetCategory.Battery, 2, 4),
        new("battery-health-analytics", "Battery Analytics", "Deep battery health: cycles, charge depth, temp exposure, DC fast ratio", WidgetCategory.Battery, 2, 4),

        // energy (web registry/energy.ts)
        new("energy-flow-animated", "Energy Flow Animated", "Animated energy flow diagram: battery→drive, regen→battery, charger→battery", WidgetCategory.Energy, 2, 4),
        new("vampire-drain", "Vampire Drain", "Phantom drain rate: avg %/day, recent drain events", WidgetCategory.Energy, 2, 4),
        new("sleep-efficiency", "Sleep Efficiency", "How well the car sleeps: efficiency %, drain rate, wake events", WidgetCategory.Energy, 1, 2),
        new("solar-production", "Solar Production", "Daily solar generation chart from Tesla Energy / Powerwall", WidgetCategory.Energy, 2, 4),
        new("live-power-flow", "Live Power Flow", "Real-time solar→battery→home→grid power routing diagram", WidgetCategory.Energy, 2, 4),
        new("energy-site-info", "Energy Site", "Tesla Energy system: solar capacity, Powerwall count, gateway firmware", WidgetCategory.Energy, 2, 4),
        new("backup-history", "Backup History", "Power outage events: Powerwall backup triggers, duration, energy used", WidgetCategory.Energy, 2, 4),
        new("power-flow-history", "Power Flow History", "Historical solar/battery/grid/home power routing over 24 hours", WidgetCategory.Energy, 2, 4),
        new("energy-stats", "Energy Stats", "Energy overview: daily usage chart, total used/charged, efficiency, CO₂ saved", WidgetCategory.Energy, 2, 4),

        // driving (web registry/driving.ts)
        new("recent-drives", "Recent Drives", "Last 5 drives with distance and efficiency", WidgetCategory.Driving, 2, 4),
        new("drive-score", "Driving Score", "Weekly efficiency and driving score", WidgetCategory.Driving, 1, 2),
        new("recent-drives-list", "Recent Drives List", "Last 5-10 drives: distance, duration, efficiency, start/end locations", WidgetCategory.Driving, 2, 4),
        new("drive-score-gauge", "Drive Score Gauge", "Radial gauge showing weekly score (0-100) with efficiency, smoothness, and speed breakdown", WidgetCategory.Driving, 1, 2),
        new("drive-efficiency-chart", "Drive Efficiency Chart", "Area chart of Wh/mi over last 30 days with rolling average overlay", WidgetCategory.Driving, 2, 4),
        new("speed-heatmap", "Speed Heatmap", "Heatmap: time-of-day vs day-of-week speed distribution", WidgetCategory.Driving, 2, 4),
        new("driving-dynamics", "Driving Dynamics", "Acceleration, braking, lateral g-forces with driving style indicator", WidgetCategory.Driving, 2, 4),
        new("speed-profile", "Speed Profile", "Speed distribution histogram with efficiency overlay — find your optimal speed", WidgetCategory.Driving, 2, 4),
        new("regen-efficiency", "Regen Braking", "Regenerative braking recovery rate, total kWh recovered, max regen power", WidgetCategory.Driving, 1, 2),
        new("route-efficiency", "Route Efficiency", "Recurring routes ranked by energy efficiency with weather/elevation impact", WidgetCategory.Driving, 2, 4),
        new("driving-coach", "Driving Coach", "Helix-powered driving tips: personalized efficiency recommendations", WidgetCategory.Driving, 2, 4),
        new("trip-summary", "Trip Summary", "Recent trips: start→end, distance, duration, drive segments, charge stops", WidgetCategory.Driving, 2, 4),
        new("drive-telemetry", "Drive Telemetry", "Last drive replay: speed, power, battery over time with route", WidgetCategory.Driving, 2, 4),

        // charging (web registry/charging.ts)
        new("charge-status", "Charge Status", "Current charge state, amps, time remaining", WidgetCategory.Charging, 2, 2),
        new("charge-status-live", "Charge Status Live", "Live charging: current amps/volts/power, time remaining, energy added", WidgetCategory.Charging, 2, 2),
        new("charge-history", "Charge History", "Recent charging sessions chart", WidgetCategory.Charging, 2, 4),
        new("charge-session-chart", "Charge Session Chart", "Bar chart of recent charge sessions: energy per session, color-coded by charger type (home/SC/destination)", WidgetCategory.Charging, 2, 4),
        new("charge-cost-tracker", "Charge Cost Tracker", "Monthly charging cost breakdown: total kWh, total cost, cost per mile, vs gas savings", WidgetCategory.Charging, 2, 2),
        new("charging-schedule", "Charging Schedule", "Shows scheduled charge time, departure time, charge limit", WidgetCategory.Charging, 2, 2),
        new("cost-forecast", "Cost Forecast", "6-month charging cost projection with seasonal trends", WidgetCategory.Charging, 2, 4),
        new("charging-optimizer", "Charging Optimizer", "Smart charging schedule: optimal time, target SOC, cost savings", WidgetCategory.Charging, 2, 2),
        new("wall-connector", "Wall Connector", "Home charging stats from Tesla Wall Connector: daily kWh, session history", WidgetCategory.Charging, 2, 4),
        new("charging-telemetry", "Charging Telemetry", "Live charging metrics: voltage, amperage, power, phases, charger type", WidgetCategory.Charging, 2, 2),
        new("supercharger-history", "Supercharger History", "Tesla Supercharger sessions: location, energy, cost from Tesla account", WidgetCategory.Charging, 2, 4),
        new("charge-plans", "Charge Plans", "Active charge plan, rate schedule: peak/off-peak hours with rates", WidgetCategory.Charging, 2, 4),
        new("charging-session-detail", "Charge Session Detail", "Last charge session power curve with SoC overlay, kWh added, peak power", WidgetCategory.Charging, 2, 4),

        // climate (web registry/climate.ts)
        new("climate-status", "Climate", "Inside/outside temp, HVAC state", WidgetCategory.Climate, 1, 2),
        new("climate-control-panel", "Climate Control Panel", "Inside/outside temp, HVAC on/off, fan speed, seat heaters, steering heat", WidgetCategory.Climate, 2, 4),
        new("weather-at-car", "Weather at Car", "Current weather at vehicle location: temp, conditions icon", WidgetCategory.Climate, 1, 2),
        new("climate-history", "Climate History", "Inside vs outside temperature chart over time", WidgetCategory.Climate, 2, 4),

        // tires (web registry/tires.ts)
        new("tire-pressure-visual", "Tire Pressure Visual", "Four-tire diagram with pressure per tire, color-coded (green/amber/red)", WidgetCategory.Tires, 2, 4),
        new("tire-pressure-history", "Tire Pressure History", "Pressure trends for all 4 tires over time with recommended range", WidgetCategory.Tires, 2, 4),

        // security (web registry/security.ts)
        new("security-status", "Security", "Lock, sentry, doors, windows status", WidgetCategory.Security, 1, 2),
        new("door-window-status", "Door & Window Status", "Grid showing 4 doors + 4 windows with open/closed/partial badges", WidgetCategory.Security, 2, 2),
        new("sentry-event-log", "Sentry Event Log", "Recent sentry events with timestamps", WidgetCategory.Security, 2, 4),
        new("safety-features", "Safety Features", "ADAS status: autopilot, collision warning, lane departure, blind spot", WidgetCategory.Security, 2, 4),
        new("safety-history", "Safety History", "ADAS event timeline: collision warnings, AEB, lane departures, disengagements", WidgetCategory.Security, 2, 4),
        new("guard-mode", "Guard Mode", "Anti-theft guard status, recent security events, panic button", WidgetCategory.Security, 2, 4),
        new("vehicle-access", "Vehicle Access", "Authorized drivers, pending invitations, mobile access status", WidgetCategory.Security, 2, 4),

        // commands (web registry/commands.ts)
        new("command-quick-actions", "Quick Actions", "Grid of command buttons: Lock, Unlock, Climate, Frunk, Horn, Flash", WidgetCategory.Commands, 2, 2),
        new("command-history", "Command History", "Recent vehicle commands: lock, unlock, climate — with success/fail status", WidgetCategory.Commands, 2, 4),

        // media (web registry/media.ts)
        new("media-now-playing", "Now Playing", "Current media: song title, artist, source", WidgetCategory.Media, 2, 2),
        new("media-history", "Media History", "Recently played tracks: title, artist, source, playback history", WidgetCategory.Media, 2, 4),

        // telemetry (web registry/telemetry.ts)
        new("live-signals", "Live Signals", "Real-time signal values with sparklines", WidgetCategory.Telemetry, 2, 4),
        new("live-signal-sparklines", "Live Signal Sparklines", "Configurable list of 4-6 signals with mini sparkline charts (last 5 min)", WidgetCategory.Telemetry, 2, 4),
        new("signal-health", "Signal Health", "Telemetry signal coverage: active signals, data gaps, freshness", WidgetCategory.Telemetry, 2, 4),
        new("signal-catalog", "Signal Catalog", "Browse all available telemetry signals with categories and observation counts", WidgetCategory.Telemetry, 2, 4),
        new("signal-log", "Signal Log", "Live feed of raw signal updates: timestamp, signal, old→new value, source", WidgetCategory.Telemetry, 2, 4),

        // analytics (web registry/analytics.ts)
        new("fleet-stats", "Fleet Stats", "Fleet-wide metrics and totals", WidgetCategory.Analytics, 4, 2),
        new("fleet-stats-bar", "Fleet Stats Bar", "Fleet-wide: total vehicles, online count, total miles today, total energy", WidgetCategory.Analytics, 4, 2),
        new("weekly-summary-card", "Weekly Summary", "This week vs last week: total miles, kWh, cost, efficiency", WidgetCategory.Analytics, 2, 2),
        new("weekly-digest", "Weekly Digest", "This week vs last week: distance, drives, energy, efficiency trends", WidgetCategory.Analytics, 2, 4),
        new("monthly-mileage", "Monthly Mileage", "Bar chart of monthly driving distance over last 12 months", WidgetCategory.Analytics, 2, 4),
        new("lifetime-stats", "Lifetime Stats", "All-time totals: distance, drives, energy, CO₂ saved, ownership days", WidgetCategory.Analytics, 2, 2),
        new("mileage-stats", "Mileage Stats", "Driving averages: daily, weekly, monthly distance + milestone projection", WidgetCategory.Analytics, 2, 2),
        new("state-timeline", "State Timeline", "Vehicle state distribution: driving, charging, asleep, idle breakdown", WidgetCategory.Analytics, 2, 4),
        new("anomaly-detector", "Anomaly Detector", "Statistical outlier alerts: unusual battery, temp, or driving anomalies", WidgetCategory.Analytics, 2, 4),
        new("fsm-distribution", "State Distribution", "Donut chart of time in each state + recent state transitions feed", WidgetCategory.Analytics, 2, 4),
        new("cost-breakdown", "Cost Breakdown", "Charging cost by source: home vs Supercharger vs destination, gas savings", WidgetCategory.Analytics, 2, 4),
        new("year-review", "Year in Review", "Annual recap: total miles, drives, energy, highlights, achievements", WidgetCategory.Analytics, 2, 4),
        new("analytics-summary", "Analytics Summary", "Fleet-wide snapshot: distance, efficiency, energy, cost per mile", WidgetCategory.Analytics, 2, 2),
        new("recently-unlocked-achievements", "Recently Unlocked", "Most recently unlocked achievements — click to view in Lifetime Stats", WidgetCategory.Analytics, 2, 2),

        // alerts (web registry/alerts.ts)
        new("alert-feed", "Alert Feed", "Recent alerts reverse-chronological with severity badges", WidgetCategory.Alerts, 2, 4),
        new("notification-stats", "Notification Stats", "Notification delivery rate, active channels, recent delivery log", WidgetCategory.Alerts, 2, 2),

        // automations (web registry/automations.ts)
        new("automation-status", "Automation Status", "Active automations: last run, success/fail badge, next scheduled", WidgetCategory.Automations, 2, 4),
        new("automation-history", "Automation History", "Recent automation runs: success/failure status, execution times", WidgetCategory.Automations, 2, 4),

        // system (web registry/system.ts)
        new("onboarding-checklist", "Setup Checklist", "First-run setup checklist: connect Tesla, pick a theme, create an alert, and more", WidgetCategory.System, 2, 4),
        new("uptime-monitor", "Uptime Monitor", "System health: DB, MQTT, Tesla API, Fleet Telemetry status", WidgetCategory.System, 2, 2),
        new("mqtt-status", "MQTT Status", "Fleet Telemetry MQTT connection: status, message rate, throughput", WidgetCategory.System, 2, 2),
        new("quick-nav", "Quick Navigation", "Shortcut links to key pages", WidgetCategory.System, 4, 2),
        new("api-usage", "API Usage", "API call volume, response times, error rates, top endpoints", WidgetCategory.System, 2, 2),
        new("system-health", "System Health", "Server health: DB, MQTT, Tesla API status, memory, connections", WidgetCategory.System, 2, 4),
        new("telemetry-errors", "Telemetry Errors", "Fleet Telemetry error monitor: VINs with errors, error types, counts", WidgetCategory.System, 2, 4),
        new("audit-log", "Audit Log", "Security audit trail: user actions, auth events, permission changes", WidgetCategory.System, 2, 4),
        new("backup-monitor", "Backup Monitor", "Database backup status: last run, size, retention, success/fail history", WidgetCategory.System, 2, 2),
        new("export-status", "Export Status", "Data export jobs: progress, format, size, success/fail status", WidgetCategory.System, 2, 4),
        new("version-info", "Version Info", "TeslaSync version, build info, uptime, data capture rates", WidgetCategory.System, 2, 2),
        new("dashboard-stats", "Dashboard Stats", "Meta-widget: dashboard usage, widgets placed, FSM current state", WidgetCategory.System, 2, 2),

        // maps (web registry/maps.ts)
        new("location-map", "Vehicle Location Map", "Live map of vehicle position with heading arrow", WidgetCategory.Maps, 2, 4),
        new("location-favorites", "Favorite Locations", "Frequently visited places, current location status (home/work/other)", WidgetCategory.Maps, 2, 4),
        new("geofence-status", "Geofence Status", "Configured geofences with inside/outside status for current vehicle", WidgetCategory.Maps, 2, 4),
        new("destination-eta", "Destination ETA", "Active navigation: destination, distance remaining, arrival countdown", WidgetCategory.Maps, 2, 2),
        new("position-heatmap", "Position Heatmap", "GPS position density heatmap: frequently visited locations glow brighter", WidgetCategory.Maps, 2, 4),
    };

    /// <summary>
    /// The layout presets shown above the catalogue, in web order (web <c>DASHBOARD_PRESETS</c>). Each carries
    /// its id, display name, the count of widgets it seeds (web <c>preset.widgets.length</c>) and whether it is
    /// the shipped default.
    /// </summary>
    public static IReadOnlyList<WidgetPresetSummary> DefaultPresets { get; } = new WidgetPresetSummary[]
    {
        new("default", "Default", 8, true),
        new("commuter", "Daily Commuter", 7, false),
        new("fleet_manager", "Fleet Manager", 6, false),
        new("data_nerd", "Data Nerd", 5, false),
        new("charging_focus", "Charging Hub", 7, false),
        new("security_monitor", "Security Monitor", 6, false),
        new("road_trip", "Road Trip", 8, false),
        new("performance", "Performance", 6, false),
        new("kiosk_wall", "Wall Display", 6, false),
        new("minimal", "Minimal", 4, false),
    };
}
