package io.teslasync.shared.core.presentation.trips

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * One trip-log summary row — the cross-platform port of the web `Trip` interface
 * (web/src/api/types.ts), returned by the web `useTrips` list and `useTrip` detail hooks. Keys are
 * snake_case, matching the Go `tripSummaryResponse` JSON tags (internal/api/trip/handler.go).
 *
 * The timestamp fields ([startDate], [startedAt], [createdAt], and the nullable [endDate]/[endedAt])
 * are carried as the raw RFC3339 strings the backend emits, exactly as the web interface types them
 * (`string`); parsing/formatting is the render boundary's job (S5). The aggregate columns are SI
 * canonical — [totalDistanceM] in metres, [totalEnergyWh] in watt-hours, [totalDurationS] in seconds
 * (Phase-48) — and round-trip verbatim through this layer; display conversion happens only at the
 * render boundary via `useUnits()` (S5), never here.
 */
@Serializable
public data class Trip(
    @SerialName("id") val id: Long,
    @SerialName("vehicle_id") val vehicleId: Long,
    @SerialName("name") val name: String? = null,
    @SerialName("start_date") val startDate: String,
    @SerialName("end_date") val endDate: String? = null,
    @SerialName("started_at") val startedAt: String,
    @SerialName("ended_at") val endedAt: String? = null,
    @SerialName("total_distance_m") val totalDistanceM: Double,
    @SerialName("total_energy_wh") val totalEnergyWh: Double,
    @SerialName("total_duration_s") val totalDurationS: Long,
    @SerialName("total_cost") val totalCost: Double,
    @SerialName("drive_count") val driveCount: Long,
    @SerialName("charge_count") val chargeCount: Long,
    @SerialName("created_at") val createdAt: String,
    @SerialName("created_by_user") val createdByUser: Long? = null,
    @SerialName("auto_generated") val autoGenerated: Boolean? = null,
    @SerialName("notes") val notes: String? = null,
)

/**
 * The optional filter/paging arguments to the web `useTrips` hook — the port of the web
 * `UseTripParams` (web/src/api/hooks/useTrips.ts). Every field is optional; a `null` here is the web
 * `undefined` (the key is simply absent). The query-string projection ([tripsQuery]) reproduces the
 * web hook's per-field truthy guards exactly, and the cache-key projection ([tripsListKey]) mirrors
 * the TanStack `['trips', params]` hash. The fields are not display-unit-bearing (an id, two page
 * cursors, and two ISO date strings), so no SI conversion applies.
 *
 * @property vehicleId restricts to one vehicle's trips (web `vehicle_id`); sent only when non-`0`.
 * @property limit page size (web `limit`); sent only when non-`0`.
 * @property offset page offset (web `offset`); sent only when `> 0`.
 * @property start inclusive ISO range start (web `start`); sent only when non-blank.
 * @property end inclusive ISO range end (web `end`); sent only when non-blank.
 */
public data class TripsParams(
    val vehicleId: Long? = null,
    val limit: Int? = null,
    val offset: Int? = null,
    val start: String? = null,
    val end: String? = null,
)
